### ISSUE TITLE
Fractions as partial marks in prt not working in v4.4.5

### ISSUE THREAD

**Issue by godfrey-godson** [maths/moodle-qtype_stack#1025]
[This question](https://drive.google.com/file/d/1GrdG82hFQ4TNTbIcvP9JfRUgwBuUC_st/view?usp=drive_link) was created using  STACK V4.4.4 with Moodle 4.0.3 (Build: 20220822).
I tried importing in another server using STACK V4.4.5 with Moodle 4.14+(build: 20230721) and it gave me the error "Error writing to database". I tried creating the question in the server and got the same error. If I change the partial marks in node 2 of the prt the question works fine and can be imported without problems.
Is this a deliberate change in STACK V4.4.5? Apologies if this is a Moodle issue rather than a STACK issue.

**Comment by aharjula** [comment]
What comes to mind is whether the upgrade of the newer server has successfully completed. If this bit of the upgrade script has not been correctly executed:
https://github.com/maths/moodle-qtype_stack/blob/ec5cc8e6dffb2b915c2fa682870e2c1ef8af396a/db/upgrade.php#L868-L899
Then the database column for those scores would still expect a float and that would indeed lead to an error when trying to write actual strings into that column.

Could you check the database, especially what are the types of columns in the `mdl_qtype_stack_prt_nodes` table? If those description fields that were added after this change are there then things are interesting, but I would guess they are not there either. If they are not there, check that the normal Moodle plugin upgrade process has been completed.

How this could have happened is that the 4.4.5 server has had a somewhat interesting upgrade path, maybe through some special branches, or some such, or maybe that plugin install/upgrade process itself has somehow been missed.

In any case, no it is not intentional to withdraw a feature as new as that, being able to use expressions in PRT scores/penalties is a thing that was built over a long time and is not going away.

**Comment by godfrey-godson** [comment]
I will check the suggestions with the Moodle providers who carried out the upgrade and report back.

**Comment by anst-i** [comment]
I've imported this question onto our Moodle using STACK 4.4.5 and it worked fine. The 1/2 is converted correctly into 0,50 marks.
![Opera Momentaufnahme_2023-09-19_181356_moodle-app2 let ethz ch](https://github.com/maths/moodle-qtype_stack/assets/52162439/92bef17c-ebad-4f10-87a8-90209e06378f)

**Comment by aharjula** [comment]
@sangwinc as this has also happened to OU people, could it be that line 868 in the above segment of code had a version number that was smaller than a release that people used? Maybe this feature got merged in the wrong order and the update chain broke? Anyway if we knew from which version the updates have happened from, it might be simpler to figure this one out. But it might be simpler for the next release to repeat those column-type changes just in case.

**Comment by sangwinc** [comment]
Thanks @aharjula I agree:  it might be simpler for the next release to repeat those column-type changes just in case.  I'd considered this and was coming to the same conclusion!

**Comment by godfrey-godson** [comment]
> @godfrey-godson, I'll also try to help track this down. I notice you used 1/2 in the PRT score, so I think here you could use 0.5 instead? I'd still like to get the bottom of what is going wrong though, Chris

Yes, I used 0.5 for partial marks and successfully imported.
Thanks @sangwinc for this help.

**Comment by sangwinc** [comment]
Ok, I'm really embarrassed about this problem Godfrey!  Thanks for reporting it and I'm sorry to have wasted so much of your time!
