### ISSUE TITLE
HTML not Evaluating in Question Text

### ISSUE THREAD

**Issue by fowal44p** [maths/moodle-qtype_stack#1036]
Hi community,

Imagining this issue will be a trivial fix, but I'm struggling to work it out.
It appears that the HTML in the question text sections of my questions doesn't appear to be evaluating when I preview the question. For example, if I write "\<p> This is my paragraph \</p>" into the question text, it just outputs that with the HTML tags displayed, rather than the desired "This is my paragraph" without the \<p> and \<\p> HTML tags displayed.

One thing to note that may help with dianosing the issue: In my editor, I don't seem to have a box immediately below the question text section that has options such as "Plain text format" and "HTML..." (and I think two others), which I have seen displayed in someone else's editor in an online tutorial. Imagining this will be relevant to my issue.

Thanks in advance

**Comment by sangwinc** [comment]
If this affects one question, then this is almost certainly an authoring problem.  I suggest you change your editor preference to "plain text area" in Moodle, then fix your HTML and make sure you choose the correct format for your question text.  You can start by following "Fixing broken MathJax and Javascript" in these docs

https://docs.stack-assessment.org/en/Authoring/Fixing_broken_questions/

If this affects any question on your site (especially those working for other people) then please let us know.

**Comment by fowal44p** [comment]
Thank you for the reply.

The issue is that I don't have access to those editor preference options whenever I create a new STACK question. That box with those options does not appear.
However, what I found was that if I created a question within STACK, exported it as an XML, then adjusted the questiontext format line to "plain_text" (it had defaulted to "html"), then when I reimported the adjusted XML then those editor preference options appeared. However, even after adjusting the preferences to plain text format, the HTML is not being evaluated.

I don't see how it is simply an authoring problem. Even if I do this for a question where the only question text is "\<p> This is my paragraph \</p>" it does the same.

**Comment by aharjula** [comment]
This is a place where Moodle options and STACK options get mixed up. In Moodle, text editors deal with a pair of details, the text content, and the format, and STACK supports any Moodle text editor; it will display that pair as the editor wants. The key thing with that "STACK supports and Moodle text editor" is that we also support any plugin editor one installs into Moodle. There are better editors than the default ones coming with Moodle, for example, Marklar has some fans in the STACK community.

Now, the more "helpful" editors tend to assume that the user does not want to deal with formats and simply hide that option to change format. After all, they are WYSIWYG editors and force whatever format they have been designed to edit and allowing changing of format might break the editor.

Some formats like "plain_text" actually work to disable certain features of the content, i.e. with that format, you cannot have HTML tags active. Now to have the editor display the format option, do change your Moodle user account editor preference to some editor and see what changes. You will find that there are not many editors that provide that option, and the editors that do tend not to be as "helpful" or fancy and are, therefore, better suited for raw scripting purposes. The linked guide will give a pretty good idea of which editor you should use if you want to do things yourself instead of letting editors be helpful.

The editor can be changed at the user level by looking at the edge of the screen for your name, picking the settings/preferences from there and on that page of many links picking text editor options/preferences. One can pick from any of the editor plugins active on that Moodle, if the relevant editor is not there your Moodle admin has disabled it and that would be a problem.

**Comment by fowal44p** [comment]
Thank you very much for the reply! Exactly the information I needed.

Did you mean to link a document on how the different editor settings differ? That would be very helpful for me to be able to read that.

When it comes to releasing questions in Moodle quizzes in student assignments, will the way the questions are read differ dependent on the editor preferences of each user writing them? In other words, if we want some of our questions to evaluate HTML (which our department does, as some of our questions require JavaScript), then will we need the editor preferences across all users across our department to be set so that HTML is evaluated, and all of our questions written according to that editor format whether they require HTML or not?

**Comment by aharjula** [comment]
Well, that would be a silly system if the user's editor preferences somehow affected the display of other people's authored materials...

The content+format pair is saved only when editing the material, when using/displaying the material Moodle will simply pipe the content out through a processing pipeline matching the format and the editors will have no role in that.

The major problem is with editing a material if you as the editing user use an editor that does not support the format of the material then you are probably going to cause issues. Unfortunately, there is no way for us to detect the capabilities of your chosen editor and then warn you about this issue.

There is a Moodle-level global default editor setting, that for major installations tends to be a WYSIWYG editor so that students can answer various essay questions and write forum posts etc. without having to understand any markup languages. At Moodle level one can also control the set of editors a given user can choose from, and if those users are particularly technically inept it may make sense to remove options that might cause confusion. And as guided, at the user level one can pick one's editor from the choices available.

The set of possible editors is infinite and I am not aware of a document that would span that set, maybe you can find it in some Moodle documentation. With STACK we allow you to use whatever you want, but if you want to do low-level work like JavaScript we do recommend a particular option as stated in the documentation that Chris linked above.

**Comment by sangwinc** [comment]
I'm glad we've been able to sort this out.

**Comment by fowal44p** [comment]
Thanks for the replies aharjula. 

Does seem a little unintuitive that the one titled "plain text area" is the one closest to using base HTML. That would sound like the one most likely to simply paste what was written as plain text rather than evaluate HTML!
