### ISSUE TITLE
Ordering of nodes in PRT listing

### ISSUE THREAD

**Issue by timlowe** [maths/moodle-qtype_stack#1041]
I just created a PRT with 12 nodes (a temporary workaround until score-as-a-variable works) and notice in the PRT the node sub-forms are given in the order

Node 1
Node 2
Node 11
Node 12
Node 3
Node 4
...
Node 9
Node 10

Not a major issue, just mildly awkward!

[I could understand an ordering of 1, 10, 11, 12, 3, 4 ,.. .]
Tim

**Comment by smborio** [comment]
I had the same issue before. It also happens with input answers but sorted that with renaming them to ans01, ans02, ... (same with 10+PRTs). There's less control on node names though so not sure I can provide a solution.

**Comment by sangwinc** [comment]
We could automatically name nodes 01, 02, 03.  That's not all that difficult.  Is it what we want?!

**Comment by timlowe** [comment]
Sounds good to me!
Tim

**Comment by aharjula** [comment]
Whaaa😭 But I want to have more than 99 nodes... No, seriously this zero padding to two digits is perfect and if anyone ever complains that they need to have proper sorting with three-digit nodes I am perfectly happy to say to them that they are doing things the wrong way and should cut down their node usage. In general, if one is actually classifying over 30 classes and requires more than two nodes for each class their tree needs to be rebalanced and the order of criteria changed.

It is especially, fine as it gives a hint that yes you can have many nodes while at the same time giving an upper limit that while large is still a limit (even if it is only a limit for functioning sorting).

The whole point of "score-as-a-variable" is to cut down the node number in cases where we are not actually classifying but instead are doing gradation of a class, and at some point, people will notice that the feedback text itself can also be a variable (or contain conditional rendering) and further cut down the need for nodes for internal variation of a class. However, I do still consider the answer note as something that should not be a variable and should be left static for analytical purposes and used to name the class identified. The whole point of this chapter now eludes me, but maybe I wanted to say that these new capabilities are there to cut down the need to create nodes just for tuning some detail of an otherwise similarly classified answer., and in the end no one should really need to have a hundred nodes ever.

**Comment by timhunt** [comment]
One minute. PRT node names are acuatlly strings, at least in the database schema. I am not sure that we should mess with them. (But that might not be exposed in the UI.)

They should be shown on the form in the order they were created.

If the order is getting shuffled, I expect that is happening during backup and restore, which is probably a subtle bug.

Remember there is the tidyquestion.php script for doing some sorting out of PRTs.

**Comment by sangwinc** [comment]
I think this is now fixed.
