### ISSUE TITLE
Wrong feedback in Int answer Test

### ISSUE THREAD

**Issue by anst-i** [maths/moodle-qtype_stack#1042]
The following feedback is wrong:

![2023-10-19_STACK-Int-bug](https://github.com/maths/moodle-qtype_stack/assets/52162439/04d4abe5-4d04-4336-be78-a42cc820d656)

The formal derivative does **not** equal the expression which was asked to integrate here!

The student (wrongly) used log(x⁴) as the antiderivative of 1/x⁴. Clearly a term containing 1/x³ is missing in the student's answer (the only thing not visible in the screenshot of the answer field is "+C"), so the formal derivative is not correct.

Here is the zipped MoodleXML of the question if you want to try yourself:
[quiz-Integral-Trainer-Direkt bestimmbare Integrale 20_x^5-x^2-2x+15x^4-20231019-1445.xml.zip](https://github.com/maths/moodle-qtype_stack/files/13042782/quiz-Integral-Trainer-Direkt.bestimmbare.Integrale.20_x.5-x.2-2x%2B15x.4-20231019-1445.xml.zip)

**Comment by sangwinc** [comment]
Andreas,
I think the problem is this language string
https://github.com/maths/moodle-qtype_stack/blob/master/lang/en/qtype_stack.php#L967
rather than the logic of the answer test itself.  I've run through your question and I don't get the note "ATInt_EqFormalDiff" which would indicate the system has established the formal derivatives are the same.  Sorry about this.  I'll fix it, and thanks for reporting the problem.
Chris
