### ISSUE TITLE
Validation does not provide line breaks

### ISSUE THREAD

**Issue by jonaslache** [maths/moodle-qtype_stack#1045]
Hello everyone,

I had a situation where a student who had problems with vision zoomed in heavily on his browser. Entering a longer mathematical expression, he could no longer see his entire entered expression in the validation because no line break (but an overflow) was generated.

Is it possible to include something like this and thus increase the accessibility of STACK?

Best regards,
Jonas

**Comment by sangwinc** [comment]
Jonas,
This is an important issue and it raises interesting questions about where STACK "begins" and "ends".  At the point you describe, the data is being displayed by MathJaX in a student's browser (unless you have another filter for mathematics).  The problem is really about how MathJaX breaks lines in an equation.  Automatic line breaks for equations is a notoriously difficult issue.  Given these are expressions typed by the student the process, or any fix, needs to be automatic.

This is a couple of years old now, https://docs.mathjax.org/en/latest/output/linebreaks.html
and I don't know if there has been any progress.

I'm open to other practical suggestions for increasing accessibility here which we can implement on the STACK end.
Chris
