### ISSUE TITLE
STACK not working after Moodle upgrade

### ISSUE THREAD

**Issue by miroi** [maths/moodle-qtype_stack#1050]
Hello,

after upgrading Moodle to 4.01 STACK question generation suddenly failed and all previous tests with STACK questions are hurt.

Error message says this (STACK) question generated unexpected internal error:

![image](https://github.com/maths/moodle-qtype_stack/assets/1047336/2ef2141b-809a-4079-b2c1-3022f669522b)

The STACK healthcheck  which I see as coadmin reports "The version of the STACK-Maxima libraries being used (stackmaximaversion) does not match what is expected (2023072101) by this version of the STACK question type. Please rebuild your optimised Maxima executable..." It means one has to rebuild the Maxima, right ?

**Comment by sangwinc** [comment]
Sorry you're having problems.  I'm fairly sure this is due to an incomplete upgrade, rather than an issue with the code in the plugin itself.  
Please follow the instructions here: https://docs.stack-assessment.org/en/Installation/Testing_installation/#maxima-optional-packages
If you are still having problems then email me a copy of the output from your Healthcheck script at Edinburgh and I'll take a look.

You will also need to bulk test your materials.  Instructions are here: 
https://docs.stack-assessment.org/en/Developer/Running_question_tests_other_site/

Please also read the release notes for upgrading from 3.x to 4.x here: https://docs.stack-assessment.org/en/Installation/Migration/
There were some big changes between STACK 3 and 4, which have given genuine improvements in the longer term.  Sorry there is some work in the short term for you to do. 

Since this is almost certainly not an issue with the plugin itself I'll close the issue here, but email me and I'll try to help.
