### ISSUE TITLE
Questions based on term - absolute_real_time and make_random_state forbidden

### ISSUE THREAD

**Issue by Famondir** [maths/moodle-qtype_stack#1054]
Hi,
a teacher asked me if it is possible to create questions that are equal for every student but chang from term to term. He has specified lists of values and would like to draw random from these.

I thought about picking at random after something like that:
```
time: absolute_real_time();
seed: decode_time(time)[1]*10+round(decode_time(time)[2]/12);
make_random_state(seed);
```

This should give different values in the questions every term without editing the questions every term. Unfortunately absolute_real_time and make_random_state are forbidden. Is there another possibility to achive the goal of the teacher?

Best regards
Simon

**Comment by Famondir** [comment]
Makes sense. I thought the question state would be saved as is - with all chosen variables fixed -  in the database; not only the seed or something like that.

I tried out if it is possible to use the stack_include() feature for this task, passing a external given number/list determining what elements to choose. This works.

I further examined what this means for test scenarios. The test was configured to always use the latest question variant.

1. You take the test.
2. The script is updated. No problem. The question seems to incorporate the script at the state when ist was saved last.
3. The question is edited later. No problem so far. Your question is still linked with the previous question version.
4. The test gets regraded. Juston - we get a problem. The option always use latest question will swap your questions.

Furthermore, even though you can't add/remove questions after someone took the quiz you still can change the question version to use. So after regrading this will give the same problem.

Conclusion: As it is either do not automatically regrade all students when you chose to deploy latest version of question in test or don't include a script which will lead to such dependencies.

Solution to make both possible on the same time: fix the question variant for a student that took the quiz already. But there are several cases where you want to regrade with new question version (if you fixed a bug). So that solution seems not to be good. Maybe there is something smarter - maybe not.

Anyhow. Should we ban stack_include because of this? Please no. Let the (wannabe) experts be responsible for their doings. Better make them aware of this possible danger in the docs.

**Comment by aharjula** [comment]
Not going to ban includes, those are indeed for people who want to build problems for themselves. Anything potentially changing the question between the time it was used and when its results might be regraded or otherwise observed is going to cause issues if not used with extra care. Eliminating time as a possible source of variance between those uses keeps most people safe, but if we truly forbid absolutely everything people can use to break things then authoring might become somewhat "boring".

Note that the inclusion will be loaded into those old question versions every time the compilation cache (not the CAS-cache) gets cleared, so every time STACK gets updated. So old versions are not safe if they use compilation time inclusions... Even if the quiz keeps on using old versions those versions might need to be regenerated if relevant caches have been cleared, and that regeneration would fetch remote content again..

And yes we do not save the question state as it could get truly massive pretty fast, and storage (and bandwidth) costs are a real issue compared to on-demand regeneration based on the singular seed value and question code, CPU time is way cheaper than IO so better to regenerate. The only state STACK stores are the values of inputs and the seed, from those everything else can be regenerated as long as the question itself has not changed. At lower levels, we do store some static results of transformations of the question code, e.g. the inclusions of external content to the code will go to the so-called compilation cache that contains the results of all such transformations. These transformations are not variant-specific, so only one copy of these exists for a given question version and is being shared by all its variants.

**Comment by sangwinc** [comment]
Sorry Simon, I really think you are fighting against the design here!  We never set out to provide "really random" or even "infinitely genuine different" questions.  That's not the goal of STACK.  If you are coming to the STACK conference in March (or we meet at another conference) I'd be happy to talk about why we made these decisions.  Briefly, since most students only get one or two variants of a particular question I question the need for "really random" or even "infinitely genuine different" questions.  Problems with special cases, and the need to pre-test random versions before students see them all mitigate against genuine random behaviour.  Then we also need to be certain which version a student got!

stack_include is designed to allow sharing of small, stable, libraries of maxima code between questions. Hopefully this makes it easier to contribute to the core of STACK by putting these libraries into https://github.com/maths/moodle-qtype_stack/tree/master/stack/maxima/contrib

I hope this makes sense?  I'm sorry we just don't support genuine time-based variables currently.

**Comment by Famondir** [comment]
Totally fine for me. I just report that this is not intended and my job is done. :)
