### ISSUE TITLE
Error when using ATAlgEquiv

### ISSUE THREAD

**Issue by jonaslache** [maths/moodle-qtype_stack#1055]
Hello everyone,

I have an issue when using the AlgEquiv answer test with `ans1: (2*s^2+6*s-25)/(10*s)` as the student's answer and `ta: 0.1*(2.0*s^2+6.0*s-25.0)/s` as the teacher's answer. I know that there are sometimes difficulties when using floats together with integers and that the test can then fail. However, in my case `ATAlgEquiv(ans1,ta)` leads to the following error message in the Maxima sandbox:

```
The value
  -8.881784197001252e-16
is not of type
  INTEGER
when binding SB-KERNEL::RESULT
algebraic_equivalence: evaluating the difference of two expressions threw an error.
#0: algebraic_equivalence(sa=(2*s^2+6*s-25)/(10*s),sb=(0.1*(2.0*s^2+6.0*s-25.0))/s) (assessment.mac line 927)
#1: ATAlgEquivfun(sa=(2*s^2+6*s-25)/(10*s),sb=(0.1*(2.0*s^2+6.0*s-25.0))/s) (stackmaxima.mac line 1218)
#2: ATAlgEquiv(sa=(2*s^2+6*s-25)/(10*s),sb=(0.1*(2.0*s^2+6.0*s-25.0))/s) (stackmaxima.mac line 1099)
 -- an error. To debug this try: debugmode(true);
```

When using the above combination of teacher's answer and student's answer in a STACK question (SAns = `(2*s^2+6*s-25)/(10*s)` and TAns = `0.1*(2.0*s^2+6.0*s-25.0)/s`), a runtime error occurs and the error message `algebraic_equivalence: evaluating the difference of two expressions threw an error.` appears.

When using the option "Check the type of the response" for the input field, the error `algebraic_equivalence: evaluating the difference of two expressions threw an error.` appears inside the validation box.

Thanks for your help!
Jonas

**Comment by sangwinc** [comment]
Right, I've had a look at this.  The issue is caused because we set the variable `keepfloat:true` at the start of the algebraic equivalence function: https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/assessment.mac#L891
This is to make sure floats (which are often taken as approximate) are not automatically rationalised.

You can probably fix the question by wrapping TAns in `rat`, i.e.  `rat(0.1*(2.0*s^2+6.0*s-25.0)/s)` if you'd like to turn floats into rationals.

Whatever happens I'd like this not to throw an error!  It's a relatively simple comparison, and I'm open to the argument that 0.1 really is equal to 1/10 (etc.).

If we automatically rationalise then this test case will fail: https://github.com/maths/moodle-qtype_stack/blob/master/tests/fixtures/answertestfixtures.class.php#L91
I don't want to change this behaviour.

I think I've found a fix by selectively reactivating this rationalisation, but this will need some further testing.

Chris
