### ISSUE TITLE
ATSets() can't handle "+-". A suggestion

### ISSUE THREAD

**Issue by Mat-Ge** [maths/moodle-qtype_stack#1056]
ATSets() cant't handle the "+-" sign. E.g. the sets {-1,1} and {+-1} are different for ATSets().

I handle this by adding the following code to the feedback variables field. 
ans1N:union(subst("+","#pm#",ans1) ,subst("-","#pm#",ans1));

Maybe this can be integrated into STACK (I'm not quite sure where, probably in stackmaxima.mac, ATSets() or ATSets_prepare() ).

**Comment by sangwinc** [comment]
The +- operator in mathematics is, I think, unique as an operator/function which needs to look "up the tree" to decide how it is interpreted.  That is, it depends on its situation in the whole expression, not on the immediate arguments.  For this reason I wish we could ban in!  Sigh.

It's really problematic when we have more than one +- in a single expression, or worse we have things like  a+-b=c-+d, giving only {a+b=c-d, a-b=c+d} and not all of {a+b=c+d, a+b=c-d, a-b=c+d, a-b=c-d}.

There is a pm_replace function here:  https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/assessment.mac#L1328
That replaces the whole expression using an or, but only works when you have 1 +- in an expression.  

However, you're using +- as a prefix function which is whole new world of ambiguity!!   

I think this issue is really best dealt with on a question by question basis for now?
