### ISSUE TITLE
AlgEquiv and inequalities

### ISSUE THREAD

**Issue by jtufto** [maths/moodle-qtype_stack#1061]
We have some questions where the correct answer is an inequality, for example, 

  ta1: sigma > 1

If testing if the student answer is correct using AlgEquiv in the usual way this mostly works except that student answers using a different variable name, for example, 

  x > 1

also gives a correct answer which is clearly not desireable.   Our site is running STACK version 2023072101 (stats)

**Comment by sangwinc** [comment]
Inequalities are actually being "solved".  That's why these two inequalities are considered equivalent.  There is some inconsistency here in the design, and we probably need to separate out ATAlgEquiv into two tests: (1) syntactic manipulation, and (2) establish the set of solutions (variety).  To make this much clearer.  This situation has crept up over the years....

**Comment by jtufto** [comment]
Ok, thanks for your answer.  So from what I understand the "solution" is always a subset of the real numbers with whichever variable name appears in the expression for the inequality just being a dummy?

Anyhow, I was able to find a workaround by creating a variable e.g. `fb1:(ans1=(sigma > 1))` in feedback variables or testing ans1 against a list of equivalent inequalities using the `member` function.
