### ISSUE TITLE
"Extra options" set to "simp" and number of decimals shown in validation field

### ISSUE THREAD

**Issue by jtufto** [maths/moodle-qtype_stack#1063]
A potentially very useful options for questions with numerical answers is the "simp" option in "Extra options".  This allow students to carry out simple numerical computations by entering expression inside the input field (without having to spend time on using external computational tools) while at the same time seeing the resulting number in the validation field.  For many types of questions (I'm teaching statistics), having the student see the resulting number is an essential part of the learning process, for instance by allowing the student to assess the plausibility of a tentative answer.

However, especially for questions with several inputs where subsequent answers depends on the values of previous answers, it is essential that a sufficient number of significant digits are shown in the validation field when the "simp" option is used.  However, from what I can tell (see the screenshot below), the number of decimals displayed in the validation field appear to depend on the number of decimals in the first floating point number in the expression entered (examples 1 below) unless the first number is an integer (example 2) in which case around 12 decimals are shown.  I guess this behaviour is perhaps related to issue https://github.com/maths/moodle-qtype_stack/issues/649?  From my perspective, this behaviour makes the "simp" option of of limited use in such cases.

For some of the same reasons as above, a nice feature would be an option to have rational numbers (as in example 3 below) shown as a single floating point number in the validation field.

I know that I can alternatively set the "Extra options" to "floatnum" to force the students to enter a single floating point number (computed externally) but I don't think this is a desirable solution as it would be more time consuming and error-prone for the students.  Additionally, not seeing the expression used by the student in the input field also makes it harder for teaching assistants to catch errors in what students are doing.   So having a working "simp" option would definitely be the ideal solution.

<img width="648" alt="Screenshot 2023-11-15 at 15 07 18" src="https://github.com/maths/moodle-qtype_stack/assets/5436691/b87b80a7-7470-4117-8ef0-227f93eba276">

**Comment by sangwinc** [comment]
Yes, we've changed the way we deal with display of floats.  Please can we review this issue after the release of v.4.6.0 and decide what, if anything is needed?

**Comment by sangwinc** [comment]
This issue was also independently raised on Zulip.
https://stack-assessment.zulipchat.com/#narrow/stream/384532-question-troubleshooting/topic/.E2.9C.94.20Validation.20of.20simplyfied.20numerical.20calculations.20in.204.2E6.2E

Having released 4.7.0, we now no longer have calculations being performed when we have `simp:true` and floating point numbers, which is an unanticipated bug we will fix.

The question remains, how many places to display!

**Comment by audaxJOGO** [comment]
@jtufto 
Chris asked for the places to display?

suggestions from my view:

A)
From a physics professor view:
https://en.wikipedia.org/wiki/Accuracy_and_precision#Quantification
1. the first example: 3 significant figures because of 21.5 = 3 sigfigs
2. the second example: 1 significant figures. But may be 1/x is from an physical equation then 2 sigfigs
3. the third example: 2 sig figs

B)
A lazy student view:
take the number with most sigfigs and caclulate it to these sigfigs
1. 5 sigfigs
2. 2 sigfigs
3. 2 sigfigs

C)
if we combine it to minsf:x e.g. minsf:4
1. 4 sigfigs
2. warning because no number with 4 sigfigs
3. warning because no number with 4 sigfigs

Any other suggestions / ideas?

**Comment by sangwinc** [comment]
Thanks - I think to fix this bug quickly, and in the simplest way, we're going to _print_ the number with decimal places sigfigs and caclulate it to these decimal places (not sigfigs).   I think we need a lot more design before we do anything more subtle.  The current behaviour of not doing _any_ calculations on floats is a bug.  The display of floats can catch up when the design is a finished.

**Comment by sangwinc** [comment]
No further comments from the community, so we'll go with this fix for the next version.
