### ISSUE TITLE
Strange behavior of equivalence reasoning and AlgEquiv with explicitly false equations

### ISSUE THREAD

**Issue by Mat-Ge** [maths/moodle-qtype_stack#1071]
Equivalence reasoning and AlgEquiv behave strangely with explicitly false equations. Why does it matter whether I write 2=0 or 3=0?
![grafik](https://github.com/maths/moodle-qtype_stack/assets/128398586/91205bae-e610-49fa-95ff-b4bfbe18e678)
![grafik](https://github.com/maths/moodle-qtype_stack/assets/128398586/f020d017-15f0-4043-ba86-365d308396c1)

**Comment by sangwinc** [comment]
The reason for this is the order in which we currently perform checks.  We check if the LHS of each equation is the same first.  So in

2=0
2=sqrt(5)

the LHS of each is identical.  This is a hangover from wanting to check individual pairs of equations, rather than lists of equations. I agree, this inconsistency is bad and I'll fix it.  Thanks for the bug report.
