### ISSUE TITLE
Input as question variable in STACK

### ISSUE THREAD

**Issue by polyneikis** [maths/moodle-qtype_stack#108]
Hello. 
I would like to ask about a possibility. 
I want the students to give three initial inputs (ans1,ans2,ans3) as input data and use these answers as question variables for STACK to compute the correct answers for ans4, ans5, ans6. In this way i want to randomize the input data for each student, without using the rand function, because i don't want the student to get different initial data each time he/she closes and opens the window of the exercise. 
So, i don't want the first three inputs of the student (ans1,ans2,ans3) to be validated, but just submitted by them. Is there a way to do this or any other idea on the issue?

Thank you very much for the help,
Polyneikis

**Comment by aharjula** [comment]
You could construct the correct answers based on the student input in the "Feedback variables" part of the potential response tree. You could also use separate response trees to generate "feedback", without grading, so that you could build a question text based on those values.

But you do not need to as the random state will persist between sessions for a student if the question is used in a correctly configured quiz. Adaptive mode and attempts that do not close before they are asked to close.

**Comment by polyneikis** [comment]
Thank you aharjula for the help. Let me ask some things about these you said. Can a student save his solution before submitting it and the random data (made by rand function) be locked so as to use the same data even if he closes the window and opens it again?

**Comment by aharjula** [comment]
Yes assuming that you do not configure the Moodle quiz otherwise. Typically, Moodle quizzes save the value of inputs when switching pages but this is something that depends on your Moodle and the way you have configured it especially how you have configured the quiz. Generally, just set the "Question behaviour" of the quiz to "Adaptive mode" and all should be fine.

The random data comes from a random number generator that has its seed number locked to the quiz attempt and therefore will generate the same values for the same quiz attempt. Closing windows or sessions does not matter as long as the student returns to the same quiz attempt.

**Comment by sangwinc** [comment]
Thanks Matti, and I hope this works.  

You might find this page helpful:  https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/CAS/Random.md

Also, I know some scientists have used STACK with experiments.  There each student does get their own data.  They feed this in as ans1 etc. and STACK asks them to calculate a value based on their own data, which STACK is able to check.  

You can turn validation off, but I don't recommend it except in very rare cases!

**Comment by timhunt** [comment]
Just to give a bit more data about Moodle randomisation. It is actually a pseudo-random but deterministic function of the student's userid, the quiz id, and which attempt it is. So, throughout the student's firs quiz attempt, the variant will not change. Then, if they are allowed a second attempt at the whole quiz (after doing submit all and finish on the first attempt) then they will get a different variant.

(Unless you turn on the 'Each attempt builds on last' option in the quiz, in which case, they will get the same variant for each attempt, as a side-effect of what that option does.)
