### ISSUE TITLE
Display of single unit with negative exponent

### ISSUE THREAD

**Issue by Famondir** [maths/moodle-qtype_stack#1080]
Hi all,
is there a solution do display something like `1/s` as `1 s^-1` instead of `1 x 1/s`. Or at least can the `x` be dropped? Some teachers here complain that this looks like a cross product without any (for the students noticable) vectors in sight.

**Comment by Famondir** [comment]
It would be cool if the `make_multsgn` function would work for unit display as well:

```
{@(make_multsgn("blank"), stackunits(1, s^-1))@}
{@(make_multsgn("blank"), a*b)@}
```

For inline displayed fractions it would be handy to get a `(a)^-1` display additional to `1/(a)` option with `stack_disp_fractions` that also should work with unit display.

**Comment by sangwinc** [comment]
Sorry it's taken a while to look into this.  The line of code which is relevant is this one 
https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/stackunits.mac#L413
it hard-wires the TeX output of `stackunits` without any multiplication symbol.  That's by design.  To over-use the `make_multsgn("blank")` function for this as well would cause chaos, since the symbol for multiplication is logically independent of the symbol for displaying units.  Just for reference the `make_multsgn` function is rather primitive:
https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/stackmaxima.mac#L216

Instead I think we need a separate option to control the display of the multiplication symbol used in stackunits, following the example here:
https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/stackmaxima.mac#L225C1-L225C45
