### ISSUE TITLE
Fractions with multiplication sign option "only numbers"

### ISSUE THREAD

**Issue by Mat-Ge** [maths/moodle-qtype_stack#1087]
This problem does not occur with the demonstration server (STACK 4.3.7). The problem therefore seems to be either with the new STACK version 4.5 or its a local problem with our server.
![grafik](https://github.com/maths/moodle-qtype_stack/assets/128398586/0a6cc8f9-558c-446e-b0f9-5fbeb912d13b)

**Comment by sangwinc** [comment]
Thanks for reporting this.  This is a new feature, and we didn't have this as a test case.  The problem is that some statements are "unknown" do not evaluate further in if statements in Maxima.  As you'll see from the fix, with simp:false (as with validation) we need to explicitly check something is the boolean true to fall through to the else clause here.
