### ISSUE TITLE
Number of attempts

### ISSUE THREAD

**Issue by impemic** [maths/moodle-qtype_stack#1125]
Hi,
I read the thread 182 "Designing the number of attempts feature" but sorry, I didn't understand much..
Is there any variable I can use in Feedback variables in order to know the number of attempts?
I woud use it in this way: after 2 (e.g.) uncorrect attempts, in  the false feedback I want to show the right answer, so that students can answer the next questions.  Is it possible? Thanks.

**Comment by aharjula** [comment]
As #182 states at the end, those features are to be implemented as a new question type, so that STACK does not get too complicated. There are some [implementations](https://zenodo.org/records/3944786) for doing this with JavaScript on top of STACK. The new question type providing such data is called Stateful, and there are no publicly available tools for authoring with that at this time. At this point in time, I, the developer of Stateful, have my hands full with current testing partners and am not prepared to help any new ones into the system.

So, no variables telling you any counts are available, nor any definitions for what would be counted for such counts. But you can count anything in JavaScript, and using some hidden input, keep a hold of that count if you really want to make your life complicated.

**Comment by sangwinc** [comment]
Thanks for raising this - as @aharjula has said this isn't something currently supported or in our near-term plans for STACK.  So I'm (reluctantly) closing this issue as a duplicate and as having been "resolved" (if not with the feature you've asked for!).  Sorry, and thanks for your interest.
Chris
