### ISSUE TITLE
Checkboxes "Whether correct" still have no function

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#114]
Hi!

We are now starting to produce stack questions for an elementary course on ordinary differential equations.

I tried to disable all four boxes "Whether correct" in a quiz, but the red banner saying that the answer is wrong still shows up: https://www.dropbox.com/s/bl6vp81npwg86hq/Feedback%20errors.png?dl=0

**Comment by timhunt** [comment]
I think STACK classes that as '(Specific) feedback' in Moodle terms. I guess we need to decide if we consider that a bug or not. It might be quite hard to change. (Not sure.)

**Comment by alcarola** [comment]
The specific feedback seems to be the feedback from the PRT. Is it not possible to separate the red/green feedback from the PRT feedback?

**Comment by timhunt** [comment]
That is how it is at the moment. Because of the way we assemble the feedback into one CAS text, and then evaluate it, I am not sure how easily it would be to make the different types of feedback response to different question_dilsplay_options properties. If it is not too hard, we should probably make the change. However, I am in the middle of somethign else, so I don't want to look at that code now. If you can make a patch, I will happily review it later.
