### ISSUE TITLE
Right answer does not render in Moodle 2.8 with the new MathJax filter

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#115]
Maybe this is a Moodle issue, but I report it here just to get started.

The problem is illustrated in the following screenshot: https://www.dropbox.com/s/bl6vp81npwg86hq/Feedback%20errors.png?dl=0

This has low priority for us, because it currently seems unlikely that we'll display the right answers anyway.

**Comment by sangwinc** [comment]
Thank you very much Michael for reporting this.

The issue also exists in Moodle 2.7.  I think this arises because we are now using Moodle's filter system for MathJax, not just relying on Javascript in the additional HTML.  There may be some other situations when this arises, so please let me know!  (Apologies in advance, my production system is behind Moodle development here).

See https://github.com/maths/moodle-qtype_stack/commit/1c5ec5dba311f8a6c171d3695d90e8004dce2ddd 
for a potential fix.  Tim will confirm is this is really the correct Moodle thing to do (I hope), and close the issue.

**Comment by timhunt** [comment]
Sorry, but I am afraid that is the wrong fix.

format_text is used for outputting content that was created by the teacher (like the question text or general feedback). The correct response display is created by the system, so it need to be passed trough some other output function. 

I think the right thing is to call one of the stack_maths functions with $this->session->get_display_key($name) before that is passed to $input->get_teacher_answer_display, but I can't quite work out which now.

**Comment by sangwinc** [comment]
OK Tim,  thanks for this. We should have chat about these functions next time we meet!  I've made a change and hope this is ok, as it isn't quite what you suggested here....
