### ISSUE TITLE
different moodle instances

### ISSUE THREAD

**Issue by sdirnboeck** [maths/moodle-qtype_stack#1157]
Hello! 

We are currently still in the beginning stages of using STACK at our university. So we will be creating the questions for one of the courses on a test instance of Moodle. On the live system (that students have access to) STACK has not yet been installed. 

Could we run into any issues when exporting the STACK questions from the test instance and importing them to the live system? Anything we will have to look out for? 

Any tipps/advice is much appreciated, thank you!

**Comment by sangwinc** [comment]
When you create/save a STACK question it gets tagged with a version number.  The bulk test system uses this to we can flag any potential changes - the code is here: https://github.com/maths/moodle-qtype_stack/blob/master/question.php#L1464

We try to keep changes to a minimum, but sometimes we have to make changes and so we try to flag where a question might be affected.  Please test your questions: https://docs.stack-assessment.org/en/Authoring/Testing/
If you add test cases then you can bulk test your questions:  https://docs.stack-assessment.org/en/Maintaining/#bulk-testing-stack-questions-on-your-site

This is not an issue with the plugin, but rather a best practice question, so I'll close the issue here.  Please do engage with the community on the Zulip chat.  Colleagues are normally very generous with helping new users.

https://stack-assessment.zulipchat.com/#

Thanks for your interest in STACK.  Please keep in touch!
Chris
