### ISSUE TITLE
Shortcut for stackvector()

### ISSUE THREAD

**Issue by Famondir** [maths/moodle-qtype_stack#1198]
Hi all,
a teacher here wants her students to type in formulas marking vector elements. Instead of $F = m \cdot a$ she wants to get $\vec{F} = m \cdot \vec{a}$. Unfortunately the `stackvector()` function ist pretty long. Defining `vec(x) := stackvector(x)`in the question variables helps shorten the required input for students but does not get evaluated in the validation.

Using JS to parse the input of the student and replacing `vec(` with `stackvector(` did not work out, because the AJAX validation does not get triggered and would have been a workaround anyhow.

Is there a way to let students specifiy which elements are vectors and which not already or planned for future?

Furthermore it would be nice if the `stackvectortex` option gets send to the validation not only `texput` options.

Sincerely Simon

**Comment by aharjula** [comment]
Sounds very much like yet another case for that "preamble", i.e. some way of declaring that this part of question variables should be present when validation gets processed.

So, at this point, the preamble could contain:
 - `texput`-rules direct or [generated from some constructors](https://github.com/maths/moodle-qtype_stack/issues/1133)
 - `declare` and `remove` statements [adjusting the properties of certain identifiers](https://stack-assessment.zulipchat.com/#narrow/stream/384532-question-troubleshooting/topic/stack_reset_vars.20in.20checkvars.20.20.26.20undefined.20function.20feedback)
 - "aliases", i.e. function declarations like in this issue
 - it could also contain any future logic needed for declaring custom units and their presentation

**Comment by sangwinc** [comment]
@LukeLongworth would you like to comment on how this relates to your work on a linear algebra library?

**Comment by LukeLongworth** [comment]
Thanks for the ping Chris! I think that my thoughts are summed up in #1133 which Matti referenced above. The things that I would most like to have access to would be:
- `if something then texput(...)` so that I can import something like `linearalgebra.mac` for its functions and deliberately omit its `texput` formatting options.
- Iterating through a for loop. Something like `differentials: [da,db,dc,...dz]` and then `for d in differentials do texput(...)` would be handy. This feels functionally the same as the previous point though.

**Comment by aharjula** [comment]
That omitting of library `texput` rules is a great example, we can even take it one step further, just imagine a common linear algebra library with tunable rules so that the logic stays the same, but if one, for example, wants to have arrows on top of their vectors (or not), they can simply set an option (some library-specific variable before including the library) to pick that particular styling. But for that to be possible, we really need to have the ability to have arbitrary logic wrappers for those `texput` rules.

**Comment by sangwinc** [comment]
Yes, this will ne fixed with issue #1133.
