### ISSUE TITLE
Typesetting of 'diff(y(t),t,2)

### ISSUE THREAD

**Issue by AndersSkj** [maths/moodle-qtype_stack#120]
With Question variable
q: 'diff(y(t),t,2)-'diff(y(t),t,1)*(b+a)+a*b*y(t) 
and Question text
\[@q@=0\] 
I get incorrect typesetting:
![capture](https://cloud.githubusercontent.com/assets/11663517/6845752/68781e36-d3c0-11e4-897e-ed44756e0fb0.PNG)
wxMaxima typesetting for comparison:
![maxima diff-typsattning](https://cloud.githubusercontent.com/assets/11663517/6845701/039f790a-d3c0-11e4-8a32-99b81cd54fe5.PNG)

**Comment by sangwinc** [comment]
Oh dear, sorry.

The source of the problem was an attempt to typeset derivatives such as this as
\[ \frac{\mathrm{d}y}{\mathrm{d}t} \] 
Note the y is in the numerator of the derivative operator.
See https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/stacktex.lisp
lines 162-177.  If you omit these lines you'll revert back to wxMaxima typesetting.  This is a bug, and I'll try to fix it.

**Comment by sangwinc** [comment]
I think I've fixed this.
https://github.com/maths/moodle-qtype_stack/commit/a12ec2995fa3318e8dcb1211fad67976b50fec54
Please let me know if you continue to have problems.

Thanks very much for reporting this.
Chris
