### ISSUE TITLE
ordergreat broken in v4.6.0

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#1207]
Sorry folks, 

This commit
https://github.com/maths/moodle-qtype_stack/commit/c7036bd7c74d3ab2ea9a3f3fe95e6d9ed430f447
is causing problems with questions using ordergreat in questions for v4.6.0

We will fix this.

**Comment by sangwinc** [comment]
See also issue #887, which is now also fixed.

**Comment by sangwinc** [comment]
@georgekinnear, sorry your question with `ordergreat` isn't operating as expected. The reason is documented in the above commit.  Yes, when we address your very helpful suggestion in issue #1302 you'll be able to find any others....

**Comment by georgekinnear** [comment]
I've had some questions using ordergreat/orderless behaving strangely since our server was updated, and I figured it was related to this issue.

Having spoken to @sangwinc I now understand that the ordergreat gets pulled out of the maxima code and applied once and for all before any other maxima code is run. My questions that were misbehaving started with:
```
v:x;
u:u;
ordergreat(v,u,C);
```
which in effect was being evaluated as
```
ordergreat(v,u,C);
v:x;
u:u;
```
and it meant that the intended ordering was not taking effect since the "v" and "u" had not been defined yet.

The solution in my case was just to remove the ordergreat (it didn't actually seem to be necessary in my case).

**Comment by georgekinnear** [comment]
Just looking a little more into ordergreat, and I see that there is an `unorder` function: https://maxima.sourceforge.io/docs/manual/maxima_33.html#unorder

Perhaps another way to handle `ordergreat`/`orderless` in a question - rather than pulling them all out front - would be to prepend each one with an `unorder` to avoid the "reordering is not allowed" message?

**Comment by sangwinc** [comment]
Thanks @georgekinnear but the real problem is that ordergreat has to be executed outside the block.  It only takes effect in the next block.

Compare the two:

````block(ordergreat(a),p:a+b);````
and
````
ordergreat(a);
p:a+b;
````

The use of unorder() does not fundamentally change that problem.  So, we still must pull them out front.
