### ISSUE TITLE
Validation of variables used in an answer

### ISSUE THREAD

**Issue by timlowe** [maths/moodle-qtype_stack#121]
A suggestion from a student, that sounds quite useful to me. To help students validate their answer, it might be useful to include in the answer validation display a list of the variables used in the answer. So under the formatted display of a students answer, include something like:

The variables used in your answer are: x, yz

where is list is nicely formatted output from  listofvars(....).
This would help students recognise when a variable or function has been inputted incorrectly.
(Of course, if the answer is a number and includes no variables, the list should be omitted).

Tim

**Comment by sangwinc** [comment]
I think this is a great idea, and would be a substantial improvement.
See https://github.com/maths/moodle-qtype_stack/commit/a5e79eac1c8185353ff3841e409af6a437bcf916

Thanks Tim.

**Comment by villehavu** [comment]
This change actually caused a small problem when using Stack in physics problems. The physical units the student is required to enter in his/her answer are technically variables from which the coefficients are stripped and checked that their numerical value is correct. Now the validation of a student's answer such as

0.13*m/s

leads to a response:

The variables used in your answer are: [m,s]

but the "m" and "s" here stand for metre and second that can't be considered variables of course. Checking the answer still works fine but I worry that such a response can be confusing to some of the students. Disabling the validation is one option of course but I like the idea that the students get to know immediately how the system interprets their input. From the physics user point of view it would be helpful, e.g., to give a response:

The units in your answer are: [m,s]

Regards,

Ville

**Comment by sangwinc** [comment]
Ville,

I'm really sorry this change has caused you problems.  Dealing with units in a better way are on my "todo" list but I didn't anticipate this when I made this change.

I think what is needed here is a new option for the input to display this or not, with the default to display it.

**Comment by villehavu** [comment]
Hi Chris,

Yes, that would solve the problem.

Ville

**Comment by aharjula** [comment]
Hi,

What about mixed cases? I know that there is no reason for things like this: "A=w*h*m^2" but the world if full of other constants that people might want to include in various answers. Obviously you are already identifying pi as constant and removing that from the list (I'll just assume that that is had-coded), could we have some way of declaring other symbols as constants? declare(m,constant)? Naturally, only when we need that declaration. So that we do not block variables from other uses, m being an obvious example of thing that appears often as a variable as we'll as a constant.

The big problem obviously is that how would that information be passed from the question to the AJAX validation? If that could be done I would hope that I could pass texput commands at the same time... For those units and other symbols...

-Matti

**Comment by sangwinc** [comment]
Yes Matti, this is straying into what the "units" testing functions should do.  I agree that if we are working in the context of units, then these shouldn't be considered as "variables" here!  Units will take some thought!

**Comment by sangwinc** [comment]
Ok, I hope this fixes the issue.  Sorry Ville but I chose the change in behaviour (showing a list of variables) to be the default, so I hope you don't have to edit too many questions to update the behaviour to what you want.

**Comment by villehavu** [comment]
Thanks, no problem there.

I agree with Matti that in the long run physics users would benefit from consistent handling of units. From CAS point of view units are something rather special:
- They can't be used as variables but are more like constants.
- They have a well defined rules to covert them back to the base units in the SI-system
- They are typeset in roman opposed to italics used with symbols.
Stack is good in problems in physics since it can deal with units better than many commercial systems from major publishers.

**Comment by aharjula** [comment]
No need to reopen this, but could we get this merged to 3.4? Otherwise I will have to setup a test environment for Ville to test this.

-Matti
