### ISSUE TITLE
Load questions from the "samplequestions" folder direct into a Moodle question bank category

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#1253]
This proposal is to add a new page in the /adminui folder to allow teachers to load questions from the "samplequestions" folder direct into a Moodle question bank category.

The page will list all questions, but subdirectory (perhaps using HTML details/summary tags to nest sub-directories).  Select questions using checkboxes and then upload them to a chosen Moodle question bank category.

In parallel, we'll release materials (e.g. HELM) into this folder to provide a ready-made selection of materials.

**Comment by sangwinc** [comment]
@EJMFarrow  thank you so much for addressing this issue - I think what you've done is really excellent here and very valuable.

Some initial comments.

1. Please could you make it more prominent when a question has been uploaded?  I would like a much clearer confirmation, as I uploaded the same question twice.
2. I really like the idea of getting to the library from a STACK question.  That's a great idea.  When you add a new question to a quiz, then follow this link, there is a change of context.  Could we fix that bug please?
3. I'd like to make the library page generally available.  It _should_ work for all question types, (not just STACK) as we'd like to distribute libraries of questions using any moodle format.  (Eventually, we'll provide access to libraries exported with gitsync.)  I'm not sure how to do that, but suggestions are welcome.

**Comment by aharjula** [comment]
Having seen the screenshot in the pull request and nothing more, I am very excited about this thing. My wishlist, however, might be a bit more outside of a single question-type style of a thing, like that third point from Chris.

 - Obviously, we will want to be able target a gitsync repo as an alternative source of material instead of just the sample-directory.
 - We would also want to be able to target multiple such repos... and most importantly assign which repos are visible to who, not everyone wants to see those annoying questions of the other field that shall not be named cluttering the lists and vice versa. Maybe some sort of subscription by user by user basis, with separate approval or enrolment keys.
 - At some point there will naturally come the issue of how to pull an upgraded version from here on top of the one pulled last time, so syncing with this might be nice. So, remembering from where the imported question came will be of some interest. _Did not look at the code to check if this is already solved there..._
 - In particular, that syncing, will be necessary if we ever gain the option to push into this through this, i.e., update or add new things. And in that case we really also need to control who sees a particular repo and who can write to a particular repo.
 - Also, if that third point of Chris were ever to become a thing, we would probably need to get other `qtype`-plugin creators to agree on some common layout of their samples and related metadata so that this could iterate over them all.
 - Finally, while it might seem to make sense to separate STACKs sample questions into a separate "gitsync" repo and point this to a master source of that, it would be a bad idea due to these reasons, so we should keep it in the local file-system under the `qtype_stack` (naturally where it is sourced into the release version is an entirely different thing):
   - Anything remote might not be accessible from some closed installations.
   - If we maintain the remote, then we need to keep it up all the time.
   - It the demand for that becomes large, it might cost money to us.

In the end, I am wondering if this belongs to `qtype_stack` or if it should be something like a customisable UI for `qbank_gitsync`, probably some new `qbank`-thing?

**Comment by sangwinc** [comment]
Thanks @aharjula, as ever you are way ahead with these suggestions!  Yes, logically this should probably be a separate plugin, but that makes is much harder to install.  It will be much easier to move this to a dedicated plugin later.  The short term/immediate goal, is to give question authors access to materials we already release.

@hayden-MB I agree some kind of interactive preview would be really valuable.  I don't want to work at cross purposes with the external question bank project which @m-r-k is working on.  (Please do comment on this development @m-r-k!).

Let's just acknowledge how much work @EJMFarrow has done in getting a rendered (static) preview, which is only now possible thanks to his incorporation of the new API into the STACK codebase.  This is all going in a very exciting direction.

We'll also need some help in sorting out, tidying up, and exporting the existing materials we want to distribute.

Thanks all,
Chris

**Comment by EJMFarrow** [comment]
Thanks for all the feedback so far. (More welcome!)

To consolidate:
- I'll make import confirmation clearer.
- The change of category/context when adding from a quiz is more a limitation than a bug. When creating a new question normally from the quiz, the question defaults to the default category for the course and the user has to select the quiz context on the edit form. I'm not sure I can do better than that but I could (presumably) fairly easily include a similar category select on the library page.
- The API currently (and rightly) rejects any non-STACK questions. I could maybe just display the question text with a disclaimer for non-STACK questions (rather than a render) as a starting point. Importing non-STACK questions from the library page already works.
- I'll look again to see whether it's possible for STACK to make changes to the quiz and/or question bank pages to make access to the library more directly available and less STACK-specific. I guess importasversion adds itself to the action dropdown for all questions so that would be something at least.
- GitSync/remote repo integration is a way off. This is a quick way to give users access to some questions. (Keeping the STACK sample questions in the local file system is definitely the intention.)
- Allowing synching of a previously imported question is probably a niche requirement. There's no option to do so at the moment. Could we allow the importasversion filepicker access to the STACK library if available?
- Getting useful, consistent metadata for STACK questions, let alone from creators of other question types, is... unlikely. :) I'm rendering the question text because there didn't seem to be any other reliable way to give users even an indication of what they might be getting.
- Question interaction: I should at least be able to fix dropdowns so users can see the potential answers. As for interaction beyond that, are we talking validation and grading? If so, that's possible but definitely 'non-trivial' in terms of effort.
- Displaying PRTs: That would require a bit of layout and design. I'd need to add tabs to the page as the amount of information would be large. At some point as we add more info and interactivity, performance will take a hit. What is our use case here? Is it 'I want to quickly click down a list of differentiation questions, import a few I like the look of and take a closer look later'? Or is it 'I want to take my time exploring all these questions and only import the ones I'm sure of'?
- I'll try to make the navigation more useful. Ideally a user would be returned to the quiz or questionbank page depending where they started from. Is there any other way into the question edit page?

**Comment by hayden-MB** [comment]
You can also access edit from a quiz preview :)
