### ISSUE TITLE
The field to write “Node 1 feedback” does not appear.

### ISSUE THREAD

**Issue by elzeviro** [maths/moodle-qtype_stack#1266]
Hi, 
I have a problem, when I go to write a question with STACK, it doesn't display the field where to write the “Node 1 feedback” (see enclosed screenshot) when I use Google Chrome Version 129.0.6668.58 (Official Build) (64-bit). 
Even though I use Firefox 130.0.1 (64 bit) it does not work. Only with Firefox you are able to unlock and view the field: for example, just click on view source code and close it and the TinyMCE box appears. 
Any suggestions?
 
P.s. 
The version of STACK is 4.6.0 for Moodle 4.0+
2024060300. The healthcheck passed without detecting any issues.
The version of TinyMCE is 6.3.2
 
![The field of the Node 1 feedback does not appear](https://github.com/user-attachments/assets/0f5104fe-fd80-4585-b8c1-14f63aec52dc)

**Comment by sangwinc** [comment]
Oh dear!  That's very annoying for sure.  

We strongly recommend users do not use the TinyMCE editor.   Most of these editors mess up JS code.    Instead turn off the editor within Moodle and edit the raw HTML.  Individual users can set their editor preferences:

User Dashboard > Preferences > Editor preferences > Manage editors

**Comment by sangwinc** [comment]
@LukeLongworth I think you asked me to increase the number of lines for PRT feedback some time ago as well?!

**Comment by LukeLongworth** [comment]
@sangwinc yes my colleague Michael has a browser extension that adds a few lines to a lot of different fields. The most important one to me is the PRT feedback because one line is definitely too few in my opinion. I would propose 3 lines by default (so I can have a `<p>` tag, content on the next line, and then `</p>` on the third line), but really anything more than one would suffice.
