### ISSUE TITLE
Validation of x^+

### ISSUE THREAD

**Issue by georgekinnear** [maths/moodle-qtype_stack#1281]
I have an algebraic input (with "don't insert stars") where a student typed `x^+5` when they had meant to type `x^2+5`.

I've tried this out for myself and the validation message looks a bit strange:
![image](https://github.com/user-attachments/assets/e65028b8-1a88-474a-a085-d35c736f8497)

Inspecting the MathJax, the underlying tex is apparently `x+^{5}`

I would have expected this would either (a) be flagged as a validation error (the ^+ being an odd combination), or (b) the expression would be interpreted and displayed as x^{+5} (which is what seems to happen if I type this into maxima).

**Comment by sangwinc** [comment]
This has already been reported, and is related to this testcase.
https://github.com/maths/moodle-qtype_stack/blob/master/tests/fixtures/inputfixtures.class.php#L420

It's related to Maxima's `tex()` function, not something we do in STACK specifically.

A minimal example in wxMaxima is

````
simp:false;
p:sin(+x);
tex(p);
````

Your example is

````
simp:false;
p:x^+5;
tex(p);
````

This gives `$$x+^{5}$$` which is why this ends up in STACK.  Please can you raise this with the Maxima community @georgekinnear?

**Comment by georgekinnear** [comment]
@sangwinc  done - see https://sourceforge.net/p/maxima/bugs/4388/

**Comment by sangwinc** [comment]
This appears to be fixed in Maxima 5.48.0 onwards.
