### ISSUE TITLE
Problem with ATString

### ISSUE THREAD

**Issue by jonaslache** [maths/moodle-qtype_stack#1313]
Hello everyone,

I know that this is a rarely used answer test, but I think that there might be a confusion: In the corresponding page in the [docs](https://docs.stack-assessment.org/en/Authoring/Answer_Tests/String/), it says:

> This test performs a string match ignoring leading and trailing white space which are stripped from all answers, using PHP's trim() function.

However, when testing the answer test in the CAS chat using for example `ATString("hello", " hello ")`, the test fails. The same happens when testing the answer test in a response tree inside an actual STACK task.

Now I wonder if this is the intended behaviour (in this case, I either misunderstand the docs or the docs are wrong) or if this is a bug.

Thanks and best regards,
Jonas

**Comment by aharjula** [comment]
One thing is certain: ever since we transferred all ATs to execute fully in CAS, they have not been able to use PHP's trim(). I wonder if string inputs do the trim before turning the content to Maxima "strings"? If that is the desired behaviour one can immediately use Maxima `strim()` to selectively remove specific chars, matching PHP trim() whitespace might require a longer sequence though:
```
ATString(strim(" ", "hello"), strim(" ", " hello "))
```
