### ISSUE TITLE
Question edit form renders slowly if the PRT has many nodes

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#133]
I guess you have also noticed the phenomenon in the topic. In firefox in ubuntu, typing in text is also very slow when the prt is big, but it works fine in windows and osx.

It is a real pain to edit a question with a big prt, with lots of waiting between every test preview of the question. Can anything be done about this, on the client or server side?

**Comment by timhunt** [comment]
I think this is a bug with Atto auto-save. I see the same with some multiple choice questions. It can also happen when you click save. It waits for all the editors to finish auto-saving before it submits the form, which can be quite irritating.

I tried reporting it at https://tracker.moodle.org/browse/MDL-48756, but so far little has happened.

So, I think all we can do is close this issue here, since I don't think this is STACK-specific.

**Comment by alcarola** [comment]
Actually, I still use tinymce.

**Comment by timhunt** [comment]
OK, alternative explanation: TinyMCE is very heavyweight, and things get very slow when there are many in a form. Still not a STACK bug.

**Comment by alcarola** [comment]
OK. Was just going to write that it is opening the form that takes a long time, not closing it. I can try if it works better with atto.

**Comment by alcarola** [comment]
Indeed, atto is much faster; thanks a lot for the advice! 

A drawback with using atto is that the latex editor plugin I adapted for tinymce probably doesn't work.
