### ISSUE TITLE
Variable names with numbers in not supported

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#134]
Today I spent some time debugging, before I figured out that variable names such as ans1p1 confuse stack. They work fine in maxima.

Maybe nobody cares about this, but I report it for your information.

**Comment by sangwinc** [comment]
I'm sorry your time has been wasted on this.

This confuses STACK because we try to insert * characters, i.e. in your case you will get the error:

You seem to be missing * characters. Perhaps you meant to type ans1*p1:x.

This was intended (to help authors) but will be frustrating to more advanced Maxima users who expect to be able to do *exactly* what the do in Maxima in STACK.  How annoying is this, and do you have a proposal?!

**Comment by alcarola** [comment]
Ah, it didn't occur to me that variable names and input in input fields both go through the inserting-asterisks treatment, but now I know. I do not find it annoying at all, and once I noticed, it is not even confusing. This report was mainly for your information, that I bumped into this by accident. I propose to leave things as they currently are, regarding this issue. :)

Thanks a lot for responding to all the issues I had raised!
