### ISSUE TITLE
Validation not showed before Check is pressed

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#136]
(Edited after initial post) 

In [this question](https://www.dropbox.com/s/y0r3yl8v40tih0t/No%20validation.xml?dl=1) the validation is not displayed before i click Check (and after that it's too late to correct any typing-in mistakes). See screen shot for the preview settings I use. 

![screen shot 2015-06-19 at 00 27 38](https://cloud.githubusercontent.com/assets/1645276/8243210/9c6a002a-161d-11e5-91fa-39f213515839.png)

**Comment by timhunt** [comment]
In the input setting you have "Student must verify" turned off for the ans1 input.

If you want the validation to appear, turn that on. I think this is not a bug.

**Comment by alcarola** [comment]
Aha, I misinterpreted the terminology then. I thought validation is that the student sees how the answer was interpreted in 2D notation, whereas verify meant that the student has to do an extra click that "yes this is really what I want". OK, I change the settings.

**Comment by alcarola** [comment]
Still I'm a bit confused about why there are two different options: validation and verification. If I turn off verification, then validation doesn't work. If, the other way around, I turn off validation, but keep verification on, then I cannot check the answer, I just get "Please verify that what you entered was interpreted as expected." 

So, what I can understand, verification has to be turned on if and only if one wishes to have validation, which would make little sense.

**Comment by sangwinc** [comment]
I'm sorry all this is unclear.  There are two separate things.
(1) forcing the two-step validation process.  
(2) displaying the results of validation.

Both options are with or without instant AJAX validation going on in the background.

For some input types, like "true/false", forcing (1) is tedious, and also a teacher might not want this displayed.  No a "no & no" option does make sense here.

Note, algebraic expressions are always validated, and if an invalid expression is found, this feedback should always be displayed.  My tests tonight suggest this is happening!

Does this make sense?  If it doesn't make sense to an experience user like you there is no hope for anyone else......!  I'll improve the docs.

The option "must verify"=yes and "display verification"=no does not make any sense, and results in a situation where the student can't answer the question.  This is because the HTML form doesn't contain a validation version of their answer.  In the past I've left it to teachers to choose sensible options, but here I think we should not allow teachers to chose this combination.  

Thanks for reporting this and apologies I've taken months to respond.  The move to Edinburgh has absorbed a lot of spare energy....
