### ISSUE TITLE
PRT-naming name length limit...

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#142]
Interesting bug appeared when an author decided to give very descriptive names to the PRTs... The field storing the PRT-name is 32-char long but these problems appeared well before that. The tracking of this bug took some time but basically the problem is in the way the question attempt related state is stored into the database table "question_attempt_step_data" which is basically a key-value store with keys limited to 32-char length.

And as STACK builds keys like "-_rawfraction_prt1", where that "prt1" is the name of the tree, the fields tend to overflow and the database will cause an error which will tell very little to the user.

To reproduce, just create a PRT with a name which is over 18 chars long. Then try to answer to that question so that that PRT activates.

I am not really worried about this issue but maybe at some point in the future those keys could just use the index of the PRT instead of the name.

-Matti

**Comment by timhunt** [comment]
"-_rawfraction_prt1" is 18 chars (if I can count) so we should alter the editing form to validate that PRT names are no more than 14 chars.

**Comment by aharjula** [comment]
You can go up to 18 those last four ("prt1") chars there are part of the name.

**Comment by timhunt** [comment]
And, while we are at it, presumably Input names should be limited as well, because of validation and matrix inputs

{name}_val
{name}_sub_99_99

2 digits for the matrix indices should be plenty, so that would allow up to 22 chars for the name. However,  that is close enough to 18 that I think we should limit it to 18 chars for both, since that is easier for people to remember, and is also reasonably long.

For interest, here are the frequency counts for the various name lengths at the OU:

Length | Frequency
------ | ---------
1	| 6
2	| 1
3	| 9
4	| 4646
5	| 304
6	| 28
7	| 3

And for PRT names

Length | Frequency
------ | ---------
1	| 3
2	| 3
3	| 6
4	| 3869
5	| 19
6	| 316
7	| 3
8	| 3
11	| 3
15	| 49

**Comment by timhunt** [comment]
Right, that seems to fix it.

**Comment by aharjula** [comment]
Yes 18 chars should be more than enough for input-names. Even though reserving room for over 99x99 matrices seems a bit mad someone will eventually do it, although maybe using some javascript.

Our lazy authors seem to have used prtX as the naming standard until recently when we started to ask for self-documenting code.

For interest indeed, the same stats from the new national STACK-question production project: 
```
abacus=# select length(name),count(*) from mdl_qtype_stack_inputs group by length order by length;
 length | count 
--------+-------
      1 |     8
      2 |    10
      3 |   151
      4 |  2154
      5 |   354
      6 |    37
      7 |    15
      8 |    66
      9 |    48
     13 |     8
     15 |     4
(11 rows)

abacus=# select length(name),count(*) from mdl_qtype_stack_prts group by length order by length;
 length | count 
--------+-------
      1 |    61
      2 |    33
      3 |    12
      4 |  1605
      5 |    85
      6 |   415
      7 |    36
      8 |    41
      9 |    28
     10 |    13
     11 |    15
     12 |     6
     13 |    10
     14 |    10
     15 |    13
     16 |    10
(16 rows)
```
Looks like we have less questions than the OU, well the project just started and they have 1 and a half years left...
