### ISSUE TITLE
Guard clauses in evaluating the PRTs

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#150]
STACK computes some things from the whole PRT prior to traversing the tree.  E.g. Sans and Tans are computed.  This leads to problems as we can't have guard clauses. 

With hindsight, this is very poor design (on my part) and should probably change.

E.g. see https://github.com/maths/moodle-qtype_stack/blob/master/stack/potentialresponsetree.class.php#L146 

See also
public function get_context_variables($key)
https://github.com/maths/moodle-qtype_stack/blob/master/stack/potentialresponsenode.class.php#L282

**Comment by aharjula** [comment]
If you only had those conditional CASStrings...

**Comment by sangwinc** [comment]
Yes Matti!, that would be one solution....

**Comment by gustavdelius** [comment]
What are guard clauses?

**Comment by timhunt** [comment]
The are a general programming technique http://c2.com/cgi/wiki?GuardClause
The idea is to evaluate some spsecial cases first, and return quickly in those cases, before getting down to the longer and more complex normal case, which you can then at least implement without having to have lots of conditionals in the logic for the special cases.

In a procedural language like PHP you can always transform a function that uses guard clauses and early returns into a function with nested if statements and a single return at the end. However in most cases, most people would say that the implementation with guard clauses is easier to understand.

**Comment by aharjula** [comment]
Or a simpler explanation for this, STACK evaluates all the nodes of the tree, no matter if the path we go through that tree would leave most of the nodes out.

The problem is that if we were to test for 0 value in the first node and then divide by that value in the false branch we still evaluate the false branch even when the test is true which causes those division by zero errors to happen anyway. With guard clauses the evaluation of the nodes would only happen if there is a path that leads to those nodes. Basically, this is an issue of how STACK maps the evaluation of the PRTs to Maxima code, now it just lists them but adding structure would help here.

So this would enable you to write code that fails in some cases if you ensure that those cases have been filtered out in the earlier nodes of the tree, currently that is not the case even though many believe so.

**Comment by gustavdelius** [comment]
Tim, Matti. Thank you very much for those very helpful explanations. Tim educated me well on guard clauses and Matti explained well what this STACK issue is about. What a wonderful developer community STACK has!

**Comment by sangwinc** [comment]
Issue moved to #156.
