### ISSUE TITLE
question-text is CASText, certain Moodle features use it without evaluating CASText, this causes some issues with some filters

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#151]
Ok. So we use [JSXGraph](http://jsxgraph.uni-bayreuth.de/wp/) and it has a Moodle filter that handles the inclusion of certain scripts to the page and moves the code we write to the correct position on the page and it works very well for what we use it, when we give it valid code that is. 

We typically use it so that inside the code defining what it should draw we include Maxima-values using the {#...#} syntax of that development branch that we have been working for quite some time. The problem is that unless those values get injected to that code the code is invalid some times even syntactically invalid and the filter obviously does not know about that and when it places that code on the page whatever code exist beneath it dies as it breaks the JavaScript engine.

The problem is that the JSXGraph filter can easily assume that the author knows what (s)he is doing and it is unreasonable to ask for it to check if the code is good and the world must have other filters with the same situation. In this case the fault is STACKs as it is the one that did not fill in the values, even though who can really blame it as it was not even asked to fill in those values.

This problem appears in Moodle 2.8s quiz-module, in such a way that if you add a STACK question with such dynamically generated JSXGraph plot in its question-text the quiz-modules editor UI breaks down and you cannot add or remove any more questions to the quiz (or if you have theme showing a question bank you can't change the category). This is due to the fact that the quiz-module calls all of the filters configured for the quiz for the raw question-text of the question and we do not get to do any of the normal CASText evaluation before it does that, it then extracts some of the first words in the rendered content and displays those in its question list while all the filters may have generated code and other includes for the page. _There is a workaround for this, just turn off the filters for that quiz while working with that UI and then turn them back on._

This problem ties to that other CASText focused branch of STACK as it does include plenty of things to CASText that look silly if you do not evaluate it and those things look slightly odd in the question bank and in the quiz listings as they show stuff that takes room from things that would actually make sense to be shown. 

I would not expect all the filter makers of the world to be able to react to the situation where the input for their filter might be bad because we did not get to evaluate it first and would think it is more our problem to fix this. At the same time we could think if those question listings could tell us something about the question other than the few first words or broken LaTeX with our injection symbols in it.

So I was thinking that the question text field of the question database table is not really important for us as every time we display that question text we render it anyway so why would we not store the actual CASText version somewhere else and place something simpler in that question text field that others use without knowing how it should be used. Maybe we would just store something we have pre-rendered during validation and then cleaned by ourself or maybe we could add more information in addition to that, for example we could add icons telling that this question has pre-chosen or random variants, a plot, multiple inputs, a model answer, multiple trees, or something completely different.

**Comment by timhunt** [comment]
For all Moodle question types. The meaning of the question text field is up too the particular question type. E.g. in qtype_shortanswer, it might be "What is 1+1? _____________"; in qtype_calculated it might be "What is {a} + {b}?"; or in qtype_ddwtos it might be "The [[1]] sat on the [[2]]."

In all cases, it should be possible to display that a more-or-less plain text.

Filters are run over arbitrary user input. It is up to each filter to be robust. Not fiter should completely break the page it is used on, otherwise that is a potential denial of service security hole. (Some student works out a malicious string and posts it in a forum, then that forum is broken for everyone.)

Also, any filter that lets users inject arbitrary JavaScript into the page is opening up XSS and XSRF security holes.

If I was building something like filter_jsxgraph, ... well, I would not build something with that sort of interface for users. Or, to put it another way, I can never see the OU deploying something like that, though if you take the risk, I can see that it is very powerful.

Since we are passing this through Moodle's html_to_text, I would expect the <script> tage to be stripped. Therefore, all that should happen at worst is that the teacher should see some of the JS source code as the question text. I don't see how it breaks the page completely.

When the page breaks, is there an error in the brower's JS console, and if so, what is it?

I wonder if jsxgraph could be made into an oembed service, with all the user-supplied JavaScript going into an iframe server from a different domain. That would be more secure, and it could then be used by anythign that supports oembed. Not just Moodle (https://moodle.org/plugins/view/filter_oembed)

**Comment by aharjula** [comment]
"What is {a} + {b}?" is a valid point but when the text area is limited to hundred chars or so and the content is "[[ if test='is(diff(blaah/blarg+ta,z)=5)']]For the following [[ some-other renderin-tag='....' ]]..." and the code content that generates the rendered question text takes the majority of the chars and you can't actually even see more than few words of the question we may have a situation where some logic might need to be applied to the text before it can be used in such an abbreviated form. Naturally, if there are conditional bits in the text we could not display all the alternatives anyway.

Maybe it is just me but there are plenty of materials in my version of STACK that use few dozen of the first chars for simple conditionals before they even get to the payload text and that is then broken by the next bit of code before you even get to the bits that would tell you what is the question. To deal with this our authors have to use the names of the questions as the primary way to describe the content and that leads to pointlessly long names.

As you say "The meaning of the question text field is up too the particular question type." the thing I am suggesting is that STACK would not use the question text field as the store for our raw question text as the future of CASText syntax used in that field may lead to a situation where the raw text presentation of that field might not be very useful, the payload/code ratio just might get too low for the first hundred or so chars. Instead we would store that raw CASText elsewhere and provide a simplified presentation for all the other tools that expect content in the question text field in a form that better suits their typical use cases.

Naturally there are a few options, we could not care about the issue at all, who needs to be able see anything informative about questions that have that much code in their start as obviously those are bad questions or maybe we could limit the possibilities of question authors and add a validation step to block adding too much code to the beginning of the question text. But maybe we could solve this in some new way and if we do solve it somehow could we maybe add something extra at the same time? I for one would really want to see a small icon signalling that this is the question with the picture and that has a model solution, even if that icon would use precious chars and were textual "[P]" would tell me so much.

I am perfectly aware about the problems of injecting scripts through JSXGraph, but as we use it in quizzes that do not have open text-area inputs that would allow the student to do such injections I am not that worried. Naturally, mixed use and the normal policy of just turning it on (the filter that is) everywhere may open plenty of attack surfaces. Maybe someone should design some solution that would allow applying different filters on course provided material vs. student injected material, maybe that would open up the possibilities of these more dangerous filters that could be useful in various materials.

But the issue with JSXGraph is completely separate thing and we can drop it from this issue as it was just one thing that brought up something that did not work in the usage context as expected and made me think if CASText works any better (the current obviously does, but the future may be very different).

**Comment by timhunt** [comment]
What evidence do you have that your questions are typical? OU STACK questions do not tend to look like that. This is mainly because our authors follow Chris's advice, and put most of the code in the question variables.

Here is the start of the question text of 4 OU STACK questions, picked pretty much at random:

* <p><span>Find the value of \(@a@ \times @c@\) in \( \mathbb{Z}_{@d@}\)<br /></span></p>
* Input the equation \(@TA@\) in the box below...
* <p>What is the gradient of the line that passes through the points \((@x1@,@y1@)\) and \((@x2@,@y2@)\).</p>
* Have a go at inputting \[@ta@\] in STACK. For Greek letters just write the Greek letter using the Latin alphabet, eg \(\epsilon=\) epsilon.

I just checked, and Moodle's html_to_text function (which is used here) strips out JavaScript, so there should not be a problem with JSXGraph code showing up.

**Comment by aharjula** [comment]
They are typical of their type, I would guess they are not the most common type of STACK questions but there are more than 5% of them in a typical large category that I randomly checked and in some sets of questions they get up to 40%, obviously they do not appear in OU materials as you do not use the CAS-blocks branch and in English language the typical grammatical structure of a question tends to put certain things in certain order. And you do know that all questions are not just asking someone to do something, sometimes there is a story and the question is hidden in it, and we do like to change the flavouring of that story.

But they are nothing compared to the possible state-variable using questions where the whole question text may be a big switch statement. So what I am looking for is something that may not be typically used in the current STACK but will surely start annoying in the future if those CAS-blocks or even state-variables join the system. And if my vision of the solution for this is something that the current STACK would want to have a say about, I am offering it for discussion here and maybe someone might have some ideas of how to do it better, but if you do not acknowledge or understand my problem it might be difficult.

Oh it does filter script-tags, how nice. But does it filter jsxgraph-tags before the jsxgraph-filter catches them and moves the code from them to ``$PAGE->requires->js_init_call()``. Note before the filter activates the code is just random words that most definitely do not reside inside a script-tag. If that function is meant to just get the text why does it let all the filters set up the page for display of more complex things if it only cares about the text maybe it should freeze the $PAGE-variable or maybe tell the filters that they should not do all of the set-up actions they typically do.

And as we so like filters, a question came up in my mind and as you are obviously the expert maybe you can say no to it immediately: Can a question (type that is) request for specific filters to be used on it? Basically, can a STACK question force the loading of MathJax in some some other way than just putting TeX on the page? (There was an issue related to this and some AJAX validation...)

**Comment by alcarola** [comment]
@aharjula asked me to comment on this, but the discussion is way too IT-technical for me to have any educated opinion on. I can only mention that for me as an end user this is a practical nuisance that adds resistance in adopting STACK. I hope that the issue is resolved in some end-user friendly way.

Are there any simple instructions for how to currently write questions so that they don't break the possibility of editing quizzes? Asking the moodle admins of the Abacus project partners to keep turning on and off the JSXgraph filter every time a teacher wants to edit a quiz that contains a broken question does not seem sensible to me. A few of our questions currently have this problem.

**Comment by sangwinc** [comment]
We now have a JSX-graph block.
