### ISSUE TITLE
How to catch errors in code used in response tree nodes

### ISSUE THREAD

**Issue by gustavdelius** [maths/moodle-qtype_stack#155]
In an answertest I am using code that I know could create an error for certain types of student input. So I thought I would just wrap it in an errcatch(). But STACK tells me that I am not allowed to use errcatch(). Is there some other way to tell STACK to ignore errors?

The particular application I have in mind is in writing a response tree node that uses the student's answer evaluated at a particular value of a parameter. I use ev() for that purpose. That works well, except if the student enters an expression that is ill defined at that value of the parameter. Probably there is a recommended way to do that in STACK that automatically and quietly catches any errors?

**Comment by sangwinc** [comment]
Gustav,

Trapping errors in PRTs is already open as issue #150.  The STACK code already uses errcatch to ensure we can catch and return errors to the user at all.  Errors in STACK and Maxima have proved hard to trap.  The errcatch command enables the code to continue running (as the empty list is returned, rather than breaking out of a loop/function) but the error message is still printed to the console.  Would guard clauses suffice here as suggested in #150 or do you really need errcatch?

Do you have a test server to hand? If so, perhaps you could try out your questions on a server where you have removed errcatch from the list of forbidden functions.   See 
https://github.com/maths/moodle-qtype_stack/blob/master/stack/cas/casstring.class.php#L75 
If this really does help you, let me know and we can talk about how to proceed!

If you don't have a server, please email me a question and I'll have a look.

**Comment by gustavdelius** [comment]
Hi Chris. I had seen that other issue, but did not know what guard clauses are. I have posted on issue #150 with a request for explanation. Then I can judge whether they will help me.

It seems to me that evaluating a student's answer at specific values of the variables must be a common task in response trees. Perhaps we should allow a list of variable-value pairs to be given as an optional argument to answer tests, and then substitute these values into the student's answer before applying the answer test. I'll open a separate issue with this idea.
