### ISSUE TITLE
Substituting values for variables in answer tests

### ISSUE THREAD

**Issue by gustavdelius** [maths/moodle-qtype_stack#156]
I sometimes want to substitute numerical values into a student's answer to test the student's answer has certain properties. For example I might want to check boundary values of functions, or I might want to check an answer in special cases in order to draw a student's attention to ways how they could have immediately have seen that their answer could not be correct. Currently I can do this by using the ev() function in the Sans field of an answer test, but that can lead to errors if the student's answer turns out to be ill defined at the special values. 

So my proposal would be to allow a list of variable-value pairs as an optional argument to answer tests. These values would then be substituted for their variables in the student's answer before the answer test is performed. If the substitution leads to an error, then the answer test will fail and give feedback telling the student that their answer is invalid at those values, unless the teacher sets the silent option,

**Comment by timhunt** [comment]
Would a better option be a 'safe_ev' function, or something like that, which traps any error, and then returns a list with two elements where the first element is a boolean for whether the evaluation is possible, and then the second element is the resut of ev, but only if the first element is true.

**Comment by sangwinc** [comment]
That is a very good idea Tim, and I think I can do this.

One side effect of "save_ev" would be to suppress any errors.  This may or may not be a very sensible side effect, but that should stop PRTs breaking.

Chris

**Comment by gustavdelius** [comment]
Tim, are you proposing that the safe_ev() function is a function that question authors can choose to use if they want to safely evaluate a student answer at some values for the variables, or is it something that will automatically be used for all evaluations of student answers? I understood the former, but I think Chris may be thinking about the latter, judging from his comment above.

**Comment by sangwinc** [comment]
Gustav,
I think this should be an option for question authors to use.  I'd like errors to be flagged up!

**Comment by gustavdelius** [comment]
I thought that's what you were suggesting. In that case however, we don't need a new function safe_ev(), we could simply take the function errcatch() off the blacklist. Then errcatch(ev(...)) does what your safe_ev() would do, but there are probably other functions besides ev() that question authors might want to make save, which they can do when errcatch() is available.

**Comment by aharjula** [comment]
I would also rather see the general errcatch() than the very specific safe_ev(). Mainly because this would again provide a new function not present in basic Maxima. Also I would rather keep errors as visible as possible and while the safe_ev() suggested already requires additional code around it to handle the cases where errors appear I think that the form required by errcatch() is more general and most likely better understood by the Maxima community.

Basically, how I see the safe_ev() is just a wrapper around errcatch() that returns a boolean inserted before the return value of errcatch() which is a bit pointless as the user of that function will basically have to do the same logic building around that function to handle the false-case than they would need to do around errcatch() which would return an empty list instead of a boolean.

Naturally, I don't know if Tim meant that safe_ev() should be a wrapper around errcatch([ev()]) or something more general but with errcatch() we could combine multiple things (even other than just ev()-calls) that might break into the same call and it would already handle the logic of failing when any of them fails.

**Comment by timhunt** [comment]
As Chris said above, indiscriminate use of errcatch will break STACK's usual error handling mechanism, which is tried and tested.

Probably the people contributing to this thread understand what is going on well enough to use errcatch safely, but making it generally available to all STACK question authors is a risk.

Therefore, my proposal was to make something more specific, and less risky, available.

However, of all the people here, I probably know least about Maxima, so it was just a suggestion, offered tentatively.

**Comment by aharjula** [comment]
Sorry, I must have completely missed that comment by Chris, where did he say that?

Anyway I have a problem seeing where one would need to place an errcatch() in the question to make STACKs normal error catching break? As it returns an empty list that you are supposedly doing something and trying to read from an empty list tends to generate new errors anyway.

**Comment by timhunt** [comment]
Chris has only made two comments above, they are both relevant.

**Comment by aharjula** [comment]
Well I still have problems to see how Chris said that with those comments... on the other hand I don't quite understand how the function safe_ev() that by your definition traps errors would have "a side effect" of suppressing errors wouldn't that be the primary function of it aside actually doing the ev()? 

Naturally, I can see that from that word "any" before that "errors" we can happily expand the context of that statement wherever we want, but I still have problems finding that comment about "indiscriminate use of errcatch".

I can't see where and how I would need to use errcatch() to cause the error handling mechanism to break, please give an example and maybe we can then decide if that safe_ev() is any better considering that constraint.

**Comment by sangwinc** [comment]
I have given this, and the guard clauses issue a lot of thought. It is related to #150. Not sure at this moment what is best to do here, but we should take these issues together (I'll close #150)

I don't have a clear idea, at this moment, when or if a "mathematical error" and a "coding error" can be separated.   E.g. if you ask for a "part" of an expression which does not exist, is this a mathematical error or a coding one.

**Comment by gustavdelius** [comment]
Why was this issue closed? Is there a resolution to this or to #150?

**Comment by aharjula** [comment]
Felt like writing a wall of text, sorry...

I don't know about the closing but I know that we are very close to so-called compiled PRTs (proof of concept has seen actual students and the key technical pre-requisites are in STACK since 4.3) that actually can be used to do these things in a sensible way. Only evaluating the branches that should be evaluated, i.e. if you detect a zero in one node then you do not need to worry about divisions by zero in some other nodes as long as you do not route to them.

In any case, it took years to shift PHP-side answer-tests to Maxima side so that we could do the whole conditional evaluation there. That point was reached just last autumn.

The current focus is on building the infrastructure for caching all the heavy lifting this requires. That caching already made certain tasks 20% faster, after first question init. But that needs some testing in various import/export cache invalidation situations. And that cache is needed so that we do not become over 20% slower everywhere...

I would not be surprised if those compiled PRTs would be in play during the summer. Though we need to find a suitable way of implementing them in the code-base, between the many meta-data files approach of [Stateful](https://github.com/maths/moodle-qtype_stateful/tree/eee28ca9fce03566043e018302bb2a12dd81748f/stateful/answertests) and the [STACK](https://github.com/maths/moodle-qtype_stack/blob/61fd8ee704c236f9ee469d2566cab2f5bb550ac6/stack/answertest/controller.class.php) approach of a single definition script. Also, I want to bring castext2 in at the same time to complete this mess, so that might take some time more.

With castext2 and its Maxima side single pass evaluation of castext one could generate the feedback of a PRT at the same pass as the PRT gets evaluated and would not need to construct a separate castext evaluation session based on the results of a feedbackless PRT evaluation, would lessen the items in CAS-.cache and so on. But for this to happen the PRT compiling logic needs to inline castext2 construction and that will not happen without castext2 being ready at the same time.

Finally, all things related to errcatch were handled in 4.3 when we replaced the cassession subsystem with one that allowed sub-statement level error catching so that we could combine multiple things to a single statement and still receive tagged errors telling from which specific point in that statement the error came. Basically, now if we turn an PRT to a single massive if-statement with branches (not actually doing that, due to repetition) we can still receive errors that can tell that the failure was in "tans of node x".. The same system will also tell which line of feedback-vars or question-vars broke and not only the line but the character range if that line has multiple statements. This error reporting expansion is also coming soon it is already in dev.-branch for question-var validation caching.

So many things have been converging on this for quite a long time now and large projects refactoring the internals of STACK are converging so that we can get guard clauses in PRTs to work, on the side we get performance boosts and open up paths for future work on the new input system and other fancy new features.

**Comment by gustavdelius** [comment]
Hi Matti, thank you for that update. However I did not understand it all, in particular what you wrote about error catching. Remember that my use case is to test whether a student answer has the correct value when a certain value is substituted for some variable. I don't think guard clauses would help me. I need to be able to catch any errors that happen due to the substitution of that value.

**Comment by aharjula** [comment]
Ahh assumed this has been mapped to guard clauses. Well, the sub-statement error trapping is now built so that one could allow the use of `errcatch` in question-logic as well. With the idea that whatever one watched in own logic is not an error at the question-level. Whether that will be allowed is another matter, I doubt there is any reason why not but maybe someone else can come up with one.

**Comment by gustavdelius** [comment]
If there is reluctance to enable `errcatch()` then I would be happy with the `safe_ev()` suggested by @timhunt .

**Comment by sangwinc** [comment]
Question authors can now use errcatch in feedback variables to create guard clauses etc.
