### ISSUE TITLE
Problem with testing when using both AlgEquiv and NumSigFigs

### ISSUE THREAD

**Issue by lentzi90** [maths/moodle-qtype_stack#185]
I'm not sure if this should be considered a bug, but anyway...

I have a question where the students are allowed to give either an exact fraction as answer or a numerical answer with 3 significant figures. I check the answers first using AlgEquiv and then NumSigFigs and this works great.

Then I decided to add automatic tests and run into this:
If I add a test to check the numeric answer and it happens to also be exact the test will fail due to the answer note.

**Example**
If the correct (exact) answer is 21/4 = 5.25 and I run the test with the number 5.25, AlgEquiv will evalute to true, and the test will fail since it expects the answer note from NumSigFigs.

Is there some other way to do this? Should I be using some other method?

**Comment by sangwinc** [comment]
Ok, I don't think this sounds like a bug with STACK itself, since my understanding is that the system is behaving correctly.  21/4 is algebraically equivalent to 5.25!  

The testing mechanism only tests the final answer note, not the whole route through the tree, only because authoring tests would become a complete nightmare and so nobody will use them!

I'm not sure why you think the "test has failed" here?  If you put in an equivalent answer, then the system has worked!  Perhaps this isn't what you expected, but there we are.  ;-)

If you want to check if a student has typed in a floating point number, then you could add your first node to check this, e.g. ATAlgEquiv(floatnump(ans1), true).  Then branch to two tests, NumSig figs if you have a floating point number, and AlgEquiv if not.  I hope this makes sense?

**Comment by lentzi90** [comment]
Ah, that makes sense! Thank you!
