### ISSUE TITLE
Update to dev docs, about that yui?

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#196]
Tim...

As you have turned that /yui/ directory to this new form, maybe you could enlighten us about how one should go on if one needs to edit it? How to build all those files? 

Obviously, this is again something obvious for YUI and Moodle devs but for me these NodeJS things are new. Do I just have to follow [this](https://docs.moodle.org/dev/YUI/Shifter)?

-Matti

**Comment by aharjula** [comment]
Mainly I am asking because if I follow that guide and install that version 0.4.6 or even the newest 0.5.0 I get this:

```
/var/www/html/moodle29b/question/type/stack/yui/src$ shifter --walk
shifter [info] racing to find the closest .shifter.json file
shifter [info] woohoo, found a config here: /var/www/html/moodle29b/.shifter.json
shifter [info] override config found for coverage
shifter [info] override config found for lint
shifter [info] override config found for clean
shifter [info] revving up
shifter [info] racing the directories
shifter [info] using --clean --no-semi --no-coverage --istanbul --lint config --build-dir /var/www/html/moodle29b/question/type/stack/yui/build
shifter [info] found 1 modules to race, let's do this
shifter [warn] this will be quiet, only status will be emitted for speed. failed builds will print after
shifter [err] /var/www/html/moodle29b/question/type/stack/yui/src/input/js/input.js contains 46 lint errors
.
shifter [info] done racing, the gears are toast
shifter [info] finished in 0.437 seconds, pretty fast huh?
```

It still seems to generate the files to the build directory, but surely there should not be an error here, how should I build it to not get that error? Or are these oh so hilarious tools with all their fancy remarks designed so that they map a style warning as an error in the output and just go on instead of crashing like you normally do with errors in builds...

**Comment by timhunt** [comment]
https://docs.moodle.org/dev/YUI/Shifter is the old way to do this. The new recommended way is https://docs.moodle.org/dev/Grunt.

It is odd that there are so many errors there, since it was all building cleanly before. It seems that Moodle have changed the jshint settings. To see the problems do

cd question/type/stack/yui/src/input
shifter

I have done a commit that fixes most of the problems. The remaining ones are just warnngs. Moodle changed its javascript coding style, which is why we now get warnings about all our constructors, but I don't want to try to change our code now.

The use of eval is pretty much unavoidable in this code. It seems fair enough that Shifter gives a warning about it.

**Comment by aharjula** [comment]
Ok. That explains it.
