### ISSUE TITLE
Issues with multi node Moodle environments

### ISSUE THREAD

**Issue by tlock** [maths/moodle-qtype_stack#214]
Hi,

We are hosting this question type for a client and have found that plot images are failing to be retrieved because of the assumption is moodledata temp directory is shared across all nodes where Moodle is hosted.

Our workaround is to embed the plot images into the CAS result array to resolve this issue.

Have you consisted doing this for the plugin?

**Comment by aharjula** [comment]
You could turn off the CAS result caching thus forcing regeneration of the images (and everything else) on the current node, thus fixing the cases where the cache is populated but the disk does not actually match the cache state, assuming that the current node is serving out everything Moodle serves. Or maybe a node specific cache table?

Or provide some other way of syncing the moodledata/stack directory between nodes sharing the cache? Probably not an option...

Embedding the images to the CAS result array in some raw form would surely make the rows in the cache table quite long and that is something that I would object to after what happened with STACK 2. But you could move the CAS caching thing from the Moodle side to MaximaPool and as MaximaPool responses already contain the plots this would not require any changes to STACK itself. Basically, put a POST-parameter aware caching system in front of your MaximaPools and let that handle the image distribution to the nodes requesting images.

**Comment by aharjula** [comment]
I am curious though how do you embed the images? Do you just modify the CAS-result on the node generating it by reading in the files there and pushing them into the array in some serialised form and then put that modified form to the CAS cache? And do you then write the images out onto the nodes that do not have them by checking the array or do you do it by putting the data to the img tag i.e. `<img src="data:image/png;base64...` thus skipping files completely?

**Comment by timhunt** [comment]
When installing Moodle, it is essential that the moodledata directory is shared between all webservers.

The only folder it is safe to not share is moodledata/localcache.

So, I don't think there is any issue with STACK here.

**Comment by tlock** [comment]
Hi Matti,

As we aren't doing at a large scale we aren't going down the path of the MaximaPools.

The caching is important for obvious recents, so we have opt'd for the base64 encoding the simple images and implement removal of cache records older than 7 weeks by adding 'timecreated' field to the cache.

**Comment by tlock** [comment]
Hi Tim,

Having a shared moodledata directory for file objects is a few assumption unless providing the file objects others like cloud file storage.

The issue here is the dependence on temp file storage for serving generated images.

So if you would consider making it configurable to embed the images via CAS would be much appreciated.

**Comment by aharjula** [comment]
Hi Tims,

Actually, I like the base64 in-line images idea and it might happen at some point but it will newer be the default behaviour as in a large scale set-up it would be an unnecessary burden for the cache. It is entirely possible though that I would do some developing on the MaximaPool side and make it do that embedding there (as an option naturally) thus dropping the need to transfer files from the pool to the Moodle.

The base64 embedding doesn't really cause that much of an increase in the cache-usage as plots are relatively rare and we are talking about 2-5kB gnuplots being base64 encoded so not a lot compared to the other stuff coming out of the CAS. But still an issue when the cache grows fast and rests in the millions of rows range.

As to the moodledata limitation, sure Moodle should be used with shared moodledata, but what if we have a reason to not do so, as said especially clouds tend to cause that and segmented installs are not that rare either and if the plots are the only thing in STACK that really requires that shared moodledata and there exists a simple way to drop that requirement why should we not provide that?

Maybe you could make a connector class with that embedding logic and a nice new name with some explanations in the documentation and send a pull request, I could then add it to the master branch...

**Comment by timhunt** [comment]
Sorry, Tim, that first sentence is not very comprehensible to me.

You keep using the phrase "temp file storage" in relation to moodledata, which is just not true. The core Moodle assumption is that moodledata is a shared resource. Moodle has some support for non-shared folders for performance https://github.com/moodle/moodle/blob/master/config-dist.php#L387, but there are still some folders that should be guaranteed to be shared, like cachedir, and arguably we should be storing this folder under cachedir, not directly under moodledata, but at least as far as core Moodle in concerned, that should not matter.

Now, according to Dan Poltawski at Moodle HQ (https://moodle.org/local/chatlogs/index.php?conversationid=19444), there are patches floating around the community to do what you are talking about. But if you are doing custom stuff, and have not done the community-spirited thing and shared it with the community, then I am afraid you have to be responsible for supporting your own non-standard set-up.

But, of course, this is open source, and if you want to scratch your own itch, and improve STACK in the process, then we all win.

aharjula - I don't see any merit in base-64 encoding images. The wire format, where we send back a .zip file works well, and is efficient. I think the only question should be, where are the plots (if any) stored in Moodle, once the zip is unpacked? We need to

1. store the plots when we get them from the CAS
2. serve them up in response to web requests (currently handled by plot.php)
3. delete them all when the CAS cache is cleared.
4. not delete them when someone does Purge all caches in Moodle.
5. improve, or at least not hurt, performance.

I think that captures all the requrirements.

Now, if someone has a proposal for how to do that, without mucking up STACK, then please make your suggestion.

**Comment by aharjula** [comment]
I see the benefit of base-64 in the elimination of those files and skipping the pointless Zip handling that comes with them in the server connector.

As to the requirements, they only apply if you want to do everything exactly as you do now:
1. Do we need to store them if we get them from the CAS (as part of the response text) or cache and immediately serve them out why hold that kind of a state in our system.
2. Why do we need to have more web requests why not have less by in-lining them.
3. If they are in the cache or nowhere they sure get deleted.
4. Well if that would purge the CAS cache we sure would want it to also delete the files also, otherwise we have orphan files.
5. Dropping the file handling would surely improve performance (file ops on shared storage are not cheap they are not cheap on local disks either) but the cost is more data in the cache someone should find out if that cost is relevant and what level of benefits we get from dropping the file ops. The base-64 overhead in the network transfers is irrelevant as the files are so small that the pure headers are close to the overheads size.

Mucking up STACK? I sure see nothing being broken if someone adds a new connector class that does that image embedding and as it has a this well defined use-case and people may want embedded images even with "valid" Moodle installs it should be accepted.

As a side note I just tested a nginx POST request cache with my MaximaPool load balancer and it works well. If I run the all answer-tests set I get 0.0034s average times for the STACK CAS-cache and 0.0027s averages with just nginx... pretty empty caches (other than those tests) though and the nginx cache was hardly tuned.

**Comment by timhunt** [comment]
In what way is the Zip handling pointless? CPUs are much, much faster than networks.

Tim Lock was suggesting storing the images as base-64 encoded strings in the CAS results. You are now suggesting doing the images as data:urls in the HTML, which is now mostly supported in browsers http://caniuse.com/#feat=datauri, but will be really bad for users on mobile networks. Note that plot.php does proper handling of If-Modified-Since: headers to work nicely with browser caching of images. That is good. Inlining all the image data in the HTML, inefficintly encoded as base-64, would be bad.

**Comment by aharjula** [comment]
I just never liked the way that Zip is opened: https://github.com/maths/moodle-qtype_stack/blob/master/stack/cas/connector.server.class.php#L70-L107 , luckilly that mess can be done on a local disk but I do not like those file-ops.

If you read the previous comments you'll find out that I wondered how he was storing those encoded strings to the CAS results and if he then writes them out from there, I am under the impression that his solution does in-lining and does it by modifying the CAS results before they get placed to the CAS cache by replacing the urls in the img tags with such in-lining, Naturally, I may have misinterpreted things. 

As to mobile networks if your users have limited data plans and you care about that you are free to not select this embedding solution, on the other hand there are places where that is not an issue and we can instead minimise requests especially requests that will require loading up infrastructure and session management just to serve few kilobytes of stuff that could have been dumped out on the side already.

**Comment by timhunt** [comment]
I agree that specific bit of code is nasty, and should be replaced as soon as it is possible to do better in PHP (http://stackoverflow.com/questions/15140063/extract-a-file-from-a-zip-string seems to have good background, but I don't have time to think about it now).

However, this is an entirely self-contains bit of code that does one task (and it has worked reliably for years).

In contrast, proposals to change now STACK communicates with the CAS about plots would require changes in many bits of STACK code.

Tim L mentions a work-around, but has not shared any code. (Note, Tim L is in Australia, and so is probably alseep for now.)

**Comment by aharjula** [comment]
I claim that all of that could be done in a single file using maybe 20 lines. Just check the cas results in the connector for img urls, read them in from the files and replace the urls with base 64 in the result before passing it forward.

**Comment by tlock** [comment]
Hi Matti & Tim,

Thank you for all your discussions about this issue. Please contact me by email and I'm happy to provide the code I have created to workaround this issue.

**Comment by timhunt** [comment]
Why not publish your own clone of this repository, and push a branch with your changes? That would be the normal way to share code.
