### ISSUE TITLE
Plugin "qtype_calculatedmulti" is installed in incorrect location "$CFG->dirroot/question/type/stack", expected location is "$CFG->dirroot/question/type/calculatedmulti"

### ISSUE THREAD

**Issue by gsovis** [maths/moodle-qtype_stack#223]
When I installed "Stack", I get the above error with the following.
Debug info: 
Error code: detectedmisplacedplugin
×Stack trace:
line 468 of \lib\upgradelib.php: plugin_misplaced_exception thrown
line 1742 of \lib\upgradelib.php: call to upgrade_plugins()
line 677 of \admin\index.php: call to upgrade_noncore()

Please help to resolve this problem.

**Comment by timhunt** [comment]
You did not get that error message by installing STACK.

You might get that error by copying the calculatedmulti question type code into a folder called stack, but there is no good reason why you would do that.

You need to start again, and carefully follow the stack question type install instructions.

**Comment by gsovis** [comment]
Thanks so much for your response. Instructions are confusing for a teacher who is a non-programmer. How ever, I will try again. Regards

**Comment by gsovis** [comment]
Thanks Tim for your advice to start again.I managed to install STACK question type following install instructions. No more errors regarding behaviours and other question types. Now I am facing a new problem. When I run the Healthcheck script, I get the following error.
-----------------------------
Maxima configuration file
Could not locate the directory into which Maxima is installed. Tried the following:C:/Program Files/Maxima-5.38.1/, C:/Program Files (x86)/Maxima-5.38.1/, C:/Program Files/Maxima-sbcl-5.38.1/, C:/Program Files (x86)/Maxima-sbcl-5.38.1/, C:/Program Files/Maxima/, C:/Program Files (x86)/Maxima/
------------------------------
I would be very grateful if you could help me to resolve this problem.

Thanks again in advance. gsovis

**Comment by timhunt** [comment]
Do you have Maxima installed? Can you run it from the Windows start menu? Whne it is running, can you find out exactly which version you have installed? (E.g. from Help -> About..., find the bit that says Maxima version: 5.31.2)

Then, in Moodle, In the STACK setting, can you make sure that the right version of Maxima is set.

Also, if necessary, find out where Maxima is installed on your computer, and put that path into the STACK setting, instead of relying on STACK's automatic guessing.

Good luck! It seems like you are making progress. The good news is that you only have to get it working once.
