### ISSUE TITLE
SigFigs [3,0]

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#239]
Request from a user:

With regard to the unit conversion question, we can certainly create additional nodes to test Significant Figures for answers with different units, however, this seems to create a great deal of unnecessary work.  In our approach, the first node uses the UnitsRelative test which accomplishes most everything we're interested in evaluating the student answer - the answer is within the established relative error, the unit is correct, and an equivalent answer with a different unit is accepted. In our second node we are only interested in checking if the student entered the answer to the correct number of significant figures, which is a relatively minor part of the answer, but something all physics instructors must address in their grading. So if the answer is 5.55 km or 5550 meters, we are only interested in checking that both answers indeed have 3 significant figures. It would be extremely helpful if the NumSigFigs test with a test option of [3,0] would check for 3 significant figures with an accuracy of 0 significant figures, essentially allowing us to check ONLY for the number of significant figures and ignore the numerical value. I'm confident that other physics instructors would appreciate a test that is able to focus solely on the number of significant figures only. This would save a great deal of work as we would not have to create a new node checking significant figures for every possible unit, which for some units can be quite tedious.

**Comment by aharjula** [comment]
Why would they need to create a new node for each unit? What does that even mean, unit-prefix combinations?

Still keeping the functionality of non zero second option for these tests? Otherwise the test surely could have that option and it would make sense. No we just need to decide how many significant figures there are in `0.000` if `0.001` has only one i.e., do they have the same number of them... and does `5550` have at least 3 and maybe even 4 significant figures? Basically will `5550` pass with both the options of `[4,0]` and `[3,0]` while `5.550` and `5.55` would only pass with the matching options.

**Comment by sangwinc** [comment]
Yes, Matti.  I've started to consider this.

The current test takes an answer x from the teacher and then asks "Is this expression x written to n sig figs?"  Without extra information it will be impossible to tell, just looking at the digits, if a number *is* written correctly.  

Is 1000 correct to 2, 3 or 4 sig figs.  On its own we don't know.

We can say 1110 is not correct to 2 sig figs.  That is all.

We can way a number is *not* correct, but not that it is correct.

Chris
