### ISSUE TITLE
Proposal to tighten up validation

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#240]
A colleague recently pointed out this example.

https://github.com/maths/moodle-qtype_stack/blob/ATUnitsNum/tests/fixtures/answertestfixtures.class.php#L281

It is interesting because in cos(a*x)/(x(ln(x))) the atom "x" appears both as a variable and as a function.

Can anyone think of a situation where a student needs to type in an expression where an atom appears  both as a variable and as a function?

If not, then perhaps we should check if this is non-empty?

`intersection(setify(listofvars(ex)),get_ops(ex));`

If not then we render the expression invalid with the error message that they need to insert * symbols to make the "function" into multiplication "x*(".

Any comments about this?

**Comment by aharjula** [comment]
Supported... makes sense.

**Comment by christianp** [comment]
I can't think of a reasonable situation when you'd use a name for both a
variable and a function, but your suggested error message could be
misleading if the name is supposed to be used as a function. For example,
if I mistype `f(t)` as `f(f)`, changing to `f*(f)` is not correct.
The warning could instead say something like "is f a variable or a
function?" and, if possible, point to where it's interpreted as each type.

**Comment by sangwinc** [comment]
Yes, Christian, that is a much better error message, thank you.

**Comment by timlowe** [comment]
OK, I'm the "colleague"! 

In this example, with a question which has "automatically insert stars" turned on, the student entered cos(ax)/(x(ln(x))).  STACK did not insert a star in the denominator leading to x being treated as both a variable and a function. (This is not what the student intended!)

I don't think in a maths question we would explicitly use x as both a function and a *different* variable, However we often interpret the *same* object as a function or variable depending on the context,  using x as shorthand for x(t). I cannot see this arising in the answer to a STACK question though.

So I'd be in favour of a validation message along the lines of "is x a function of variable? ".  If "insert stars. You may need to explicitly enter * for multiplication to clarify your input" .



But, I wonder if there is an more fundamental issue with the "insert stars" that I don't understand.

a(b+c)   is interpreted as  a*(b+c).   Great.

but
1/(a(b+c)) is interpreted as 1 over the function  a of  b+c.

Oh, it seems to be the additional brackets needed to group the two factors of the denominator that is confusing things because

(a(b+c)) is also interpreted as a function a of b+c

I guess the display of the "variables in your answer" would pick this up, it was the fact the same letter was being used as a function and variable in the first example that meant this feedback didn't help.
