### ISSUE TITLE
Release of STACK 3.5.6: todo list.

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#253]
We've made quite a few improvements and added a few new features since August.

Before the new teaching term (Jan 2017) I'd like to tag and release the current code as STACK 3.5.6.  This will involve merging the current version in the ATUnitsNum branch into master, testing and tidying etc.

I am aware of no major features left.  I have a couple of minor bugs to fix.  Please use this issue to add anything you'd like added before we release.

**Comment by timhunt** [comment]
We really ought to get Travis-CI fixed before the release. I'll see what I can do.

**Comment by aharjula** [comment]
Naturally, I would also like to know what is coming as early as possible as Abacus merge will need to be done by mid December so that people can install and test before the next teaching period starting the second day of January...

The one issue I have left, that came from my test merging ATUnitsNum with Abacus, is the issue of running unit tests with MaximaPool i.e., the fixture tests like `answertest_general_fixtures_test.php` and two more seem to run on local Maxima even though rest of the tests go to the Pool. I have been unable to understand why it does that and would hope that either of you would try running tests with server-type configuration (you will probably need to mess with the default maxima symlink of /usr/bin/maxima or similar to detect the wrong maxima being called, I was lucky as my local maxima was broken) and reporting if this is a real issue. Running tests with MaximaPool is important to me as I want to ensure nothing that works without it fails with it and I like my dev system to be able to run the tests fast... Probably it is not just an issue with my [merge](https://github.com/aharjula/moodle-qtype_stack/tree/abacus-1.4) maybe more an issue with my dev setup as it does not work with raw ATUnitsNum either.

**Comment by aharjula** [comment]
#255 needs to be fixed.

**Comment by sangwinc** [comment]
This is now a release candidate: https://github.com/maths/moodle-qtype_stack/tree/rel-3.5.6

**Comment by aharjula** [comment]
Any chance that any of you has tested running those tests on MaximaPool? My latest merge of abacus with rel-3.5.6 at [abacus-1.4 branch](https://github.com/aharjula/moodle-qtype_stack/tree/abacus-1.4) still has this issue and I still can't find out why. Also it has that same issue on my Linux/CLISP/Maxima 5.36.1 dev machine when using local maxima, same with the rel-3.5.6. Am I missing something really obvious with the settings for maxima in unit tests?

**Comment by sangwinc** [comment]
Matti,

It is odd that only some of the unit tests fail.  I've just set up the rel-3.5.6 as a MaximaPool and run the answer tests through the web.  Not the unit testing from the command line.  Note, the unit tests probably need to be run from the direct connection (not optimised and not server).

**Comment by aharjula** [comment]
Chris,

Note that the tests fail for me also when running directly on non optimised 'linux' Maxima 5.36.1 on CLISP...

**Comment by aharjula** [comment]
What I can't understand is what makes those tests so different from the other CAS using unit tests? I see nothing special being done there. Also remember that I said that those tests are not getting evaluated on MaximaPool, I noticed that my machine was constantly calling a broken local Maxima install when running tests and that install filled my temp with compilation files, and it only did that when calling those specific tests not the other unit test, why on earth would it call the local maxima at all when configured to use MaximaPool?

**Comment by aharjula** [comment]
Hey, just to confirm... Nothing major is coming any more right? I need to publish my merge and time is running out, can't wait too much more...

**Comment by sangwinc** [comment]
Nothing more.  I'm just trying to get the code checker to be more happy and failing.....

**Comment by aharjula** [comment]
Ok. That is something a gave up on already. Abacus releases now, with version 2016122109. If you happen to release today please pick one of the smaller ones, the situation where people install master branch and have to switch to  abacus are somewhat more common than other way around and Moodle tends to be difficult for downgrading.
