### ISSUE TITLE
Problem displaying sets

### ISSUE THREAD

**Issue by azampa** [maths/moodle-qtype_stack#254]
Recently I updated STACK to version 2016100700 and since then I have a problem when displaying sets.
To give an example, suppose that

s : {2,9,16,23};

then @s@ displays as

{\left(2 , 9 , 16 , 23\right)

This problem does not involve lists, e.g. if

l : [2,9,16,23]

then @l@ shows correctly as

[2,9,16,23]

Sincerely

Alessandro Zampa

**Comment by sangwinc** [comment]
Yes, that problem has been fixed in the latest code (I hope).  I did reproduce it, and we've added tests to the unit testing (https://github.com/maths/moodle-qtype_stack/blob/master/tests/cassession_test.php#L690) which should pick up this problem.  These tests currently pass.

We hope to release this before Christmas.
