### ISSUE TITLE
Confusing Unit validation display

### ISSUE THREAD

**Issue by jmbragg** [maths/moodle-qtype_stack#255]
![weird units display](https://cloud.githubusercontent.com/assets/4606870/20697782/f4eacb56-b5c9-11e6-8fb2-6dc32d134532.PNG)

I'm not sure why the units are being displayed like this in the student validation, but it just confused me and I'm sure it will confuse my kids.  It looks to me as though the units would simplify to M/s instead of 1/(sM) with the way that's displayed.

**Comment by aharjula** [comment]
I am confused by the input of a prefix `M` without any unit tied to it? I don't think this is even valid form of input... but how to identify prefixes without the connecting units and to warn about it. Or have you by any chance defined `M` as a new unit, and more specifically unit without prefixes?

**Comment by jmbragg** [comment]
It is molarity (mol/L).  Chris added it in for me as a unit back in September.  The answer here is a rate law constant.

**Comment by aharjula** [comment]
Ok. Interesting, and something Chris better fix for the next release. It seems that no matter how you input that it will drop the parenthesis from there and it will make things confusing. Probably, just an issue on the presentation side with all the fine tuning that unit presentation and exponents have received this was probably inevitable.

**Comment by jmbragg** [comment]
![more weird units](https://cloud.githubusercontent.com/assets/4606870/21010234/f5918ce2-bd18-11e6-9886-a26964b6fd59.PNG)

Here is another one that is similar.

**Comment by sangwinc** [comment]
This issue was an interesting combination of two things.

The transformation of 4*1/s -> stackunits(4*1,s^(-1)) 
has an extra "1" in the numerical part.  Not a silly outcome, since we'd want 
4*2/s -> stackunits(4*2,s^(-1))
but an edge case we need to weed out.

The "inline" display function to display fractions as
{1}/{a}
and not
\frac{1}{a}
needs extra parentheses. E.g. 1/(a+b) 
should be not be {1}/{a+b}.
