### ISSUE TITLE
Line Break after Drop-Down Input Field

### ISSUE THREAD

**Issue by dhilsen** [maths/moodle-qtype_stack#262]
With regard to the drop-down input type in STACK, we sometimes use multiple drop-down questions scattered throughout a paragraph and have the student "fill in the blanks". This works nicely to test a student's grasp of a complex concept. 

A formatting issue arises when assembling this type of drop-down question. When the student views the question a line break seems to be automatically inserted immediately after the first input field. This presents a formatting problem if the first input field is located in the middle of a sentence. What's interesting is that a line break is not automatically inserted after the 2nd, 3rd, 4th . . . input fields and the text continues to flow nicely on the same line immediately after the input field. 

Removing the automatic line break after the first input field would remedy this issue.

**Comment by sangwinc** [comment]
Thanks for reporting this.  

This sounds like a bug and I'll fix this.  I can't reproduce it myself this morning. Please could you email me a sample question and also note which version of Moodle you are using?  I think this could be related to another problem reported to me last week with Moodle inserting <br> tags in elements of a textarea.  Not sure.

**Comment by aharjula** [comment]
Probably not related to that issue, but might have the same root cause.

Try switching off the the WYSIWYG editor in you Moodle user preferences (use the plain text area) and then you should see the formatting option in the question editor just set that to raw HTML-format instead of Moodle auto-format and you should be able to place whatever you want where-ever you want without Moodle messing with your layout. When using some WYSIWYGs you can't see that format option at all.

If that does not work the drop-down input is getting some random spacing from somewhere as it should just be a raw select-tag by itself.

**Comment by aharjula** [comment]
As to the first input having different spacing, it is probably just the traditional default layout... that might be hidden by whatever HTML editor you might be using.

**Comment by dhilsen** [comment]
Chris, I've attached a sample question showing the issue in a separate email. The WYSIWYG editor in the text editing window is switched off so all HTML is visible (except for any HTML which Moodle might be inserting behind the scenes).

I just happened to note that the problem goes away when the HTML paragraph tags are removed from the beginning and end of the paragraph containing the multiple drop-down fields. We have always used paragraph tags in our STACK problems and I assume this is correct procedure?

**Comment by aharjula** [comment]
Have not seen your example, but maybe Moodle does something odd again. HTML typically has no problem with raw select-elements within a block like the p-tag and typically selects flow inline just fine so having those paragraph tags there should not be a problem `<p>...<select><option...</select>...</p>` is all fine as long as all the tags are what they should be. Maybe there is some mystical CSS rule being applied to the first select? Anyway the select should be a select and we are not placing anything around it to break the line, it is generated [here](https://github.com/maths/moodle-qtype_stack/blob/master/stack/input/dropdown/dropdown.class.php#L356) and placed [here](https://github.com/maths/moodle-qtype_stack/blob/master/renderer.php#L49) and there is nothing added. 

As I have not seen the sample, did you check that the question-text is not using Moodle-autoformat and instead uses HTML-format so that we can be sure that we eliminated Moodles interference there. And are there any interesting filters in use that might cause this?

**Comment by dhilsen** [comment]
Thank you Matti for your helpful suggestions. The question text is not using Moodle-autoformat, and is indeed using HTML-format. The HTML editor does not display any HTML tag appearing after the first input field. To my knowledge there are no additional filters being used.

**Comment by dhilsen** [comment]
We have uncovered additional information regarding what is triggering this issue. The line-break (which does not show up in the editable HTML code) is being automatically inserted after the first validation field in the paragraph and not the first input field as reported above. If the first validation field is moved to the end of the paragraph, a line-break is then automatically inserted at the second validation field in the paragraph. 

Hopefully this information might be useful in resolving this issue.

**Comment by sangwinc** [comment]
Thanks, I will look into this.  Very busy couple of weeks with a big new "calculus for chemists" course....

**Comment by sangwinc** [comment]
This is nothing to do with the "dropdown" input type, but is easily recreated with the algebraic inputs.

I think it is caused by the following "div" tags which are used for instant validation.

`<div class="stackinputfeedback empty" id="q27:1_ans1_val"></div>`

I'll investigate what we can do to fix this.

**Comment by timhunt** [comment]
I don't think it is feasible to show the validation on the same line as the input. It has to be underneath.

Therefore, for any input with validation, there must be a line-break immediately afterwards.

I suppose that, for inputs with valdiation disabled, we don't need that, and therefore, we can not output the div in that case.

**Comment by sangwinc** [comment]
David,
Are you showing validation at all? If not, you can just move the validation tags to the end of the question text. This is not an ideal solution, and I can appreciate this does look like a bug!

**Comment by dhilsen** [comment]
Thank you for your input Chris. We are not showing validation for these type of questions, so yes, we can move the validation tags to the end of the question text. This is very easy to do and a good solution. I just wanted to make sure that in doing so we were not creating some unforeseen problem.
