### ISSUE TITLE
Spurious validation error breaking a previously working question

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#275]
We have a question where the question variables start by defining

```
binomialtex(e) := block([a, b], [a, b]:args(e), concat("{}^{",tex1(a),"}C_{",tex1(b),"}"))
texput(binomial, binomialtex)
```

This now give the error:

The following use of underscore characters is not permitted: _{.

This used to work.

I guess this is Matti's point that validation should ignore things in quotes.

**Comment by timhunt** [comment]
Oh! simple fix here:

```
binomialtex(e) := block([a, b], [a, b]:args(e), concat("{}^{",tex1(a),"}C_","{",tex1(b),"}"))
texput(binomial, binomialtex)
```

Since we are contatenating strings, we can just break the string into more bits.

**Comment by aharjula** [comment]
#273 and the fix I have in Abacus for this is enough. Concatenation, is not the way to go in any large scale.

**Comment by timhunt** [comment]
Thanks, but I need a quick fix for out questions now. I agree that your brance is the right long-term fix.

**Comment by aharjula** [comment]
Sure immediate issues aside... concatenation does not help you too much if those are in multiple choice questions option labels those might get validated twice...

**Comment by sangwinc** [comment]
Thanks for this Matti,
I would really appreciate your help in working on removing strings in master.  This and other issues need to be fixed, and as we support a wider range of cases (including subscripts etc.) this will become more important.

**Comment by aharjula** [comment]
I might have time for re-factoring the casstring validation so that it separates the things that do not care about string contents from the general syntax things that do care, around next week, but if I do that I would really wish that in the future when you add new validations like that `_{` you remember that most validations should not care about the contents of strings. And if I do that I will probably rename most of the component functions doing specific validations so that the function name is enough to tell if the function cares about strings, I would probably also rewrite quite a lot of loops... The main issue to be expected from this is the ordering of possible error messages as doing the checks in the same order as currently might not be sensible and that would probably lead to quite a lot of unit tests changing.

But we already have the base there from #234 we just need to remember the possibility of strings every time new validations are added.

Now if my unit testing only worked... I still have the same issues as I had in #253 and would really want to know why, could you tell me on what sort of an Linux install you are running the tests on as I can't get them working on Ubuntu 14.04 or 16.04 (installed a new vm from scratch just for this just last week and it did not work either) neither with local or pool maxima. It's still the fixtures tests that have that issue.

Should I do this I would also need to take unicode (#260) into account as that will surely affect the validation at quite high level (e.g. does our "-string parser actually survive a string with unicode in it) and would really appreciate sample questions actually using those fancy new symbols as my own test question set really does not contain much more than umlauts and those are not really exotic enough to require unicode to be used...

**Comment by timhunt** [comment]
Wouild it not be better to work on getting the abacus branch in a state to merge into master, rather than write yet another parser?

I am happy to help, but this is probably not the best place to debug your PHPUnit setup. Can you paste the output you get when you try to run the tests (possibly just in an email to me), and I will see if I can suggest anything.

**Comment by aharjula** [comment]
I don't think we need to write another parser other than to check that [these](https://github.com/maths/moodle-qtype_stack/blob/master/stack/utils.class.php#L554-L626) handle the potential new unicode. What I was thinking of doing is to split [this overgrown function](https://github.com/maths/moodle-qtype_stack/blob/master/stack/cas/casstring.class.php#L546-L843), and the smaller checks it calls, into pieces and to clearly separate the parts that can ignore string contents from the parts that do not.

As to Abacus, in my opinion it has been ready to merge for many years now. So, shall I just collapse its long history of merges with master to a few commits and create a pull request for that? In essence we need just to include the following things:
1. The "new" castext parser and block system with its primary blocks. (The external block part can even be dropped from this as no-one really uses it and if they do it can exist as a plug-in of sorts)
2. The conditionalcasstring that is the basis of the if-blocks.
3. The expanded question-note as the only database change.
4. The unit-tests from those and the rewrite of the old unit test from `@...@` to `{@...@}` and the slight change in output from them.
5. The conversion tool for automatic `@...@` to `{@...@}` question conversion.

For the PHPUnit issue, I do not believe it is an issue of my PHPUnit setup as that did not change and it only applies to those few very specific new test-sets that deal with the fixtures. But yes you can get my systems output as a mail soonish as I run it again with master-branch.

**Comment by timhunt** [comment]
I see now that #273 is an exact duplicate of this, so I will close this one.
