### ISSUE TITLE
Problem accessing the question tests page for a question with a multiple-choice input

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#290]
Someone told me about this today. And I have not had time to really work out what is going on, but I thought I would get it reported here.

To reproduce: Save this file [questions-M248-17J-07.ProductRule.polyexp-20170425-1547.xml.txt](https://github.com/maths/moodle-qtype_stack/files/955813/questions-M248-17J-07.ProductRule.polyexp-20170425-1547.xml.txt); rename it to .xml; and import it into the question bank. It looks like this:

![image](https://cloud.githubusercontent.com/assets/138653/25396961/73e0a09c-29de-11e7-9924-bcff4c519600.png)

(There is a good reason why this question has been done as mulitple choice in this particular quiz.) When you try to access the question tests and deployed variants page, you get this error:

stack_dropdown_input: could not find a key for `[6*(2*x-3)^2*%e^-(2*x)-2*(2*x-3)^3*%e^-(2*x),6*(2*x-3)^5-2*%e^-(4*x),%e^-(2*x)+(2*x-3)^3,6*(2*x-3)^2-2*%e^-(2*x),-12*(2*x-3)^2*%e^-(2*x),6*(2*x-3)^2*%e^-(2*x),-2*(2*x-3)^3*%e^-(2*x)]`

More information about this error

Debug info:
Error code: exceptionmessage

Stack trace:
* line 490 of /question/type/stack/stack/input/dropdown/dropdown.class.php: stack_exception thrown
* line 417 of /question/type/stack/stack/input/dropdown/dropdown.class.php: call to stack_dropdown_input->get_input_ddl_key()
* line 138 of /question/type/stack/stack/questiontest.php: call to stack_dropdown_input->maxima_to_response_array()
* line 68 of /question/type/stack/stack/questiontest.php: call to stack_question_test::compute_response()
* line 101 of /question/type/stack/questiontestrun.php: call to stack_question_test->test_question()

**Comment by sangwinc** [comment]
Sorry about this Tim,
I put in an exception because we wanted to enforce the integrity with dropdowns etc.  This does not apply when a teacher chooses a value for a test.

My guess here is that the question has been copied, and the old question tests get copied as well? Then you edit the question and the question tests lag behind.

This can be subverted by commenting out this line and deleting the question tests.
https://github.com/maths/moodle-qtype_stack/blob/master/stack/input/dropdown/dropdown.class.php#L492

Attached is an updated question.

Options for fixing the issue.
(1) Remove the exception.
(2) Better error trapping when teachers create question tests.

[questions-moodle32-07.ProductRule.polyexp-20170425-1842.xml.txt](https://github.com/maths/moodle-qtype_stack/files/955985/questions-moodle32-07.ProductRule.polyexp-20170425-1842.xml.txt)

**Comment by timhunt** [comment]
Confirmed. This was a question that was copied.

I think the answer here is to trap the error better in this case. It should be reported as a question test failure/error. It should not prevent the test page from displaying.

And also, now that I think about it, this sort of error causes the question tests to crash out when you run them all in bulk, and that is a pain. Better error handling would help there too.

**Comment by sangwinc** [comment]
This was a good opportunity to refactor the runtime error trapping for inputs.  Now there is one mechanism across all input types, and I've downgraded this from an exception to an error.  Comments welcome before I merge the code and close this issue.

**Comment by sangwinc** [comment]
Resolved, and code merged into master.
