### ISSUE TITLE
AlgEquiv test not recongising equal fractions

### ISSUE THREAD

**Issue by timlowe** [maths/moodle-qtype_stack#297]
Hi,
I'm not sure if this is new or not, but AlgEquiv does not, for example, recognise the following as equivalent.

\( \sqrt{2x/10+1} \)  and  \( \sqrt{ \frac{2x+10}{10}} \)

Sorry - I had my fingers crossed latex would be rendered. In plain text:

sqrt(2x/10 + 1)  and  sqrt (  (2x+10)/10  )

Any ideas?

Thanks,
Tim

**Comment by sangwinc** [comment]
Tim,
This issue is caused because Maxima automatically simplifies some expressions.  Have a look at the following example in a plain Maxima session.

```
radexpand:false$
sqrt((2*x+10)/10);
radexpand:true$
sqrt((2*x+10)/10);

```

Normally we have radexpand:true and so the expressions are changed, and Maxima can no longer show they are equivalent.  

In this case you can add "radcan" to each of the arguments of the answer test.  That is instead of

` ATAlgEquiv(ans1,ta) 
`
in the potential response tree try

` ATAlgEquiv(radcan(ans1),radcan(ta)) 
`

The reason we don't apply radcan by default is that it expands out any brackets.  Comparing (x-a)^6000 with (a-x)^6000 then becomes problematic!

**Comment by timlowe** [comment]
Great, thanks very much. Interesting that the issue hadn't arisen with us before!
