### ISSUE TITLE
Radio button deselect

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#304]
Problem: students can't "deselect" a radio button once pushed.  This leads to an awkward situation where a student selects an option, but then changes their mind.  They need to be able to de-select in order to avoid a potential penalty.

Solution: STACK always adds in a hard-coded "not answered" option to the radio input type.

However, some users don't like this.

(1) Separate the "not answered" from other other genuine options with better style.
(2) Add in an option to the input to remove the "not answered" option.  Suggest "mustanswer" as the option name?

See
https://github.com/maths/moodle-qtype_stack/commit/2b07becc9a067837948e66fcbb743d6d7aca6ca7#commitcomment-23813327

**Comment by georgekinnear** [comment]
This issue arose for me in writing a test where there were no penalties. The "not answered" option could be misleading for students in that situation.

Option (1) could work. Instead of inserting an extra radio item, there could be a "Clear selection" button added after the radio list. This would require some javascript to work though, which may not be desirable/possible. This would also make sense on the checkbox input type.

Given that imposing penalties is a design choice by the question author, my view is that including the "not answered" option should also be an active choice. However I can see that this would break existing functionality that people may be relying on, so option (2) would be a sensible compromise.

Incidentally, I don't mind the "not answered" option on dropdown lists, but perhaps for consistency the "mustanswer" option should apply to those too, if we go for option (2)?

**Comment by aharjula** [comment]
To add more complications, may I suggest that in the case of dropdowns the "not answered"-option could be replaced with the syntax hint fields contents... So that one can customise the field a bit more.

Essentially, the problem only arises when we have penalties and the input in question is the only input for any PRT with non zero point value. So we could identify that case and warn the author if that option is removed in such a case. However, as penalties can be disabled through question behaviours we cannot be sure if penalties exist.

Option (1) could act so that the "not answered"/"undo selection" option would only appear once something is selected and would be suitably styled, but that might cause usability issues with screen readers and such. Personally I would like something behaving like [this](http://jsfiddle.net/jSy35/80/).

**Comment by timhunt** [comment]
Reading some links, to remind myself of the issues here (https://ux.stackexchange.com/questions/13511/why-is-it-impossible-to-deselect-html-radio-inputs is a good summary).

Really, the only 'correct' solution is to have  'Not aswered' choice, which is what we currently do. I think we should not change this underlying HTML structure.

I think what we should do is to use CSS and JavaScript, to improve how it looks, and I think we can do quite a good job of that. Here is a very minimal proof-of-concept: http://jsfiddle.net/7qngu7ub/1/. Obviously not polished, but should be polishable.

**Comment by sangwinc** [comment]
Argh George, you have opened a can of worms here.
I never intended STACK to be used with MCQ anyway!
The standard Moodle MCQ (with radio buttons) has no "uncheck" options, but then has no penalties either.
I had something much simpler in mind with a very simple style: https://jsfiddle.net/8ssxhtpm/

**Comment by timhunt** [comment]
The fact that standard Moodle does not have this is a (very!) long-standing issue. https://tracker.moodle.org/browse/MDL-5311

**Comment by georgekinnear** [comment]
Sorry! MCQ are useful though :)

I like Tim's proposed solution - it builds on Matti's suggestion of being able to click to deselect, with a sensible reformatting of the "clear my choice" option which degrades nicely without CSS/JavaScript.

We should steer clear of "none of the others" as it's a subtly different question then (see p319 of https://sites.educ.ualberta.ca/staff/ldelia/M'Choice'Tests=Haladyna_Guidelines_AME_2002.pdf)

**Comment by aharjula** [comment]
The 'clear my selection' text/link in Tim's version is very important as people have very strong assumptions on how radio buttons work and may need to be given guidance that these are special and can be deselected. Now someone just needs to decide how that text will be aligned with the options so that the student understands what it means and what it connects to. 

Personally, I would keep that 'clear my selection' text hidden until something gets selected to avoid confusing the user by having an extra action presented before it is usable. By keeping it hidden we can handle the edge case of people printing out questions and being annoyed by that extra space it takes...

**Comment by sangwinc** [comment]
This issue is essentially fixed, and I've merged this fix back into master.  However, I've also started to add in the feature request to add in an optional alternative "algebraic" input for the MCQ classes, and this issue can be used to track progress on that feature request.
