### ISSUE TITLE
Answer tests fail with numbers smaller than 1e-9

### ISSUE THREAD

**Issue by dhilsen** [maths/moodle-qtype_stack#312]
We encountered an issue in which the NumRelative and UnitsRelative answer tests behave incorrectly when the teacher answer is on the order of 1e-9 and smaller. In these situations, the student answer can be any number which is significantly less than the teacher answer and it will be marked correct. For example, if the teacher answer is 1e-9, a student answer of 1e-10, or 1e-11, or 1e-12, or 1e-13 . . . will all be marked correct. The threshold where this issue starts to surface seems to be in the neighborhood of 1e-9 (a teacher answer of 1e-8 seems to be fine, whereas the problem is observed for 1e-9, 1e-10, 1e-11, 1e-12 . . . ). It was noted the issue occurs with teacher answers entered in exponent form, decimal form, and fractions composed of integers. 

It was also noted this issue occurs when unit conversions come into play. For example, if the teacher answer is 1.0 eV (a value equal to 1.6 x 10^-19 J), then a student answer of 1.6 x 10^-20 J, or 1.6 x 10^-21 J, or 1.6 x 10^-22 J . . .  will all be marked correct.

**Comment by aharjula** [comment]
Could you try running this attached question in your STACK 4.0 installation and tell us on which line the columns stop matching on the system these problems occur. Some LISP installations use double precision and others single precision floats and it might be a part of this issue. In any case this is something a sample question to debug would make much simpler to debug.

You should also know that inside Maxima "1*10^-3" "1/1000" are accurate but "0.001" or "1/1000.0" are not and in general it would be better to use the accurate form when constructing the teachers answer. The unit conversion functions use the accurate multipliers but if the value is not accurate the result is not accurate.

Naturally, accuracy is only an issue if you are summing non accurate values of wildly different scales and what I understand of your description that might not be the issue here.

[floats.zip](https://github.com/maths/moodle-qtype_stack/files/1336052/floats.zip)

**Comment by aharjula** [comment]
I think I found what causes this issue, but I am still very interested in knowing if your STACK works to line 16 in the question I attached.

Chris, this line might need some serious re-thinking, it probably is just a copy-paste error from the previous line but still:
https://github.com/maths/moodle-qtype_stack/blob/cf4d3a98c841c8278c7b44a0b003f8423f89c66d/stack/maxima/stackmaxima.mac#L931

it basically destroys the relative answer tests when dealing with values close to STACK_NUM_TOL.

**Comment by sangwinc** [comment]
Thanks for that Matti.  
Yes, I've engineered a situation in the code you identify which is classic numerical instability!  I agree we need a rethink.

Your question works up to line 16 on
Maxima 5.34.1 http://maxima.sourceforge.net
using Lisp GNU Common Lisp (GCL) GCL 2.6.12 (a.k.a. GCL)
My older machine at home has many other versions of Maxima on, and I can certainly have a look there.

**Comment by aharjula** [comment]
`abs(sa-ta) < abs(ta*max(tol,STACK_NUM_TOL))` would make more sense than the current `abs(sa-ta) < abs(ta*tol)+STACK_NUM_TOL`. Both would cap the tolerance to the defined but the first one would not add that extra bit of tolerance to larger tolerances. 

However as we are dealing with relative tolerances **we do not actually need nor want any capping** of that tolerance and the correct one (as far as I know) is `abs(sa-ta) < abs(ta*tol)`. Numerical accuracy does not really matter here as we are dealing with multiplications with "short" numbers and have none of the problems of additions/subtractions of different scale numbers where that STACK_NUM_TOL might have a role.

The absolute tolerance test however does need capping and in that case the `max(tol,STACK_NUM_TOL)` would make sense, maybe more than the current form.

**Comment by aharjula** [comment]
`abs(sa-ta) < abs(ta*tol)+STACK_NUM_TOL` does however have one place where it makes sense. `ta=0` but doing relative tolerance testing in that case makes no sense at all.

**Comment by sangwinc** [comment]
Re-reading the Maxima docs we have

```
 -- Option variable: fpprintprec
     Default value: 0
     'fpprintprec' is the number of digits to print when printing an
     ordinary float or bigfloat number.
     For ordinary floating point numbers, when 'fpprintprec' has a value
     between 2 and 16 (inclusive), the number of digits printed is equal
     to 'fpprintprec'.  Otherwise, 'fpprintprec' is 0, or greater than
     16, and the number of digits printed is 16.
     For bigfloat numbers, when 'fpprintprec' has a value between 2 and
     'fpprec' (inclusive), the number of digits printed is equal to
     'fpprintprec'.  Otherwise, 'fpprintprec' is 0, or greater than
     'fpprec', and the number of digits printed is equal to 'fpprec'.
     For both ordinary floats and bigfloats, trailing zero digits are
     suppressed.  The actual number of digits printed is less than
     'fpprintprec' if there are trailing zero digits.
     'fpprintprec' cannot be 1.
```
STACK currently sets this variable to 12 (which seemed reasonable to me as a pure mathematician!).  The maximum is 16, which probably explains why your example gives up at the 16th decimal place.

**Comment by aharjula** [comment]
`fpprintprec` is about presentation, what matters is the evaluation accuracy, which depends on whether the LISP uses single or double precision floats. In my example I use `dispdp()` to modify that presentation logic to ignore `fpprintprec`. The default 'fpprintprec=12' is probably used as it it is safely within the realistic accuracy of double precision floats but should the floats be calculated with single precision arithmetic it would lead to funny results.

**Comment by sangwinc** [comment]
True Matti,
However, values get passes to and from Maxima<->PHP.  Question authors might get confused when values are displayed correctly once, then passed back to PHP (where information is lost) and subsequently used.  I don't have an example of this happening at this point...

**Comment by aharjula** [comment]
Huh? The problem in this issue is the maxima code of `numrelativep()` which does not pass numbers to PHP? And in my example the values displayed are passed as LaTeX representation strings from Maxima and are not parsed by PHP at any point.

**Comment by aharjula** [comment]
Oops sorry I thought the `dispdp()` was still in pure lisp at https://github.com/maths/moodle-qtype_stack/blob/c8cf3aacf79cd82b2442051cd0fc27a2ceec2309/stack/maxima/stacktex.lisp but it seems to be commented out now.

**Comment by dhilsen** [comment]
Matti, Thank you for providing the _floats_ test question. We ran this question on our STACK installation and the two columns did indeed match up to line 16, with non-matching values beginning on line 17.  

We are running STACK 4.0 with Maxima 5.36.1.

**Comment by dhilsen** [comment]
After reviewing the above discussion, I was hoping to get clarification as to what decision has been made regarding how `STACK_NUM_TOL` is to be used in the `numrelative` answer test. For our particular use of wide ranging scientific values (1E-35 to 1E+35),  the inclusion of `STACK_NUM_TOL` as an additive term in the numrelative answer test presents a serious problem. With `STACK_NUM_TOL` presently equal to 1E-9, using `(ta*tol)+STACK_NUM_TOL` in the answer test results in the `(ta*tol)` term becoming insignificant for any teacher answer on the order of 1E-9 or smaller. This causes all students answers less than 1E-9 to be marked correct.  

Numerical accuracy doesn't appear to be the issue here. In the scientific community, numerical accuracy would seem to be equivalent to significant figures. As an example, we can use a numerical accuracy of 3 in the problem `4.50E-15/2.00E+20 = 2.25E-35` to adequately handle the computation. All the decimal places preceding 225 would not be part of the numerical accuracy.

**Comment by sangwinc** [comment]
David,
Thanks for prodding me to fix this.  I'm in week 2 of term and I have a very large class, so I'm sorry I haven't been able to deal with this as quickly as I might.  Clearly the existing code is wrong!  Apologies.  I've looked at Matti's suggestion, but we still do need our own STACK_NUM_TOL to ensure we condone some internal rounding.  So, I'm about to push a proposed fix. This contains some passing test cases for the very small and very large numbers you will need.  If you have more test cases this will be very welcome.  

Comments on this proposed fix before I merge it back into master?

Chris

**Comment by dhilsen** [comment]
Chris,
I believe we can work with `ev(abs(ta*tol)+STACK_NUM_TOL`. For this to work for very small numbers less than 1.0E-9 we would need to do the following:
1) `ta*tol` should be converted to scientific notation (**a** x 10^**b** where 1 ≤ **a** < 10).
2) Then `STACK_NUM_TOL` is added to **a,** and not the overall number.

Is this something in line with what you're thinking?

**Comment by aharjula** [comment]
Chris,

The proposed fix `abs(sa-ta) < abs(ta*tol*(1+STACK_NUM_TOL))` makes sense in essence it is the same as `STACK_NUM_TOL = 0` but adds that little fudge factor that is needed when we deal with -0 = +0 and 0.9999999999999999 = 1.0 kinds of things, although I do think relative testing does not actually need that... What is important here is that this test would work for values of any scale whereas the previous one only worked with scales larger than `STACK_NUM_TOL`.

What David says is essentially what happens there.

**Comment by sangwinc** [comment]
Just for the record, without the "fudge factor" the following tests fail.

https://github.com/maths/moodle-qtype_stack/blob/iss312/tests/fixtures/answertestfixtures.class.php#L958
https://github.com/maths/moodle-qtype_stack/blob/iss312/tests/fixtures/answertestfixtures.class.php#L959
https://github.com/maths/moodle-qtype_stack/blob/iss312/tests/fixtures/answertestfixtures.class.php#L961
https://github.com/maths/moodle-qtype_stack/blob/iss312/tests/fixtures/answertestfixtures.class.php#L963

I'd want the test to say that 1.05 and 0.95 are both "within 5% of 1", (even with the <= in the test) so I propose we keep in the rounding factor.

(A) My proposal is to test against ta*tol*(1+STACK_NUM_TOL)
(B) David's proposal a*10^b:ta*tol Test (a+STACK_NUM_TOL)*10^b

Since (a+STACK_NUM_TOL)*10^b is not  a*(1+STACK_NUM_TOL)*10^b these test different things.
However 0<=a<1, and so the real tolerance used will be somewhere between STACK_NUM_TOL and STACK_NUM_TOL/10.  We've chosen STACK_NUM_TOL=10^-10
(see https://github.com/maths/moodle-qtype_stack/blob/iss312/stack/maxima/stackmaxima.mac#L928)
which is well within the working precision of 10^-16.  We could have chosen 10^-11.  

The point (as I now understand it...) is to add some non-zero factor to account for rounding.

If we strictly adhere to David's proposal we will have to convert the internal binary representation of the float into a decimal to get "a" and then do the adding.  I expect this conversion will involve some rounding as well.

So, I agree David's code is correct, I think mine will have the same effect without needing the conversion in David's.  Comments?

**Comment by dhilsen** [comment]
I made my proposal prior to seeing that Chris had already proposed a very good solution - my apologies. In my opinion, Chris's solution of `ta*tol*(1+STACK_NUM_TOL)` would seem to address this issue in the most effective manner. Given our application of wide ranging scientific values, I cannot envision any case where it would give an incorrect result. 

Just thought I would add a reminder that all three relative answer tests will need to be updated: NumRelative, UnitsRelative, and UnitsStrictRelative.

**Comment by sangwinc** [comment]
Thanks for reminding me to check the UnitsRelative, and UnitsStrictRelative answer tests  These tests share the existing code, i.e. https://github.com/maths/moodle-qtype_stack/blob/iss312/stack/maxima/stackunits.mac#L513
