### ISSUE TITLE
New answer test - at least n significant figures

### ISSUE THREAD

**Issue by georgekinnear** [maths/moodle-qtype_stack#313]
In some situations I would like to be able to ask students to enter answers as decimals rounded to a given number of significant figures, but accept answers given to a greater number of significant figures (provided the figures I asked for are given correctly).

I think this is a good way to check that students have got the right number as the answer, and have done a bit of rounding, while not being too fussy about rounding issues (which are generally not the focus of the question).

This could possibly be achieved with a combination of existing answer tests in PRT, but I think it might merit having its own answer test.

My proposal would be a variant of NumSigFigs with the following behaviour:

NumSigFigs(ans,ta,[n,-1]) - accepts answers correct to at least n significant figures

NumSigFigs(8.250,8.250,[4,-1]) = 1
NumSigFigs(8.25,8.250,[4,-1]) = 0 % does not have sufficient sig figs
NumSigFigs(8.25000,8.250,[4,-1]) = 1

1/7 = 0.142857142857...
NumSigFigs(0.1428,1/7,[4,-1]) = 1
NumSigFigs(0.143,1/7,[4,-1]) = 0
NumSigFigs(0.14285,1/7,[4,-1]) = 1 % extra final digit, incorrectly rounded but condoned
NumSigFigs(0.14286,1/7,[4,-1]) = 1 % rounded correctly to 5 s.f.

**Comment by sangwinc** [comment]
George,

My first attempt is in the previous commit.  The "at least n sig figs" is easy, and useful.  I'm not sure I understand how you want to deal with numerical accuracy.  For example, does this test case make sense?

https://github.com/maths/moodle-qtype_stack/blob/iss313/tests/fixtures/answertestfixtures.class.php#L1148

I suggest you review all the test cases in lines 1137-1155.  Feel free to check out this branch, and add in more test cases as you see fit! 

We've added this into NumSigFigs as it shares a lot of code.  Any comments about overloading the options in this way, or should we have another answer test?

Chris

**Comment by georgekinnear** [comment]
Thanks for this, Chris.

I think I disagree with the behaviour in line 1148, where the truncation "0.14285" is not given the mark as it's deemed inaccurate. This seems odd when it's actually closer to the true value than the correct 4sf rounding, 0.1429.

Is it perhaps enough to check that the student and teacher answer have the same value when both are rounded to n s.f.?

**Comment by sangwinc** [comment]
I think this should also be an option for validation of input.  That is to say, we should be able to reject as invalid a number which does not have enough significant numerical information (sfs or dps).  

I'm thinking we need a bespoke "number" input (related to "units" perhaps?) where the student is *required* to enter just a number (no variables allowed, that would be invalid) and where one option is for the teacher to specify accuracy as a validation issue.  This would have solved a lot of problems this year with students being penalised on a technicality when really they have done a correct calculation.

Are there any more requests in this direction?

**Comment by sangwinc** [comment]
I'm planning to add in some new features to validation for dealing with numbers.  This will (1) ensure a student has entered just a number (so no variables) or a number and units, and (2) they have given enough information (decimal places/significant figures) to decide if they have answered a question correctly.  This will ensure students know how many figures we expect, and are not penalized on a technicality when assessed. 

These new options will apply to the Algebraic and Units input types only.

I'm planning to add this into the "other options" (rather than creating a new option) and in the form
```
  sf[n,m]
  dp[n,m]
```

If this option is chosen then the student's answer *must* be a decimal numbers (including integers, scientific notation, floats etc.) but not an exact number such as "sqrt(2)".   For sf[n,m] the student's answer must have between n and m significant figures.  

sf[0,m] will just check the student has at most m figures.
sf[n,+] will ensure the student has at least n figures.

If n>m we'll throw an error.

At this stage the options cannot be randomly generated, so n & m must be hard-wired.  This might change, but not in v1 of this feature.

Any comments?

**Comment by timhunt** [comment]
Sounds like a good idea.

**Comment by dhilsen** [comment]
Based on our experience, I believe the sf[n,m] option will be very useful. It's my understanding that this option is being proposed for the validation code only. 

Might I also propose sf[n,m] be added as a test option to the sigfigs answer tests in the PRT. It is our practice to make a small deduction to the student score when the student enters an incorrect number of significant figures, so it is our expectation that the student understands how to handle significant figures rather than being prompted as to the correct number of significant figures in the validation. However, the rules for handling significant figures in multiple-step calculations can be somewhat bewildering, particularly when multiplication/division is combined with addition/subtraction. For these instances it would be nice have the option to accept a range of significant figures in the student answer.

In regard to the topic of validation, there are two additional proposals I would like to put forth.

1) For those instances where we wish to provide validation prohibiting negative numbers (particularly useful when vector quantities are involved), it is our practice to add a minus sign to the Forbidden Words field in the validation. We run into a problem when the answer involves scientific notation with a negative exponent as the student is unable to enter the negative exponent. Perhaps a method could be devised to distinguish between negative numbers and negative exponents for the validation.

2) When a student inputs a character/expression that's been added to Forbidden Words, the validation text displays "This answer is invalid. The expression . . . is forbidden." My concern is that the word "forbidden" might be a bit strong, running the risk the disallowed character might be interpreted by students as one which should never be used in any question. (We disallow certain units in introductory questions in order that students are forced to make a particular unit conversion, however, we don't want to give the impression those units should never be used in the future.) Might I recommend the following language be used instead: "This answer is invalid. The expression . . . is not allowed in this particular answer."

**Comment by dhilsen** [comment]
I thought I should add a qualifying statement to my proposal to add a sf[n,m] type feature as a test option to the sigfigs answer tests in the PRT. As previously stated, handling significant figures in certain multiple-step calculations can be somewhat bewildering, and for these instances it would be nice have the option to accept a range of significant figures in the student answer. However, it may be best in these instances to use the validation to prompt the student for the correct number of significant figures (if they entered something different), and not leave them guessing as to whether or not rigid multi-calculation significant figure rules should be followed.     

Having said all that, a sf[n,m] option in the validation only may well be all that is needed.
