### ISSUE TITLE
Error in STACK question when solving trig cyclic equation

### ISSUE THREAD

**Issue by spinozarabel** [maths/moodle-qtype_stack#326]
Get an error that some solutions will be lost when solving a Trig equation Now given that solving a cyclic function we are interested here in only the primary solution (1st quadrant), this should be a warning and ignored. However, this breaks the question. Same code works fine in Maxima terminal as shown below together with Moodle's error.

Problem: solve for acute angle A,in 4cos(A)-1 = 1.
CAS code:
eq1:4*cos(A)-1=1;
b:solve(eq1,A);
A:map(rhs,b);
ta1:A[1];

The standalone Maxima terminal gives the following output:
eq1:4*cos(A)-1=1;
(%o1)                          4 cos(A) - 1 = 1
(%i2) b:solve(eq1,A);

solve: using arc-trig functions to get a solution.
Some solutions will be lost.
                                        %pi
(%o2)                              [A = ---]
                                         3
(%i3) A:map(rhs,b);
                                      %pi
(%o3)                                [---]
                                       3
(%i4) ta1:A[1];
                                      %pi
(%o4)                                 ---
                                       3
(%i5) 
The Moodle question gives the following error when I try to save the question with same code in the question variable section:
**The CAS returned the following error(s):b:solve(eq1,A) caused the following error: solve: using arc-trig functions to get a solution.Some solutions will be lost.**

**Comment by sangwinc** [comment]
Thanks for pointing this out.

As a general rule in online assessment I normally avoid inverse process such as solve, precisely because this leads to lost solutions and other such problems.  I start from the solutions and work towards the question, therefore avoiding the use of "solve" completely.  When assessing student's work, I substitute their values into the equation, thus establishing it is a solution, rather than "solve" and compare with the teacher's answer.

Something like the Maxima code

```
ans1:%pi/3+2*n*%pi;

lv:listofvars(ans1);
declare(lv,integer);
ev(eq1,A=ans1);
```

If you also want to check the student's answer looks like %pi/3+2*n*%pi; you can use the "SubstEquiv" test to make sure the arbitrary variable names doesn't matter.

One option would be to ignore the errors from "solve", but I'm reluctant to do this.  I think they are issued for a good reason!

**Comment by spinozarabel** [comment]
Thanks for taking time to reply. I understand your point. In this case, the problem was some other teacher's and I was lazy to do the solution :-) In such cases, I can easily enough do the solve offline and get the solution. I just wanted to know philosophy regarding treatment of errors in CAS.
