### ISSUE TITLE
optimising maxima documentation incorrect.

### ISSUE THREAD

**Issue by danmarsden** [maths/moodle-qtype_stack#331]
in: https://github.com/maths/moodle-qtype_stack/blob/maxima5-40-0/doc/en/CAS/Optimising_Maxima.md#gcl

it states you need to load stackmaxima.mac after loading maximalocal.mac - but maximalocal.mac already calls stackmaxima.mac and a 2nd attempt at loading it will cause a timeout/failure.

**Comment by sangwinc** [comment]
Thank you for reporting this and apologies.   Can I ask, is there also a problem with the automatic optimised image generation in the healthcheck scripts?  I use the automated process now, which I think is why the docs have drifted (as I don't refer back to them often any more).

Please close this issue if you are happy with the optimization process.

**Comment by danmarsden** [comment]
Thanks Chris, maybe the docs need further improvements? - I did see the button at the end of the healthcheck scripts but just hitting that button didn't seem to improve performance of maxima at all. Is there another step to follow after hitting that button?
Creating the optimised version using gcl, updating the path to point to the optimised version and switching from "linux" to "linux optimised" did seem to improve it a lot.

**Comment by sgparry** [comment]
You need the bug  fix for 327. It does it correctly (on linux) and reports success / error. The process gets very confused otherwise - it is supposed to:

set the config to non-optimized
generate the config (non-optimized - full library loads)
run maxima
save the new image
set the config to optimized
generate the config (optimized - no library loads)
run maxima
run simple 1+1 = 2 test
If anything fails it is supposed to reset the config back to start.
It does not report any meaningful result.
Unfortunately Stack caches everything so much, the config changes just get knotted up.
The fix 327 makes sure all the cached copies are in sync, allow it to work and adds a proper success / failure message.

**Comment by sangwinc** [comment]
That fix should be in the master branch now.  See https://github.com/maths/moodle-qtype_stack/commit/b524f70cbfdab0a3666985a1757431351cba478b

**Comment by danmarsden** [comment]
cool - good to know thanks - maybe the optimising maxima docs need to be updated to tell people to try this first before going through the manual steps to generate the new image?

**Comment by danmarsden** [comment]
in fact - reading it again it is there now  - I must have been reading an older version of the docs.

is there a reason why you bundle the docs inside the git repo instead of using the github wiki? - do the docs change quite a bit depending on the release?

**Comment by sangwinc** [comment]
In an earlier version of Maxima I put the docs on a wiki, and it got vandalized.  I think the github wiki is probably less prone to bots etc., _but_ try to keep the docs up to date.  You can check your version on your server for the features you have.  This is why the docs are a static wiki.  Github does an ok job of rendering them on the source pages (without the MathJax or images) and so people can also read that.

I'm very open to suggestions here.  If you have a proposal, let me know, but I'll close this issue for now!
Chris
