### ISSUE TITLE
addrow(M, list_1, …, list_n) is schadowed by addrow(m,i,j,k)

### ISSUE THREAD

**Issue by V55V551N** [maths/moodle-qtype_stack#333]
This is the Error Stack throws:

> Das CAS lieferte folgende Fehler zurück:s:for i:1 thru mRank-1 do m1:addrow(mx,col(mxtemplate,i+1)) verursacht durch den folgenden Fehler: Too few arguments supplied to addrow(m,i,j,k); found: [matrix([x1]),matrix()]

The function `addrow (M, list_1, …, list_n)` is a maxima internal function wich returns the matrix M with each list appended as new row.
![image](https://user-images.githubusercontent.com/1459179/33941835-3fb60432-e014-11e7-8894-7998b714fe8f.png)

The function `addrow(m,i,j,k)` is **not** needed **at all** because the same result can be archieved by using rowop instead:
`rowop(m,i,j,k)` Where `m[i]: m[i] - k * m[j]`
when invoked with a negative k it works exactly the same as `addrow(m,i,j,k)`
![image](https://user-images.githubusercontent.com/1459179/33941910-86af1496-e014-11e7-81bf-4f8ba6e3ab4e.png)

I suggest removing the function `addrow(m,i,j,k)` or renaming the function `addrow(m,i,j,k)` to something else like `rowop_add(m,i,j,k)`

**Comment by sangwinc** [comment]
Thank you very much indeed for pointing this out.  I've had a quick look at the STACK and Maxima git repros, and I've failed to identify exactly when the two functions were added.  From my memory (10 years...) I think we added our matrix operations before they were in the Maxima core, but anyway, we certainly now have an unfortunate conflict....

Our "addrow" has been there for a very long time, and I know we (in Edinburgh) make a lot of use of it.  Before we change anything in STACK we will need to quantify the effect of that change, e.g. in the number of questions which need updating as a result.

For this reason I'm not going to rush to delete this for the forthcoming 4.1 release next week.  Sorry if that is inconvenient, but we have live questions which might well break!

Options:
(1) delete our addrow and accept STACK users will have to edit questions
(2) do nothing and expect maxima users to live with the differences between STACK and Maxima
(3) other (suggestions welcome).

What do other people think?

Chris

**Comment by aharjula** [comment]
Chris,
It would be really nice if STACK questions would store what version of STACK they were created on or last modified on. If we had that we could eventually identify the old "ones" and fix them if a functions definition changes. We could even use the too slow (for live validation) prototype parser to simply find the calls and replace them with suitably shifted arguments and new expressions, but only if we know that we are not fixing something already fixed. However, I think that if we were to redefine functions we should not do it often and we should fix as many things as possible at the same time for example turn on mandatory semicolons and add the missing ones, and remove certain old aliases for other functions.

1) I do not really accept that people would need to edit questions as there are plenty of questions and we do not even have a tool to easily find the ones which use a given function. If changes need to be made they must be done by us automatically (part of the upgrade script and maybe after import of questions marked with old version).

2) Not good, our world is so much simpler if the Maxima documentation is the correct documentation and we never override any functions present in it and that we allow to be used. If we have to create new functions in the future we should name them so that this will never happen again.

**Comment by timhunt** [comment]
The approach Moodle takes to deprecating old functions is this:

* First make a change so the emit a debugging message to developers if used, but still work.
* The, eventually, remove them completely.

Translating this into the STACK context, I suggest that the equivalent of the first step would be to make form valdiation complain about use if these functions when a question is edited. We could also warn when the question-tests are run.

(Also, I will note that, when doing this sort of thing, the warning should not just say the function that is deprecated. It must also tell you what to use instead. Otherwise it is just annoying.)

**Comment by V55V551N** [comment]
Marking functions depricated and removing them in the future is a good approach.
What is the reccomended way to disable the addrow function in stack?
Do I need filesystem access to disable it?

**Comment by aharjula** [comment]
Sorry for the late response... but the way to forbid things would be to tune the arrays of forbidden and allowed identifiers in `stack/cas/casstring.class.php` simply add `'addrow' => true` to `$globalforbid` and you can never create a question with it nor will any questions using it run. Note that it will break existing questions!

And yes you need filesystem access to do that.

**Comment by V55V551N** [comment]
Thanks for the reply.
I dont want to dissallow the use of the function, i want to get rid of the definition shadowing the maxima core function.
I found the mac file where the function is defined. I will delete the definition there, that should unshadow the core function.

**Comment by sangwinc** [comment]
Yes, this is the problem we have: we want to **change** the function name, which will break a lot of existing questions.  I think ultimately the solution to this will be
(1) Adding in a version number to questions. I'll do this for v4.2.
(2) Adding a _warning_ system which allows teachers to use questions (i.e. does not render them invalid) but gives some helpful feedback.  I've wanted this for some time for other reasons.
(3) Adding a "grep" type functionality to search all existing questions.  This means a moodle site admin can seek out and fix existing questions as new functionality is implemented.
All the above is very general.

For 4.2, if we can get this done, I suggest we change the name of STACK's addrow, but keep the old STACK addrow in place for v4.2.  This will not break any existing questions, but users will be warned to use the new on.

For v4.3 we will change the behaviour so addrow now does what Maxima expects.

The general groundwork above is worth doing anyway.

Sorry if this doesn't help V55V551N in the short term (and until v4.3!) but you can always modify your local files if you want to have Maxima's addrow in the short term.

Chris

**Comment by sangwinc** [comment]
I've added in code into this branch which records the version number of STACK when a question is saved via the Moodle forms.

This will be needed to address the addrow issue.

**Comment by sangwinc** [comment]
I have tried to fix this problem in a way which enables people to identify the questions which are affected.  After some thought, I have decided to put the checking code into here: https://github.com/maths/moodle-qtype_stack/blob/iss333/question.php#L978

The reason for doing this is that both the questiontestrun.php and the bulk testing scripts have access to the "question" form of Moodle questions, not to the "fromform" version.  We don't want to do these checks everytime we edit a question either.   

This makes the re-factoring of the validation into questiontype not strictly necessary (as I wrongly anticipated it would be needed here).  However, I think the refactoring of the validation away from the Moodle form logic is a good move.  See issue #378 for comments on this as well.

Comments welcome on this.
