### ISSUE TITLE
Add in an option to resize the plots

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#334]
Add in an option to resize the plots

**Comment by sangwinc** [comment]
Comments please.

**Comment by georgekinnear** [comment]
For some questions (e.g. matching plots of functions with plots of their derivatives) it would be helpful to be able to adjust the size of the plots, from the default of 450px wide.

Additionally, the plots are currently being produced with a lot of blank space embedded in them (see example below, where a border has been added to illustrate the image dimensions). It would be good if this could be removed, as this would make it easier to fit multiple plots in one question.

![image](https://user-images.githubusercontent.com/30723394/33955709-6547ae88-e034-11e7-856f-f77b8f0528f8.png)

**Comment by sangwinc** [comment]
This is a start, but in your example Maxima is still producing a square plot within a rectangular image file, with some white padding.  If you want a tighter cropped image you will have to investigate maxima, gnuplot and how you can create an image you are completely happy with.  If you send me an example, with some info on the Maxima/gnuplot options which generate it, we can wrangle over how to expose them through STACK!

**Comment by georgekinnear** [comment]
Thanks, I think that is working fine.

The issue with the whitespace is that the plots are hard-coded to have certain dimensions:
https://github.com/maths/moodle-qtype_stack/blob/742d805efeb91c6730e50d6411825545e4886f55/stack/cas/installhelper.class.php#L74 

Unfortunately I can't see a good way around this - the png driver for gnuplot does include a "crop" option which gets rid of unnecessary whitespace (http://gnuplot.sourceforge.net/docs_4.2/node409.html) but this doesn't seem to be part of the svg driver.

You could potentially expose a "PLOT_DIMENSIONS" global variable which should be a list of two integers, and this would be used here instead of the hard-coded dimensions:
https://github.com/maths/moodle-qtype_stack/blob/c680a66ff77ebd7ac3f1a0495f3d45baa10917e9/stack/maxima/stackmaxima.mac#L838
(with the width also used to set the img width). I don't know if that perhaps allows users too much power to produce bad-looking plots...

**Comment by sangwinc** [comment]
OK George, please leave this with me and I'll include plot options in the next release.
