### ISSUE TITLE
Please copy all contents of doc/en into a new doc/es_mx directory

### ISSUE THREAD

**Issue by germanvaleroelizondo** [maths/moodle-qtype_stack#337]
Hi,

I want to try to translate (some of the most important) user documentation currently available only in the doc/en directory of this GitHub page into the mexican Spanish language.

I have tried unsuccessfully to do it myself, but I think it would be a lot faster and less error-prone if you were so kind as to copy all of the current contents of your doc/en directory into a new doc/es_mx directory.

I will later fork this repository, edit one file at a time and do pull requests for changes into this doc/es_mx folder.

Thans in advance for your help.

BTW: The new language packs for https://stack2.maths.ed.ac.uk/demo seem to be working quite nicely. I have Emailed one mexican STACK user (Victor Hugo Huerta) listed in https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/About/Community.md and asked for his help in improving the now complete qtype_stack es_mx translated strings.

**Comment by sangwinc** [comment]
Firstly, thank you very much indeed for translating STACK.  Much appreciated!

I'm really keen to have docs in many languages, and also some sample materials.  And, I'm very happy to help you get this all working.

Are you sure that copying the files over is the right approach?  We've not given a lot of thought to multi-language support for the docs yet, and there is quite a lot in the docs.  My expectation is that where a file exists in a multi-language docs it will be served, otherwise it will default back to the English.  Therefore, _copying_ the files wouldn't be a good idea.  An alternative is to have a shorter introduction to STACK in many languages, e.g. with things like the authoring "quickstart", which then have the definitive references in English.

I must apologise that I only speak English!  I know this effectively means currently all question authors will have to understand a little to use the Maxima function names etc., but I will help people make the most use of this in their own languages, both as teachers and students.

Chris

**Comment by germanvaleroelizondo** [comment]
Hi,
I think I remember that Tim Hunt once commented that he thought that having the instructions in the author's preferred site (in several languages) would be the better way to keep them updated, but It looked too complicated for me back then. Replacing an existing string with a translated one would be easy for me now, even in GitHub.

I would personally prefer to have the basic instructions in all languages available in Moodle Docs, as any Moodle user who is stuck inside a plugin configuration page (or a question design page) might click on the 'Moodle Docs for this page' link at the bottom of the page. 

Please see the Modle Docs page at https://docs.moodle.org/34/en/Offline_quiz_activity for one case of point. 

Also, there are many Moodle Docs translators working daily in many languages.

But if you copy the most important English document files into a new es_mx directory here in GitHub, I can translate them (via fork and pull request) and later copy the text into Moodle Docs in Spanish.

Maybe we can try with just one file and see if the downloaded ZIP file does show the information in Spanish once installed.

Or maybe we can think about it for a while and continue this chat after the holidays :)

I will be looking forward to your reply.

Happy holidays!

**Comment by sangwinc** [comment]
I've created a new branch for the es_mx docs.

This code: https://github.com/maths/moodle-qtype_stack/blob/master/doc/doc.php#L45
ensures the language preferences are set.

I've not created the directories or the files because the directory _names_ and the _filenames_ have some meaning in the docs system!  Therefore, the filenames should be translated as well... For example, if you look at the "sitemap" link you will see a list of pages, which is generated from the filenames and directory names.

I really like having this simple static wiki.  It enables me to document as I do, secure in the knowledge that the docs are tied to the code in git, etc.  I didn't really think ahead to supporting multiple translations.

Now the stub is in place we have to think about whether you would like to somehow translate the docs, and link any "missing" pages back to the English docs, or some other suggestion.
