### ISSUE TITLE
Maxima's load command

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#34]
Hi!

Just a quick question. Some additional functions can be used in Maxima if one issues a load("package"); command. Can this be done in Stack? 

Thanks again, Mikael

**Comment by Famondir** [comment]
I wanted to ask the same question. We are using some custom code to check for significant digits (including zeros at the end) on a string basis and many more. This code is copied from one question to the next. It would be great to just put them in a custom package and load these. Can you explain where to alter the maxima code locally or to remove the load restriction (in the STACK code?)?

**Comment by sangwinc** [comment]
I really want to support letting teachers create and share custom code between questions.

If you create a maxima-init.mac file in the share folder in the maxima folder on your server then any questions you write which use this code will only work on your server.  That will make it very difficult to maintain your questions, and you will not be able to share them with anyone else.  Only system admins can edit this code. I want a solution which enables teachers with only normal permissions to share maxima code fragments.

The problem is really one of design.  Things to consider.
1. who gets to edit any shared code? (classic problem of permissions)
2. what happens to questions when shared code is edited? (classic problem of version control)
3. import/export?
4. how can we get useful and widely used shared code into the core STACK codebase (long term support, public sharing in an OS project, documentation, testing....)

None of these issues is particularly difficult but the design is really the main problem!  I'd welcome some help with this.

If you have custom code to check for significant digits (including zeros at the end) on a string basis are you willing to share this? How does it differ from https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/utils.mac#L72 

Really, I'd like any solution to help us share useful bits of code easily between questions and help people contribute back to the project as a whole.  Suggestions welcome!

**Comment by aharjula** [comment]
The problems that Chris stated are quite important but the fifth one that I fear the most is one that basically kills all solutions requiring modification of the system level Maxima libraries. Including common code at the system level means that all questions being executed in the system will include that code and if it is there it affects them all, maybe not directly but through slight interaction with whatever they try to do, and those side effects will make the long term viability of those questions quite problematic. I fear the minefield that may form through such extension and the trouble of debugging the situation if one does not know the extensions in play.

My view is that we should have the means for a question to request specific extensions (fragments of code) to be included in that question and only that question and thus avoid side effects to other questions. In my opinion, the import/include-commands mentioned in #691 represent the most viable route forward and I am pursuing that route in my development. Both for the CAS-code and the CASText code inclusion so that questions can share logic as well as presentation details.

**Comment by Famondir** [comment]
@aharjula you are totaly right. This approach would be much better. I came to some of the points both of you mentioned earlier by myself. How can we include the most recent version of our files in the used docker image without bother our admin every time? I thought about sourcing it from github somehow.

What about other groups that use the same function name in their source code? Therefore, the load statement would be pretty good to only load our own code. But the possibility to `load` only stuff you need. And if this gets possible from a url... that would be awesome!

I thought about the possibility to achieve this via java script code as we have seen many cool stuff via JS recently. But I'm not experienced in JS right now.

Looking forward to the import/include possibility!

**Comment by aharjula** [comment]
Indeed the possibility of name collision is also a problem especially if we consider versions of the same code developing into different directions in different installations. This is why I would much prefer to see the code that is being loaded existing outside the system and loaded in from an URL as in that case the party controlling the URL is unique and anyone wishing to freeze or modify the version being served can just make their own fork and serve it out through a different URL.

Of course, the URL solution does bring up one major risk. It is not hard to imagine a large family of questions using a single shared URL logic and that URL disappearing after some person changes universities in that case we would need some easy means for replacing the URL in the questions and we would surely hope that someone held on to a backup copy of that logic.

Unfortunately, inclusion through JS is not a possibility, the CAS side logic happens on the server in a place where we do not wish to see JS.
