### ISSUE TITLE
Better distribution of plot files on disc

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#415]
At the moment, all the plot files are stored in moodledata/stack/plots. At the moment at the OU, our plots folder contains ~350K files, and that many files in one folder is a good way to make filesystems cry.

So, some sort of sharding of the directories might be good. In the plot filename (e.g. stackplot-3750071431-46248239.svg) the first number is the current timestamp (Maxima code string(absolute_real_time())) and the second number is string(rand(10^8)).

So, the second number will be randomly distributed, and so a good hash key. It is proably enough to put the plot in a directory named for the first 3 digits of that, then we would have 1000 folders each containing about 4000 files. that should be fine.

However, really what we should do is change the code so the mapping plot filename <-> path on disc is just defined in two functions (one to go each way) so it is easy to change in future. (I don't currently have a lot of time to work on that, so I am happy for anyone else to have a go.)

**Comment by timhunt** [comment]
Note, another improvement, if it were possible, woudl be to stop using random numbers in the filename, and instead use something like a SHA1 hash of the file contents. That way we woudl be sure to only store one copy of each different image. Not sure if that is possible in Maxima.

**Comment by aharjula** [comment]
Well there are hash functions in Maxima, we just need to read the currently generated plot in from the file for hashing and rename / move it based on the hash. Otherwise we would need to build the data to be hashed from the plot arguments and that might be difficult as those arguments are probably expressions... and some might be global parameters.

[Census](https://raw.githubusercontent.com/aharjula/moodle-qtype_stack/iss324/stack/cas/base-identifier-map.json) says that `md5sum` has been available since 5.31.1 and `sha1sum` since 5.34.0, can't see any older ones available. As #409 will probably raise our Maxima requirement to 5.32.0 we can probably go for `md5sum` as long as its package doe not bring too many bad things with it.

For MaximaPool users we need to check that the unpacking in the connector deals with folders and that Pool recurses into folders when it packs the result files if we go for Maxima logic placing the files.

**Comment by sangwinc** [comment]
Note to self: it we change the plot filenames by adding in an md5dum, and removing the random element, we will change the number of random number generation actions. This may mess up the randomisation of number which come after a plot command....

**Comment by aharjula** [comment]
Note to Chris, `md5` sums are smaller than `sha1` sums and we would prefer more bits in the hash for the hope of less chance for collisions. The chance is small but it suffers very much from the birthday problem, which matters for most of us. Ideally, bump maxima to 5.38.1 and have `sha256` and Unicode at the same time. Or use multiple different hashes in the filename to combat the collision risk. I do not expect that people have millions of plots in their systems when the collision risk starts to be very real I expect that people might have tens of thousands and would not like to see collisions to happen in either case. As long as we use hashes the risk of collision exists but we can always try to minimise it, and a bigger or multiple hashes is the easiest way to have that.

**Comment by sangwinc** [comment]
Ok, so we wait until we can assume 5.38.1.  Both our servers in Edinburgh are using 5.38.1, so this is no blocker for us.  Do you have a suggestion when we might be able to require this?

**Comment by aharjula** [comment]
In my opinion, we should require 5.38.1 immediately and should in no case allow anything less in 4.4. That version would also bring everyone to the Unicode era.

5.38.1 is about four years old release. The oldest Moodle we support is merely two years old so it would not be a disproportionally stricter requirement.

**Comment by sangwinc** [comment]
Matti, I'm keen to make sure we support the version of Maxima which comes "out of the box" with popular Linux distributions such as Debian, using the package manager.  STACK is difficult enough to install as it is, and asking people to compile Maxima from source would be an insuperable barrier.  Especially as they then also have to get LISP!  So, it is inevitable we will maintain support for Maxima versions long after we stop support for Moodle.

**Comment by sangwinc** [comment]
This issue is not currently a priority for the project, sorry.
