### ISSUE TITLE
Allow empty inputs

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#419]
Following from the very interesting conference in Germany last week (Thanks to the ILIAS group), I've been persuaded that we should support "empty inputs" in some edge cases.

My original design was to expect uses to type in a "set" of objects, when the number of was uncertain but this does not work in all cases.
1. Sometime each expression in the set is too large for comfort, or benefits from separate validation
2. Sometimes inputs are also needed separately (in multiple PRTs)

This was not all that hard to do, but there will be other problems

**Comment by aharjula** [comment]
Chris, I hope that you would explain this a bit more as for now my understanding has been that a PRT fires only when inputs tied to it have valid values. My quick interpretation of this issue is as follows can you say which of these is closest to the issue?

 - A. Inputs with multiple values, e.g. input undefined number of expressions with some way of the student to ask for more or less boxes to fill. Like in a matrix input with no predefined dimension but now generating a list (a set could be an option if one wants to limit the input to unique values at validation level and does not care about order) instead. Would "empty" here mean that the student intentionally removes the last box and we then interpret that as an empty value that is intentionally empty and thus valid?
 - B. More complex trigger conditions for PRTs. i.e. a PRT could say that a given input is not mandatory, however how would it then separate the situation of it having a value as opposed to not. Or more likely PRT specific validation rules for inputs?

As to your points:
 1. Sure but that is an authoring problem if people ask for lists/sets they need to structure things so that the elements will be sensible. Otherwise we need to provide a way of providing a validation-function that would be called for the items to do the separate validation after the input has otherwise found to be valid. Could be done as an option of the input but could make things quite complex. Especially, from localisation point of view as for such an additional validation to make sense it needs to provide custom validation messages and currently we have no means of localisation within Maxima for author generated strings. 
 2. Yes and do not forget that some inputs are not part of any PRTs at all. For example some of us add confidence level style inputs to questions (manually and inline not through behaviours) that have absolutely no role in grading but can have their values extracted in latter analysis. Especially, the notes input type is one of these things.

In any case please say that I understood correctly and A is the correct interpretation as B brings quite a lot of complexity with it to the model.

**Comment by sangwinc** [comment]
Sorry if this isn't clear Matti,

Yes, up until now we required some kind of non-empty valid input.  I'm proposing that we add in an option for accepting an empty box.  In particular, there will be an "EMPTYANSWER" atom which will be used internally.  This means PRTs still get a definite object to work with, and one which says to the PRT "the student left this input empty intentionally".

If inputs are not part of a PRT then they will be unaffected by this proposal.  

I didn't really consider more complex PRT trigger conditions.  This might be an alternative way to go.   (My guess is they are equivalent), but we would still need to assign a value to any input which the student left blank within the PRT!  I'm in the process of unit testing the proposed code, which I hope will be self-explanatory.  I'm very happy to reconsider.

**Comment by aharjula** [comment]
Ok. Understood, and the `hideanswer` is indeed handy with JSXGraphs as if we dump the values of "state"-inputs even to quiz reporting things get messy.

PRT triggers is something I would hope that you will not consider they just happened to come into mind as a possible bad solution. The validation-function being one other bad idea.

I hope that you make the question editor validation say something if people create PRTs that only have inputs with `allowempty` as question having such an configuration will behave very badly.

**Comment by timhunt** [comment]
Had a quick look at the initial implementation. Looks OK to me.

**Comment by sangwinc** [comment]
Thanks Tim,
Nothing unexpected from the unit tests, so I've merged this into master.
Chris
