### ISSUE TITLE
[Proposal] Provide buttons for separate PRTs.

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#422]
At the recent STACK conference, some users (mainly through ILIAS) wanted "separate check buttons for each PRT".

In the move from STACK 1 to STACK 2 (where I introduced my first multi-part questions, although Matti had developed "multi-input" questions much earlier in another branch) I devised the separation of inputs from PRTs.  This is difficult for users (teachers) to understand!

At that point I decided that it would be best to have one button, "check" at the end, and let the system sort out the logic.  There are some edge cases, e.g. what happens if someone changes a correct answer to an invalid one, and then presses "check" on a different PRT?  And to avoid having to worry about these edge cases I put in one check button.  This is clean, and everyone knows where they are with the design.  As a design it has served us well.

I do completely understand the request from users for more than one button, and as STACK questions get more complex we are probably going to need it.  People are already writing more complex questions than I had in mind when I stared out, and for them separate buttons matter more.

I've always designed STACK by looking for questions that really need a feature.  Do you/your users have examples where they want this feature?   If we work from examples we can decide if they also really need it and how to proceed.

I'm worried because we probably want "buttons" which are linked to groups of PRTs, not a single PRT, with the default to link the button at the end to all the PRTs!  

I propose to introduce a tag  [[check: prt1, prt2]] would add a button in that location which executes prt1, prt2 etc. (assuming all inputs on which each PRT relies is at the valid status of course!).

1. If there is no [[check: ....]] tags in the question text then we keen the current behaviour.
2. If there is at least one [[check: ....]] tag then all PRTs must appear in at least one check tag (otherwise we get a question error).
3. PRTs can appear in any, and as many tags as needed.  Easy to create "nonsense" questions, but that is the teacher/question author's problem!

That would get us the feature you like, within the current system and without breaking old questions.  It adds flexibility not really asked for, but which I think people don't know they need.

Please can we have some examples?

**Comment by jcopado** [comment]
Hi Chris, 

As you know, I find this idea great, and very useful. Something important to decide would be the message of these new buttons, if it's just check would be OK but will give not so much information, and if it is check + PRT name, it will mean nothing for the student. Which plan do you have about this?

**Comment by aharjula** [comment]
Some technical things to consider:
- Labels for those buttons, "Check: prt1, prt2" is not a sensible text to place on a button not even if authors start to name PRTs with more verbose names. I would expect people wanting buttons like "Check part A", and the rules governing PRT naming might make such labels dificult.
- Localisation of those labels, for multi-lang using questions might need to provide multiple labels. For them having a forced "Check" no matter translated prefixed to the label might be a problem, so we should consider that too. Probably something like: `[[check: prt1, prt2]]<span class="multilang" lang="X">..</span><span class="multilang" lang="Y">..</span>[[/check]]`
- `[[check: prt1, prt2]]` in the case where `prt1` has all the necessary inputs but `prt2` does not. Should it stop checking because it cannot check both or should it just check `prt1` i.e. do we say that we cannot check as there is not enough input to check if even one PRT lacks input. Also how do we tell the student pressing the button which fields they should fill first? Should there be scripting that would activate the button when relevant fields have content?

**Comment by aharjula** [comment]
The major hurdle for this will obviously be the question behaviour side on Moodle and whatever corresponds to that in ILIAS. Telling that to only grade some PRTs might be difficult especially if we want to not grade others.

In any case I hope that this separate check button feature would lead to more imaginative naming of PRTs on the side, often enough they are obviously testing part A or B but often the test focuses on some interesting feature and one would wish to see the PRT name reflect it. Just for fun here are twenty most used PRT names in Abacus, so very imaginative...
```
  n   |    name    
------+------------
 7812 | prt1
 2312 | prt2
 1292 | prt3
  715 | prt4
  578 | akohdanpuu
  452 | bkohdanpuu
  408 | Result
  294 | prt5
  288 | ckohdanpuu
  202 | a
  200 | b
  178 | prt6
  163 | dkohdanpuu
  125 | prtans1
  119 | prt7
  118 | ans1
   91 | prt8
   80 | c
   67 | ans2
   65 | SAns1
(20 rows)
```

**Comment by sangwinc** [comment]
I had in mind not giving the user the ability to name the button, and just having "check" on the button.  The position of the button should be enough to make it clear.  Indeed, students think that input=part, but teachers think prt=part, so we already have this kind of slight blurring of what a "part" of a question really is. That is the whole point and strength of the design.

So, perhaps a pass (1) would be to create the feature with just pulling the language string for "check"?  By naming the buttons, we can get the STACK question type to deal with the logic of this through the normal grading request call.  E.g. if the field "check_A" exists within the data posted back, we know check button "A" has been pushed, and internally that fires PRTs, akohdanpuu and bkohdanpuu in this question.

This this proves to be a useful feature, and people really _need_ to name buttons we can add an additional feature leater?

**Comment by timhunt** [comment]
In the standard STACK demo quiz (https://stack2.maths.ed.ac.uk/demo2018/mod/quiz/view.php?id=140) the places where this might be most useful are questoins 2, 3, 4 and 8, and I am not sure that all of them need it.

Instead of mulitple check buttons, there is an alternative which might be worth considering: What about an option to disable input2 until prt1 is graded right? That would then guide students through the right sequence in which to answer the question, but with only a single check button.

**Comment by aharjula** [comment]
Chris, I would go for labels from the start, I do believe they have a role here. But obviously, raw "Check" buttons will work if one uses layout to tie them to the question e.g. put a `<hr/>` after each check or some such.

Tim has an interesting idea there... now if we also had access to knowledge of whether a given PRT is complete in the question text we could expose the question text as answers are given maybe even hide the previous parts... Having spent quite a lot of time trying to have the question engine handle information for doing just that it would be interesting to see how even that input exposing would be done. Lets just say that behavior vs. question type vars and access to them at the correct places for that to work might prove surprisingly difficult.

**Comment by fneumann** [comment]
I see a concptual difference between moodle and ILIAS regarding the check buttons. In ILIAS we do not have question behaviors, just the question types and the standard test object. So we might get problems with the second condition of your proposal:

"If there is at least one [[check: ....]] tag then all PRTs must appear in at least one check tag (otherwise we get a question error)."

In ILIAS, when instant feedback is switched on in a test, the general "Check" button is rendered by the test player, not the question type. So it will always be there, even if there are additional partial check buttons generated by STACK. Grading will only be done for the that general check, or when the user moves to another question. So we intended that a click on a partial check button will just call STACK by ajax and only show the feedback coming from its prt(s), without storing anything.

Specifying labels for check buttons would not be essential for us, as a check button can be included in the question text an something written before. But the localisation like proposed by Matti would be the best solution.

Is it really needed to allow multipe PRTs being checked at once with a button? Questions using partial check buttons can be designed in a way that all feedback provided by a check button is put in one PRT. But I'm not a question author, I hope our colleagues will provide examples.

**Comment by sangwinc** [comment]
Fred,

"So we intended that a click on a partial check button will just call STACK by ajax and only show the feedback coming from its prt(s), without storing anything." 

I think could be very confusing to users! It could also be very difficult with the penalty scheme.  We need to store the fact than an "attempt" has been send back.

Chris

**Comment by fneumann** [comment]
Yes, penalties are serious point. It gets even more complicated as ILIAS has its own functionality for static hints and penalties that can be defined for any question. We do not yet support this for STACK as it would conflict with the penalties in the response trees.

In ILIAS tests we also do not yet have a general concept for question states and stepwise answering. We could introduce it with some tricks for STACK, but that behavior would deviate from other question types and we may get problems with future updates of the question service.

As a consequence I see our current 'ajax' solution that we implement for one University as the lowest possible step forward with a certain range of usages. A partial check button will only call the evaluation of one PRT and that PRT should not produce points or penalties. The question authors have to take care that this 'Partial feedback PRT'  is used in combination with the granding PRT(s) in a meanigful way.

I like Tims idea of showing question parts depending on the grading of one PRT. At the STACK conference we already saw examples of this being done with javascript magic in the feedback of a PRT. But it has security issues to allow javascript in feedback texts. In ILIAS it would only work if instant feedback is switched on in the settings of a test. This is a typical setting for self-assesment, but it can't be enforced by single questions.

**Comment by sangwinc** [comment]
I think this functionality will be possible with the new "allowempty" features we put in here.
https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Authoring/Inputs.md
This is relatively new, and will get us a long way.

Adding a button to check one PRT completely changes the "model" of how STACK works.  I will revisit this issue, but it isn't something I can manage in the next couple of weeks.

**Comment by sangwinc** [comment]
Five years later, and we still don't have a compelling reason to address this issue!  If you really need this, please contact us again.

**Comment by sangwinc** [comment]
Just to note, some of this can be achieved by variant matching which has advantages of splitting questions into much smaller units. See https://docs.stack-assessment.org/en/Moodle/Variant_matching/
