### ISSUE TITLE
Bad field stackversion definition

### ISSUE THREAD

**Issue by bobopinna** [maths/moodle-qtype_stack#425]
I tested moodle database schema with /admin/cli/check_database_schema.php

This was the result:
qtype_stack_options
 * column 'stackversion' should be NOT NULL (X)

I made some troubleshooting and I found that there is a mismatch in stackversion definition:
install.xml define stackversion as NOT NULL
upgrade.php create it as NULL

No values are set on plugin upgrade and it seems that also questions editing not set stackversion.

HTH

**Comment by sangwinc** [comment]
Thank you very much indeed for pointing this out.  Appologies, we will fix this.

**Comment by timhunt** [comment]
As Matti says, becuase of import from other sites, we need to allow NULL. Also, all the existing STACK sites that ran upgraded from preview versions have that column set to allow nulls, and we don't get errors. So, I will change the install to allow null too, and that should be fine.

I will also do an upgrade step so that anyone who installed recently has the NOT NULL constraint removed.
