### ISSUE TITLE
facexp not found

### ISSUE THREAD

**Issue by jIyajbe** [maths/moodle-qtype_stack#432]
Hi Chris, I have one for you. Hope it's something simple!

Issue: 
Whenever "Check the type of the response" is set to "Yes", any student-submitted answer throws a file_search1 error.

Details: 
in the "Input" section of the question authoring UI: Regardless of any other setting or formatting of a STACK answer (e.g., numeric, algebraic, units, etc.), if the option to check the type of the response is set to "Yes", then when an answer is entered in the answer field, the following error is displayed:

"This answer is invalid.
file_search1: simplification/facexp not found in file_search_maxima,system.algebraic_equivalence: evaluating collectterms threw an error."

Steps to Reproduce:
1. Create a question whose answer is mu_0*(I_1-I_2)
2. In the "Input: ans1" section, set "Check the type of the response" to "Yes"
3. Save the question ("Save changes"), and then preview the question (from the Question Bank).
4. In the preview window, click "Fill in correct responses"

Actual Result:
The following output is displayed:

"Your last answer was interpreted as follows: (I1−I2)μ0"
"This answer is invalid."

"file_search1: simplification/facexp not found in file_search_maxima,system.algebraic_equivalence: evaluating collectterms threw an error. file_search1: simplification/facexp not found in file_search_maxima,system.algebraic_equivalence: evaluating collectterms threw an error."

"The variables found in your answer were: [I1,I2,μ0]"

Expected Result:
System should report "Correct answer, well done."

Additional Errors: 
When "Check the type of the response" is set to "No", the question appears to work normally, but upon clicking "Submit and finish", the following errors get thrown:

"TEST_FAILEDThe answer test failed to execute correctly: please alert your teacher. file_search1: simplification/facexp not found in file_search_maxima,system.algebraic_equivalence: evaluating collectterms threw an error. file_search1: simplification/facexp not found in file_search_maxima,system.algebraic_equivalence: evaluating collectterms threw an error."

and

"Saved: ans1: (I_1-I_2)*mu_0 [score]; prt1: CASError: file_search1: simplification/facexp not found in file_search_maxima,system.algebraic_equivalence: evaluating collectterms threw an error. file_search1: simplification/facexp not found in file_search_maxima,system.algebraic_equivalence: evaluating collectterms threw an error. | | prt1-1-F"

Notes:
This problem also occurs when the answer is a simple numeric value.
OS: macOS High Sierra
Maxima: 5.38 SBCL
Using optimized image
--Same behavior with both using Maxima directly, and using the optimized image

**Comment by sangwinc** [comment]
I'm very sorry indeed you are having these problems.  Thank you for such a detailed and helpful error report.  Much appreciated.

The option you describe is "sameType", and there are lots of unit tests in the current code base, e.g. 
https://github.com/maths/moodle-qtype_stack/blob/master/tests/input_algebraic_test.php#L295

None of these tests fail. In addition I've written a question and tested this on Maxima 5.38.1, using Lisp GNU Common Lisp (GCL) GCL 2.6.12 on Debian.

Subscripts have caused problems in the past, so I've used your example and added in two further unit tests with "sameType" and subscripts.  These both pass on my setup as well, but are useful additions for the future.

I can't reproduce the error!  I think this is caused by an incomplete version of Maxima on your system.  

Perhaps you could try to find a minimal example in the STACK-maxima sandbox on your system?
https://stack2.maths.ed.ac.uk/demo2018/question/type/stack/doc/doc.php/CAS/STACK-Maxima_sandbox.md

Also, you could remove all the options in the settings "Load optional Maxima libraries:" qtype_stack | maximalibraries.  If you leave this blank and re-create the image you may find it works (this was one reason for leaving these libraries as optional).

I have to confess, I don't use MacOS, so I hope someone else who does will be able to offer more specific advice here on Maxima on that platform.  If we need to change STACK to accommodate you let me know, and I'm happy to work to fix this.

Chris

**Comment by jIyajbe** [comment]
Appears to be fixed on my machine.
