### ISSUE TITLE
Strange issue with significant figures

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#441]
The attached example is cut down from one of our real tests. And, after uploading this I found that it could be cut down futher. No need to computer Tans. You can just say Tans: 0.138.

If the student enters this as 1.38*10^-1, they get marked wrong.

[questions-C100-13B-3SF-20190212-1709.xml.txt](https://github.com/maths/moodle-qtype_stack/files/2856819/questions-C100-13B-3SF-20190212-1709.xml.txt)

Note, this does not happen in the right answer is 0.123.

This could well be an authoring issue. This question could well be using the wrong answer test. I am hoping you know, Chris, to save me the time of working it out myself.

**Comment by aharjula** [comment]
Well I can already say that the problem is that you are calculating `1.38*1/10` and the other term is not exact (there is no float value for 1/10) and shifts the first one just a bit thus the AlgEquiv will not match. there is a `-2.776e-17` difference there (and `fpprec` is quite big in STACK). You really should use the sigfigs tests for this as those do the comparison with some amount of cutting of the tail. `1.38e-1` would also work and we should maybe look into rewriting the input if it is presented like your example to floats at the PHP level to deal with this thing and cases where we have overly large powers of ten.

Relative and absolute tests also work if you need to use floats it all depends on what you are testing for

**Comment by sangwinc** [comment]
Thanks for replying Matti,
I agree, this is an authoring issue: please use one of the numerical tests!

[questions-Scratch-3SF-20190213-0911.xml.txt](https://github.com/maths/moodle-qtype_stack/files/2859613/questions-Scratch-3SF-20190213-0911.xml.txt)
