### ISSUE TITLE
Feature request: additional input option "simp" 

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#444]
I propose we add in an additional input option "simp" to existing inputs.

When this is set, we will "simplify" students answers. This will be done via
https://github.com/maths/moodle-qtype_stack/blob/master/stack/input/inputbase.class.php#L651

There are cases where we want students to enter expressions like
makelist(k^2,k,1,8)
and for their answer to be the value of this simplified.

Currently, makelist throws an error when simp:false.

This is an edge case, but is useful in some situations. It is additional functionality which does not break anything else.  Any comments?

**Comment by aharjula** [comment]
Well it completes the current set of simplify settings. The current whole question and PRT level ones do somewhat limit ones ability to fine tune things and this is a thing that needs to happen at that specific point the input goes into the CAS. You just need to make sure it happens correctly in the unit tests also.

Bit scary that example of yours, simply inputting makelist(k^2,k,1,**8^8**) would be one place where you really do not want the input to be evaluated and simplified. Have you considered an option of getting that inputted with a `'` in front of it (might need parenthesis too for arbitrary expressions) so that one could do something like this:
```
ans1: 'makelist(k^2,k,1,8^8),simp=false;
validated_ans1: if fourth(ans1) < 100 then ev(ans1,nouns) else invalid;
```

I trust that you will do the simplification as an option in the new "JSON" option way and not as a new field in the model. Also have you though of starting to eliminate those separate fields from the DB-model and migrating them to the option field, `boxsize` being one obvious candidate for that. Should be easy now that we have version numbers in the XML and can identify such model changes during import and we can simply move existing stuff with the DB-migrations in `db/upgrade.php`. Such migration might simplify the code base somewhat, and open up some other things too...

**Comment by aharjula** [comment]
Just to make it clear, while the load, to the Maxima process, that example of mine would cause is an issue I do not mean that people should start to write such guard clauses. Instead I think about working feedback being possible if one could catch them in cases where one creates a situation where such things might happen as the feedback a student gets from the timeout that that would cause is a bit less than ideal compared to what one could do by adding that check, not to mention stopping that before it causes that issue would give feedback faster.

**Comment by sangwinc** [comment]
Yes Matti, I agree we should provide the most helpful and specific feedback possible.  I'll give that some thought.

As to completely re-factoring the options available to each input!  That might have to wait for STACK 5.0 I think....

Chris

**Comment by aharjula** [comment]
Chris,

Once you see what I have in mind for the new AnswerTest option metadata system and how it would map to inputs and their options I hope we can design the refactoring for those inputs. But for now I think that is yet another thing that goes into Stateful for proof of concept demonstration. Lets just say that the vision in my mind is to make the logic easier to read and to provide metadata that can be used both to generate documentation and editor fields, and to validate values. And for all that to work it would be simpler if as many of the options as possible functioned the same way and were also stored in the same way.
