### ISSUE TITLE
STACK Numsigfigs issue

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#445]
From a user:

Suppose we wish to test to 3sf and the correct answer is 0.138.

Entering  1.38*10^-1  is marked as correct. Good!

Entering 138*10^-3 is rejected as it is interpreted as 138/1000 and NumSigFigs requires decimal input. However the input is accepted as a valid numeric input type with exactly 3sf (minsf:3, maxsf:3).

**Comment by sangwinc** [comment]
Students can type in 138e-3 to indicate their answer, and this is accepted.

One option to to interpret 138*10^-3 as "wrong".  We would not accept 138/1000, so why accept this?  In this case we should reject 1.38*10-1 as well, which we currently don't reject.

**Comment by timhunt** [comment]
138.0x10^-3 is a comletely valid way to write that number (https://en.wikipedia.org/wiki/Engineering_notation) 

And, even if you are not an engineer, 1.38x10^-1 is the recommended form of scientific notation.

Wanting to outlaw it because we find it awkward to mark correctly does not seem like a good idea to me.

Also, at the Open University, we have other question types that encourage students to write their numerical answers this way. https://moodle.org/plugins/qtype_varnumeric

**Comment by sangwinc** [comment]
Tim,
Ok, noted.  Some of the physics people might have different views but we will see.  This is about getting the rules right, not convenience of marking.  If there are sensible and strong objections to change, I'll support the request with a new feature to get this working for the OU.  It is sensible.
Chris

**Comment by aharjula** [comment]
Chris,
I too think that all the formats Tim noted are valid. I however also think that `138*10^-3` is also valid and that the NumSigFigs test has no reason to be picky about whether the value is an integer or a float as long as it is either. The strict variant might be picky about this but it is a different matter as `138*10^-3` is not exactly the most strict way of representing that number.

**Comment by aharjula** [comment]
and rational numbers are good also...

**Comment by timhunt** [comment]
I know nothing about this, but does it do any good if NumSigFigs test goes through the Maxima epxression and turns any ints to floats before grading (if you can even do that).

I mean, is 138.0*10^-3 treated the same as 138*10^-3?

**Comment by sangwinc** [comment]
Matti,
When you say rational numbers are good also, do you mean you will accept both 138/1000 and 69/500?

NumSigFigs is intended as a more liberal test, (https://stack2.maths.ed.ac.uk/demo2018/question/type/stack/doc/doc.php/Authoring/Answer_tests_numerical.md)  

However, I don't think we want more than rational numbers over a power of 10.

**Comment by sangwinc** [comment]
138.0_10^-3 is not treated the same as 138_10^-3 because the first is a float, and the second is a rational number.  This is the whole point!  See 
https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/stackmaxima.mac#L1154

**Comment by aharjula** [comment]
Chris,
I see no trouble accepting `69/500` as a value it just is not a value with three significant figures it has only two. And we still do the digit counting with the input string and it counts those from the original `138*10^-3` and gets the correct digit count of 3. Same logic would give two for '69/500' although I would think that the Numeric/Units input field itself should stop you from entering that as a rational number directly. In my opinion not accepting the input `138*10^-3` due to it being logically a rational number is not sensible when it is quite obvious what the student meant, it is so obvious that we should be able to identify it if you wish to forbid `138/1000` as an input form that is another matter entirely. The test itself should not care either way.

You should maybe look into the possibilities the parser gives you, you should be able to use it to identify whether the input is a direct float, integer, or something of the form `a*10^b` and give validation feedback otherwise.

**Comment by aharjula** [comment]
From my point of view `138.0*10^-3` is not the same as `138*10^-3` as they have different number of significant figures... But more seriously, what would be the harm of allowing `numberp` instead of `floatp` values in the test? It would be the simplest fix to the issue...

**Comment by dhilsen** [comment]
From a physics standpoint I believe it's important to accept both `1.38*10^-1` and `138*10^-3` as correct answers. It would not be logical to mark an answer wrong which is indeed numerically correct but uses a non-standard form of scientific notation. (In physics the standard form of scientific notation is to have only a single digit appear to the left of the decimal.)

With our PRT structure we do not experience this issue. We do in fact use the NumSigFigs answer test, however, it is only used to check for the correct number of significant figures so therefore we use the test option [3,0]. (We use other answer tests in the PRT to check for numerical accuracy.) This test option works perfectly fine, it's only when also testing for numerical accuracy the issue surfaces.

**Comment by sangwinc** [comment]
Ok folks thanks.  This is looking more like a bug.  I'll fix it!
