### ISSUE TITLE
mat_unblocker(M) not working since addrow(...) is shadowed

### ISSUE THREAD

**Issue by rio-** [maths/moodle-qtype_stack#447]
As has been pointed out in #333, STACKS `addrow` function overshadows the internal maxima function `addrow`. However, this affects _other functions_ as well: in this case the maxima function `mat_unblocker` that converts block matrices to ordinary matrices internally uses `addrow` and hence fails when STACK is loaded:

`mat_unblocker(diag_matrix(matrix([1,2],[3,4]),matrix([5,6],[7,8])));` produces the error

    Too few arguments supplied to addrow(m,i,j,k); found: [matrix([1,2,0,0],[3,4,0,0]),matrix([0,0,5,6],[0,0,7,8])]

While this is not fixed: any suggestions on how create block diagonal matrices instead of using `diag_matrix` followed by `mat_unblocker`?

**Comment by sangwinc** [comment]
Rio,
This is only an issue for people with STACK versions before the addrow fix.
So, the solution is to upgrade to STACK which I committed on 3rd June 2018.  In any version of STACK after
$plugin->version   = 2018060601;
you will be able to use mat_unblocker. I just tried your example.

The "addrow" function is defined here
https://github.com/maths/moodle-qtype_stack/commit/c8017a23c649be4d8af0d111104c026d3a7a83a4#diff-c8bf47f3f4e78bbaf12ba8bc5fa1f8e6L1183
but I don't recommend patching just that as any questions which use the old "addrow" will break.

Sorry, but the fix is to upgrade!
