### ISSUE TITLE
Make {4,4} \neq {4}

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#470]
We need a test in which {4,4} \neq {4}.

**Comment by aharjula** [comment]
What!? a set containing just 4 would not be equal to a set containing just 4? If you want that you need to test that before it goes into Maxima or you need to disable the `{}` operator connection to `set()` to stop the unique-processing.

**Comment by aharjula** [comment]
Or are you looking into a bag style of an data-structure?

**Comment by sangwinc** [comment]
Yes Matti, people want a bag structure, but didn't use that name....

**Comment by sangwinc** [comment]
I should say, with simp:false, the input {3,1,3} does not get changed, so we already accept sets with duplicate elements.

**Comment by aharjula** [comment]
Multiset then? Well I would really prefer if you used lists as the input form instead of sets and added some magic functions to sort them for comparison tasks and so on, as `{}` being a declaration for `set()` is kinda handy and overloading that to do different things is far from simple. And I do believe sets are used quite a lot more often than bags.

Now if we only has more types for brackets to use... We do support unicode but unfortunately most of us do not have keyboards with abundance of brackets.

simp:false is obviously one way to work but it tends to lead having to be extra careful...

**Comment by aharjula** [comment]
Note that simp:false has its own problems as you will want to deal with bags that have been filled in random order...
```
(%i7) simp:false;

(%o7) false
(%i8) is({1,2,1,1}={1,1,1,2});

(%o8) false
(%i9) is({1,1,1,2}={1,1,1,2});

(%o9) true
```

**Comment by sangwinc** [comment]
Exactly!

**Comment by aharjula** [comment]
Lists that are sorted to a canonical order for comparison are so much simpler, but that will mean that the items in the bag must be comparable to each other so that they can be sorted and in any case you will need to define the rules of equality for them anyway as if you ask the bag for the number items it matters quite a lot how you define equality if that bag contains `2`,`1+1` and `4-2`.

**Comment by sangwinc** [comment]
Well, all those issues already occur with sets!  E.g. the "algebraic equivalence" testing is much stronger than the set testing.  This one is already in the unit tests
ATAlgEquiv({-sqrt(2)/sqrt(3)},{-2/sqrt(6)});
