### ISSUE TITLE
ATDecimalPlaces answer test needs to remove_displaydp

### ISSUE THREAD

**Issue by georgekinnear** [maths/moodle-qtype_stack#481]
I have a teacher answer which I need to insist is given to 2 decimal places, so I use e.g. displaydp(0.1,2) to do this. However the ATDecimalPlaces answer test does not recognise this teacher answer as a decimal.

I think this can be fixed by adding remove_displaydp around the teacher answer here:
https://github.com/maths/moodle-qtype_stack/blob/d4985b984385126d1183e364944f549811f5a76b/stack/answertest/atdecplaces.class.php#L73

**Comment by sangwinc** [comment]
I've done a fix directly here, but actually this should be fixed with the new "internal trees" Matti and I have been working on, in which we strip of the ephemeral forms before passing the arguments to an answer test....

**Comment by aharjula** [comment]
Chris,
No this should not be fixed with the "internal trees". Always remember #150 and the path to compiled PRTs. Here that means that we do not want to push values to CAS and back to be pushed there again just so that we could apply internal trees to something like `ta`, as the "internal trees" only apply in local scope and cannot see that `ta` has been defined elsewhere to include presentational candy wrappers.
In my opinion it is the responsibility of the answertests and of their Maxima side code to unwrap any values of any ephemeral forms if those are blocking the tests execution and in the case of most tests they are blocking such comparisons.
It would make sense to have a CAS side utility function to detect all (numeric not the units one) possible ephemeral forms as a predicate and an utility to remove them. Note that `displaydp` is not the only one even if it is the one things map to if evaluated and simplified enough.

**Comment by sangwinc** [comment]
Thanks for the reminder Matti,
Yes, I think we should probably remove them all....
