### ISSUE TITLE
Error catching in potential response trees

### ISSUE THREAD

**Issue by malthesporring** [maths/moodle-qtype_stack#492]
I have a question that includes giving an angle x s.t. tan(x)=1. My first ptr node checks if x is in the range of tan(x), and if it is not it [stops]. Otherwise, it goes to node 2, which checks the value of tan(x) against 1.

Despite these attempts to "catch the error" of out-of-domain answers, the student gets a CAS error message if they enter pi/2. 

![error](https://user-images.githubusercontent.com/52042426/61281187-2434c980-a7b1-11e9-9581-0e028f7ea900.PNG)

Is this because the CAS evaluates all nodes first, and then traverses the tree? I would have thought it would evaluate Node 1 first, and only evaluate Node 2 if it was sent there by Node 1. 

It does not seem to be a problem to have {@tan(ans1)@} in the node feedback, only in SAns/TAns.

I have attached the question below.
[question.zip](https://github.com/maths/moodle-qtype_stack/files/3396219/question.zip)

**Comment by aharjula** [comment]
Unfortunately, guard clauses within the PRT nodes do not work as the nodes are indeed all evaluated no matter what the correct path is. The way to overcome this is to use proper if statements in the feedback variables to evaluate that bit of logic safely.
This is a know issue (e.g. #150) with a long history and fixing it is in process, there are however many things in the system that need to be rewritten to properly get this done. My estimate is that better performance and security PRTs will appear in STACK 5 or maybe earlier but will no matter what take more than a year as the amount of things to rewrite for them is quite ridiculous. However, there already exists an implementation of compiled PRTs that do provide the expected behaviour that is being currently tested elsewhere, the results seem promising and once that matures we might at some point be able to take advantage of it.
Should you be interested in the complexity of this just look at the only project in STACKs github repository. Nevertheless, should Chris get the iss324 branch merged this summer we would be a major step closer to this and the planned elimination of RegExp tests is also a major step on this track.

**Comment by sangwinc** [comment]
I've tested this question on the current development code, and we can now trap errors in feedback variables.
