### ISSUE TITLE
Multiline Logicals

### ISSUE THREAD

**Issue by samfearn** [maths/moodle-qtype_stack#496]
I get an error if I try to let a 'complex' `if` statement span multiple lines. Schematically I want something like
~~~
if cond then
  (A,
   B,
   C)
elseif cond2 then
  (D,
   E)
else
  (F,
   G);
~~~
but I get errors telling me that a comma can't be the final character in a line, and that I have mismatched brackets. The command with formatting as given works in maxima however, so it's a shame to have to compress it into a horrible one-liner.

This should probably be a separate issue, but I also get an error if the `if` statement is the last expression in the question variables, as STACK thinks the CAS doesn't return anything. Adding an additional last line like `a:1` is requires to let me save the question.

**Comment by aharjula** [comment]
In the old STACK world of <= 4.2 one cannot have multi-line statements, other than strings, this is inconvenient and has annoyed many people over the years, a solution is coming in 4.3 assuming the so called iss324b branch turns out to be 4.3.

The same branch will also remove the need to have every statement assign something to a variable, which is basically what happens in that second part of your issue. It might currently work also by putting the `a:` at the beginning of the if statements i.e. `a:if ....`.

So you are in luck, a fix, well a major rewrite of the whole CAS-logic handling and evaluation engine is coming, possibly even soon and it will make writing multi line statements and function definitions much more user friendly for the authors.

In the new so called parser world one can write pretty much anything one could write into Maxima-batch file excluding:
 - silent statements ending with `$`
 - declare/define statements with certain keywords
 - security violations of the old and new types
 - lisp-code and the operators for inputting it.

In it one should separate statements with `;` signs, as opposet to the previous logic of using line changes as the separators, but it can guess where those would go in very high percentage accuracy, so old materials should work even if one has been lazy with the semi-colons.

**Comment by samfearn** [comment]
That sounds great, thanks for the update. I have one question about the "need to have every statement assign something to a variable" -- in my example, once I turn the if statement into a one-liner, STACK is happy with it, as long as it isn't the final statement in the question variables CAS block, so isn't that a working line that doesn't assign something to a variable?

**Comment by aharjula** [comment]
Well, there was/is (<=4.2) a logic that added an assignment to the statement if you did not, but what I think is happening is that when it fails spectacularly in handling of that multi-line statement it constructs something that is broken in a way that leads to error messages related to other things and detection of missing assignment may be the catch all error coming up from the depths of the history of this code-base. In any case not much point in trying to figure that out as the new system does this very differently indeed.

So as to why the final statement would be different I have no idea but the new system seems to have no trouble with having the first, the last, or the only statement being complex and multi-line so that too should be fixed with it.
