### ISSUE TITLE
STACK breaks if Moodle option 'forceclean' is turned on (e.g. View as Student)

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#504]
STACK breaks if Moodle option 'forceclean' is turned on (it's on the /admin/settings.php?section=experimentalsettings page).

This is basically because in the renderer, we call format_text too late. https://github.com/maths/moodle-qtype_stack/blob/50adb2c2b81422c77bc541049065299c5650395a/renderer.php#L80. We need to do that before replacing the PRTs and Inputs.

At some point Moodle is going to turn that option on by default (https://tracker.moodle.org/browse/MDL-62352), so we will have to fix this.

Also, if you use Moodle's Log in as feature, then that option gets forced on (https://github.com/moodle/moodle/blob/a672f021eaf0640c6f3b0094839c8c4fd3b2df7a/lib/moodlelib.php#L2798). So, if you Log in as another user, STACK is broken now. So, if anyone spots that, this is why.

**Comment by aharjula** [comment]
Ok. You are probably aware that this would be simpler if we had access to the same question object instance at the rendering phase as the quiz/whatever uses when processing input. Then we could format the feedback when it gets first created at that phase, hold onto it and use it when rendering, naturally we then need to hope that that is early enough.
When we go for compiled PRTs and if we include CASText2 based compiled castext into them we get the feedback out of those at the same call to Maxima and if we can just keep a hold onto that feedback between processing and rendering all is probably solved. Of course one problem will be calling format_text for content that might not be displayed depending on the behaviour and other render settings (well we can add some markers and cut out the bits that are not to be displayed and just process everything ass early as possible), wasted cycles and it could also load stuff to the $PAGE even if we do not actually display it it.

**Comment by sangwinc** [comment]
I confess I'm not sure what I'm doing here.  The unit tests are running in the background....

I've tested this with the "input samples" which all seem to work.  So, I'm not sure why the old code suggested the format text needed to be done after the substitution of the inputs etc.  Sorry, can either of you explain why this is the case?

**Comment by timhunt** [comment]
I wasn't necessarily expecting an immediate fix. I was logging this to deal with later.

The danger with the proposed fix is that during format_text, another Moodle filter might see [[input:ans1]] and do somthing to it before we have processed it. Our unit tests won't necessarily catch that, because they run with a minimal number of text filters enabled.

The safer way to handle this would be to replace [[input:ans1]] with something else long and unique that we can be fairly sure won't clash with what other filters do, then format_text, then replace our alternate content with the input/prt stuff.

Perhpas that is too hacky. At the very least, we should extract the list of [[..]] placeholders before calling format text, then extrac them again afterwards, and throw an error if the list has changed (because that woudl be evidence that format_text has done soemthing we cannot handle.) Acuatlly, that woudl be my preferred solution for now. Then, if we detect a real problem with some filter (rather than a theoretical worry from my paranoid imagination) then we can put a work-around in place if really necessary.

I disagree with Matti's comment. It always has to be possible to review a question later just from teh data recorded in the database (think quiz review page). Hoping for ephemeral data to last from grading to redisplay misunderstands how Moodle questions work.

**Comment by aharjula** [comment]
Tim I think you misunderstood me, I am not talking about ephemeral data lasting between attempts or what not I am talking about it lasting between phases of the same page rendering, when a quiz is rendered for example we first instantiate a question object to do the input processing after which we instantiate another to do the rendering which will have to start everything from scratch to generate the feedback and all that, if we were to use the same object-instance then it could at the very least keep the content it evaluated just few milliseconds ago and then use it. By "we" I mean your question-engine...

Naturally, I understand that this might be a problem if the rendering logic is in the input processing as then the return to the page would be an issue, where the stuff gets rendered from the "state", but then it would basically need to be in the renderer and if that is too late what can we do? Somehow I think the rendering would have to be in the apply_attempt_state as that probably is the earliest place we could do it.

As to extracting `[[...]]` before format_text calls (and that fix), that won't work as those do contain stuff that needs to be filtered, like MathJax and some more complex stuff. So we need to format their content too at some point. And if we are holding them back because we cannot format_text any later, then when can we format them? Might as well just plug those in at the earliest point available if we only have the response arrays we can do it for inputs and if we had the response arrays we can also generate the feedback and validation.

**Comment by aharjula** [comment]
If I understand this issue correctly what forceclean does is to simply add something new to the filter chain and we should therefore ensure that we do not give anything to that chain before we have finalised the content. So shouldn't we therefore ensure that we call format_text at the very last moment possible instead of earlier? And that we do not call it for fragments but only for the whole thing? So compose all before filtering anything, is that the idea?

**Comment by sangwinc** [comment]
No new unit test failures.

I also would expect to "filter at the last possible moment"! 

I'd prefer to fix this sooner.  I forget these things otherwise....

**Comment by timhunt** [comment]
Moodle format_text is for processing user input - like the bits of the question text that surround the placeholders. It is not for processing system-generated HTML. format_text is an important part of sanitising user input to avoid cross-site scripting etc. That is why it can mangle complext HTML like form controls that we want to output. We need to apply format_text to questiontext at the point when it is user input.

Yes, we need to do thinks like render maths in output we generate, that is why we have the stack_maths class, and stack_string function, etc. We are not relying on format_string for this.

The only thing that goes in place of a placeholder that should go through format_text is the PRT feedback, and we already do that in ->prt_feedback_display(). format_text is absolutely not idempotent, so the fact we are calling format_text twice on the same user input is a bug, which would again be fixed by calling format_text sooner.

Would be really good to add some unit tests to nail down the correct behaviour (e.g. a test that would fail if format_text is called twice on the same HTML). I am in the middle of other work right now, but I might be able to have a go at this next week.

**Comment by aharjula** [comment]
So essentially we should apply it to certain bits of validation that show the raw input and probably only those bits of PRT-feedback that contains input-variables in their definition chain? Sounds like it could cause some issues with some of our questions that e.g. draw JSXGraph plots in the PRT feedback, or use feedback to deliver script commands to update the question presentation, well at least those that still use `<jsxgraph>` instead of `[[jsxgraph]]`. Much of the PRT feedback is system generated and thus we might need finer control on applying this.

Thinking difficultly, we could "simply" calculate the definition graph using the parser and some simple heuristics and ensure that the castext processing applies the formatter to injections that have questionable content in their heritage. Beyond that some answer test feedback would need to also deal with this.

**Comment by HuongNV13** [comment]
Hi all,

Base on Tim's suggestion,

I already made some changes to fix this issue.

Could you please take a look?

Thanks,
