### ISSUE TITLE
Validation feedback to make some elements vectors (in bold)

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#505]
From a user:  In the next generation of my quiz questions I would like to ask my students to type in vector equations (e.g equation of force equilibrium). These equations can contain scalars and vectors, too. I would be happy if the students could see the vectors as bold characters in the validation field similar to official publications. For example: \(\mathbf{F}=m\cdot\mathbf{a}\)

**Comment by aharjula** [comment]
One of the things that 4.3 changes is that the question-variables get evaluated for every validation context, as well as feedback. This means that should one declare overriding `texput` rules there they would apply everywhere in the question, including the validation.`How one declares those rules is naturally a different thing... 

Personally, I am thinking of investigating (in Stateful) annotations through comments to tag things as various types, as then I would also get that type information easily from the parser for other uses.

```
/* @vector b,x; @matrix A; */
x:inv(A)*b;
```
One could then have a setting somewhere through which one could define the display style of vectors and matrices etc. according to ones wishes (well selecting from the styles we have implemented), instead of declaring it at the code level and having to change everything in the code.

**Comment by sangwinc** [comment]
Matti,
In 4.3, the question variables do not get evaluated in the validation context as you suggest above.  If I put `texput(v,"\\mathbf{v}");` into the question variables, then \(v\) is indeed bold everywhere except in the student validation.  Did I miss something?

**Comment by aharjula** [comment]
Hmm,
I am sure I loaded the question-variables to the session that does the validation at some point of 4.3 development but I see nothing like that in the `get_input_state()` that the STACK version of validation uses. Could be that I have simply mixed my various code-bases in my mind when making that comment. The comment does apply for other evaluation scopes though.

The problem seems to be that in the STACK input-system the inputs do not know about the question and can evaluate things on their own cassessions, in input2 the inputs always ask the question to evaluate whatever they need and the question ensures that question-variables (or equivalent) is in the session. If you want to do this in the old system you will need to give the inputs the question-variables and seed to work with.

**Comment by sangwinc** [comment]
If we do the above, then then define
```
texput(v,"\\mathbf{v}");
v:2;
```
then the student types in "Your last answer is 2".

I know we forbid multi-letter variable names in student's answers, but I'm worried about this!

**Comment by sangwinc** [comment]
Matti, most users won't know what "input2" refers to here.  The "old system" is the current system!

**Comment by sangwinc** [comment]
Perhaps it would be better to tag functions within the security map as "relevant for student validation" and extract only those for the input validation session?  That would also prevent re-evaluation of all the question variables which might be substantial computation.

**Comment by aharjula** [comment]
> If we do the above, then define
> 
> ```
> texput(v,"\\mathbf{v}");
> v:2;
> ```
> 
> then the student types in v and gets "Your last answer is 2".

I wonder why one would do that if one expects variables in the answer one does not typically bind them in advance, or ever for that matter. My understanding is that the question-variables exist to set up the world for asking the question and we might do something like assigning values to variables in the feedback variables if we so choose. Although it is typically a bad idea to bind any variables ever, one tends to just evaluate the expressions in scopes where the variables are locally bound or do some substitutions.

Indeed "the old" is "the current" I just have startted to leave the old behind.

**Comment by aharjula** [comment]
Hmm,
Just picking relevant statements is one way, but I do doubt whether that would be a significant boost in performance. Note how much work Stateful [does when doing AJAX-validation](https://github.com/maths/moodle-qtype_stateful/blob/master/classes/external.php) for an input2 system, it actually evaluates the question-variables fully, initialises all the inputs and generates validation-messages for all the active validation boxes, in total it does up to three CASSession evaluations yet it is still responsive enough (well I feel like it is).
