### ISSUE TITLE
Graph theory in STACK question

### ISSUE THREAD

**Issue by impemic** [maths/moodle-qtype_stack#514]
I am teaching graph theory in an academic course.
Is it possible to use the "graphs" package of Maxima in a stack question?
Thanks

**Comment by sangwinc** [comment]
Thanks for contacting me.  I have reviewed the graphs package very recently for a colleague here in Edinburgh.  There are some fundamental difficulties with (1) the internal representation used by graphs which is non-standard and makes input-output with PHP impossible, and (2) calls to draw for representation.  These two issues make it impossible for us to support graphs in the short to medium term.  

Very sorry indeed as this looks like a very useful set of functions.
Chris

**Comment by fdamore95** [comment]
Hello, is there progress regarding this?

**Comment by aharjula** [comment]
The short answer is no.

The long answer is that the problem is, as Chris said, with the representation and what it breaks is the ability for STACK to provide debugging of any variable inside the question simply by printing it out. Also, in the end, printing/plotting/drawing out the graphs using that package's tools would require additional tooling to transfer the images generated, were it outputted as a matrix and plotted from it using some other tooling would not be a problem.

As a side note, the STACK infrastructure no longer relies on transferring data between execution sessions using such representations, so it is possible to manufacture a question that would do operations with graphs as long as at no point is a graph stored in a variable (which would it make it appear in debugging, disabling debugging features is not recommended) or "printed" out, however, to do that one would need to modify one's Maxima library loading and the STACK security-map to allow use such library functions.

So basically, those graphs in their special representation (or lack of serialised representation through the `string`-function in Maxima) are causing issues in tooling for authors. Authoring without the ability to debug is something we do not want to go back to, and these break that. And as long as these break that, the issue of transferring any special graph plotting results generated by this library's functions is pretty much irrelevant.

So as long as [this bit of documentation](https://docs.stack-assessment.org/en/Developer/Maxima_packages/#maxima-graph-theory-package) applies no real progress will happen. However, those dabbling with graphs will probably write their own libraries that work with lists and such directly using `string`-serialisable datatypes and now that STACK has [inclusion](https://docs.stack-assessment.org/en/Authoring/Inclusions/) mechanisms sharing and use of such tooling could be simpler.

**Comment by fdamore95** [comment]
Thanks a lot for your answer. 
Indeed I was wondering whether one could only store graphs in variables (without drawing any graph) but it appears it is not good. 
The only "good" use I could have made of that library consists in functions such as "get a maximal independent set".

It means I have to design my owns then. 
Thanks again.

**Comment by aharjula** [comment]
Naturally, someone might at some point contribute a wrapper for that library that would provide us with `string`-serialisable values, and that wrapper could then become the route through which the library gets used inside STACK, though that would still leave the plotting issue open. If anyone is willing to do all that work and understands how is another matter, this would require some serious LISP-level coding.
