### ISSUE TITLE
require_login() using

### ISSUE THREAD

**Issue by OlenaTatarintseva** [maths/moodle-qtype_stack#516]
Hello,

First of all I want to say thank you for your work with this plugin.

I noticed one place where require_login(); is used in if statement in if part and not in else part. 
I mean question/type/stack/caschat.php  file.
Of course, question_require_capability_on is used in else part, but I think it would be better to move require_login() call upper before if statement.

And one more small thing. Reg. question/type/stack/stack/cas/castext/autogen/castextparser.class.php. It require MOODLE_INTERNAL checking to be add.

Best regards,
Olena Tatarintseva

**Comment by sangwinc** [comment]
Olena,
Thanks very much for raising this.  I've made the changes to question/type/stack/caschat.php you suggest.

The file
question/type/stack/stack/cas/castext/autogen/castextparser.class.php
is auto-generated.  So, I'll ask Matti to review this suggestion and if needed we should add that to the file which creates it!

**Comment by aharjula** [comment]
Chris,
I see no reason why MOODLE_INTERNAL would be required in castextparser. That script has no active code on its own, it just contains some class definitions, and opening it directly thus does absolutely nothing (well wastes some PHP-parsing time). If you were to add that MOODLE_INTERNAL check in to it it would only exist to pass some Moodle style checker and waste a few cycles, it would also mean that everyone using that script in other contexts (ILIAS and similar users) needs to declare MOODLE_INTERNAL. ILIAS people probably already do that so it's up to you to decide what you want.

Guess who considers stamping scripts with that check pointless if those scripts contains nothing that it protects against. I do accept that it has its role with active scripts that do something to the persistent state or are truly expensive to evaluate, but this does neither. I would really like to see someone stripping all those checks out of Moodle and instead stopping those scripts being accessed at the servers request handling level, it would probably be a measurable speed-up although very small... One could maybe declare scripts that should not be directly accessed by placing some token in the file-name and entry-point scripts similarly thus simplifying the access control quite a lot. In any case I understand why Moodle does it, there are actual reasons for it that I accept, I just consider the solution less than ideal and inefficient.

**Comment by timhunt** [comment]
Someone did invent a way to "declare scripts that should not be directly accessed". It is inserting this line. The magic of this line is it works on its own. It does not need any other code anywhere else.

**Comment by aharjula** [comment]
Ahh... I felt like winding Tim up a bit. In my opinion the "other code elsewhere" would make more sense, as to me it makes no sense to start the PHP interpreter at all to load up a file that then contains a line saying it should not be executed. The fact that the current solution of this magical constant value is simple and requires no other code and most importantly does not require the admin to configure the execution environment at all does not mean that it is the best solution. To me it is just a sign of giving up on your users and assuming that they are unable to follow additional rules about securing things on their specific HTTP-servers. I as an end user able to follow most of such rules feel like I am being penalised by such a simple solution wasting processing power and IO-ops by loading stuff up, just because you don't trust users to be able to secure things.

But then again who am I to say so given the line on user abilities I have taken on the MaximaPool side.

One day I might just grep the files for that check and tell the server not to serve them directly at all, after that I could purge the whole code with a simple search and replace and be happy. But I would rather just identify files that should be blocked by tokens in their names thus making the rules somewhat shorter.

Just for context for those wondering, Tim is a developer with ties to Moodle and I am a person that considers Moodle as a necessary evil and takes a critical stance on pretty much everything in it. Typically, I think that Moodle takes the wrong compromises like here, that it is missing something obvious, that it does something in a convoluted way, or that it carries way too much baggage. So feel free to rate my comments accordingly.

**Comment by sangwinc** [comment]
Well, good to have some banter on a Monday morning!

What is the solution?  Should I add the require MOODLE_INTERNAL?

Chris

**Comment by aharjula** [comment]
Assuming that I fully grok what the MOODLE_INTERNAL is supposed to protect against I say we do not need it. My feeling is that it is bad practice to rubber stamp files with it unless it is really required. But then we already have it in various files where we have the same situation i.e. nothing active present. 

I say flip a coin... it has no significant effect in any direction other than the size of the file and cycles used.

**Comment by timhunt** [comment]
I think that roughly speaking files should fall into one of 3 cases:

1. Files that are the main entry point scripts for the web. These should all include config.php and then call require_login.
2. Files that are CLI scripts. Should include config.php and define('CLI_SCRIPT', true);
3. Library code that is used by other scripts, these should all have the MOODLE_INTERNAL check.

I know almost all files of type 3 will not do anything if executed directly in Apache, because they just define functions and classes, but the point of the MOODLE_INTERNAL is ot prevent accidents, so you should always have it.

Clearly, if you want ot use any Moodle library code in another application, you will have to define MOODLE_INTERNAL  before including the Moodle code.
If you run CodeChecker, it has a rule that tests this, so that can be used to find missing MOODLE_INTERNAL checks.
