### ISSUE TITLE
Performance issues with large quizzes

### ISSUE THREAD

**Issue by hgeorgsch** [maths/moodle-qtype_stack#517]
I hit on severe performance limit when I use quizzes with many STACK questions in many deployed variants.  This has been discussed in some length in the Moodle forum: https://moodle.org/mod/forum/discuss.php?d=393058
I repeat it here  in the hope to put it on the STACK roadmap.

The use case arises in combination with CAPQuiz, where a large number of questions and variants would be expected, but I can reproduce the problem in the standard Quiz, so it is not a bug in CAPQuiz.

I run a (CAP)Quiz with 40-50 STACK questions (+ non-STACK questions) almost all of them in 100-120 variants each. Symptoms:
1.  Student pages are slow to load, both feedback and next question, when a single student is active.
2.  At busy times the students often get error messages and blank screens.
3.  The database log shows tens of thousands of queries on the qtype_stack_cas_cache table. (almost 100,000 queries across about two question cycles with grading and next question).
4.  The profiler shows that almost all the wall time is spent in question_engine::load_questions_usage_by_activity() and its children.
5.  This also happens when neither the previous nor the next question are STACK questions.

Retesting with about half of these STACK question in a Vanilla Quiz, and no previous question_attempt records in the DB, I get a similar bad performance.

I am going to continue work on this, but I am working primarily towards a workaround. I doubt I have the resources to find a lasting high-quality solution, but contribute what I can.

**Comment by aharjula** [comment]
Thank you, for the use case example and CAPQuiz as an example where things break.

You should know that things are getting better in the future (maybe in a year or so) as STACK starts to rearrange certain bits of its internals. The primary problem however is (I believe so) that Moodle Quizzes (I don't know about CAPQuiz, but maybe it has some relation to the orginal Quiz activity) tend to initialise the same question many times (once for grading and once for rendering) and expensive question types like STACK do quite heavy things even at the basic initialisation level, although maybe there could be some more lazy loading in the instantiation to deal with stuff being instantiated but not actually fully used.

Basically, be warned that the bits where STACK could be optimised are currently largely under work and will probably get rewritten and thus optimising the current stuff might be a wasted effort. However, if you can optimise the number of times the same question gets instantiated with the same seed at the quiz level that would surely lead to large benefits no matter what happens inside STACK.

That 100k queries number sounds really bad and I cannot promise anything but I do have plans to cut that down by almost one order of magnitude (in actual use cases, here I think something is being called too much by something probably at the quiz level). But those plans are slow to progress. For now I just have to say that 100k queries seem like you are instantiating over 5k questions which is obviously a lot more than your description lists, surely you only instantiate questions that you use?

In any case as Tim already said `qtype_stack_cas_cache` is way faster than generating the results stored there from scratch (from scratch it would typically take multiple milliseconds, so a sub ms DB-query will always be better). But given that it is the place where we store the evaluated question variables for a given seed, text rendering variables and grading related variables it really seems odd to go and fetch that much from there unless there is some repetition in the code.

**Comment by hgeorgsch** [comment]
Lazy loading from CAPQuiz was the first fix I attempted when my quiz assignment went tits up last week.

The problem, as the profiler shows, is isolated to question_engine::load_questions_usage_by_activity(), which clearly loads a lot of data which is not required or not even remotely relevant to the current question.  I have made sure that this function is not called more than once per page, and the profiler reports one call only. The API is stateless, is it not?  So that I need to load it for every new server page?  And I cannot load only what I need without bypassing or changing the core API.

Tim did suggest a workaround in the moodle core, and I am going to try to implement that, in spite of some reluctance against fiddling with the core.

**Comment by aharjula** [comment]
> The API is stateless, is it not?

Who knows with Moodle. In any case the problem seems to be that Moodles logic was originally built with the assumption of very light questions like MCQ and essay style things that are trivial in the evaluation sense and therefore it often simply fully instantiates them and no one tends to suffer from the wasted CPU cycles as long as the questions are light. STACK is everything but light. While we aim to make it lighter it will never belong to the same weight class and therefore anyone needing large numbers of STACK questions needs to get Moodle to acknowledge the possibility of questions that should not be initialised before actual need.

So if and as it more than likely is a problem in `question_engine::load_questions_usage_by_activity()` we from the STACK side have very little options for dealing with it. If we had the option of saying "please lazy init us" we would do so but as that is not a feature we cannot do so. We will eventtualy improve our performance quite a lot but for us the initialisation will always be heavy.

**Comment by timhunt** [comment]
Moodle was not built on the assumption of light questions. Exciting question types like STACK are exactly the sort of thing Moodle wants to support.

Moodle was built on the advice of Knuth "Premature optimisation is the root of all evil." Or, as other people put it, "Make it work right, then make it work fast." Now that this issue has been found, we can do somthing about it.

As well as making STACK much more efficient (there is no good reason why calling apply_attempt_state once on one question make 100s of CAS calls - I still want to do my own profiling of this because I don't believe it) this discussion has helped me think of a possible performance win in the core question system. That is recorded as https://tracker.moodle.org/browse/MDL-67183.

**Comment by aharjula** [comment]
Well yes I cannot assume anything about Moodles assumptions, sorry about that. My assumption is that originally Moodle had light question types and as the logic seems to fit them then it probably was built for them. But lets forget that.

Sane STACK questions should not generate 100s of CAS calls, having done some thoughts about this there is basically three things that could generate more than normal number of calls for a STACK question:

 1. In initialisation if you have large numbers of inputs and those input contain MCQ inputs then you will have more calls.
 2. In answer processing if one has large numbers of PRTs then the evaluation of those will generate 2-3 calls for each of them the third call is for the rendering of the feedback. Before the PRTs get to work there is also a call doing the input validation and the question must have been instantiated to do anything.
 3. The use of CASText loops will generate one extra call for each level of loops present in the deepest nesting of loops. This applies to both initialisation and feedback generation.

All of those are already fixed in the design ideas of, the new input system which collects initialisation statements together, the compiled PRTs with inline feedback and the new CASText2 which is a single pass evaluatable thing. Once those get done STACK question instantiation takes just one CAS call the validation of input takes one more and the evaluation takes another.

Assuming that the STACK questions don't have insane numbers of PRTs, MCQ inputs, or iterate over very high dimensional hyper-cubes in their CASText and that no one is processing full input histories of inputs and instantiating insane amounts of variants then the issue must be higher.

**Comment by hgeorgsch** [comment]
The questions I used in the most minimal example was 15 (sorry not 20) quadratic equations, where the students would select the number of real solutions (radio button) and give two floating point roots (possibly "none").  All randomised with large sample spaces.   Apologies for insulting the powers of STACK with such trivial questions.  

If anybody wants a backup file to reproduce the test, I can send it.
https://www.ntnu.edu/employees/hasc
