### ISSUE TITLE
Expression sequences and "tuples"

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#519]
From a user: we have lists, [1,2,3] and sets, {1,2,3} but we also need expression sequences such as 1,2,3 and "tuples" (1,2,3).  These need to be "types" of object, which can be used anywhere, and also are displayed correctly with round brackets (tuples) or no brackets at all.

Providing inert functions to do this is easy.  Functionality to do things with these inert place-holder functions can be developed in due course.

**Comment by sangwinc** [comment]
George, 
Please would you review these proposed changed and confirm you agree this is what you asked me for?

**Comment by georgekinnear** [comment]
This looks great, thanks Chris.

I would just suggest a change of terminology - perhaps we could just use `sequence` rather than `expressionsequence`? Then we could have `sequenceify` rather than `innards`, which is in line with `list`/`listify`.

From what I can see, `sequence` is not going to conflict with anything in Maxima. There's perhaps a risk of it clashing with variables that teachers might have defined, though. In which case, another option would be `exprseq` and `exprseqify`.

**Comment by sangwinc** [comment]
George, I did that here: 468b74298b9a7b1dc3270af38ec3cc6ac6c085bf
Can you double check and confirm?

**Comment by georgekinnear** [comment]
Looks good, thanks!
