### ISSUE TITLE
Complex number validation

### ISSUE THREAD

**Issue by aacchhee** [maths/moodle-qtype_stack#540]
<img width="2681" alt="STACK_issue2" src="https://user-images.githubusercontent.com/59649991/72259964-fe7a6700-3611-11ea-8da1-f2278d19b290.png">

I have a question where some complex numbers have to be multiplied. We see that 2-2*i^2 (and its EqualComAss) is a common answer that we do not want to allow.

However, we never get into Node 2 True branch -- it goes straight to Node 3.

The test works as expected when we replace 2-2*i^2 with 2-2*i or 2-2*x. I assume that i^2 gets represented as -1 somewhere in the internals, as though the manual says that EqualComAss test  does not simplify.

**Comment by sangwinc** [comment]
Yes, EqualComAss does not "simplify" but it does the evaluation i to -1.  We do need to evaluate, otherwise we could not create a teacher's answer from the values of variables.  This is a rather subtle one, but I rather agree with you.  We need the test you asked for, and another colleague has asked for better ways to test complex numbers.  So, I'll add this to the list of things we need to address, even if it isn't really a "bug" with the current test.  It does rather look like one though....Sorry!

**Comment by sangwinc** [comment]
I've been looking at this today with the latest code (v4.3 release candidate in master), and I can't reproduce the issue.  Please could you email me the question and I'll look into it?
