### ISSUE TITLE
3D graphics in  STACK

### ISSUE THREAD

**Issue by aacchhee** [maths/moodle-qtype_stack#546]
This is a feature request. I am teaching multivariate analysis and would really enjoy having some proper 3D plotting in STACK.

Would you consider three.js (https://threejs.org/) as a viable solution for 3D plots?

Here is a website that uses it in a very nice way: https://mathinsight.org/differentiability_multivariable_subtleties

**Comment by aharjula** [comment]
Can't comment further now but [Plotly](https://plot.ly/javascript/) has been used and it has been fine. Just remember that not everyone has WebGL supporting browsers or operating systems and some form of fall-back is good to have.

Eventually,  STACK will probably provide an integration for using some 3D-plotting library, but for now all we provide is 2D-plotting with [JSXGraph](https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Authoring/JSXGraph.md), one can use the same block to provide other JavaScript code references to a div with and unique id ('divid' in the examples) and to inputs if need be.

**Comment by sangwinc** [comment]
Thank you very much for this suggestion.  We do need some kind of 3D graphics, and this looks good.

For now, we are supporting JSXGraph, and adding more javascript libraries is a risk.
You can embed things into "Description" question types, next to a STACK question.  So, you can probably get this kind of functionality without us changing STACK (for now).
We need volunteers for the project, and a comprehensive evaluation of the 3D options, together with some discussion from other STACK users would help guide future priorities.  Help with this would be appreciated.

Since this is a feature request, and not an issue with STACK, I'll add this to the future plans list and close this issue.
