### ISSUE TITLE
Run all tests on all deployed variants gives incorrect information

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#552]
It happens for me that Run all tests... claims that all question instances passe all tests when they don't, and vice versa; see the two screenshots.

![Question_tests_inconsistent](https://user-images.githubusercontent.com/1645276/73597632-934bf280-4536-11ea-8b04-164d0f93a96e.png)

![Question_tests_inconsistent2](https://user-images.githubusercontent.com/1645276/73597635-97781000-4536-11ea-95b5-71074a363c7d.png)

**EDIT:** I did a git pull on master today before reporting this bug. Indeed, the fix to #531 seems to have solved my problem. Thank you once more!

**Comment by alcarola** [comment]
One of my worries with this is that I don't know if the question bulk tests return the correct or incorrect information on whether all tests were passed.

**Comment by sangwinc** [comment]
State is evil.

**Comment by sangwinc** [comment]
I'm sorry about this.  The new "cassession2" stores the evaluated variables in objects which are passed by reference.  So, to ensure we really have a clean question for the tests, bulk test and command line bulk test I've moved the creation of the question to be tested inside the testing function here: https://github.com/maths/moodle-qtype_stack/commit/386a651df31eace354b1d37920807efa10045b23#diff-1f63f418790d6b2410777c26bed1d36cR70

This will slow down the testing a bit, because we create questions for a variety of other reasons, e.g. showing the question note, printing out variable values and so on.  This effort is now duplicated.  But, I can't see a way to be really sure we have a clean question on each test case.

Matti, any comments?

**Comment by sangwinc** [comment]
Thank you very much for posting your problematic question.  This has been very useful indeed in helping to track down the state problems.

We also rely on the bulk testing, and integrity of this is going to be essential for confident upgrade.
