### ISSUE TITLE
correct answer display for checkbox?

### ISSUE THREAD

**Issue by nfa019** [maths/moodle-qtype_stack#556]
The documentation says

> When STACK displays the "teacher's answer", e.g. after a quiz is due, this will be constructed from the display fields corresponding to those elements for which correct is true.

what it does: it displays the value fields
![checkbox](https://user-images.githubusercontent.com/1466212/74145386-fd335e80-4bfe-11ea-8e68-936cafe14d1d.png)

**Comment by aharjula** [comment]
Unfortunately, the current input-system has flaws and so does the documentation. The documentation above that statement is closer to true. The primary problem as I understand it is that the thing you see displayed there comes from the same source as the "fill in correct answers" buttons data which primarily focuses on what input-fields to set to which values and does not deal with the labels of those fields. Hopefully, we can in the future separate those use cases so that the displayed bit would make more sense.

Chris, Tim: do you see where this goes wrong? Does that happen at behaviour or Moodle level, how does Moodle MCQ handle this?

**Comment by sangwinc** [comment]
Leave this with me.  I've already sorted out what is happening, and I just have to decide on a route to fix it.  The input system has grown over time, and we try to accommodate a lot of options now.  This feature looks like it slipped off the radar and got lot.  Sorry.

**Comment by sangwinc** [comment]
Thank you again for reporting this bug.
