### ISSUE TITLE
I'm new, please help me to understand where to look for answers.

### ISSUE THREAD

**Issue by Robert-Hartley** [maths/moodle-qtype_stack#557]
Hello,

My apologies if this is an inappropriate place to post this question but that is part of my issue; I'm not sure where to get the assistance I need with this Stack stuff.

I am student in my final semester of a Bachelor of Science in Applied Mathematics and I'm currently working with Stack as part of a research scholarship in Mathematics Education. I have gotten fairly familiar with most of the features but I think I am still confined to the demonstration version. How do I get access to the full version? 

When I am prompted to log in to Stack, it says 'Stack demonstration site' and when using Stack, I have 'demov4.3' in the top left. I often feel like the things I'm trying to do, (like add a graph to a question, for example), are not possible to me and I wonder if it's because I am on the demo version.

I have tried asking my supervisor for this project but he is much less familiar with Stack than I am at this stage and has admitted he can't help.

Any assistance would be appreciated, 

Thanks,

Robert.

**Comment by aharjula** [comment]
Well...
Firstly, there is no "full version" available for random users. STACK is an open source project that, assuming I have understood the principal developer correctly, will never have a singular commercial provider. Basically, one gains a "full version" by installing STACK by themselves on their own Moodle. In practice however, most commercial entities hosting Moodle as a service have been able to install STACK into their service.
Secondly, the typical situation for people authoring materials is that they have an institutional or some federated STACK-installation where they do the work. They do not do it at the demonstration site as I would imagine that that site does not guarantee that any materials are present the next morning. Alternatively, people setup their own Moodle installations and do their work there, this option naturally requires some skill, however there are packaged Moodles (XAMPP or WAMP based) for just such task, you just need to add [STACK](https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Installation/index.md) into them.
Thirdly, it might be that the development of the version 4.3 is affecting the demonstration site so that there are additional issues there. I would imagine that the demonstration site is currently being used as a proving ground for certain new features and might be a bit messy. So what you are experiencing might be because you are on the demo-site and the demo-site is not running a release version of STACK.

Finally, if you can edit STACK-questions you have pretty much all the capabilities of a normal STACK-using teacher. The next step upwards, in capabilities, from that is just the ability to configure certain system level features and defaults, and running of some bulk actions on the questions.

**Comment by timhunt** [comment]
To answer your question about support, the best place to ask for help is the Mathematics tools forum on Moodle.org https://moodle.org/mod/forum/view.php?id=752

This issue tracker is really for reporting and fixing bugs in the STACK software, so I am going to close this issue now.

**Comment by sangwinc** [comment]
Robert,
Welcome to STACK!  Thanks for contacting us, we will help.  As Tim suggested, you are better posting a question on the Moodle mathematics tools forum.

As Matti also said, the demo site is to demonstrate questions, and we don't allow random people to author questions on that site. It would become a mess!  If you would like access to a private area for question authoring please email me at C.J.Sangwin@ed.ac.uk and we can talk about options in private.  We all need some help getting started, and I'm happy to help you.

It would, of course, be much better if you have your own site to work on.

Chris Sangwin
