### ISSUE TITLE
The model answer isn't evaluating the integral in some cases.

### ISSUE THREAD

**Issue by Robert-Hartley** [maths/moodle-qtype_stack#558]
I am currently working with the link between definite integrals and areas and have created a question with three parts. Each gives a 'nice' function (linear, quadratic, trigonometric) with a positive and negative area within the bounds given, and if the student simply find the definite integral, they will get the wrong answer but the system will be able to recognise that and reply appropriately. 

However, for the linear function, the code evaluates my integral of the absolute value of the function over the bounds, but for the quadratic and trigonometric, the model answer returns simply the integral itself, without evaluating it. 

I can't see how the code is different at all nor why it should be doing this for me so any fresh eyes would be greatly appreciated.

The question variables:

b1: rand(9)+2
m1: rand(19)-9
r1: rand(b1-1)+1
c1: -r1*m1
function1: m1*x+c1
answer1: int(abs(function1), x, 0, b1)

b2: rand(9)+2
neg: rand([-1,1])
r2: rand(b2-2)+1
c2: rand(b2)
function2: ratexpand(neg*(x-r2)*(x+c2))
answer2: int(abs(function2), x, 0, b2)

k: rand(10)
a3: -(pi/2+k*pi/2)
b3: pi/2+k*pi/2
c3: rand(19)-9
wave: rand([sin(x), cos(x)])
function3: c3*wave
answer3: int(abs(function3), x, a3, b3)

wrong1: int(function1, x, 0, b1)
wrong2: int(function2, x, 0, b2)
wrong3: int(function3, x, a3, b3)

The Question:

Given the function, \(f(x) = {@function1@}\) 
What is the area between the x-axis and the curve of that function over the interval [0,{@b1@}]?
[[input:ans1]] [[validation:ans1]]
{@answer1@}
{@wrong1@}

Given the function, \(f(x) = {@function2@}\) 
What is the area between the x-axis and the curve of that function over the interval [0,{@b2@}]?
[[input:ans2]] [[validation:ans2]]
{@answer2@}
{@wrong2@}

Given the function, \(f(x) = {@function3@}\) 
What is the area between the x-axis and the curve of that function over the interval [{@a3@},{@b3@}]?
[[input:ans3]] [[validation:ans3]]
{@answer3@}
{@wrong3@}

**Comment by sangwinc** [comment]
Robert,
The github tracker is primarily for bugs in the core code, rather than authoring questions, but I'm happy to deal with your question here.

In your question variables you have some * signs missing.  I think for the first part you actually want c1: -r1*m1, etc.  Also, it is good practice to put ; at the end of each statement.  STACK v4.3 will allow multi-line statements and so we will start to need these soon.  More importantly, if you use semicolons then you can cut and paste into Maxima on your local computer.

Starting with your variables, copy these into Maxima:

b1: rand(9)+2;
m1: rand(19)-9;
r1: rand(b1-1)+1;
c1: -r1*m1;
function1: m1*x+c1;
answer1: int(abs(function1), x, 0, b1);

You will notice in desktop maxima that "rand" is not evaluated.  Maxima returns the function unevaluated when it is either not defined (rand) or it can't evaluate it (try integrate(x^x,x); )

Now, this won't work because both "rand" and "int" are defined by STACK and are not part of Maxima.  In this case you can add in

alias(int,integrate);
alias(rand,random);

which is basically what STACK does, e.g.
https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/stackmaxima.mac#L77

("rand" is different, because we want to "overload" the function, e.g. https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/stackmaxima.mac#L284 )

You should also use %pi (as Maxima does).  Students can use "pi" and so can teachers, but we strongly recommend teachers stick to strict Maxima syntax.  

I find working offline is very useful for debugging questions, and I suggest you have a look at the "sandbox" to find out how to set up Maxima with all the STACK functions loaded.  That way you won't need to worry about ad-hoc alias commands.

https://stack2.maths.ed.ac.uk/demo2018/question/type/stack/doc/doc.php/CAS/STACK-Maxima_sandbox.md

In your last example, I've modified your question variables.

k: rand(10);
a3: -(pi/2+k*%pi/2);
b3: %pi/2+k*%pi/2;
c3: rand(19)-9;
wave: rand([sin(x), cos(x)]);
/* rand is overloaded in this example! */
wave:sin(x);
function3: c3*wave;
answer3: int(abs(function3), x, a3, b3);

Maxima can't integrate abs(sin(x)), so it returns this un-evaluated.

I hope this helps?

**Comment by aharjula** [comment]
Am I correct to assume that these lines:
```
c1: -r1m1
function1: m1x+c1
```
mean/are actually this:
```
c1: -r1*m1;
function1: m1*x+c1;
```
While, STACK tries to add implied multiplication signs to the students answers it does not even try to do it at the teacher side as the teacher is assumed to write explicit statements. However, in this case I assume that you are just having formatting issues when copying to GitHub (the code quoting feature is somewhat recommended here) and the issue is elsewhere.

As I am not a mathematician I don't really see the difference between those integrals either but what I remember from my studies is that evaluating those with that `abs()`-wrapping requires one to take various steps (splitting it to pieces...). I would imagine that the [integration](http://maxima.sourceforge.net/docs/manual/maxima_19.html#Item_003a-integrate)-logic does not take those steps automatically, maybe you'll find a way to convince it to do so from the documentation of the underlying CAS, Maxima.

Or more likely, Chris will come and tell how this should be done as he has done enough integrals with Maxima.

Side notes:
- It is recommended to end statements in your code with semicolons. This will allow you (and people reading these issues) to simply copy the code into Maxima (well Maxima running the STACK-library)
- `rand(19)` is not a large number of variants but in general people have learned that overt number of variants tend to lead to more trouble as maintaining equivalent difficulty for them is difficult as is ensuring that all combinations even work.
- Apparently, there is a [Maxima-package](http://maxima.sourceforge.net/docs/manual/de/maxima_31.html) which would be able to evaluate those integrals, but as it is likely to mess up the rather complex logic related to integrals in general elsewhere in STACK I would not hope to get it to the system. However, one could look into the code of that package and extract the relevant logic to a singular question.
- `r2` is bad in the code as `b2-2` could be `0`, `rand(0)` won't work.
- Probably just simpler to do that integration by hand or write a loop like this, note that one needs version 4.3 of STACK to be able to write that if-statement on multiple lines like that:
```
/* The zeros of that function */
f2z: setify(map(rhs,solve(function2,x)));
/* Remove things outside and at the range */
discontinuities: subset(f2z, lambda([x],is(x < b2) and is(x > 0)));

total: 0;
if cardinality(discontinuities) = 0 then (
 total: abs(int(function2, x, 0, b2))
) else if cardinality(discontinuities) = 1 then (
 total: abs(int(function2, x, 0, first(discontinuities))) + abs(int(function2, x, first(discontinuities), b2))
) else (
 prevdisco: 0,
 total: 0,
 discos: sort(listify(discontinuities)),
 for disco in discos do (
  total: total + abs(int(function2, x, prevdisco, disco)),
  tmp: prevdisco
 ),
 total:  total + abs(int(function2, x, prevdisco, b2))
);
```

**Comment by aharjula** [comment]
Chris, I wonder if we should have some guide to GitHub issues? Mainly using the code formatting for code-samples, as the default formatting will break multiplication signs like in this case, also maybe asking for semi-colons to make our lives simpler? Anyway, pressed "comment" one second before the mail about your comment came to my mailbox...

**Comment by sangwinc** [comment]
Sorry Matti, it looks like the three of us are unusually "on the ball" today!  We don't get many requests for support here (and I'm not sure guidelines will help the person who hasn't got far enough though the docs to read them....) so for now, with the number of requests we typically get, I'm happy to mop up authoring queries and move them elsewhere as needed.

Chris

**Comment by Robert-Hartley** [comment]
Thank you all for your replies, and sorry it isn;t what this forum is intended to be used for, I'm entirely new to all this and still figuring it out. Is there a forum where this sort of question is more appropriate?

In regards to my question, for some reason the * signs disappeared when I copied across from my stack question to this forum but I do have them in place. I shall try some of the other suggestions.

**Comment by aharjula** [comment]
Robert,
I think Tim linked the Moodle.org sub-forum in the other ticket. In any case when copying code to any web-site it is always worth checking if it needs to be somehow escaped or wrapped to be corerrectly displayed. At the Moodle.org side things will probably be different but here in GitHub one tends to wrap everything code related in backtics, why your multiplication signs dissapeared and the text turned italic is probably explained by the [syntax-guide for GitHub](https://guides.github.com/features/mastering-markdown/).
