### ISSUE TITLE
PHP Unit test failures in 4.3.0B3

### ISSUE THREAD

**Issue by tlock** [maths/moodle-qtype_stack#560]
I'm upgrading from 2018080600 (v4.2.1) which everything is passing with some tweaks. Trying to update to 4.2.2, massive failures and same with master code.

Can you please resolve the issues in the next month to so? 

Total result: Tests | 2749 | Assertions | 60969 | Errors | 106 | Failures | 2147 | Skipped | 48 |

[qtype_stack-4.3.0b3-failures.txt](https://github.com/maths/moodle-qtype_stack/files/4233653/qtype_stack-4.3.0b3-failures.txt)

**Comment by sangwinc** [comment]
I'm very sorry you are having these problems with 4.2.2.  It was for reasons like this we started developing v4.3.   At Edinburgh we are using STACK 4.3,  (specifically  2020020300, which is HEAD in the master branch).  We have been using this, in anger, with very large groups of students since January.

These unit tests are not failing in that branch:  https://travis-ci.org/maths/moodle-qtype_stack/jobs/651455718?utm_medium=notification&utm_source=github_status

2020020300 is tagged as MATURITY_RC (see https://github.com/maths/moodle-qtype_stack/blob/master/version.php) because the changes are so extensive that I want to run STACK for a semester in Edinburgh, so we can identify any issues here before I release and recommend you upgrade to 4.3.

The only "TODO" I'm aware of is to improve performance.  See
https://github.com/maths/moodle-qtype_stack/blob/dev/doc/en/Developer/Development_track.md

STACK 4.3 does have a parser, and by its very nature this is slower.  So, now is the time to optimize some parts of the code.  So, I'm going to look into that but I'm basically ready to do an official release as soon as we are all happy we have done as much as we can.

So, if you have a dev machine I recommend you look at the HEAD of master.

Under these circumstances, I will not be fixing 4.2.2!  (Sorry)
Chris
