### ISSUE TITLE
DB Case sensitivity problem

### ISSUE THREAD

**Issue by t-schroeder** [maths/moodle-qtype_stack#562]
We use MySQL with a case-insensitive collation. We recently ran into the problem where a user had a question where he used the variable "A", then changed it to "a" and got a DB error that a unique constraint would be violated. When making the column "name" in table qtype_stacks_inputs case-sensitive this problem is fixed.

I'm not sure you can necessarily prevent this problem in code, but a short notice in the Readme would be nice.

**Comment by aharjula** [comment]
Skipping my opinions about MySQL (or not depending how you read this). This is indeed a problem, back when this was first spotted (#194 all the other things the issue talks about have changed) the Moodle side was aware of this as a serious problem. Maybe someone at the Moodle side could check if we could now or eventually have the ability to define case-sensitivity rules on XMLDB definitions of tables so that if people use databases that think in case-insensitive ways the definition would ensure sensible behaviour. Apparently, one can tell MySQL that some columns are case-sensitive...

The problem is that STACK leaves the handling of databases to Moodle so we would need for Moodle to provide a way for us to say that this column (and PRTs and their nodes that all have names) needs to be case-sensitive. Until that happens the safest bet for people wanting to use STACK without worrying about materials that might have inputs named `A` and `a` at the same time is to use some database that does not by default use case-insensitive collation. As long as case-insensitive collation is not important for you I would recommend Postgres as the better database-option, but as you already have solved this with additional commands on the MySQL side all is fine.

**Comment by sangwinc** [comment]
Oh dear.

I will certainly include a warning in the STACK docs.  Would you be willing to draft the words?  (Since you know exactly what the problem is....).   Please send a pull request, or the text in an email to me C.J.Sangwin@ed.ac.uk and I'll happily add it.  

Or, let's hope there is a Moodle fix...

**Comment by t-schroeder** [comment]
Alright, I made a pull request that adds a step to the installation doc.

Do you think it's okay to include an example SQL command there? Or should I remove it since it would become outdated once the column type, recommended character set/collation changes?

**Comment by aharjula** [comment]
Thank you.

I would maybe put the version number of the MySQL next to any example command, for the reasons you have stated.

Also I think we will add some other text about this applying mainly on MySQL where this happens easily by default. We might also want to setup some form of a test on the healthcheck page to identify installations where this happens. As it might be that people do not read or understand this, it might be better to also state it if it applies to them.

**Comment by sangwinc** [comment]
Good idea about the healtcheck page Matti,
I don't fully understand the issue.  Are you able to write the check please?
Chris

**Comment by aharjula** [comment]
At some point Chris... The idea would be to have a DB-transaction and try to create a dummy question-row and then two inputs with suitable names (`A` and `a`) for it. If one can execute that then things are ok if not (exception from DB) then things are not. One just needs to clear those created rows after the test.

Probably needs some comments from Tim, as when one created that dummy question is there a particular category or other place where it would be best to create it, is there a staging area in Moodle where it could be built and removed without messing up any existing category/question bank?

**Comment by t-schroeder** [comment]
I added the MySQL version to the example command.

As for the test I noticed there are a few DB tables specifically for running tests:

* qtype_stack_qtests
* qtype_stack_qtest_
