### ISSUE TITLE
Error writing the Database

### ISSUE THREAD

**Issue by sehomer** [maths/moodle-qtype_stack#568]
Hello,

one of our teachers was faced with the error in the subject when he tried to save a question (Moodle3.5.11+ / STACK 2019090200). Opening the existent question and saving it without changing it does not work. 

Any help would be appreciated. Best wishes
Sebastian

The following debug information is shown when saving:
```
`Notice: Trying to get property 'contentsdisplayed' of non-object in /var/www/moodle/question/type/stack/stack/questiontest.php on line 92

Notice: Trying to get property 'status' of non-object in /var/www/moodle/question/type/stack/stack/questiontest.php on line 92

Notice: Trying to get property 'errors' of non-object in /var/www/moodle/question/type/stack/stack/questiontest.php on line 92

Notice: Trying to get property 'contentsdisplayed' of non-object in /var/www/moodle/question/type/stack/stack/questiontest.php on line 92

Notice: Trying to get property 'status' of non-object in /var/www/moodle/question/type/stack/stack/questiontest.php on line 92

Notice: Trying to get property 'errors' of non-object in /var/www/moodle/question/type/stack/stack/questiontest.php on line 92

Notice: Trying to get property 'contentsdisplayed' of non-object in /var/www/moodle/question/type/stack/stack/questiontest.php on line 92

Notice: Trying to get property 'status' of non-object in /var/www/moodle/question/type/stack/stack/questiontest.php on line 92

Notice: Trying to get property 'errors' of non-object in /var/www/moodle/question/type/stack/stack/questiontest.php on line 92

Notice: Undefined index: prt2 in /var/www/moodle/question/type/stack/question.php on line 785
Fehler: Argument 1 passed to qtype_stack_question::has_necessary_prt_inputs() must be an instance of stack_potentialresponse_tree, null given, called in [dirroot]/question/type/stack/question.php on line 787

Weitere Informationen über diesen Fehler

×Debug info: 
Error code: generalexceptionmessage
×Stack trace:
line 714 of /question/type/stack/question.php: TypeError thrown
line 787 of /question/type/stack/question.php: call to qtype_stack_question->has_necessary_prt_inputs()
line 95 of /question/type/stack/stack/questiontest.php: call to qtype_stack_question->get_prt_result()
line 298 of /question/type/stack/questiontestrun.php: call to stack_question_test->test_question()`
```

**Comment by sehomer** [comment]
The following xml-file of the question was provided by the teacher (renamed to txt to upload it)

[quiz-Physikalische Grundlagen Musterkurs-Debug-20200326-0830.txt](https://github.com/maths/moodle-qtype_stack/files/4385649/quiz-Physikalische.Grundlagen.Musterkurs-Debug-20200326-0830.txt)

**Comment by paulschwarz-htw** [comment]
Hello trhere,

i created the given question at first and it's made for physics practical courses. 
I wanted the students to mesaure a cuboid and put in the side lengths a, b, c and afterwards they shall determine the errors in mesaurement and give the correct rounded result.
That worked well at this point. 

Now i wanted to create a digital only version without measuring because of shut down university due to Corona. So i deleted the inputs and response-trees and replaced them with a list of measured data. The given set will be randomly chosen at start of the test.
After finishing the edit the error occured: error writing in database.

I could not fix this so i created a new question typing in everything again. After finishing, saving worked well - 1 time. I wanted to change a layout issue, then the error occured again. The change was not saved. Then i changed something in the main variables on top, this change was saved although the same error occured again.

Maybe there is somthng broken in the question-text? I don't get it.

Thanks, paul

**Comment by aharjula** [comment]
Wild guess based on those errors... Maybe the question had question-tests for PRTs that were removed and when doing the save the database gets confused as it cannot have tests that point to PRTs that no longer exist? Maybe check if you can remove those tests before starting to remove the PRTs?

Sounds like incomplete logic related to saving the tests, or removing them when PRTs are removed, but as fixes getting through during the current crisis might take some time maybe removing the test could be a workaround, maybe you can test that? You can actually strip the tests out of the XML by hand if need be they should be obvious when looking at the end of the file.

**Comment by paulschwarz-htw** [comment]
Thanks for the hint Matti.

There actually were Tests on the prt's and i deleted them before deleting the PRT's too.  It seems, my changes are saved now but the error message still pops up.

Looks like this problem is anyhow solved.
