### ISSUE TITLE
AlgEquiv test: TEST_FAILED

### ISSUE THREAD

**Issue by aacchhee** [maths/moodle-qtype_stack#569]
We have a question with AlgEquiv test and one of the students found an input where the test fails. Test failure somehow affects performance of the whole attempt: STACK becomes extremely slow also for other questions.

We wanted students to input numbers, but one tried inequalities. As though the test recognizes it and gives a warning message, something else is wrong.

When a similar code runs directly in Maxima, things work -- so we think that this is a STACK issue.

![Capture3](https://user-images.githubusercontent.com/59649991/77746282-ffba0e00-701c-11ea-88d1-658ed5630f23.PNG)
![stack_trøbbel](https://user-images.githubusercontent.com/59649991/77746305-08124900-701d-11ea-98f7-5756e570b6f4.PNG)
[questions-IMAG2021 2020V-Oppgave 3.1.6-20200327-1116.zip](https://github.com/maths/moodle-qtype_stack/files/4392778/questions-IMAG2021.2020V-Oppgave.3.1.6-20200327-1116.zip)

**Comment by sangwinc** [comment]
Thanks, that is quite an interesting example!
The problem is that the student's answer [m>n,n<m] gets transformed into this answer test by your PRT.

`ATAlgEquiv((n < m)/(m > n), 'round((n < m)/(m > n)))`

In Maxima the expression `(m>n)/(n<m)` is legitimate, if meaningless.  This comparison is sending Maxima into an infinite loop (hence the TIMEDOUT).

One solution in your question is to check if the student's answer is a list of numbers in the PRT before this last check, e.g. test `all_listp(numberp, ans1);` or `all_listp(integerp, ans1);` with `true`.

I'm not sure exactly where this goes into an infinite loop, but your student is throwing some nonsense into the test, so I'm not completely surprised this isn't working!
