### ISSUE TITLE
Formative PRTs.

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#573]
From a user:

In a STACK question, I want to ask for two numbers, a and b so I have a PRT for a and one for b. In case, both inputs are given (a and b), I want to check if they meet a certain condition (say, a=b) and give a hint, if that condition isn't met, but keep silence if it is met. Now, if I integrate that test into one or both PRTs for a and b, then there will only be feedback upon "check", if both inputs are given. Therefore, this is not an option. On the other hand, if I add a separate PRT for this check, then it seems that I can't suppress the wrong/write statement. Thus I have twice "right" under the last input, which looks stupid. How can I get rid of that? 

I already learned that I can switch off automatic feedback from a PRT node, but that doesn't seem to affect the right/wrong/partially right response. I see a hard workaround: delete the default answers in the question options and add wrong/right to the PRT feedback. This would be very inconvenient and prone to inconsistency.

**Comment by sangwinc** [comment]
The "Compact" input validation has proved to be very useful indeed, especially for the work we are currently doing on reading comprehensions of mathematical proof.

The feedback from PRTs is somewhat fixed, and sits inside DIVS.    I've been thinking about, and mocking up, some options for more flexible display of PRT feedback.

This will include

1. A compact version, which will sit inside tables much better.
2. The ability to suppress the generic feedback, such as "Correct answer, well done", for a single PRT in a question.
3. A purely "formative" PRT mode which does not contribute at all to marks, or the completeness of the attempt.

These modes could be used to subvert the behaviours, and quiz options.  But, for multi-part questions I am starting to think they will be very useful indeed.

**Comment by sangwinc** [comment]
Here is an example question.

[examplequestion.txt](https://github.com/maths/moodle-qtype_stack/files/4462114/examplequestion.txt)

**Comment by aharjula** [comment]
Sounds like we should have a type-property in the PRTs that could be used to tell what type of a PRT it is. Of course, I have to bring Stateful up here... In Stateful, the common feedback messages do not exist as sharing them between all the scenes and PRTs is pretty pointless, in addition to that the PRTs there have a type property that says how the PRT behaves in grading. One of the options is to not have any grade weight and in that case, it does not even require point values for nodes to be defined. If the type says that it has no grade weight then as you say it would not include the default messages.

If we were to do modification to the PRT model, one of the things I have been thinking is related to the notes that are generated based on the branch activated in the tree. Could we have an explicit tag attached to each leaf to state that it represents a correct answer or specific error case or even a catch-all unknown error, this might make it simpler to do data-analysis without knowing the meanings of the notes themselves, or guessing based on point values.

**Comment by sangwinc** [comment]
Yes, Matti,
I envisage a new column "feedbackstyle" next to this one.
https://github.com/maths/moodle-qtype_stack/blob/master/db/install.xml#L72
If we have an integer, then we can accommodate a range of future PRT layout and functionality styles.

Yes, basically the "formative" type I enisage will be the equivalent of the type in stateless without weight.  I've not made the editor remove the needs for grades (convenience to me today), but that is the logical thing to do.

I have some working code (running unit tests before commit) which don't make database modifications for now.

**Comment by sangwinc** [comment]
Tags:  Can you give me examples of what the tags would look like?
I can imagine a "correct" tag. But if a question author wants tags for "specific error case or even a catch-all unknown error," then we need to define these.  The auto-generated notes from the answer tests are a step in that direction.

The purpose of the answernote is to carry those tags!  The problem is question authors have to fill them in by hand.  Hence the auto-generated place holders to make sure we don't get too many empty notes which would make stats pointless....  Perhaps a better editor which gives common pre-defined "tags" (such as "correct")?

Examples beyond correct/incorrect would help here.

**Comment by aharjula** [comment]
The answer note (in the nodes, not the test generated ones), even if it is filled in by hand is just a string which makes it difficult for data analysis to understand what they mean. When I said "tag" it was probably the wrong word, it would be enough to have four values unknown (the default), correct, specific error and unknown error. The author could then use the existing answer note or the chain of notes to specify which specific error and which specific correct exit from the tree it is. Key is that whatever analysis tool there would be would not need to understand the notes, as even the answer-test notes do not explicitly define correctness as the correctness of an answer can be defined as a negation using them.

If you wonder why have unknown and unknown error separately it's due to the structure of the tree, as one can probably set these at all nodes not just the leaves of the tree one needs to be able to define an unknown result when doing classifications earlier in the tree. Going from unknown classification to unknown error or correct when travelling through the tree makes sense, but if one would first have the answer classified as unknown error and then turn it to correct it would seem somewhat odd.

**Comment by sangwinc** [comment]
Example question to illustrate the use.

[oddfunctions.txt](https://github.com/maths/moodle-qtype_stack/files/4464736/oddfunctions.txt)
