### ISSUE TITLE
JSXGraph on mobile devices

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#577]
Santiago, thanks for suggesting that we support JSXGraph plots with a size which works on a mobile screen.

Either, we have some styling which re-sizes graphs for mobile screens, or users can set the sizes explicitly for different media.  E.g. as here
https://github.com/maths/moodle-qtype_stack/blob/master/styles.css#L155

The JSXGraph block and options are set here
https://github.com/maths/moodle-qtype_stack/blob/master/stack/cas/castext/jsxgraph.block.php#L97

Can you make some concrete suggestions?

**Comment by aharjula** [comment]
Chris,
JSXGraph itself is very well suited for mobile devices as the scaling and layout of the contents happens according the axis selected, and the block size can simply be given with relative units, eg. `width='90vw'` or maybe `width='95vmin' height='35vmin'`. Beyond that it the author can simply place the `[[]jsxgraph]]` into whatever `<div>` they want and give it all the reactive behaviour they need.

The Abacus style guide has always recommended the use of relative units for sizing plots and the JSXGraph block has been specifically made so that those can be used so this should be all fine already. Naturally, we could (but should not) by default define the plot size as viewport relative instead of the current pixel-size (thought that it was font-size relative at some point). For now, this just requires that the author defines the size they want and that they define it so that it will work with mobile devices, i.e. in relation to `vmin` for those portrait iPhones... 

Problem is that `vmin` is rather inconvenient when working with the whole Moodle layout, so those CSS-media rules may be the thing that will be needed. Also as it is unlikely that all graphs have the same aspect-ratio the CSS-media rules might not be an easy solution as the aspect-ratio would need to be transferred to them. Or maybe we just provide a limited set of options e.g. by default `4:3` and `1:1`, `16:9`, and `16:10` could be defined as `mobileaspectratio` which would be used with the maximum size available. Could also just have `aspectratio` and allow normal size definition by giving the aspect-ratio and one dimension.

**Comment by sangwinc** [comment]
Thanks Matti,
That is all very helpful indeed.  I hope Santiago can help here, by investigating and proposing some specifics (in the docs for example).

**Comment by sangwinc** [comment]
We should solve this issue in conjunction with issue #1010.
