### ISSUE TITLE
MathJax in dropdowns

### ISSUE THREAD

**Issue by hwesterholt** [maths/moodle-qtype_stack#579]
In the dropdown menu `p1:[[2,false,"<="],[1,true,">="],[3,false,"?"]]`,
I'd like to replace the strings "<=" and ">=" by their LaTeX equivalents `\leq` and `\geq`.
Using `"\[\leq\]"` outputs `[leq]` so it appears that simple backslashes are automatically escaped. However, using `"\\[\\leq\\]"` prints the less-or-equal sign twice.

I think that the latex options in the extra options field should be correct, any advice on this would be highly appreciated.

**Comment by timhunt** [comment]
In the drop-downs you can use TeX. (Think about how this is represented in HTML, if you know about that sort of thing.)

However, you can use the Unicdoe characters. Here they are if you want to copy-and-paste: ≤, ≥.

**Comment by aharjula** [comment]
*"**can not** use TeX" is what I imagine Tim was saying. Unicode should work just fine as long as your STACK is new enough and your Maxima is not older than 5.38.1. if Unicode does not work, you might want to look at HTML-entities as an option, tedious and inconvenient but still a fall-back option.

There are no native HTML-dropdowns that would work with MathJax and as we use native dropdowns to ensure screen-reader support, LaTeX just does not work in dropdowns in our world.

The option for LaTeX in the dropdown input should not exist, but it is there due to the dropdown and radio inputs sharing logic and in the radio input that option just works.

**Comment by sangwinc** [comment]
Yes, this is a known limitation of the basic system and isn't really a "STACK thing", sorry! it would be great if it worked...

**Comment by hwesterholt** [comment]
HTML entities worked like a charm, thank you all

**Comment by sangwinc** [comment]
Could I ask you to send me an actual example (email C.J.Sangwin@ed.ac.uk) which I can include in the documentation please?  I'd like to document this issue, so we can point future colleagues to a practical way to proceed.

**Comment by hwesterholt** [comment]
I'll send you the example as soon as possible (probably later this week) and I'd love to contribute where I can.
