### ISSUE TITLE
Variants lost when you duplicate a question

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#587]
If you copy a question in the Moodle question bank, the question variants get "lost".  I.e. the new copy has no variants.

Is this a "STACK thing" or a "Moodle thing"?

**Comment by timhunt** [comment]
I would say that it is a bug that is the result of an mismatch between what Moodle expects and what STACK does.

Moodle expects that all the data that defines a question is present in the editing form, and therefore that you can duplicate a question by populating the form from the old question, and then saving it as a new question.

STACK has data linked to the question (deployed variants and questoin tests) which are not present in the form.

In the past, we had a work-around to this for question tests, but not for deployed variants: https://github.com/maths/moodle-qtype_stack/blob/master/questiontype.php#L336 However, what was written for the old way that Moodle question bank used to work, where to copy a question, you did Edit question, and then Save as new question. I am pretty sure that no longer works. (We really ought to have a Behat test for this!)

I'm just thinking about how best to fix this.

**Comment by aharjula** [comment]
Ok. Good to know Tim... I just read through the backup logic just in case someone had changed that and this was dropped from there. But as this is a different way of cloning data that did not apply here. Maybe Moodle could use the backup-classes to do a backup/restore for that cloning?

**Comment by timhunt** [comment]
This is not backup/restore. This is the 'Duplicate' option in the question bank user interface.

**Comment by aharjula** [comment]
Tim. Yes I thanked you for clarifying that "Duplicate" does not use the logical means of using the backup/restore-logic but instead provides its own limit for what can and should be copied.

Chris: Note, it might not make sense to transfer the variants when cloning. If you clone with the intention modifying the question and its randomisation the seeds might not map to unique variant anymore.

Also note this from the point of view of #473 and the way that Statefult handles multiple variant pools within the same question.

**Comment by timhunt** [comment]
Like Matti, I am not entirely sure what the desired behaviour is. For example, in the scenario where you choose 'Duplicate' on an existing question, and then make lots of edits before saving (e.g. remove or add inputs an/or PRTs).

Anyway, what I have done (on branch iss587) is make a Behat test for this, which fails.

However, I was surprised to find that it is only the deployed variants bit that fails. The code about copying question tests, which I did not believe would work, actually did copy them. However, now that I look at how the question editing code works (rather than relying on my memory) I can see that I was wrong before. The code we have to copy question tests is the way to do it.

OK. Let me do a fix. Then if Chris is sure he wants this behaviour he can merge the branch. (I can see the reasoning. If you don't want the copied deployed variants, it is not hard to delete them. It is more work to manually copy the list of variants from the other question.)

**Comment by timhunt** [comment]
Second commit pushed, which copies the variants. Chris, if you are happy, please merge the iss587 branch.

**Comment by sangwinc** [comment]
I think I would expect, when you copy a question, that all the question tests, and all the variants would also copy over.  Often we copy questions to use them in more than one place so dropping the variants is strange.  We can drop all the variants easily.

Thanks for pushing the change Tim.

**Comment by sangwinc** [comment]
This is now merged into master, and fixed.
