### ISSUE TITLE
Doc hint on problems with case sensitivity in input names

### ISSUE THREAD

**Issue by mkraska** [maths/moodle-qtype_stack#588]
Depending on database settings in moodle, the input names may or may not be case sensitive. If you use two names in a multipart question like S_M and S_m, then you will not be able to store the question. You get the error message "Error writing database". Unless you are aware that mysql is non-case-sensitive and postgres is, you won't guess what you made wrong.

Most users probably aren't aware of the database back end.

The [CAStext doc page](https://stack2.maths.ed.ac.uk/demo2018/question/type/stack/doc/doc.php/Authoring/CASText.md) explicitly says that input names can be any legitimate variable name. My understanding when reading this page was of legitimate in the scope of Maxima. This isn't true for users with a mysql backed moodle. 

I also would recommend to add that warning to the question mark callouts (mini help texts) on the STACK editor page. 

Alternatively you could try to catch such errors with a more helpful error message. See the discussion in https://moodle.org/mod/forum/discuss.php?d=405264

**Comment by aharjula** [comment]
Worth noting that in addition to inputs this also applies to PRTs and their nodes (although node naming is not a thing people tend to do, it's not even in the editor).

https://github.com/maths/moodle-qtype_stack/issues/562 is the most recent mention of this issue, basically, it is (well has recently been added) in the installation instructions and we hope that people installing STACK take it into account so that users would never need to deal with it. If we had the means of asking for Moodle to set those column encodings in the database to case-sensitive we would do so to avoid the issue entirely. Problem is that this only applies to a subpopulation of MySQL and its derivatives and targeting that fix is, therefore, a bit difficult.

Like Tim said, using Postgres or some other database with sensible defaults tends to be the best long term solution. I'll leave my personal opinions about MySQL not stated here, but I guess anyone can read between the lines and guess what they are.

Given that there are large sets of materials that have been authored on systems that have case-sensitive databases and trying to use/import them (well those that have this issue)  is impossible if one has a case-insensitive database this a real problem. However, if most people can use them it is questionable to write messages warning about their use, especially as varying the case is a pretty common pattern that people use. Also worth noting that the largest material-sharing pool that I am aware of actually has case-sensitivity as a stated requirement for installations expecting to use the materials.

Maybe Tim could fashion some form of plugin requirement check method for the Moodle requirement checking system? Like that recent YAML-check. I doubt we want to stop people from installing STACK on a "database" with these issues but maybe we could at least warn about it.

In any case that suggestion for the wishlist: When writing those inputs/PRTs to the database catch any exceptions and if such are caught check if it could be case-insensitivity related if so translate the error to something sensible. A nightmare to test though as one would need to install MySQL to do that.

**Comment by mkraska** [comment]
Thank you for the comprehensive explanation. I just discussed this with our Moodle admin and the clear statement is that switching database is not an option. Yet there seems to be hope to make mysql case sensitive. Let's keep fingers crossed ;)
