### ISSUE TITLE
Strict validation of integer input

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#589]
It would be very helpful to have an option to require an integer.

E.g. these kinds of things would be valid
1
-2
10000

These kinds of things would be invalid
1+1
2-1
10^100

Note the "-2" example would prevent us just using "forbidden words" to disallow -.

Any other examples?

**Comment by aharjula** [comment]
Chris,
Please check [the options](https://github.com/maths/moodle-qtype_stateful/blob/master/stateful/input2/inputs/numerical.input.php#L200-L213) for the numerical-input in the input2 proto. It is an input that only accepts singleton values ie no expressions beyond a single prefix-operator and an optional power of 10 suffix. It can be instructed to accept floats or integers and the power of 10 option can be forbidden to only accept pure integers.
![intsonly](https://user-images.githubusercontent.com/980957/85131991-97a44e00-b240-11ea-8f7c-d89897290a09.png)
Note that the AST-filters it uses are already in STACK...

The concept of forbidden-words does not exist for the numerical input in input2 (trying to avoid providing options that have no real role) but maybe it could have an option to forbid negative values and if so probably also positive values could be forbidden. Not at the same time though, we do not want to figure out what `0` is if both `-0` and `+0` have been forbidden.

**Comment by mkraska** [comment]
More examples: \sqrt(16), sin(pi/2) evaluate to integers but would still delegate  calculations to the system, which I want to suppress. If I want expressions, then I am fine with variables.

**Comment by sangwinc** [comment]
Thanks Matti, I'd already spotted your very helpful AST-filters.  Your suggestion of no forbidden-word for numerical inputs is sensible, but might be restrictive if you want to allow 10^100 but not 2*3.  I don't know, as I'm always surprised how people use STACK!

Any sense of when input2 might make it into the STACK code base?

**Comment by aharjula** [comment]
Chris, the input2 numerical logic is primarily intended to allow scientific notation and it has specific logic to only allow powers of ten in the expression and even then just one of those. It would not allow `2*3` in any form, as long as the config says that "integers are ok" and that "powers of ten suffixes are ok" then it will allow `10^100`. Just for fun though see what happens if you then give it `10^400`.

I am not optimistic for input2 getting to master before 2022 and it will essentially mean a version bump to STACK 5 as it will again require massive amounts of translation of materials and will not be revertable change. I would prefer to test it on Stateful at least for a year, before starting the merge. The caching and PRT-overhaul + CASText2 are things that will make it to STACK 4.x long before input2, and even those are held back by having to divert resources to the preparation for the second wave. All of these require that you familiarise yourself with their function in Stateful before we start to move them to STACK.

One of the big question related to input2 is entirely open. Will you accept the way of it having that many options and thus making authors view more complex or will you accept the Stateful way of having more options, but fewer input-types which leads to inputs like the matrix-input that has 40+ different options that can be tuned and multiple of them having CAS-backed-values. For example, the numerical input currently has ~20 options. Someone would also need to come up with a way of editing those options in Moodle (e.g. rendering schema-backed forms) which is something that also needs to be solved. In any case, options have a central role in input2.

Also providing those customised validation messages will add an entirely new section to the editor, so again a place where added capability will make the editor more complex.

**Comment by sangwinc** [comment]
Lots to discuss here Matti, but thank you for posting this publicly so everyone else can see what is going on.  We should have a separate thread/project for input2.

**Comment by aharjula** [comment]
Indeed Chris, lots to discuss. I am pretty sure the underlying technical structure of input2 is sound but the balancing will need to be done at the level of input-types and their options. The outside facing authoring portion is also something that needs to be solved, but even for that the schema-based declaration and validation seems to be the best way forward. I am sure that we can implement all the features of existing input-types, but the question is should we, and how some of the oddities should be mapped to new options that may have different granularity.

But yes maybe a project, although that PRT-project page has been quiet and has gotten a bit outdated this might suit even better as such a project. More objectives and so on.
