### ISSUE TITLE
Algebraic input issue with inserting stars

### ISSUE THREAD

**Issue by dhilsen** [maths/moodle-qtype_stack#597]
STACK v4.3.3 with Maxima 5.41.0
For Algebraic input(AlgEquiv answer test), with the option "Insert stars assuming single-character variables, implied, and for spaces", the following behavior is observed:
a) Teacher answer `x*y*(a+b)`.   Entering student answer `xy(a+b)`, using no stars, looks like a correct answer in the validation, however, the answer is marked as incorrect.
b) Teacher answer `x*y*(a+b)^2`.  Entering student answer `xy(a+b)^2`, using no stars, appears in the validation as xy^2(a+b).

Of course if students always insert multiplication stars everything is fine. A problem arises for students when many algebraic expressions can be entered perfectly fine without multiplication stars (using the option stated above), then exceptions occur where multiplication stars are necessary.

**Comment by sangwinc** [comment]
Ok, this is because the parser interprets xy( as function application.  We have had a request for "no user-defined functions" before.

**Comment by aharjula** [comment]
Actually, the capability exists as a filter already the problem is that it is difficult to add options for toggling such features. In a few years input2 will solve this and provide options like these:
![Screenshot_2020-06-27_17-30-00](https://user-images.githubusercontent.com/980957/85924651-4e857700-b89c-11ea-8fd6-b1f4b7c9a1e6.png)

**Comment by sangwinc** [comment]
Exactly Matti, all that work on v4.3 paying dividends.....
