### ISSUE TITLE
problems with multilang tag inside PRT feedback

### ISSUE THREAD

**Issue by nfa019** [maths/moodle-qtype_stack#600]
Here is one of the issues I mentioned at EAMS:

I have tried a multilingual question in STACK using the multilang tag. This works fine in almost all places, where text can be placed. But using it in the feedback of the PRT nodes I see a strang behaviour: only the feedback of the last node is shown. Without the multilang tag (only one language) everything works fine.

I include an example here.

Best wishes
Frauke

[Regex Test international.xml.zip](https://github.com/maths/moodle-qtype_stack/files/4857433/Regex.Test.international.xml.zip)

**Comment by aharjula** [comment]
Thank you, that is a new failure mode for the multilang-filter that I had not seen before even though we have used it quite a lot.

Oh how much simpler things would be if STACK handled this multi-lang stuff itself, and did not play around with the stuff that Moodle filters do, we could actually have performance gains (no need to render all the variants) if we would do it ourselves as well as provide deeper level localisation. The reason why things break here is again the quality of that plugin. For reasons unknown having two multilang-spans touch each other leads to the former span being discarded. Just try putting this anywhere where the filter is active (does not need to be in STACK) and see what happens.
```
<span lang="en" class="multilang">A</span><span lang="en" class="multilang">B</span>
```
In your example, the feedback from the first node ends with one such span and the second one starts with one. Leading to the filter dropping the content. It does not help that STACK or Moodle-forms trims the feedback-text so just adding a space to the end would not fix this. As a bandaid, I would suggest a zero-width-space (`&#8203;`) to be added to the end of the feedback-text if it ends with a `</span>`.

As you obviously know regexps maybe you could look at [the filter](https://github.com/moodle/moodle/blob/master/filter/multilang/filter.php). Hopefully, someone makes a bug-report on the Moodle-side.

For others doing multilang, the things that caused the most trouble, before this new observation:
 1. Do not put other `<span>`-tags inside the multilang content, it will break it does not understand nesting.
 2. Note that feedback, input and validation blocks may produce spans, depending on the type of input etc.
 3. Remember that the type of quotes matters when doing this `<span class='multilang' ...>` just won't work it needs to be  `<span class="multilang" ...>`.
 4. When enabling the multilang filter in Moodle make sure that it is at the top of the list of filters, otherwise it will get confused by spans generated by other filters, especially those generated by the MathJax-filter.

**Comment by nfa019** [comment]
Thank you, Matti.

Works.

Best wishes
Frauke
