### ISSUE TITLE
Feature Request for Tests/Cache Bulk Script

### ISSUE THREAD

**Issue by dhilsen** [maths/moodle-qtype_stack#604]
Our question bank currently has several thousand STACK questions, with each question possessing many variants. Each question requires 4 to 5 minutes to cache after a STACK upgrade and clearing the cache. Re-caching the entire question bank requires two weeks of continuous running of the tests/cache bulk script. 

One issue we encounter is the bulk script unexpectedly shutting down at times (this may be caused from running out of memory or perhaps certain cron jobs interfering with the bulk script). Upon resuming the bulk script it will start over from the beginning, and even though it moves relatively quickly through the already cached questions, it can take a number of days to catch up to where it left off. We get caught in a cycle where it may take a month to re-cache all the STACK questions.

A helpful feature would be to create an input allowing the user to specify the starting point for the bulk script. The bulk script appears to progress through the questions according to the order they appear in the question bank. Perhaps such an input could allow the user to enter a question number as the starting point.

**Comment by aharjula** [comment]
Sounds slow... My thousands of questions bank has fewer variants but it might be organised differently as I can typically generate it in a day or two if there are issues. I tend to do it by starting the bulk processes from the browser where one can select to run one course at a time, I can typically run a few courses in parallel. Naturally, this is really inconvenient to do as one needs to start up new courses as others get ready. However, it allows me to test those courses that I am suspicious about first and leave the rest to the bulk script when I am not there. The bulk script is not much slower but it does indeed require one to start from scratch and should have options for starting from an offset or running e.g. even-numbered questions and odd questions in parallel.

I do hope that once the API eventually materialises one could use it to build continuous testing tools that continuously check and pre-seed materials and can do that in parallel with some sane UI to manage issues.

However, your reported times sound really slow unless you truly have e.g. 5k questions with ~100 variants each and even in that case you would be using 5 seconds per-variant to take a full month (yes I understood that the time goes into the restarts). That time would only make sense if you also have dozens of tests and not just a few for those questions. Otherwise, something is slow, it has to be either Maxima, the machine doing it, or the database. If there actually is half a million variants you might also want to consider whether your database can efficiently (with it current config) handle that large a cache table, as each variant and tests for them will add multiple items to that table, the response time of that table will have a huge effect here.

**Comment by dhilsen** [comment]
Thank you Matti for this insight. I'm interested in learning if our database is operating slower than it should be. 

With our several thousand STACK questions we do indeed average approximately 100 variants for each question. We generally use only one or two tests per question. The per seed caching time is 3 to 4 seconds. This is how we end up with running the bulk script for two weeks if continuous, and 4 weeks if we are re-starting the bulk script a number of times.  

Does the per seed caching time of 3 to 4 seconds sound unusually slow?

**Comment by aharjula** [comment]
Yes, it seems slow unless all of them have hundreds of lines of question-variables and text as well as plots. Generally one would expect to render a question variant to take less than a second or even less (0.25s would be fast here). It is not entirely impossible to actually run the whole system without the cache if one has a really fast Maxima and can offset the cache search times with it. Naturally, it always depends on the scale of the operation for which things are being served, caching is pretty much mandatory if you have large user numbers as run-time generation might not be feasible in those cases.

**Comment by dhilsen** [comment]
Thank you, this is very helpful information. We will investigate potential sources of slow downs in our database.

**Comment by sangwinc** [comment]
David, I hope the modifications to the scripts I made (email discussions) have helped.  If you need more, please don't hesitate to re-open this issue.
Chris
