### ISSUE TITLE
Missing Unit: curie Ci

### ISSUE THREAD

**Issue by dhilsen** [maths/moodle-qtype_stack#606]
One final unit to include that was previously missed is the radioactivity unit curie `Ci`. 

I'm curious to find out if this particular unit introduces any issues. We added `Ci` to our local casstring.units.class.php file and have noticed some unusual behaviors with questions utilizing this unit. In particular, an answer of `0 Ci` seems to cause issues with the validation.

**Comment by sangwinc** [comment]
Ok David,
Can you share your code and be more specific with the problems before I add this in!  If you know we can break something, please let me know and I'll add it to the unit tests.

**Comment by dhilsen** [comment]
Sorry for the late follow-up on this issue. The unit `Ci` is presently working fine on our system, not sure what may have caused the issue I mentioned earlier. Perhaps clearing the STACK cache fixed this issue for us.

Please do go ahead and add the unit `Ci` to the list of supported units.

**Comment by sangwinc** [comment]
Great David, can you send me your casstring.units.class.php file, or just the line I need to add?!

**Comment by dhilsen** [comment]
Chris, with regard to the curie `Ci` unit here is the line we added to the casstring.units.class.php file:
`array('Ci', 'Ci', 'Ci', 'curie'),`

We did not include conversions to other radioactivity units.

Also, I wanted to make sure we have the following British units included in the current STACK version which I believe we discussed earlier:
```
array('lb', '4.4482*N', 'lb', 'pound'),
array('hp', '746*W', 'hp', 'horsepower'),
array('yd', '36*in', 'yd', 'yard'),
```
Thank you!

**Comment by aharjula** [comment]
Oh my, weight and mass... We really need a unit-system where one can toggle various units and interpretations. That kind of a system will be a complex thing and most people requiring units will make very odd mistakes with it unless certain things are very obviously marked, e.g. this mass vs. force interpretation issue is something where the default must be clearly understood, for me `lb` is a unit of mass, but I have no idea if my interpretation is correct as I really don't deal with imperial units beyond using Google to auto-convert them when some website uses them, and then wondering if they already had conversion errors in them.

What do we think about this: https://en.wikipedia.org/wiki/Pound_(force) vs. https://en.wikipedia.org/wiki/Pound_(mass) i.e. should that triplet in the above message start with a definition for `lbf` instead of `lb`?

**Comment by dhilsen** [comment]
Thank you for your comment Matti. The unit `lb` if often misunderstood and often incorrectly used as a unit of mass. The `lb` unit is most definitely a unit of force, and used in physics as only a unit of force, not mass. This is always a struggle with introductory physics students in the United States as the `lb` is used ubiquitously to measure an amount of matter, such as in the grocery market. The British unit for mass is the `slug`, which after initial consideration as an addition to STACK, thought it best to let it go.

**Comment by aharjula** [comment]
So basically, the choice here is between supportting market-maths or physics. luckily it is not my decision to make. Have to say that it seems odd to not just use the `lbf` to make things clear if there is any risk of students (or journalists) having the market interpretation.

**Comment by sangwinc** [comment]
Matti,

I hope we don't have to make a "choice" here.  I am mystified why some people still use pounds, but then there are decision made in my country which mystify me just as much!

We will add curie to the core.  David you have defined it as an independent unit.   You don't want it linked to its SI base unit 3.7×1010 s^(−1), (according to https://en.wikipedia.org/wiki/Curie_(unit) )?

We also need to support you with US customary units.  STACK should be inclusive, and you are asking for support for an official national system.  Regardless of my personal views (and is this a moment to encourage you to inch toward metric once more....!) it isn't for me to put my foot down here.

We can't have this in the core units, as it will overload all sorts of things.  I think the corresponding thing to do would be to have 

`stack_unit_US_customary_declare(true);`

That should then load the others.  Is that ok for you David, and will that be workable Matti?

**Comment by sangwinc** [comment]
Ok, I'm forgetting code I've written again David, sorry.  The units lb, hp, yd are already here.
https://github.com/maths/moodle-qtype_stack/blob/master/stack/cas/casstring.units.class.php#L144
I will add in the conversion factors you have requested.

**Comment by dhilsen** [comment]
Thank you Chris for adding these units. Please accept my apology for all the headaches surrounding British Imperial units. We use them early on in a physics course, mainly in terms of converting them to SI units, then never use them again.

With regard to the curie unit, for our purposes we only need it to act as an independent unit. However, others may benefit from having it linked to its SI base unit.

**Comment by aharjula** [comment]
Chris,

As to `stack_unit_US_customary_declare(true);` sure it could be a solution, but the problem is that we need to in any case detect the units in use at the validation phase and the recent comments about not doing single-letter splits for certain combinations would only be solveable by the validation and splitting logic knowing when and which units are active. Basically, the CAS-security needs to be tuned in such a way that it can be told which units are active.

As to Curie I would not try to convert it to the base units `1/s` as there are already others that convert to that very same and detecting the original unit after conversion is quite difficult. Overall, all radiation related questions are likely to require custom unit handling anyway as the units related to dosages and levels of radiation are quite complex anyway.

**Comment by sangwinc** [comment]
Ok, thanks for your comments.  For now I think we are done.
