### ISSUE TITLE
strict syntax:no does not invalidate answers in scientific notation (1.23e2/1.23E2)

### ISSUE THREAD

**Issue by malthefogsporring** [maths/moodle-qtype_stack#608]
The docs (Authoring/Input) say that setting strict syntax to no in an input will invalidate answers written in scientific notation using e/E:

> If set to no, this increases the range of things into which stars might be inserted. In particular when no we assume (...) the student's expression does not contain any scientific notation, so that 3E2 or 3e2 (which Maxima interprets as 300.0) is looked for, and expects `3*E*2` or `3*e*2`.

However, this does not seem to be the case in the current version of STACK. This is important for questions that ask students to write a number in scientific notation. Since there is no way (as far as I know) to distinguish between the numbers 123.0 and 1.23E2 in STACK, the best way to grade these questions is invalidating answers that use e/E and require students write their answer as 1.23*10^2.

Question that demonstrates this issue:
[questions-Tutoring 2020-Strict Syntax Error Example-20200709-1857.zip](https://github.com/maths/moodle-qtype_stack/files/4898614/questions-Tutoring.2020-Strict.Syntax.Error.Example-20200709-1857.zip)

**Comment by sangwinc** [comment]
Thanks for pointing this out.  One of the side effects of the improvements Matti made in the parser is that we now correctly parse floating point numbers, and so don't need to worry about inserting *s.  The downside, if there is one, is that we can no longer use these options to spot the form a student has used to type in a number.  This is a good thing.

In your case you could forbid both "e" and "E" I think?  Not ideal.  We probably need to have more nuanced tests for forms of numbers.

**Comment by sangwinc** [comment]
I've created a branch for #608 and not deleted the strickSyntax option completely, because I'd like to propose that we use the existing strict syntax option to allow teachers to allow/forbid user defined functions.

We already have the filter stack_ast_filter_541_no_unknown_functions (which I think is not used).

We rename "strictSyntax" to be "Forbid user-defined functions".  The current default of "false" is then sensible. Proposed behaviour

1. If "true" then we use 541 to look for user-defined functions, e.g. f(x) or x(t+1).
2. if "false" and insert *s is non-zero then we interpret juxtaposition as multiplication, not function application.  So a(a+1) -> a*(a+1).

This change most closely corresponds to the intention of the previous behaviour, and people have asked to forbid user defined functions for years.  We can now do this (thanks Matti!).  In particular the original intention is that 

* Strict Syntax defines the patterns to look for.
* Insert Stars decides whether to insert stars automatically.

This idea has drifted....

Comments?

**Comment by aharjula** [comment]
Honestly, I have no idea what that strict syntax even means and I am all for removing it. My understanding has been that if it is on then no fixes (inserted stars, fixed spaces) are accepted but may be explained as validation feedback and if it is off then whatever fixes were done including elective fixes like single-char-vars are accepted. 

The current algebraic-input2 view is that one selects which types of fixes are to be done and those insert stars, fix spaces is a corrective parser feature. One then selects if one accepts inserted stars and separately whether fix spaces are accepted, basically, two different groups of accepted fixes the first being the larger and has many options ranging from that function disabling/forbidding (the (441,442,541,542) group) to even splitting floats down at the `e` if need be. There is no strict syntax there if one wants pure Maxima syntax one jsut toggless all the fixes off and says that no corrective-parser fixes are accepted either.

**Comment by malthefogsporring** [comment]
> In your case you could forbid both "e" and "E" I think? Not ideal. We probably need to have more nuanced tests for forms of numbers.

I'm afraid this doesn't work, probably because e/E are not considered variables or functions. But what Matti mentions sounds great, so I will find some temporary solution and wait for algebraic-input2 to complete. Thanks!
