### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by alexmorrisnz** [maths/moodle-qtype_stack#612]
Hi,

We are getting performance issues when generating random variants of questions. I've profiled it and it looks like it might just be the communication with maxima, which I'm assuming there aren't many gains in performance you can get there?

We are running the latest Moodle 3.7, qtype_stack is version 2019090200 release 4.2.2 and maxima 5.41.0

This isn't critical but it slows the development of questions significantly.

To replicate:
• Go to question bank
• Create a STACK question type question
• Give it a name
• In Question variables include the command (which will generate a number between 0 and 99). (Note it's a colon, not an equals sign).
a: rand(100);
• In Question Text, above the [[input:ans1]] [[validation:ans1]] tags, type the question, for example
Type the following number into the answer box: {@a@}
• In Question Note type in
{@a@}
• Scroll down and expand Input: ans1
• In Model answer, enter
a
• Scroll down and expand Potential response tree: prt1
• Under Node 1, in SAns enter
ans1
in Tans enter
a
• Now at the bottom hit Save changes and continue editing.
• Hit Preview. Because there are no deployed variants, this will take quite a while (this is one place where the problem is observed, as it makes the debug->edit cycle very slow)
• At the top of the page, click on Question tests & deployed variants.
• Try to generate 20, this takes an extremely long time.

**Comment by ledship** [comment]
Would upgrading to 4.3 help? Reading the development log says there were major internal changes, any of these performance related?

**Comment by aharjula** [comment]
"Quite a while" >> 0.5s and "exremely long time" >> ~5s I assume.

4.3 is unlikely to make your situation better, it actually adds a separate type of a load to the system, it does provide security and feature updates so do update if you can. It sounds like you have a slow Maxima and you'll need to look at improving its performance. You could also have a slow database but that is less likely unless your operation is truly large. Generally, we do not expect anyone to have underpowered servers but do check that the server is not running out of memory or CPU during the slowness.

You should probably look at [this](https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/CAS/Optimising_Maxima.md), note how Maxima 5.41.0 does not actually describe your situation, nor would the type of the LISP describe it any more as it all depends on the full ecosystem of the machine running things and the libraries it uses as well as the power of the actual machine. Often it is just simpler to try installing additional LISP interpreters and checking if they would act faster and then instructing STACK to use the best one, STACK cannot do that choice for you. Moving the Maxima into a separate machine with MaximaPool may help to off-load the strain and as MaximaPool specialises on amortising the general startup cost of Maxima processes it can be used to lessen the impact of just having a slow Maxima, but it cannot help if one is memory or CPU bound in the server.

The best way of identifying if your slowness is due to Maxima evaluation or database/general performance is to execute the so-called answer-tests-script (the ALL tests version for best results, do try the smaller batches if the ALL tests one does not complete in <5 minutes, on heathy systems <3 minutes is currently expected) on the settings page for the STACK-plugin. One should first clear the cache through the healthcheck-script to ensure that no cache will be used (clearing the cache will obviously be a bad thing for you if your system is so slow to regenerate it). With clear a cache one should expect to average times of <0.25s (got 0.16 just now, and 0.1 on a bit more optimised system) and from the cache the times should be around 0.01s. If the former value is significantly higher your Maxima just does not respond in time and if the latter is significantly larger then your database cache is slow or your machine is slow.

**Comment by aspark21** [comment]
@ledship are you using https://github.com/uni-halle/maximapool-docker which I believe has the optimisations?

**Comment by ledship** [comment]
> "Quite a while" >> 0.5s and "exremely long time" >> ~5s I assume.
We are getting more significant delays than that, generating 20 variants of a question with a couple random numbers can take 5 minutes. 

> You should probably look at [this](https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/CAS/Optimising_Maxima.md)
From what I can tell (I wasn't the one who configured the system) it has been optimised following those instructions already.

> The best way of identifying if your slowness is due to Maxima evaluation or database/general performance is to execute the so-called answer-tests-script
It's taking around 6-7~ minutes to complete the all tests version, I wouldn't expect it to be any kind of database slowness, we are running a certainly overspec'd DB server and we don't have issues anywhere else on the site.

> @ledship are you using https://github.com/uni-halle/maximapool-docker which I believe has the optimisations?
No but we have an upgrade project coming up so I'll put it forward.

**Comment by timhunt** [comment]
If you want to get to the bottom of this, you are going to have to measure it accurately, to see where the problem is. If you can, the best way to do that is tideways, which will show you exactly how long things are taking (https://docs.moodle.org/dev/Profiling_PHP#Tideways_.28replacement_for_XHProf.29). If you can't do that then measuring the time for the back-end to do one CASText evaluation (e.g. by timing CAS chat.). Should be under half a second for the maths processing, probably.
