### ISSUE TITLE
Unused $runtime parameter in input constructor

### ISSUE THREAD

**Issue by NeilStrickland** [maths/moodle-qtype_stack#622]
I am trying to understand the framework for new input types.  I hope that someone can clarify some behaviour which seems wrong to me, although possibly harmless in practice.

In [inputbase.class.php](https://github.com/maths/moodle-qtype_stack/blob/b2919a7f8649e5425e0d42a8f251f8882468894f/stack/input/inputbase.class.php#L128) we see the following:
```
     * @param bool $runtime This decides if we are at runtime (true) or in edit mode.  Can we rely on the value of
     * the teacher's answer as an instantiated variable?
     */
    public function __construct($name, $teacheranswer, $options = null, $parameters = null, $runtime = true) {
```
(and I don't think that any of the classes extending `stack_input` override this constructor).  If I understand correctly, the issue with the `$runtime` parameter is as follows.  For a typical multiple choice question we have something like 
```
ta : [[42,true],[43,false]];
```
in the question variables, and then `ta` as the teacher's answer.  In various contexts we want to call the input constructor without doing the CAS-work necessary to substitute the value `[[42,true],[43,true]]` for `ta`.  However, for the constructor calls `set_parameter()` repeatedly, and `set_parameter()` calls `internal_construct()`, and then the constructor calls `internal_construct()` again.  For things like dropdown questions, the `internal_construct()` method calls `adapt_to_model_answer()`, which generates lots of errors if the value of `ta` has not been substituted.  The call to `adapt_to_model_answer()` is supposed to be blocked if `$runtime` is false.  However, it seems that the constructor is only ever called by `stack_input_factory::make()`, which is only ever called by `qtype_stack->initialise_question_instance()`.  This call omits the `$runtime` parameter, so it defaults to `true`.  Because of this, the method `question_bank::load_question()` ends up generating lots of errors in `adapt_to_model_answer()`.

It is not clear to me whether any of these calls to `adapt_to_model_answer()` from the constructor are actually useful.  If I understand correctly, when the question is actually being used we call `adapt_to_model_answer()` from `qtype_stack_question->initialise_question_from_seed()` via  `qtype_stack_question->adapt_inputs()` instead, and this ensures that the question variables have been processed by Maxima.

Is there something that I am missing here?

**Comment by NeilStrickland** [comment]
Thanks, Chris.  So long as I am understanding this correctly, it should not be a big issue to work around it for the time being.

**Comment by aharjula** [comment]
Well, the input2 system is in testing on the Stateful side and I am pretty certain that it will be less messy for a few years but these things grow into tangled messes. The quick overview of the input2 is this:
 1. Input initialisation and processing are being done in steps, by collecting things to evaluate from the inputs, if any input requires CAS-evaluation to be initialised they all get initialised during the same CAS-call. Likewise, if any input requires CAS-evaluation for validation they all get collected to the same CAS-call.
 2. The whole input validation and validation message processing has been interleaved to the normal question processing. The input initialisation goes into the same CAS-session as the question-variables and question-text rendering, the validation if needed takes its own CAS-evaluation but after that PRTs (logic&rendering) and validation-message rendering happen in a combined CAS-session.
 3. The input2 view is that not all inputs provide CAS-values, most do but it is not required and not all inputs generate validation-messages, again most do but...
 4. All inputs do have options though, and they declare them freely as JSON-schema (which can be used to define the editing interface for authoring tools) and the database stores them as a JSON-object, there is no need to worry about creating new columns in the input-table. There is no reason for an option to not be a list of objects or something that gets CAS-evaluated or references question-variables, could even be CASText, e.g. the MCQ-inputs option set...
 5. Most of the initialisation logic related to inputs and validation-boxes is typically static or something that can be represented as a static block that references question-variables or the teacher's answer. This is why the input2 system provides the inputs means for caching the complex CAS-statements they need to execute for initialisation. For example if an MCQ input needs to render few options with some conditions and shuffle them the logic might be complex and checking it for errors expensive, so we allow that checked version to be cached and used directly in later executions.
 6. Validation-boxes are a new concept externalising the validation-message representation from inputs so that we can modify the representation separately, it also allows multiple inputs to use the same validation-box with custom layout and templates for the placements of the validation-renders of the input value. For example, rendering of an equation system as a system instead of multiple separate validation-boxes with no sensible context.

One could read through the [input2 interfaces](https://github.com/maths/moodle-qtype_stateful/blob/master/stateful/input2/input_interfaces.php) to have a better understanding of how things happen. Looking at how the [MCQ-input](https://github.com/maths/moodle-qtype_stateful/blob/master/stateful/input2/inputs/mcq.input.php) is built for input2 might also be of interest, note how the options are defined there, there is also a `mcq_legacy` that can eat the old form of definitions. Essentially, everything (some Javascript elsewhere) related to input2 is in that single [directory](https://github.com/maths/moodle-qtype_stateful/tree/master/stateful/input2).

However, given the current situation, input2 is not currently progressing at full-steam, it is not coming to STACK in the next few upgrades and as it essentially re-creates all the old inputs its something that will need a mapping of old materials to new options, which is something requiring a major release. So maybe STACK 5 if the testing in Stateful does not expose massive issues.
