### ISSUE TITLE
Insert stars fails with functions

### ISSUE THREAD

**Issue by timlowe** [maths/moodle-qtype_stack#623]
With
•	Strict syntax=No
•	Insert stars assuming single character variable names

the documentation suggests an input of “f(x)” is interpreted as “f*x”.
I’m sure this used to be true, but it seems to be no longer.

When inputting “f(x)” the validation only recognises ‘x’ as a variable, and f is treated as a function.

When the input changed to “f(x+f)” – the inner ‘f’ forces the system to realise it is a variable, the hence expression is interpreted as “f *(x+f)”.

[The actual issue had 'a' and 'b' - but the letter does not matter, so changed to match the documentation]

An extremely minimal question demonstrating this is attached – which has no content other than enabling the validation feedback to be seen with the questions settings as above.

This is possibly a bug due to the new parser? Possibly related to issues #620,  Probably the same as #597?
[Expression interpretation test.xml.zip](https://github.com/maths/moodle-qtype_stack/files/5143388/Expression.interpretation.test.xml.zip)

Best wishes,
Tim

**Comment by shinuito** [comment]
I have also noticed this although I'm not sure how to confirm which version of stack is being used as I'm not an admin.

At present I couldn't see much difference between turning strict syntax 'on' and 'off'. 

> With
• Strict syntax=No
• Insert stars assuming single character variable names

I was looking at this exact combination for multivariate calculus to ease the input of combinations like xyz. Certain factorizations of an answer from partial differentiation have expressions like yz(...) which get interpreted as if z was a function with either strict syntax setting.

**Comment by sangwinc** [comment]
Yes, we need to weed out the whole "strict syntax" option completely, and add in a more subtle and sophisticated mechanism for including rules for validating strings with functions.  Over the years this has become a mess (sorry).  The current design is discussed here:
https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Developer/Syntax_Future.md
(probably better to look at the dev branch: https://github.com/maths/moodle-qtype_stack/blob/dev/doc/en/Developer/Syntax_Future.md )
Since this is all discussed there already ("Insert stars" option) I'll close this issue as a duplicate.  Thanks for raising it.  If you'd like to make more proposals on syntax, please help by discussing the design proposed there.

Chris
