### ISSUE TITLE
Feature request: Question tests

### ISSUE THREAD

**Issue by timlowe** [maths/moodle-qtype_stack#628]
Like #627 this arises from thinking about #623 , but I'm keeping the suggestions separate.

It is impossible to detect problems (for example arising from system changes) with the behaviour of the "insert stars" function, since the question test input must contain stars. (Not least because the input is often a variable storing a Maxima expression).

Would it be possible to have a "remove_stars(expression)" function that takes a Maxima expression (for example, one containing the Teachers Answer) and returns a string without the stars.  Then one could use "remove_stars(Tans)" as the input to a Question Test.  (This assumes the question test input is run through the same input validation/adding stars code as the actual student answer.)
Thanks,
Tim

**Comment by aharjula** [comment]
As a comment to this on the Stateful side, I have prefixes for the test inputs one of them is `RAW:` which uses the remainder as is, obviously, this is not enough as it would not allow Maxima values and would only work with static strings. But no one says there could not be a prefix that would do more, etc. fetch a Maxima-generated string and use that as the input value. All test input values in Stateful go though the full input validation of the matching input. One can see `RAW:` in action in the Stateful test-questions that check for units answer tests, where seeing for example `RAW:1.230 kg` is not that uncommon.

As to `remove_stars`, I doubt it would actually work for all inputs. The problem is that just removing stars is not necessarily enough as the stars might need to be replaced with spaces and it might be that only some of the stars are such that they are reasonably implicit, e.g. `x*4*2*y` might have some interesting interpretations. Also any function going there would need to return a single value and in this case there might be many possible removals.

**Comment by sangwinc** [comment]
@aharjula do you have code available which deals with the `RAW:` prefix?  If so, I'd like to get this into STACK as it's a useful suggestion.

**Comment by aharjula** [comment]
Chris, there is absolutely no way to map the Stateful multi-phase parallel test case handling to STACK, it would need to be completely rewritten. You will simply need to check if the thing you see starts with the prefix and handle it differently in that case. This is how Stateful does it, it does not send those to CAS to be generated it pulls them out of the input generation session to be joined back at about line 148

https://github.com/maths/moodle-qtype_stateful/blob/08342759944e4738debb3322af14fa48248e6cf2/stateful/handling/testing.php#L79-L83

In Stateful, we basically do the test as follows:
 1. We are in a scene in a particular state and ask the CAS to check if there are any active tests for that state and, if so, generate input values for them. Some of those values are overridden by the `RAW:`-prefix. This is session 1.
 2. Then we do the whole input validation for all those (active) test-case inputs leading to processed inputs. All CAS validation related to this happens in session 2.
 3. The third session sends all test cases that still have valid inputs to the CAS and checks if they end up with the same PRT exits. It does all cases in the same session, resetting the (question/scene/feedback-variables) state between cases.

**Comment by sangwinc** [comment]
Ok!  Thanks for confirming.

**Comment by sangwinc** [comment]
I'm sorry, but as @aharjula points out the "remove_stars" function proposed is ill-defined and will lead to other problems.  I hope the "Raw:..." feature added helps.  If you have another, more specific proposal, then please add it as a new issue.

**Comment by aharjula** [comment]
@sangwinc as an idea for those "remove_stars" situations, why not have a prefix that leads to the remainder being interpreted as CASText as opposed to raw value like with `RAW:`, then you could have something like `CT:{#a#}x - {#b#}(x)` which would render to whatever one wants and at the same time allow values to be tied to question variables. In most cases, people would only use `{#...#}`-injections with that, but who knows, someone might throw in some `[[if]]`-blocks or even loops. So supporting full CASText would make sense. Naturally, all STACK-JS-related things would just not work as we could not provide the larger environment for them.

**Comment by aharjula** [comment]
Basically, at here:

https://github.com/maths/moodle-qtype_stack/commit/6b141fe196d84acaf70a9a944a7ed84844057203#diff-2f3931ce6d5ae00df6611866d34d24444012e6d3106ded7f507b5ec0173c2a98R187

You would instead create a `castext2_evaluatable` and about here:

https://github.com/maths/moodle-qtype_stack/commit/6b141fe196d84acaf70a9a944a7ed84844057203#diff-2f3931ce6d5ae00df6611866d34d24444012e6d3106ded7f507b5ec0173c2a98R212

You would then note that if it is such a thing you would get the rendered value instead of the dispvalue...
