### ISSUE TITLE
Uppercase Phi as function

### ISSUE THREAD

**Issue by hayyanhelal** [maths/moodle-qtype_stack#631]
Why is it not allowed to use the uppercase Phi Greek letter as a function in STACK? The validation shows that one should use lowercase phi instead.

**Comment by sangwinc** [comment]
This is related to issue #625?  Let's put all the related issues in one place.

**Comment by sangwinc** [comment]
Ok, the answer to this is as follows.

phi is known by STACK to be a function.  Phi is not a Maxima function. If students type in "Phi(n)" then the parser tries to be helpful and suggests case sensitivity.  This was introduced because so many students typed in things like "Sin(x)" and not "sin(x)".  I can see a good case for not doing this check in the case of Phi(x) though.
