### ISSUE TITLE
Assessment: 

### ISSUE THREAD

**Issue by fmantoniali** [maths/moodle-qtype_stack#653]
The function call **numerical_not_alg_equiv(p2/p1,p2/p1)** returns a **true** value.  Apparently the problem relates to p1 and p2 being the parameters in the function definition (assessment.mac). A quick, but inelegant workaround is changing the name of parameters p1 and p2 into something possibly more infrequent in maxima expressions, such as parameter1 and parameter2.

**Comment by shinuito** [comment]
It's a fairly confusing issue. I'm playing around with it in a Maxima terminal as well, to see if I can understand it.

Some other examples are 
- `numerical_not_alg_equiv(2,p1)` and `numerical_not_alg_equiv(p2,2)` both returning `false`, 
- `numerical_not_alg_equiv(2,x)` and `numerical_not_alg_equiv(x,2)` both return `true`,
- `numerical_not_alg_equiv(x,p1)` and `numerical_not_alg_equiv(p2,x)` both returning `false`.

So it does seem to be something strange about using the input variables names and the process in the line
https://github.com/maths/moodle-qtype_stack/blob/c252205afc925eba2d6d45dc11cba02b2e7044f4/stack/maxima/assessment.mac#L778

It seems when calling say `numerical_not_alg_equiv(x,p1)` it makes the list `pvars:[x,p1]` and the list `lv:[x=2,p1=3]` but then `ev(p1-p2, lv, simp)` is `0` presumably since `p1` is recognised as the `p1=3` from lv, while `p2:p1` in the function call.

It seems like `ev(p1-p2, lv, simp)` will first try to sub in directly for `p1` and `p2` if they appear in the equations of `lv`, next evaluate them from the function input and then use the equations of lv on that. For example `numerical_not_alg_equiv(p2,p1)` returns `true`, but on further inspection `ev(p1-p2, lv, simp)` returns `1` using the equations `[p2=2,p1=3]` and 1=3-2. Whereas if it evaluated the function arguments first, then it should replace `p1` by `p2` and vice versa get `p2-p1=2-3=-1` which it doesn't. 

I believe this same idea explains the OP issue. For `numerical_not_alg_equiv(p1/p2,p1/p2)` you get `pvars:[p1,p2]` and `lv:[p1=2,p2=3]` but `ev(p1-p2, lv, simp)` is `2-3=-1` which you get by subbing in directly as opposed to first replacing `p1->p1/p2` and `p2->p1/p2` which should be `2/3-2/3=0` which it isn't.

Maybe a shorter sillier example would be defining a function `myfunc(x,y):=ev(x-y,[x=2,y=3],simp)$` which would always (it seems anyway) return `-1` no matter the inputs of `x` and `y`.

I'm still testing with STACK version: 2020070100, Maxima version: [5,41,0] and STACK version: 2020081700,
Maxima version: [5,42,2].

**Comment by shinuito** [comment]
I think there are some differences with `ev()` and `subst()` that could be useful (at least on Maxima version: [5,42,2]). It's possible that replacing `ev(p1-p2, lv, simp)`  by `subst(lv,p1-p2)` in https://github.com/maths/moodle-qtype_stack/blob/c252205afc925eba2d6d45dc11cba02b2e7044f4/stack/maxima/assessment.mac#L778
behaves a bit better in that numerical_not_alg_equiv(x,p1) and numerical_not_alg_equiv(p2,x) both return 'true' and a lot of the other cases advance further in the code.

Then I think one needs to go and change
https://github.com/maths/moodle-qtype_stack/blob/c252205afc925eba2d6d45dc11cba02b2e7044f4/stack/maxima/assessment.mac#L789
to ` p1:errcatch(subst(lv,p1)),`
and https://github.com/maths/moodle-qtype_stack/blob/c252205afc925eba2d6d45dc11cba02b2e7044f4/stack/maxima/assessment.mac#L791
to ` p2:errcatch(subst(lv,p2)),`.

Then after these three changes it seems like the following happens:
- `numerical_not_alg_equiv(p2/p1,p2/p1)` returns `false`.
- `numerical_not_alg_equiv(2,p1)` and `numerical_not_alg_equiv(p2,2)` both returning `true`.
- `numerical_not_alg_equiv(x,p1)` and `numerical_not_alg_equiv(p2,x)` both returning `true`.

I think the definition of `sz` also needs to be edited from
https://github.com/maths/moodle-qtype_stack/blob/c252205afc925eba2d6d45dc11cba02b2e7044f4/stack/maxima/assessment.mac#L794
to `sz:errcatch(ev(abs(float(first(p1)-first(p2))/max(min(abs(first(p1)),abs(first(p2))),1)), simp)),`

I obviously don't want to push this change since I don't yet understand if anything breaks without the ev(...,simp) or ev(...,numer_pbranch:true).

I think though it's not as simple as just adding in an extra `ev(...,simp)` enclosing around the `subst` call. However I think just redefining `pval, p1 and p2` on separate lines using eval after using `subst` does seem to work ok.

So my suggester changes (at least for Maxima 5.42.2) are change `pval:errcatch(ev(p1-p2, lv, simp)), ` to
>pval:errcatch(subst(lv,p1-p2)),
pval:ev(pval,simp),
and change `p1:errcatch(ev(float(p1), lv, numer_pbranch:true, simp)),` to
>p1:errcatch(subst(lv,p1)),
p1:ev(p1,numer_pbranch:true,simp),
and change `p2:errcatch(ev(float(p2), lv, numer_pbranch:true, simp)),` to
>p2:errcatch(subst(lv,p2)),
p2:ev(p2,numer_pbranch:true,simp),

Hopefully this is helpful to @sangwinc and others and not just wasting time and space :)

**Comment by shinuito** [comment]
I'd like to suggest `subst()` instead of `ev()` as they behave differently and I think produce the intended behaviour

If one changed `pval:errcatch(ev(p1-p2, lv, simp)), ` to
>pval:subst(lv,p1-p2),
pval:ev(pval,simp),

changed `p1:errcatch(ev(float(p1), lv, numer_pbranch:true, simp)),` to
>p1:subst(lv,p1),
p1:ev(p1,numer_pbranch:true,simp),

changed `p2:errcatch(ev(float(p2), lv, numer_pbranch:true, simp)),` to
>p2:subst(lv,p2),
p2:ev(p2,numer_pbranch:true,simp),

one would get the results that

- `numerical_not_alg_equiv(2,p1)` and `numerical_not_alg_equiv(p2,2)` both returning `true`.
- `numerical_not_alg_equiv(x,p1)` and `numerical_not_alg_equiv(p2,x)` both returning `true`.
- `numerical_not_alg_equiv(p2/p1,p2/p1)` returns `false`.

The issue I'm having is how to work back in the `errcatch` functions to catch say `1/(x-2)` when `x=2`. It only happens in the `ev` step for `simp:false` but the `subst` step for `simp:true`. Adding in two `errcatch` in each step either nests the output in square brackets `[[ ]]` when `simp:true` and there's a division by error being caught, but then with simp:false there isn't any nesting of brackets, just returning `[ ]` so I'm not exactly sure how to work back in the `errcatch` functions for both cases.

Apologies and hope this is useful, and not just wasting time.

**Comment by sangwinc** [comment]
Thank you very much indeed for such a helpful report, for the test cases and the suggested fix.
