### ISSUE TITLE
Error reported: abnormal root count

### ISSUE THREAD

**Issue by melanietreitinger** [maths/moodle-qtype_stack#655]
When I restore a question of an arbitrary question type (not STACK!), I get the following error:
`The PRT named "prt1" is malformed in question id <id> and does not have a single root, (Question name "<name>").  Error reported: abnormal root count: 0(<>1)`

This is due to entries in the table `qtype_stack_prts` which have the value "-1" in the field `firstnodename` - obviously created by the `function process_qtype_stack_prt `in line 142 in `restore_qtype_stack_plugin.class.php`.
https://github.com/maths/moodle-qtype_stack/blob/master/backup/moodle2/restore_qtype_stack_plugin.class.php

The line 142 says `$data->firstnodename = -1`; // This will be fixed later. 
So I guess this is a bug?

I am using Moodle 3.7.4 and Stack 4.2.2

**Comment by aharjula** [comment]
Few questions:
Does STACK otherwise work for you?
Which (export/backup) file-format are you restoring and by using what restore feature?
The error appears during the restore/import process? Not after it?
Can you describe how and from where, you installed STACK and is there a possibility that there are STACK scripts in wrong directories, i.e. not under `/question/type/stack/`?
Have you imported STACK questions created outside the normal editing tools or otherwise built questions manually through editing text-files? Basically, is there a chance that a malformed import could have created a nodeless PRT into the database? 
Maybe the STACK-API has been incolved at some point, probably not for 4.2.2?
Is ILIAS involved in this situation? Basically, could some questions have been created in something else than Moodle/STACK setup and been imported from there?

The `// This will be fixed later.` comment is there just to point out that at that point of the restoration logic we need to have a placeholder identifier for the reference to the root node and if the imported content does not define it the value will be filled in the logic starting on line 279 of that file, i.e. "fixed later".

What is odd about your report is that the logic related to restoring STACK questions would trigger for some other question types, for that to happen quite a lot has to happen, including the names functions and classes in that file you referenced changing. For it to trigger at all there has to be atleast one STACK question in the thing that is being restored. Could there be some question type that is built on top of STACK and inherits STACKs logic, in play here?

Note that not all question export formats can carry STACK questions as STACK does not provide export logic for all of them, it might be that you have managed to export for example a question bank which also includes STACK questions in one of those other formats and things fail not at the arbitrary other question but at the STACK question itself. Course backups should be safe from this as the format is something supported by STACK. 

@sangwinc is the import logic for STACK currently able to deal with non numeric node names? Those `+1 -1` casts do not look healthy and I am pretty sure that YAML-authoring and other formats might soon see nodes with more interesting names which would cause trouble if the format forgets to define the root node and we need to drop into [this logic.](https://github.com/maths/moodle-qtype_stack/blob/master/backup/moodle2/restore_qtype_stack_plugin.class.php#L279-L339) What worries me is the situation where one manages to get named nodes in and then exports them in Moodle-XML-format where we apparently do not export the firstnodename...

**Comment by melanietreitinger** [comment]
Hi Matti,

thanks a lot for your detailed answer. Stack generally works. I use the mbz format for export/import.

Unfortunately I really can't say anything about the possible history (creation, restoration) of the corrupted stack datasets, that happend before my time.

Your explanations about "This will be fixed later" are very helpful, thanks. So it is not a bug in the stack plugin :-)

What really is odd - as you mentioned - is that I definitly don't have a single stack question in this course and yet the function in `question/type/stack/backup/moodle2/restore_qtype_stack_plugin.class.php` is triggered. This also happend with a single question of the multichoice type!

I hope I will be able to do more testing next week.
Thanks a lot for your support.
