### ISSUE TITLE
Feature request: Testing for spurious variables

### ISSUE THREAD

**Issue by mkraska** [maths/moodle-qtype_stack#662]
I increasingly find myself testing for not-given variables in student's responses. I'd like to reject this already on input level but currently the allowed words just add on top of what is allowed anyways. 

Main use is to reject typos or poor question reading of students, e.g. typing r for radius if d (diameter) is given.

Currently I do this: 
feedback variables:

    given: {a,b,c}
    spurious: setdifference( setify( listofvars( ans1 ) ),given)

Test: 
    
    AlgEquiv( emptyp(spurious),  true)

false feedback:

    Variables {@spurious@} not given.

How about having "given: {...}" as an extra option  to algebraic input?

**Comment by sangwinc** [comment]
Yes, this is a very sensible suggestion.  @aharjula, is this something you have already done in "input2"?  I don't want to work at cross purposes here.

**Comment by aharjula** [comment]
Chris,
Have not done it yet but it did get to the list based on this issue. Basically, just another option belonging to the same-type and lowest-terms class of validation that happens at the CAS-level, though it is doable at AST-level as well it is still simpler to handle at the CAS side as then we can evaluate the tans with all the possible internal structure it may have. The total size of this feature is about ~20 lines in input2:

 1. Four lines of language strings "Missing variables", "Extra variables" and a label and description for the option.
 2. Six lines of option schema definition for the algebraic input-type and some lines to remove that option from some of the input-types inheriting the basic logic of algebraic inputs.
 3. Ten lines to send that `setdifference` to CAS (if the option is active) and to interpret the result for validation-messages. Maybe few extra lines to ensure a nice presentation of the listing of variables (no need for the set-wrapping here). Possibly some CAS code to turn the variable list into an error message at the CAS side.

What comes to mind, is that this option should have four operation modes. Not active, react to extra variables only, react to missing variables only and reaction to both. Also if the question is in units mode the comparison should probably have strict units mode requiring specific units to be used, and a more lenient mode to allow conversions, bringing the total to seven modes. Though, I would assume we are not providing units-mode support for the first iteration. In any case, not a boolean option if these modes are ever to be an option. With all these options the schema definition will grow a bit and it becomes even more attractive to generate any messages at the CAS-side so that we do not need to examine the mode parameter at the input-type side.

It will surely happen, and if I forget to add it to input2 then just remind me and it should not take long to do. Not doing it just now as I have a feeling that I'll refactor a quite large chunk of input2 soon...

**Comment by aharjula** [comment]
Basically, would need something like this on the CAS side, note CASText2 messages:
```
spurious_or_missing_vars(%_tans,%_sans,%_mode) := block([%_tansvar,%_sansvar,%_extras,%_missing,simp],
 simp: true, /* Extract vars with simp:true does mean that "x/x+y" -> [y] */
 %_sansvar: setify(listofvars(%_sans)),
 %_tansvar: setify(listofvars(%_tans)),
 %_extras: setdifference(%_sansvar, %_tansvar),
 %_missing: setdifference(%_tansvar, %_sansvar),
 if mode = "off" then return(false), /* This will never activate. */
 if length(%_extras) > 0 and (%_mode = "spurious" or (%_mode = "spurious_and_missing" and length(%_missing) = 0))
  then return(["%root",["%commonstring", "validation_spurious_vars", stack_disp_comma_separate(listify(%_extras))]]),
 if length(%_missing) > 0 and (%_mode = "missing" or (%_mode = "spurious_and_missing" and length(%_extras) = 0))
  then return(["%root",["%commonstring", "validation_missing_vars", stack_disp_comma_separate(listify(%_missing))]]),
 if %_mode = "spurious_and_missing" and length(%_missing) > 0 and length(%_extras) > 0 
  then return(["%root",["%commonstring", "validation_missing_and_spurious_vars", stack_disp_comma_separate(listify(%_missing)), stack_disp_comma_separate(listify(%_extras))]]),
 false /* The default return value if nothing is wrong. */
)$
```
Could benefit form a `stack_disp_comma_separate` returning a LaTeX representation.

Currently, STACK has all the features Stateful needs in the Maxima-libraries so starting to expect this would break that. Maybe this could be added in advance?

**Comment by mkraska** [comment]
> What comes to mind, is that this option should have four operation modes. Not active, react to extra variables only, react to missing variables only and reaction to both. Also if the question is in units mode the comparison should probably have strict units mode requiring specific units to be used, and a more lenient mode to allow conversions, bringing the total to seven modes. Though, I would assume we are not providing units-mode support for the first iteration. In any case, not a boolean option if these modes are ever to be an option. With all these options the schema definition will grow a bit and it becomes even more attractive to generate any messages at the CAS-side so that we do not need to examine the mode parameter at the input-type side.

In my use cases there will probably never be parallel usage of units and symbols for quantities (variables) on input level (but it frequently happens on question level, when first asking for a formula and then for a numeric result).

An exception would be asking for a formula on how to establish the numeric value of a quantity for a particular unit. But that is very special.

**Comment by mkraska** [comment]
I played around a bit with the function proposed by Matti.

Basically I copied the function to the question variables and called it in the response variables like this:

`[res, [comment, vars]]: spurious_or_missing_vars(L_AC, S_L_AC,"missing");`

In the response tree entry I do this (in the false branch of an algeqiv test with S_xx and xx):

`{@comment@}\({@vars@}\)`

This displays the comment and the list of variables for option "missing" and "spurious" in case something is found.
If nothing is found, I get both comment and vars set to false, because the function's signature changes depending on the result.

As I don't want to do case selection inside the response variables to generate the appropriate strings, I need to return something like ["%root", ["",""] ] as the default value.

I don't understand how to How is the original function above being used efficiently?  Is it a question test already? How would I access strings generated by the question test for use in the response? Or would any response being auto-generated by the question text?

**Comment by aharjula** [comment]
The above one was just something written for this issue, I don't think it exists anywhere else. It also included so-called CASText2 in the form of those `["%root",...]` lists and it is not a feature that STACK supports currently.
You can simply replace the `false` there with a return statement or any other value you want as the default, in Maxima that `block()` will by default return the last argument if no return statements are present.

**Comment by mkraska** [comment]
Based on the proposal by Matti I designed a feedback function, which requires the following steps to provide the additional feedback in an existing PRT.

- copy the function definition to question variables 
- add a function call in the top level false branch of the PRT

[https://github.com/mkraska/meclib/wiki/fb_vars](https://github.com/mkraska/meclib/wiki/fb_vars)
