### ISSUE TITLE
Parser error on valid input causes timeout and invalid input message

### ISSUE THREAD

**Issue by leo-butler** [maths/moodle-qtype_stack#664]
With 

moodle v3.9.3+ (current weekly release)
stack v4.3.8

both from their git repositories.

I am encountering errors like the following (attached).
[stack-bug-2020-12-09.pdf](https://github.com/maths/moodle-qtype_stack/files/5668739/stack-bug-2020-12-09.pdf)

Oddly, the number of parentheses and the number of variables both seem to matter (hence the advice to students). It seems like the php pre-processor/parser is mangling the expressions, because maxima ends up hanging (reported [here](https://moodle.org/mod/forum/discuss.php?d=414791)).

**Comment by aharjula** [comment]
In the Moodle forums thread, you say that it mangles statements are you saying that it modifies them in some form if so can you show what turns to what?

Given that the input `e^(-5*t*(((2*n+1)*pi)/(2*L))^2)` seems to go through every algebraic-input field I tested it against and if it had any parsing issues the errors would be very different as it would not get the chance to timeout due to syntax/parse errors never being set to Maxima, we have something odd here. It would be very beneficial to know what else happens in the question especially in the question-variables and what are the settings of the input and if there might be something else affecting the validation logic there.

![ummm](https://user-images.githubusercontent.com/980957/101695313-0ee2ce00-3a7d-11eb-8231-a590bab37f00.png)


That is not a parse error, it seems to have trouble executing the CAS-side validation steps that focus on identifying the variables used and rendering the representation of the answer and something related to that seems to timeout. Again given that input it itself should not lead to that so we really should look at the question as a whole.

Wild guess, do you happen to have any interesting `texput` rules? Though if the situation was the same before you updated to 4.3.8 then those were probably not causing this.

**Comment by sangwinc** [comment]
I agree with Matti here and can't reproduce this bug. Please email me your question and I'll have a closer look at the actual issue.
