### ISSUE TITLE
solve equations question does not work

### ISSUE THREAD

**Issue by MinecraftPlaye** [maths/moodle-qtype_stack#667]
Working my way through the following [documentation](https://docs.stack-assessment.org/en/CAS/Equations/), I've got some problems:

1. The fourth code example `setify(append(first(ta)+1, rest(ta))` is missing a closing bracket.
2. An empty answer `{}` is always accepted as the correct answer, even if it is not correct.
3. Inputing an answer which where solutions are missing or where the student has put in too many solutions results in the following error: `append: operators of arguments must all be the same.`

![image](https://user-images.githubusercontent.com/9168045/102882570-d5cc3580-444e-11eb-8d4e-b6215ed6dfbb.png)

![image](https://user-images.githubusercontent.com/9168045/102882617-ec728c80-444e-11eb-834e-e2b2cc8a5d94.png)

![image](https://user-images.githubusercontent.com/9168045/102882652-fbf1d580-444e-11eb-9007-a009237f3c82.png)

**Comment by sangwinc** [comment]
Many thanks indeed for raising this.  I think the line `setify(append(first(ta)+1, rest(ta))` should not be there at all.  It probably got pasted into a file by mistake at some point. Sorry about that, and any confusion it caused.  I think this is responsible for your 1 & 3.  Issue 2 needs another approach, since this example just checks all things entered are actually solutions, of course the empty set will pass that test!  (So, you need another test for your purpose....)   I've reviewed the whole page, and I hope this is an improvement.
