### ISSUE TITLE
Again about #542 (matrix+string: something wrong)

### ISSUE THREAD

**Issue by impemic** [maths/moodle-qtype_stack#669]
Sorry, I can't reproduce the error with a simpler question. I have a question with 10 answers: answers 1->4 and 6->9 are numbers, answers 5 and 10 are strings. As I had reported last year, by answering the first questions and clicking CHECK, I get error on the string answers, even though I didn't answer yet.
You find the XML Moodle question here:
https://www.sugarsync.com/pf/D7169623_09667745_6652137
![image](https://user-images.githubusercontent.com/56223576/103140301-2a88de00-46e5-11eb-9d85-2aed1ba175ed.png)

**Comment by sangwinc** [comment]
This is an edge case in the "string" input type (which I have to confess I basically don't use in my own questions, sorry...).  If you use a string input and the student's answer is empty, then Maxima gets "".  So, currently there is no way to reject a blank input as "blank" as this is always the valid empty string "".  Hence, your PRTs fire.

I consider this is a bug, since we have an "allowempty" option already.

**Comment by sangwinc** [comment]
Thanks for reporting this.

**Comment by impemic** [comment]
Thanks.

Anyway, for your info, in order to prevent the error, it's enough to 
write "?" in the "Sintax hint" field.

Michele

Il 26/12/2020 12:44, Chris Sangwin ha scritto:

**Comment by sangwinc** [comment]
Argh, yes, good temporary fix!
