### ISSUE TITLE
Feature request: Common variables for multiple questions

### ISSUE THREAD

**Issue by mikkovasti** [maths/moodle-qtype_stack#681]
Greetings,

I would like to request a feature to separate common variables for multiple questions and variables specific for that particular questions.

Use case:

We are using stack in exams where students are calculating short circuit currents in radial network and investigating relay settings etc. Thus the solution work flow is something of following:

1. Calculate impedances at required points.
2. Calculate fault currents at required points.
3. Calculate maximum load currents and define current transformer primary values
4. Define overcorrect relay settings

For example if we have line A - B - C. In part 1 student will calculate impedance until point B. Then in next question until point C. For the fault currents we need the impedance values. For relay settings we require fault currents and current transformer primary values and maximum load currents. This results in same calculations done multiple times. How to eliminate unnecessary calculations:

1. Make common calculations and necessary data sharing between questions
2. Make separate question specific variables. Some data does not need to be carried through all calculations... e.g. private variables

The other approach is to merge all questions into one huge question and hide all complexity behind solution tree, which will blow up in size. Since now one has to check if the future answers would be correct using wrong values that student has given previously. E.g. trying to prevent cascading of faults. In the model that I suggest we can give them correct answer, which they can use to proceed further in solving the problem.

This feature request will replicate functionality that current Moodle calculated question already has.

**Comment by aharjula** [comment]
Well, I do see what you want (not #474 style things but something else) but I have to say that saving the cost of evaluating something multiple times is unlikely to be a significant benefit compared to the cost of managing materials as interdependent sets. If I am not entirely mistaken the calculations you are talking about are "just" matrix inversions and not that big matrices anyway and do get nicely cached if used with deployed seeds. I would not worry about such costs and if your STACK is slow it is unlikely to be due to this unless you are doing something truly expensive in those calculations.

Overall, we are trying to make STACK questions as self-contained as possible and having something outside the question itself would mean that we would need to coordinate the evaluation of that outside content and splice it into the evaluation contexts of the questions. This would not be cheap as it would require various validation steps on the way and it would also present complex limitations on what can be shared, it would need to be "serialisable", which is something we have been trying to lift as a restriction.

I trust you already know of the setting between question-variables and question-text that allows you to sync the randomisation seed of questions in the same quiz, and use it to share the values between the questions that relate to the same setup.

As to building a huge question merging all, you should probably seek information about STACK with State and Stateful, or the adaptive flow control extension, over that side you can indeed progress in the question step by step and reveal more as the student gives answers and "propagation of errors" is a thing that is being thought of. Though I fear that AFC would lead to large PRTs as you feared, Stateful would probably allow you to structure things in a more natural way and does indeed have shard code at above the sub-question (scene) level.

**Comment by aharjula** [comment]
The common-variable evaluation will not help and will not be explored, merging values from multiple scopes would add expensive tasks to the processing. My opinion is that this would only benefit an edge case that is vanishingly small at the expense of normal use and complication of the system infrastructure.

Side note the requester says they have ~60 questions in a quiz that have common values, obviously calculating those values ~60 times is probably slower than just once and then merging them back to the questions but the dominant slowness here is the sequential evaluation of questions in the single-threaded evaluation of the quiz logic. For now, the recommendation is to merge questions or split the quiz to parts if possible. [Note that questions can have multiple separately scored parts, that is why we can have multiple PRTs in a single question.](https://docs.stack-assessment.org/en/Authoring/Authoring_quick_start_6/)
