### ISSUE TITLE
Feature request: Means for inclusion of external code.

### ISSUE THREAD

**Issue by mkraska** [maths/moodle-qtype_stack#691]
The request is to allow linking to external urls (e.g. github repositories) on question level both in the question text and in the question variables.

In both cases, a text block-alike syntax could work:

- in the question variables:  `[[Library: url]] `.
The url would provide a .m or wxm file with definitions of functions and variables or whatever Maxima stuff.
- in the question text: `[[URL: xxx]]` This wpuld expand into the text provided at the url. 

It would be great to have some global STACK options (perhaps on course level) for definition of the links. That would allow fast switch of all the questions to different versions of the library stuff without having to touch each question individually.

Background: Currently I develop a means of defining dynamic (in the sense of variable driven, randomizable) images for questions of Engineering Mechanics based on JSXGraph. 

The idea is to completely drive the image with a Maxima variable containing a lists of object definitions, without the user even having to care about JSXGraph. The corresponding library is approx 500 lines with the to do list halfway down. 

On the left you see the content of the Maxima list of objects, on the right you see the stuff generated by these objects. Ignore the UI buttons, they are generated separately.

![image](https://user-images.githubusercontent.com/12987918/108258481-5a41e880-7160-11eb-96b8-5f0d0504b422.png)

What you gain: 

- less complex editing (no need for javascript)
- set of objects tailored to the particular subject with consistent and configurable appearance (by text block parameters or maxima variables) throughout entire sets of moodle courses
- intermediate step towards an interactive model editing tool e.g. for e-assessment of free body diagrams created by students based on given systems.
 
Evaluation of such interactively generated content is where the need for external maxima sourcing comes in.

For now I develop the objects on jsfiddle and transfer the contents to a sample text block.
Then  I copy this into the question text. But you imagine what a pain it is to test new versions of the library with even just a few questions. 

In case of interest I am ready to share the library. Yet as I said: It is no fun if you can't link to it from within the questions.

**Comment by aharjula** [comment]
The dev-branch has received a feature that might make this feasible soonish. It now compiles the question-vars into a single statement that gets cached (on question level, not at attempt or variant) so that it does not need to be re-validated on each run. It would not be impossible that during that compiling we would bring in content from elsewhere.

I am not saying that we would start with full GIT-logic or include system-level management of URLs and aliases for them, but I would not be too surprised if this would be the year when you could write e.g. `ext_lib("https://whatever/my.mac");` into the question-vars and have the text content from that address included into the compilation. It would stay there and not update as it would be expensive to keep checking for changes, but one could clear some caches to force everything to be reloaded during the next init of the question. The compilation happens only if no compiled version is in the cache and basically happens only during the first time the question is used after an upgrade.

CASText is going through similar upgrades, though it has not yet reached the dev-branch. CASText2 will provide similar functionality, i.e. it gets compiled to a cached object, so there is no reason why it could not inline something during compile time. For it there could be something like `[[ext_fragment src="https://whatever/my.txt"/]]`. That same branch is finally working on compiling PRTs so it would at the same time allow such inclusion to feedback-vars and the feedback-texts.

This has been a long-standing item on the wish-list (#474 and #306) and many things have been rearranged under the hood to open up the possibility to have this. We are getting there and while your exact syntax suggestions will not work for the parser logic we want to use, the current ideas do match quite well, the bit that is still open is the dealing with this on the system-level and handling the fact that not all users have access to the full settings of STACK or can be trusted to make system-wide modifications. So how details shared between questions would be managed (talking about using aliases for the URLs and changing their targets, or search-replacing URLs over materials) and how to deal with versioning and all that, is still an open issue and I for one would rather first see some way of library handling to be possible at the question level before we get to the level of sets of questions.

Anyway, the lib looks great and I do believe that we can get you that newer JSXGraph as well, it just requires re-packaging the scripts and I am never quite sure if I did it correctly. I'll try to make a branch with it, maybe you could test it out, I'll let you know in the other issue...

**Comment by mkraska** [comment]
Would testing a branch mean having to run my own moodle instance? Or is that something I might ask our admin to install on a central non-production moodle instance?

**Comment by aharjula** [comment]
I would not recommend testing on production systems and admins tend to dislike installing non-release versions. With Moodle reverting to an earlier version is not simple so should the testing bring up something unexpected (which is why we want to test things) you might have trouble returning the whole Moodle into a consistent state.

Given the complexity of the changes currently happening in various branches, I would not recommend testing them anywhere but on separate test Moodles, unless one is the developer of those changes and can fix things on the run, which really is not fun to do. So if you, for example, want to see how much faster your long question-vars scripts run on the dev-branches compiling/caching logic you really should have a separate install for that.

With JSXGraph things are somewhat simpler as one can simply replace the scripts and clear Moodles JavaScript caches, but that is still something not recommended on production systems as it might affect other users.

**Comment by sangwinc** [comment]
This is now fixed with a combination of the include blocks
https://docs.stack-assessment.org/en/Authoring/Question_blocks/Static_blocks/#include-block
and including maxima libraries with `stack_include`
https://docs.stack-assessment.org/en/Authoring/Inclusions/#inclusions-within-cas-logic
