### ISSUE TITLE
Multiplying with a constant in an equation

### ISSUE THREAD

**Issue by tkokkone** [maths/moodle-qtype_stack#692]
Hi everyone,

This may be rather my lacking experience of using STACK than an issue in the system, but I would still much appreciate if I could receive help - or be directed to another forum.

I would like my students to write a very simple mass balance equation. In steady state, when there is no change in storage, the fluxes entering and leaving a control volume should be equal, i.e,

q_in = q_out

Alternatviely, a student might (correctly) use the face area of the control volume (A), and express the same with discharges instead of fluxes. This would read:

A*q_in = A*q_out

Now STACK (test: algebraic equivalence) does not accept the latter equation if the first one is given as Teacher's answer. Clearly A is not considered as a constant that can be simplified out. But inserting a number instead of A, e.g.

2*q_in = 2*q_out

is accepted. Now I wonder if there is a way to instruct STACK to accpet both 

q_in = q_out 

and 

A*q_in = A*q_out

as a correct answer? For example, one could replace the A with a number (2) before evaluating the student response. I tried to achieve this by writing in the corresponding SAns field:

ratsubst("2","A",ans1)

Probably I missed the syntax. Maybe there is a better way of fixing this?

Any help is appreciated - thanks!

Teemu

**Comment by aharjula** [comment]
I guess you are working with PRTs with only one node in them. The typical way to work if you have only a small number of alternative forms of correct answers is to add nodes to the PRT to first test for one and if not test another. This is also something that one does when one wants to give feedback about specific errors.

Note that when comparing against multiple different targets one should think if they want to silence (using the quiet option in the node) most of the feedback from the tests. Otherwise, the students may get canned feedback about how their answer does not match some specific error. It is much better to give your own feedback in such cases. Also, remember to check how you score those cases...

Naturally, the other way that may better suit your use case is to preprocess the answer in the feedback-variables field. Your attempt to do so in the SAns-field probably did not work due to the simplification steps not being done for that specific field, so use the feedback-variables area to do more complex modifications, place the result into some variable and reverence that variable in the SAns-field, Here are two different syntax options for doing so (as demonstrated in Maxima), note that you may not store the modified form into the answer itself as it is read-only:
```
simp:false; /* Always assume that simplification is off when working with student answers,
               you may turn it on if need be. */
(%o1)                                false
ans1: A=B;
(%o2)                                A = B
modded1: ans1, A=foo*a;
(%o3)                              foo a = B
modded1: subst(foo*a, A, ans1);
(%o4)                              foo a = B
modded1: ratsubst(foo*a, A, ans1);
(%o5)                              foo a = B
```

I would recommend the add nodes option, it will open up more options for you, so just work with the button circled in the picture behind this [link](https://docs.stack-assessment.org/en/Authoring/Authoring_quick_start_3/#enhancing-the-feedback-further).

However, I expect your specific case with a relation being multiplied with a scalar is something we should probably be able to deal with anyway. Maybe Chris knows how to, I don't remember how. In the case of a linear thing like that one could maybe do things like this, to drop the multipliers from the picture, basically, solve the relevant bit out of the equation the student gave:
```
simp:false;
(%o1)                                false
ans1: 2*A=2*B;
(%o2)                              2 A = 2 B
tans: A=B;
(%o3)                                A = B
solve(ans1,A);
(%o4)                               [A = B]
is(solve(ans1,A)=[tans]);
(%o5)                                true
solve(0=0,A); /* This is relatively robust. */
(%o6)                               [A = A]

```
Note that `solve` may return more solutions for more complex things and the comparison becomes more complex then as you want to sort the solutions or compare sets of solutions. This solution would make any multiplier work for you

**Comment by sangwinc** [comment]
So, you have rightly identified that seeking to establish algebraic equivalence between the two _equations_ is not the correct test here.  The test cases I've pushed illustrate and record this.

A*q_in = A*q_out is equivalent to q_in = q_out or A=0
A*q_in = A*q_out is not equivalent to q_in = q_out

So, the general test fails to pick up the context that you somehow get to assume A is not zero.

(Is A really not zero in your situation?  Your business I guess!)

I agree with Matti that you probably need to preprocess the answer in the feedback-variables field. 

You do know quite a lot about the kind of equations students will type in here. So, using solve, as you suggest, is probably a sensible practical solution.

Try defining the following in the feedback variables.
sa1:first(solve(ans1,q_out));

Then check with sa1 in the potential response tree.
ATAlgEquiv(sa1, ta);

**Comment by tkokkone** [comment]
Thanks for the extremely fast replies! The easy fix was to add one more node to the PRT. As I expect only two different answers, it is straighforward to check for both of them. Something I should have thought myself, too, but was too fixed on getting this done with just one test...

Thanks to both of you!

Teemu

**Comment by sangwinc** [comment]
Teemu,
It is a constant source of discussion about what general tools should be part of STACK, e.g. in this case "test for equivalence of equations, with some non-zero constants" and what needs to be done in an individual question.  If you find yourself repeatedly doing something artificial feeling, or where a function in the core would really help, then please let us know. Sometimes adding a simple function to Maxima makes things much easier.
Chris
