### ISSUE TITLE
Test consistency of language translation

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#694]
I'm working in a relatively large international project to translate STACK materials and create multi-language versions of questions.  

As part of the bulk test, we would like to make sure that all parts of the question have the same language tags.  E.g. if there are particular language tags in the question text, then any other parts of the question which contain language, specifically the general feedback and the nodes of the PRT, then the tags in each part should match the tags in the question itself.

It is very easy for a translator to miss feedback in the PRT, or forget to translate the general feedback.   Saying 

- "Your question is in Finnish and Swedish, but the branch prt1-3-T only has Finnish"
- "Your question is in French and German, but the branch prt1-3-T only has non-trivial text but no language tags at all.  Is this wrong!"

Some specific proposal for discussion.

1. The language tags occurring in the "Question text" de facto define what languages the question support.  Extra and missing tags elsewhere are matched against this list.
2. This does not throw errors in the question (which prevent saving a question), but appear in the question testing page.
3. We add this to the bulk-test and upgrade scripts.

Comments welcome before I code this.

**Comment by sangwinc** [comment]
Note, we already have code to find which languages are used in a particular text fragment.
https://github.com/maths/moodle-qtype_stack/blob/master/lang/multilang.php#L89

**Comment by aharjula** [comment]
Personally, I am starting to lose faith on the multi-lang filter especially in cases where we need to do styling and would want to have nested spans and stuff like that. That combined with conditional-rendering from the block system, MCQ-localisation, and WYSIWYG-editor issues leads me to consider building our own language system as I mentioned in #392, I would like to detect the languages at a logical level during CASText parsing and maybe in the case of truly large question-texts or model-solutions pre-evaluate the language variant splitting so that we could cache the code for each separately to save CAS-evaluation load by only sending the relevant bits there. For me, our own internal CASText2 level system would at the same time solve issues with localising MCQ and JSXGraph content.

filter_multilang2 (as mentioned in #689) might be the better tool but then we would need to support the identification of languages from multiple types of filters. At least it sounds like it works better with WYSIWYG.

As to "Your question is in French and German, but the branch prt1-3-T only has non-trivial text but no language tags at all. Is this wrong!" I am not so sure that makes sense. I can easily imagine a branch that would only contain a shared JSXGraph that would not have any language-specific strings. Of course, if one can add an annotation to the code to silence this, things would be better e.g. `[[comment]] @disable language_check; [[/comment]]`.

As to 1. I think one would need to notice all the possible languages everywhere in the question so that if one of the PRT branches somewhere contains some random language we don't drop all the others in every other part of the PRTs feedback. Remember how multi-lang works if it happens to find a match in the particular fragment we are working with and also note how we concatenate some things before multi-lang gets to work with them.

**Comment by malthefogsporring** [comment]
"the branch prt1-3-T only has non-trivial text but no language tags at all. Is this wrong!" would be helpful if by "non-trivial" you are suggesting a system that can distinguish text from equations, JSXGraphs, etc, to avoid what Matti is suggesting. Otherwise, I can see it becoming annoying if I write a lot of questions where CASText areas just have an equation.

"Your question is in Finnish and Swedish, but the branch prt1-3-T only has Finnish" would be very helpful. When translating a question into many languages, especially when you have multiple people working on it, it is very easy to miss a CASText area, and can be tedious to check what is missing.

Multilang is generally quite tedious to work with when the CASText is long, or you want to do semi-complex things, because the CASText is swarmed by spans upon spans. I would be very happy to see an alternate solution. What I would really like to see is something like the attached, or otherwise detecting which blocks of text are valid for translation, i.e. avoiding input blocks and the like, and serving them up for the translator in a usable way. This would have to be done in a way so the question does not break when it is changed in the "Reference language". However, maybe this is wishful thinking.

<img width="600" alt="1" src="https://user-images.githubusercontent.com/67361419/110319647-17f52400-8007-11eb-9720-96895cd68ed4.png">
------------------------------------------------
<img width="600" alt="2" src="https://user-images.githubusercontent.com/67361419/110319645-175c8d80-8007-11eb-9f79-abb89ea28e63.png">

**Comment by aharjula** [comment]
If we would have our own language system (or could reliably parse the systems people use) and could add some logic to the editor that would be possible. 

However, the "non-editable" (I assumed that they are non-movable and you cannot permute them or populate white-space between them, if this is not the case then this is not an issue) thing in the latter example is not something we should have. While it is unlikely to be an issue from LTR vs. RTL locale point of view, there is a use-case of localisation that might lead to content appearing between such non-editable blocks, possibly leading to rearrangement of the question. An example of this could be the use of "simple English" or some generated language-codes for levels of description to present the question with more or less "hints"/"descriptions" depending on the usage context. I do understand that one might say that this is using the localisation system for something else than it was it is still something to consider. Localisation to the audience is not just about choosing between US vs. UK English it can also be about the age, the field or language capabilities of the audience, and at that point, we might generate extra content instead of one-to-one translations. Taking this further though now at not that practical to handle level, consider that some questions used with physics students are the same as they are for chemistry students, but you typically set the context differently for these students.
