### ISSUE TITLE
Parse blocks e.g. (a,b,c) as ntuple in student's input

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#695]
1. Please can we adjust the parser to that when a student types in (a,b,c) this is accepted and interpreted as the (existing) ntuple inert function?

2. (a,b,c)(c,d,e) should then be ntuple(a,b,c)*ntuple(c,d,e) internally.

This would allow students to more easily type in coordinates, and other things.  This is only needed for students' input.

**Comment by aharjula** [comment]
Just add an AST-filter to rewrite the groups to those function-calls when you want to do so. The parser itself does not need to know about this.

**Comment by aharjula** [comment]
You can make the filter parametric so that you can define how many items there must be so that people can define if they are acting on 2D or 3D coordinates and so on... The filter can then give validation feedback about extra groups it sees or wrong length groups.

**Comment by aharjula** [comment]
Just apply this, what you call "blocks" I called "groups".
```
$filter = function($node) {
 if ($node instance MP_Group) {
  $node->parentnode->replace($node, new MP_FunctionCall(new MP_Identifier('ntuple'), $node->items));
  return false;
 }
 return true;
};

**Comment by aharjula** [comment]
Naturally, you will need some more logic in the decision to do that conversion maybe not convert inside another group and so on:
```
(1+1,1/(1+1),1) => ntuple(1+1,1/ntuple(1+1),1)
```

**Comment by sangwinc** [comment]
Thanks Matti,
Do we already have code which decides if a group is interpreted as a Maxima Block?    That would be the right logic.
Chris

**Comment by aharjula** [comment]
What do you mean by that? The parser generates groups or function-calls (if a group is immediately preceded by an identifier, a string or some indexing), lists or indexing (list index or array-function call, if preceded by the same things as in a function-call), or sets based on what it sees. A group is just something that did not meet the conditions for being a function call. There exists no AST logic that I recall that would do anything specific about these other than identify that commas are in play if one wants to forbid those as an operator.

To me, a `block` is something like these function calls, which very much come out of the parser as function calls as they are function calls:
```
block([a,b,c],...);
block(local(a,b,c),...);
```
And a "group" is content dependent, if it only contains one thing it is typically just a way to signal that this op has higher precedence e.g. `e^(2+x)` otherwise it a tool for evaluating many things and returning just the last as the value of the group. As long as you don't want to have a local variable scope (or return statements for that matter) a group and a block are functionally equivalent but syntactically different, but that scope is a big thing.

**Comment by sangwinc** [comment]
A shorthand for blocks in Maxima is just (a,b,c) rather than block(a,b,c).  Students can't use blocks in their answers already.  I'd like any "implicit" blocks in student's answers to become explicit ntuples.  So, if a student types in [(a,b,c),(c)] this becomes [ntuple(a,b,c),ntuple(c)] etc.

So, no changes to groups, just this one function call (block) for student's input.   Does that make sense?

**Comment by aharjula** [comment]
The parser itself does not distinguish between the cases where wrapping in parentheses means just raising the priority of some operation or is being used as a visual guide like in loops and conditionals, or as an actual "lite block" style construct with multiple items in it. So to it `(a,b)` and `(b)` are logically equivalent things. What you want is to take the former form and turn it into a function-call which you can indeed do at the AST-filter level.

So like this, if there are any commas present, i.e. more than one item inside the parenthesis, then it turns to a function-call for `ntuple`. Note that there are actually already filters like 105 an 505 in there that forbid things in different phases of the rewriting.
```
$filter = function($node) {
 if ($node instance MP_Group && count($node->items) > 1) {
  $node->parentnode->replace($node, new MP_FunctionCall(new MP_Identifier('ntuple'), $node->items));
  return false; // This filter needs to be in that while-loop construct.
 }
 return true;
};
```

I would still check that one does not end with nested `ntuples` as that would probably be an error. I'll leave checking for that as an exercise.

**Comment by sangwinc** [comment]
Matti, from a mathematical perspective nested tuples are fine.
