### ISSUE TITLE
CAS Connection, unit test only fails once.

### ISSUE THREAD

**Issue by ScottVerbeek** [maths/moodle-qtype_stack#696]
Hi, we're having this issue where whatever unit test is ran it fails the first time and passes the second. Could you explain to me why this is happening. For an example I used the `connection_test.php`

```
root@48a706baf97d:/siteroot# vendor/bin/phpunit question/type/stack/tests/connection_test.php 
Moodle 3.7.6+ (Build: 20200515), 37bb1b5f926236df142d89e6d13873931e28b2a9
Php: 7.2.24.0.0.18.04.7, pgsql: 13.1 (Debian 13.1-1.pgdg100+1), OS: Linux 5.8.0-44-generic x86_64
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

F...                                                                4 / 4 (100%)

Time: 23.78 seconds, Memory: 54.00 MB

There was 1 failure:

1) stack_cas_connection_base_test::test_compute_true
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => Array (...)
 )

/siteroot/question/type/stack/tests/connection_test.php:38
/siteroot/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "stack_cas_connection_base_test" question/type/stack/tests/connection_test.php

FAILURES!
Tests: 4, Assertions: 4, Failures: 1.
root@48a706baf97d:/siteroot# vendor/bin/phpunit question/type/stack/tests/connection_test.php 
Moodle 3.7.6+ (Build: 20200515), 37bb1b5f926236df142d89e6d13873931e28b2a9
Php: 7.2.24.0.0.18.04.7, pgsql: 13.1 (Debian 13.1-1.pgdg100+1), OS: Linux 5.8.0-44-generic x86_64
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

....                                                                4 / 4 (100%)

Time: 13.91 seconds, Memory: 54.00 MB

OK (4 tests, 4 assertions)
```
The same results when running the healthcheck script the first time here `localhost/question/type/stack/healthcheck.php` I get CAS connection errors. Reload that page and everything works perfectly.

**Comment by aharjula** [comment]
Note the times 23.78s vs 13.91s, compare that to the default timeout settings. Maybe there is a timeout with the way the first-ever connection is being built. Depending on how you have configured the connection it could be that you are connecting to a MaximaPool that is not yet running and needs to spin up or you are using some optimised connection that would need to generate the image for the first execution but should store them to the moodledata-directory. Could also be that the testing machine just needs to spin up itself to start testing and that takes enough time to trigger the timeout for the first test, note that it needs to do quite a bit of IO to load all the relevant bits in and once the static files have been loaded to various caches they are ready for the next attempt.

For comparison, if I start up a VM from a full shutdown that test takes 7.6s and it does not fail, after that repetitions take about 5.6s, and that makes sense as there are four tests and in my world the timeout is set to 5s so as long as each test takes less than 5s all should work. My math says that if the total time is 23.78s then the tests can only pass if they are all equally fast and the overhead is very large and that would be unlikely in the first-time IO cache situation.

So maybe try upping the timeout:
```
define('QTYPE_STACK_TEST_CONFIG_CASTIMEOUT',      '5');
```
Or beef up the machine.

**Comment by sangwinc** [comment]
Scott,
Thanks for contacting us.  Sometimes I feel like Matti and I are the only people running the unit tests, so thanks for taking the time to do so!

The first time you run Maxima on a machine is does a whole bunch of compiling of lisp code (I think), but that may depend on the lisp version and so on.  That could well be the issue here.

Chris

**Comment by ScottVerbeek** [comment]
Hi, thanks for the very quick reaction. Now all of my unit test did run successfully. I ended up having to set the timeout at 40 seconds. And the total unittest ran 10 hours. Normally we manage to run a basic moodle site under 1 hour. I'd like to suggest a functionality that does this prewarming. But that's a differnt issue. This one is solved. Thanks again!

**Comment by timhunt** [comment]
As you can see here https://github.com/maths/moodle-qtype_stack/actions/runs/584717411, it is possible to run all the STACK unit tests is much less than one hour (and about 20 minutes if you use SBCL lisp).

If you are seeing ~10 hours, then you set-up is a long way from being optimised.

**Comment by ScottVerbeek** [comment]
I've tried to mimic this `.github/workflows/other_maxima.yml` but I can't get it to work with `linux-optimised` which seems to be so much quicker. I'm running this in my Docker container https://github.com/ScottVerbeek/docker_moodle/tree/1804-psql-maxima 
You have any advice what I can do? Also could you explain this line https://github.com/maths/moodle-qtype_stack/blob/github-ci/.github/workflows/other_maxima.yml#L92 ?   

ps those 10 hours we're all unit test in a Moodle site.

Reopening temporarely

**Comment by aharjula** [comment]
Note that when Tim says about 20 minutes that is indeed just the `--group qtype_stack` and 20 minutes for that is a lot for a tuned system, I can get down to ~4 minutes, but you just can't get there if you are constrained by memory (IO being the other primary one) or any other key resource. We do not typically run the whole Moodle unit-tests but even if we do that should not take that long, around an hour less than two.

Note that while your docker container is configured to bring in a MaximaPool it does not appear to use it when running the tests. And that line you refer just includes a specific wrapper command to ensure that the process gets killed if left hanging. This might be useful if one stops the test running and thus also kill the logic that would have closed the command.

Then my general performance issue comments:
 1. ~~I really dislike it when people just say that things are slow without defining how slow in actually seconds.~~ Well this time we have that 10 hours but we do not know how many other plugins are being tested in that Moodle, assuming none beyond STACK then it is slow.
 2. I really dislike the assumption that everyone is running the code on a similar absolutely perfectly balanced (magically for every task at the same time) supercomputer, i.e. some context (CPU, RAM, IO-speeds, storage-specs for the relevant file-systems etc,) on the specs of the machine might give us some hints on the expected performance. You say docker is in play, assuming the container has not been limited on its resource use one needs to consider if the resources remaining after all the other containers have eaten their share of the resource the host has and consider the resources any other user uses on the host side. One can get down to under 10 minute times if you have a workstation-class machine and don't overprovision it but starting with a generic desktop or laptop one will more than likely get bottlenecked by either memory or IO bandwidth.
 3.  In most cases just try some other LISP with the Maxima, that is the thing with the most effect for most people. SBCL and CLISP tend to be much better in general use than the default GCL on various distributions. Though one can get better performance from GCL in some use cases, the use cases here are related to the use of integers vs. floating-point numbers and the level of use of linear algebra and various data-structures. Learn to install some other LISP interpreted and to compile Maxima so that it is configured to use them.
 4. MaximaPool is a tool for trading memory for IO-bandwidth and startup times, while at the same time placing the load to some other place. It won't help much if you are out of memory or if you could run your thing from ram-disk with blazingly fast processors. Though as it uses the memory of that other place that is typically not an issue, with container setups you just need to make sure that the other place is not in the same host.

Finally, how high is the [load](https://en.wikipedia.org/wiki/Load_(computing)) in your system when running those tests, that will tell you something about the balance between CPU-power and IO-wait. For example, my ~4 minute run gets the load up to 0.57, so I can pretty much assume that 43% of the time is being used to wait for something, probably IO. Though in this case the IO being waited for is the response from MaximaPool which is elsewhere. If all the system is running are the unit-tests and you are not running them in parallel then the load should not rise too much over 1 and assuming you have more than one CPU-core then that should not be an issue.
