### ISSUE TITLE
Checking answers to multi-part STACK questions independently

### ISSUE THREAD

**Issue by kk2dev** [maths/moodle-qtype_stack#698]
Is there a possibility for students to check each part of their answer of a multi-part STACK question, independently? 

There is the option for students to check their answers if they input all of their answers to a multi-part question, but can they check their answers bit by bit, without completing the whole question in one go? 

If so, what are the settings that would need to be applied? If not, then can this be included as a new feature in the next release?

**Comment by sangwinc** [comment]
Yes, you need one potential response tree (PRT) per input.  Actually, the PRTs are designed to be independent of the inputs and you can match them up in any combination.  STACK auto-detects which inputs a PRT relies on.

You can add PRTs by adding more tags, just like you do with inputs.  

Part 6 of the quick-start guide has an example: https://docs.stack-assessment.org/en/Authoring/Authoring_quick_start_6/

There is currently no facility to put "check this bit" buttons on the question because (1) the check button is a function of the Moodle quiz behviour, and (2) the logic become impossible!
