### ISSUE TITLE
Validation of real sets

### ISSUE THREAD

**Issue by stebac** [maths/moodle-qtype_stack#700]
Hi
if the teacher's answer is a real set, such as `oo(0,1)` and the input option "check type of response" is enabled, students are allowed to enter any real set such as `all`, `oo(0,1)`, `{1}` or a union of intervals, which is great. 
But they are also allowed to enter sets of other objects but real numbers, e.g. `{x<2}` (which students may use instead of `oo(-inf,2)`) or something strange like `{all}`. It would be great, if such expressions would be rejected as invalid and they actually aren't subsets of the real numbers. Consequently `realsetp({x<2})` evaluates to `false`.
Could the validation just check, if the student's anwer is a real set in the same way `realsetp` does? 
Stephan

**Comment by sangwinc** [comment]
I've been asked for the opposite as well, e.g. %union(oo(0,1),{2}) and similar examples!  This is getting complicated, and really needs a careful re-design.

**Comment by stebac** [comment]
But `realsetp(%union(oo(0,1),{2}))` does evaluate to `true`, so this is surely not the opposite of my suggestion. 
Why not implenting the check of the answer type consistently to `realsetp`?

**Comment by aharjula** [comment]
Firstly the "check type of response" feature probably has a bad name. The types it checks are quite rare and it only compares them against the teachers answer anyway and even then at the very top level only. So I would not expect it to be able to do this type of classification without some additional hints.

Then a longer story.
Chris,
Lately, I have been thinking about similar validation rules that might be complex and varied at such a level that we cannot pre-define them. I have actually thought about adding a feature to the input2 system (that already allows the customised layout of the validation messages from current validation tests) to also allow CAS-side logic to be defined for validation i.e. give the input a function to call with the otherwise valid input and the function would return `true` if it is valid or a CASText2-fragment as a validation message if it is not. This should allow one to construct arbitrarily complex rules for those cases where the existing core rules are not enough and obviously this would be something that could be added alongside the existing rules to avoid having to repeat them.

Obviously, this would only work in the world of input2 where the validation and input-systems have much more options and those options have direct CAS-connections. It also requires the CASText2 features that allow writing CASText inline among CAS-code. What I mean is that one would have an option in the input definition where one would give a name of a function to call e.g. "extra_validation = val_ans1" and one would define that function in the question variables like this:

```
val_ans1(x) := if realsetp(x) then 
 true
 else /* Obviously we need to identify how it is not and say something sensible about that. */
 castext("The answer {@x@} is not a simple set.");
```

Now one might ask why would one not just give `realsetp` as that option value or have an option that accepts any predicate function as the test for the input. The reason is that we need to define what is to be said when it does not meet the predicates conditions and in most cases one might expect there to be the need to tune that message a bit to fit the use-case and the input itself.

In my view, it does not make sense to just add all the possible predicates as options to the inputs and to define some static messages for each of them, as it is unlikely that most of them have clear messages that would make sense in many cases. While that might work for `integerp` or `numberp`, for `realsetp` it is unlikely to function unless the error message is a long definition about what such a thing is, how to input it, and how not to input it. The more complex the definition is the less sense outputting it based on a binary test becomes, at that point, the logic needs to be something that can examine the input further and give more specific feedback.

Finally, I am not talking about type-checks here, not about the specific predicate checks or the "check type of response" feature that mainly looks at the way it appears at the very top level in Maxima. I am talking about arbitrary input validation rules, for example, imagine what this `val_ans1` would do:

```
/* For MYSTERY expressions these apply: 
 1. The top level operator is "*".
 2. Each operand of that is of one of these types:
   a. Expression free of "x"
   b. Expression where something free of "x" is being added or subtracted from just "x". Or just "x".
   c. Positive integer power of class b.
*/
is_a(expr) := ev(freeof(x, expr), simp);

is_b(expr) := block([countx, arg],
 if is(expr=x) or is(expr=-x) then return(true),
 if not (is(op(expr)="-") or is(op(expr)="+")) then return(false),
 /* These are N-ary ops so we need to check each arg.*/
 countx: 0,
 for arg in args(expr) do (
  if not freeof(x, arg) then (
   countx: countx + 1,
   if not (is(arg = x) or is(arg = -x)) then (
    /* If it is not just "x". */
    countx: countx + 1
   )
  )
 ),
 return(is(countx=1))
);

is_c(expr) := block([],
 if not is(op(expr)="^") then return(false),
 if not integerp(args(expr)[2]) then return(false),
 if is(args(expr)[2] < 1) then return(false),
 return(is_b(args(expr)[1]))
);

val_ans1(expr):=block([tmp],
 if not is(safe_op(expr)="*") then return(castext("The answer should be a multiplication of terms, hint not all of the roots are at 0 or at the same place.")),
 tmp: sublist(args(expr), lambda([E], ev(not (is_a(E) or is_b(E) or is_c(E)), simp=true))),
 if is(length(tmp) > 0) then return(castext("The following terms in your expression need work: {@tmp@}")),
 return(true)
);

```

**Comment by stebac** [comment]
The option of defining validation rules sounds great to me. Something I found great would be to check on the type of the elements of a set (not only in the context of real sets). If for example the students are to give the set of all the asymptotes of a rational function, one might like to check in the validation if all the elements of the set are (linear) equations and give feedback on this.

**Comment by aharjula** [comment]
Thank you for that example, it makes much more sense than the check for factored expression above, it is an example of a complex "data-type" that needs to fulfil different rules at different levels of its definition. Validating that a set consists of equalities (or some other base "type") might be reasonable for a common case (although I would think inputting them through one of the 2D inputs would make more sense) but once one starts to add additional rules for the equations themselves it becomes obvious that the number of possible combinations is just too large to pre-define, as in system-level common definitions.

Personally, I feel like this would be a great new feature allowing STACK to leverage its strengths i.e. to extend on the validation step by giving the author the option to tune the features to validate and the messages used to guide those that fail that validation. It is not that uncommon to see some "validation" of input content in the PRTs with zero penalties, but as that is not something one can do when working with "deferred-feedback" it would be nice to be able to move such things to the actual validation.  

In any case, this would be something happening in STACK 5 timeframe. We would first need the new CASText2 system for the definition of those inline castext-messages. And the input system would also need to be replaced, as adding more special handling in the current one would make it even more convoluted.

@sangwinc what do you think, does this start to sound overly complex? In short, in addition to the current way of toggleable checks one could give a custom function to be executed after them.

**Comment by sangwinc** [comment]
This kind of validation can now be done with the bespoke validation functions.
