### ISSUE TITLE
Traversing prt's

### ISSUE THREAD

**Issue by stebac** [maths/moodle-qtype_stack#702]
Hi, 
this is an issue I've been running into several times. It is about the following situation: 
In one node of a prt I am using a function, which is only defined for certain mathematical objects (e.g. polynomials, equations, real intervals). I do make sure that the tree is not being traversed through this node if the answer is of a different type. But still the following happens: 
- The question will throw an error.
- The standard feedback is not being displayed. 
- The respective test case will still pass. 

In the following question I'm using `interval_subsetp` in node 3, which I only get to if `intervalp(ans1)` evaluates to true.
![Error_message](https://user-images.githubusercontent.com/52776824/114406232-a9782880-9ba7-11eb-844f-117d57d36e07.PNG)
![Test_case](https://user-images.githubusercontent.com/52776824/114406255-ae3cdc80-9ba7-11eb-86d8-38c0b823e919.PNG)

So is the answer test of a node of the prt tree being executed, even if the tree is not being traversed through this node for a specific answer? And if yes, why?

My workaround is to define question variables, which are also checking on the type of the student's answer, and then use these variables instead of the function. In this case something like `sans_subset_tans: if intervalp(ans1) then interval_subsetp(ans1,ta) else false` But this can lead to extensive question variables. And it is still not nice that the errors can not be seen in the question tests. 
Is there a better way to handle this?

**Comment by aharjula** [comment]
So basically the old #150 issue, that has been a problem since STACK 1 and the first person that managed to divide by 0 in the PRT. Unfortunately, at this moment there are no better ways to handle this.

The way the PRTs are currently executed is a very old implementation that just executes all the nodes and then figures out the path through the tree and does not try to think about the consequences of particular nodes. This is something that will get fixed once the long project aiming to "compile" the whole PRT into a singular expression with actual `if`-statements completes. I am not promising that it will be ready this summer, but major updates in 4.3 gave us certain missing capabilities (primarily the so-called sub-statement level error-catching logic) that can be used for this. And assuming we are going to follow the [docs](https://github.com/maths/moodle-qtype_stack/blob/dev/doc/en/Developer/Development_track.md) this issue will be eliminated in 4.4 (unless someone else steals that version number). 

And indeed people have been working around this by evaluating the tricky bits in the feedback variables for quite some time and we really would want things to work without the need for such trickery. Basically, we do acknowledge that the intuitive conceptual model of the PRT does not match the implementation and we are working to make the implementation match. I will be very happy the day that this whole issue can be removed from the "future plans"-document as it has been there for quite some time.

**Comment by stebac** [comment]
Thank you for the prompt answer, I didn't know the #150 issue. This helps to understand the whole thing! So indeed I will continue to use feedback variables until 4.4 but at least know why ...

**Comment by sangwinc** [comment]
Yes, you can now use Maxima's errcatch to catch errors you would like to condone.

**Comment by aharjula** [comment]
Chris, I am starting to get worried, what is all this about errcatch and catching errors in feedback vars? It has nothing to do with this or #492 in both of these the issue was that all the nodes were evaluated, and that evaluation exploded, even though the preceding nodes should have stopped the evaluation. Now that we actually have if-statements in the logic and actually evaluate only the nodes that we need then these errors do not happen unless one does not notice that they are e.g. "dividing by zero". While it is nice that we can now add errcatches everywhere that was not the issue, here nor in the original #150...

Anyway 4.4. is near and this issue is indeed closed.
