### ISSUE TITLE
PHPunit - noisy undefined constant

### ISSUE THREAD

**Issue by aspark21** [maths/moodle-qtype_stack#705]
In the process of setting up our pipeline to properly run the STACK phpunit tests. However getting very polluted run with 3100+ failures with these kind of message thrown:

`Use of undefined constant QTYPE_STACK_TEST_CONFIG_MAXIMALIBRARIES - assumed 'QTYPE_STACK_TEST_CONFIG_MAXIMALIBRARIES' (this will throw an Error in a future version of PHP)`
  
While yes I will now add that to our config.php it still seems to me like the default way these are defined needs to be in single quotes at least here - https://github.com/maths/moodle-qtype_stack/blob/2657c7e427ca2312829b0810ad6804e4a8716882/tests/fixtures/test_maxima_configuration.php#L69-L81

We previously had to chop out stack from our CI runs because of this noise.

**Comment by sangwinc** [comment]
Ok, well we don't want people chopping the unit testing because of noise created by the test setup!   Thanks for reporting this problem.   I'm not getting these errors, and I have recently set up a fresh server with a new PHPUnit set up. Can you confirm which version of PHP, etc. you are using and I'll get to the bottom of this before the next release?

**Comment by aspark21** [comment]
Thanks!

We're running the unit tests on PHP 7.3, Moodle 3.9 latest (3.9.6+) and STACK 4.3.7

**Comment by timhunt** [comment]
Have you followed the instructions in the developer docs which tell you how to set up to run the unit tests?

(You need to tell the PHPUnit install where to find Maxima.)

https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Developer/Unit_tests.md#stack-specific-set-up-steps
