### ISSUE TITLE
100% CPU load when starting a quiz in exam-setting

### ISSUE THREAD

**Issue by aacchhee** [maths/moodle-qtype_stack#709]
Recently we tried two assignments with STACK-questions with quite a strict time limit (3 hours compared to usual 1 week). This resulted in all of our 200 students starting a new quiz attempt precisely at the same time. First assignment resulted in 100% CPU load on STACK-server right after opening of the quiz, so the system became totally irresponsible. For the second assignment (two weeks later) we have divided the class as 50+50+100 students such that each new group could start working with 5 min delay compared to the previous group. 

Each assignment consisted of three quizzes, the first being very lightweight (attached). Almost all students started with the first quiz before proceeding to nr2 and nr3. 85% have logged in on STACK-server in good time before the start, and just started working with the quiz when it opened.

The largest group of 100 students was the last group to start working with the assignment, at 09.00. Period 09:00–09:01: 87% CPU load. 

We also think that 20% CPU load afterwards is way too high load given how small the number of requests per second was.

High SQL-load at deadline (11:50) is due to 70% of students using "submit all open attempts automatically"-feature.

Any ideas what can be wrong here? Sounds more like a Moodle issue. The same system was capable of serving 1200 simultaneous students before, the only difference with our case being spread starting time.

Almost all CPU-use goes to PHP, Maxima time is negligible. 

CPU load on STACK-server around opening time:
![image](https://user-images.githubusercontent.com/59649991/116696757-98f6e900-a9c2-11eb-97ef-8521fdd6f7d2.png)
A bit later:
![image](https://user-images.githubusercontent.com/59649991/116696825-af9d4000-a9c2-11eb-9e67-27150aa0e51b.png)

MySQL is performing very good:
![image](https://user-images.githubusercontent.com/59649991/116696883-c348a680-a9c2-11eb-99a9-db7743d69b2a.png)
![image](https://user-images.githubusercontent.com/59649991/116696914-c80d5a80-a9c2-11eb-85fa-195125bfa322.png)
![image](https://user-images.githubusercontent.com/59649991/116696927-cd6aa500-a9c2-11eb-8133-73d863098140.png)

CPU time on STACK over quiz duration (3 hours)
![image](https://user-images.githubusercontent.com/59649991/116696979-e2dfcf00-a9c2-11eb-9fff-fabce769e754.png)
CPU time on MySQL
![image](https://user-images.githubusercontent.com/59649991/116697029-f4c17200-a9c2-11eb-8e71-09315fcbe3db.png)
Network on MySQL:
![image](https://user-images.githubusercontent.com/59649991/116697069-01de6100-a9c3-11eb-84b2-4b958f97b36d.png)

Server data:
Both STACK- and MySQL-servers: 16 GB memory, Intel(R) Xeon(R) CPU E5-2637 v3 @ 3.50GHz CPU. STACK-server has 8 cores, MySQL-server has 4 cores. Disc: iSCSI with both spinning HDD and SSD, approx. 8 GB ram (m/batterybackup) is used for writing cache. Due to writes going to batterybacked RAM and enough memory the whole Moodle-installation is cached (htdocs+moodledata). The whole SQL-database is in RAM. 
System data: 
STACK:
•	Ubuntu 18.04
•	Moodle 3.10+ (Build: 20201224)
•	STACK 4.3.8 for Moodle 3.5+ (2020120600)
•	PHP 7.2.24 (7.2.24-0ubuntu0.18.04.7)

MySQL:
•	Ubuntu 16.04
•	MySQL 5.7.33 (5.7.33-0ubuntu0.16.04.1)

[problematic_quiz.zip](https://github.com/maths/moodle-qtype_stack/files/6405322/problematic_quiz.zip)

**Comment by aharjula** [comment]
Thank you for providing context and numbers, it is rare to see those. The issue is probably with the parser of the STACK 4.3 being less thatn optimal in dealing with questions that have question-variables without the semicolons between statements, i.e. stuff like this:
```
...
set5 : cartesian_product(set_A, set_B)
set6 : union(cartesian_product(set_A, set_B), cartesian_product(set_A, set_C))
set7 : powerset(set_A)
set8 : powerset(cartesian_product(set_A, set_B))
exampleA : cardinality(set_A)
exampleB : rand_selection(list_A,1)[1]
ta1A : cardinality(set1)
ta1B : set1
ta2A : cardinality(set2)
ta2B : set2
ta3A : cardinality(set3)
ta3B : set3
ta4A : cardinality(set4)
ta4B : set4
ta5A : cardinality(set5)
ta5B : set5
...
```
Looking at the attached set of questions there are questions with long bits of code without those semicolons and they are probably causing the vast majority of the load. Same issue applies to feedback-variables. The attached file has over 90 questions so I assume that you were having only a subset of them in the quiz as even with deployed variants that is way more than we currenlyt expect to work and obviously three hours for that many is quite a fast pace... Anyway adding the semicolons to those materials should improve their performance significantly if they are to be executed on the current version.

The logic for figuring out where the semicolons should be is quite expensive, especially if there are large numbers of them missing and it is not cached so it will need to be repeated quite often. The logic changed so that people can write multi-line statements like for-loops and longer functions in a more clear way (as you have apparently done in the code) as opposed to the old way of simply having each statement on its own line. The PHP load is most likely from that. The next STACK release will include a cache for this very thing and should fix this.

If works for 1200 simultaneous users it is likely due to them running different questions and or spreading the load just a bit more, in this case they all probably had the same ones so the same issue multiplied and the timing constraint surely led to even more  concentration of the requests, the load surely did not improve the situation.

**Comment by sangwinc** [comment]
The question caching in recent versions will have solved this problem. There will be resource limits, but please contact us again if you have this problem.
