### ISSUE TITLE
High CPU Usage when starting multiple quiz attempts in concurrency.

### ISSUE THREAD

**Issue by David010203** [maths/moodle-qtype_stack#712]
Hello,

First of all I would like to say that this is a great plugin for STEM courses and managing mathematical and computing questions within quizzes. 
I would like to raise a question about a set of results I have following a performance and load testing exercise against a quiz using Stack type questions. The quiz contained 4 pages, each with 4 Stack questions, totaling at 16 Stack questions in the entire quiz. The Moodle is hosted on very capable infrastructure with 4 machines handling Maxima-Pool.

We deployed 250 moodle users and started 250 individual attempts of said quiz, containing 16 Stack questions. The most time consuming request was when a user clicked `Start Attempt`. We saw this request go upwards of 600 seconds, but in the end, completed and managed to begin the attempt. The following requests, completing Stack questions and submitting the attempt were well within reasonable response times limits.

We then tried reducing the number of users attempting the quiz and increasing Maxima-Pool machine from 4 to 6 and then from 6 to 12. The results was a mild improvement in the response time for the attempt quiz requests.

Stack Version: 4.3.7 for Moodle 3.5+
Moodle Version: 3.9.6

Thank you,

David

Edit: --added moodle version

**Comment by David010203** [comment]
Hello,

Thank you very much for the reply, we were able to substantially improve the performance of the Stack quiz by generating question variants prior to starting the quiz attempts. We were able to complete the 16 question quiz without any issues.

Thank you,
David

**Comment by timhunt** [comment]
I just wantedd to drop in a link to the core Moodle issue which is on-topic for the issue fo starting a lot of quiz attempts at the same time: https://tracker.moodle.org/browse/MDL-68806.

**Comment by aharjula** [comment]
> We're looking to address the missing semicolons from existing and new STACK questions by adding a feature that checks the question and feedback variables for missing semicolons, and adds them if they are not there, when saving the question. However, given that we are using an older version of STACK, does the newer versions address the issues caused by missing semicolons?

**Yes** and no, the parser that does the semicolon fixing is still very slow as it iteratively adds those missing ones, and if the number of missing ones is large, it will take time, even up to the timeout of PHP. But that is no longer an issue as now we cache things (we already did in some latter 4.3.x versions) in 4.4 so that we only parse that original code during the first execution of the question and validate and cache a "compiled" version of it which will never (outside debug screens) again get parsed and directly usable by our logic. Thus even if your authoring process is slow, if you don't use those semi-colons, the execution time performance should be much much better. Also, various security checks are being executed much faster...
