### ISSUE TITLE
Failing test for Diff answer test

### ISSUE THREAD

**Issue by wehro** [maths/moodle-qtype_stack#722]
I ran into a serious problem with the Diff answer test. Some faulty student answers cannot be checked correctly.
![Response_tree](https://user-images.githubusercontent.com/33468411/124514832-36fd9a00-ddde-11eb-8943-e03dec705432.png)

![Derivation](https://user-images.githubusercontent.com/33468411/124514554-98713900-dddd-11eb-960f-8200742ff32f.png)

**Comment by sangwinc** [comment]
Yes, Maxima by default an interactive mode.  Try the following on the Maxima command line.

`integrate(x^n,x);`

You will get asked a very sensible question!    The Diff test also checks if a student has integrated, so we do some integration in the background and since your example has a variable in the exponent, it asks a similar question.  That is the cause of this problem!  (There is a very interesting discussion in the CAS community about what `integrate(x^n,x);` "should" return, and I rather like `(x^(n+1)-1)/(n+1)` try taking the limit as n-> -1 and see what happens! Anyway this idea isn't going to catch on, so back to your problem....)

Try changing the teacher's answer to

`(assume(n>0), n*x^(n-1))`

If this solves the problem please let me know and I'll better document this issue. It isn't a bug (but I agree it very much looks like one).

Thanks for reporting it, and I hope this helps?

**Comment by wehro** [comment]
Thank you for the explanation.
I have changed the answer test to AlgEquiv to avoid further trouble with Diff.
