### ISSUE TITLE
Feature request: Import and export lists with random seeds for questions various in a random group

### ISSUE THREAD

**Issue by rb-clz** [maths/moodle-qtype_stack#724]
Would it be possible to implement a way to export an existig list of seeds in the page "Deployed variants" and to import it into other questions?

(related to https://github.com/maths/moodle-qtype_stack/issues/723)

**Comment by sangwinc** [comment]
Linking questions in this was is not a feature I regularly make use of, so I'm sorry if this is not something we have really got on top of.

Is this the kind of functionality you are thinking of?

![Screenshot_2021-07-22_15-35-45](https://user-images.githubusercontent.com/781615/126657577-5997f93f-c211-4d1f-930b-d511058fb6ac.png)

**Comment by sangwinc** [comment]
The numbers to the right of the box are the current variants, in order, which can be copied into the corresponding box of another question.

**Comment by rb-clz** [comment]
Yes, that would be great.

**Comment by sangwinc** [comment]
Ok, the problem with this is that when you copy over a list of seeds from one question to another you might get duplicate question notes!   Currently you can only deploy each question note once - indeed that is the whole point so that data for each variant is collected together.  I think your proposal would seek to weaken that, or do you have a proposal for how that should work?

**Comment by sangwinc** [comment]
Ok, so the code itself is very easy to do.  The question really is "do we want to do this"?

I'm very keen to make sure each question note is only deployed once.  Can you help me understand how you are using STACK and why you need this feature?  I'm not using STACK with variants matching between questions in a quiz.  At the very least, we should document this usage, and ideally make sure anything you are relying on is set up in the test cases as well so it doesn't get lost.

**Comment by krostas1983** [comment]
Teachers regularly want to create "random groups" with questions being based on each other.
Students might be presented with a set of questions that are all based on some common variables (e.g. an architect might need to compute different values based on the dimensions of a roof after calculating the dimensions of the roof depending on the foundation and desired inclination of the roof.). This feature would:
- enable students to stay with one set of numbers, preventing error-prone context switches
- enable teachers to arrange these questions clearly without putting all calculations and input fields in a single large question, which would be confusing / cluttered
- still provide the full benefit of having randomized question variables and presenting most students with different variants

We're aware that both variable generation and question notes would need to be identical for this to work. It might be beneficial to have some sort of identifying string ("Random group" seems to be a good fit for this) which STACK could use to check, whether any questions within the same "Random group" differ in any of these aspects:
- Amount or order of deployed seeds
- Question variable generation
- Question notes
If this is the case, a warning could be displayed. And it should, since any of these points would prevent the "Random group" feature from working as intended.

This should not lead to question notes being deployed more than once. If in any such case questions are formally identical (they require the same answer), they could still differ regarding other questions of the same random group - as such, their question notes would need to differ and it should be the teacher's responsibility to ensure consistency in question notes among their random group. This feature would enable them to do this.

Performance from overhead (of unused question variables / oversized question notes) should only be an issue if caching is disabled.

**Comment by aharjula** [comment]
Chris,
While not an extremely common need I have memories of seed-linking being used in the past. The pattern of shared-seed and a shared preamble generating similar random parameters for questions is fairly handy if one tries to go over large amounts of things and wants to keep using the same construction be it a physical model or otherwise. The pattern I first think of is to split a question with large amounts of instructions and running over long into seed-linked questions with the information placed between as some "information items" and a clearer display of progress through the quiz logic.

Currently, I don't quite see how the logic with `variantsselectionseed` actually works currently but to me the logical way for it to work would be to handle cases where the seed-linking would be active so that the linked seed would be used instead of any deployed even if it would cause a situation where multiple variants of the linked seeds would have same notes. To me, deploying variants is good for performance and testing and should be encouraged but in this case, the selected seed should be overridden if linking is found to be active, the current caching logic will quite fast fill in the performance gap especially if the first question determining the seed already has deployed variants.

**Comment by aharjula** [comment]
Chris,
I have serious trouble figuring out how the feature we should already have i.e. `variantselectionseed` actually functions in the code... To me it should handle this, i.e., the first question in a quiz would determine the seed for all the remaining ones linked to it overriding any deployed-seeds lists they might have. Performance would not suffer too much but the analysis issues would naturally be one thing unless one prints out the same base parameters in all the question notes and it being the recommended way for analysis why would one not do that if one does analysis... It would still be good to deploy variants for the other questions for testing purposes but this logic should be able to skip them.

To me splitting long questions into parts using seed-linking is something that makes much sense and if it is not currently a working feature (I don't know if it is) should be restored. Just being able to turn one extremely long question, think pages of instruction for multiple steps, into a few questions within information items between them is helpful to pace the student and gives the additional benefit of progress tracking through the quiz level tools both for the student and teacher.

**Comment by aharjula** [comment]
Ok. Now I understand how this works, `get_variants_selection_seed` is a Moodle-side feature syncing the seed we get from Moodle based on the group names we have in the questions. It fights against the deployed seeds logic in such a way that if even one of the questions has even one deployed variant the received "seed"/"variant-number" is taken as an index in the deployed seeds lists instead of a direct seed, and if the lists do not perfectly match the linking does not work.

To me, this means that such linked questions cannot currently have any deployed variants or one will indeed need to sync the deployed variants lists. The only other option is for the question to know of the other questions alongside it and to question them about their seeds and as that goes against sensible encapsulation, in the question engine above us, I don't see any reason (critical enough reason as those holes would probably go against the design of it) to poke holes in that wall. So we indeed need a way to sync deployed seeds of a random group and the copy-paste import-export does indeed seem like the most natural way, even if it is a complex thing one just needs to know of.

**Comment by sangwinc** [comment]
Thanks folks, I have written some documentation on how to achieve "variant matching" within the current system.  It is rather fragile I think, and really relies on author expertise...

1. I'm not sure how I can unit test this.
2. I'd really welcome some comments from @timhunt about how this proposal fits with development of the question bank he is working on.

One option would be for a meta-question which has little more than

1. question variables.
2. a list of (STACK?) questions (in order)
3. a list of seeds

The meta question in a quiz would then prepend the question variables to any variables within the STACK question itself, and use the list of seeds, and use all the listed questions in order.  This rather subverts the quiz.  I think we need to talk to Tim about the relationship between matched variants and quiz structures!  A new question would be a lot of work.  How would that fit with stateful?

A great suggestion, thanks.  Can I ask @rb-clz and @krostas1983 to check and contribute any amendments to the docs?

**Comment by rb-clz** [comment]
Thank you @sangwinc and @aharjul, for your work.
Thanks for your reply, krostas1983, I agree.

One of my colleagues presented me the following "solution" as a workaround: 

1. Exporting as moodle-XML
2. Appending
"<deployedseed>1</deployedseed>

...

<deployedseed>50</deployedseed>"
 to the end of each question

3. Importing it again.
He wrote that he didn't need question tests in his case and for him it was ok to have few duplicates. 

How do you think about this "solution"?

**Comment by krostas1983** [comment]
Thank you @sangwinc & @aharjula for your feedback on this suggestion!
I definitely agree that "variant matching" in its current stat requires extensive knowledge of the STACK plugin. A first goal could be to make these workings more transparent to users.

Unfortunately, I don't know enough about the deeper workings of the STACK plugin to be of any help in design decisions going forward. I'd be more than happy to support with testing and writing documentation where applicable.

So please excuse if any of the following is presumptuous guesswork:

A deeper look into the suggested meta-question:
I don't think it'd be necessary to have a meta-question have references to all questions of one random group. The other way round might be more adjustable:
- A meta-question handles question variables, notes and seed management / deployment for the whole random group. (It should be disabled in other questions of the same random group. If the variables were only prepended, they might still be overwritten later on.)
- Other random questions of the same random group simply reference the meta-question where applicable. For error checking (correct grading) and performance issues (caching), variant deployment / testing should still be available. Seed list is loaded from meta-question, though.
- Including the question note in shared characteristics from the meta-question ensures that no duplicates can be created (questions might be identical regarding problem / solution), but 

Advantages:
- In quizzes, questions of a random group could still be used alone, in combination with others or as a complete set.
- Multiple variants / versions of a question could exist within the same random group.

Possible problems:
- Don't know how this would work with export / import.
- What happens to other questions / deployed variants when meta-question is updated / deleted?

It would seem very wise to check in with @timhunt , especially regarding the upcoming work with the question bank overhaul.

@rb-clz : The solution seems to be a practical workaround. Haven't come around to testing it yet, but can't see why that wouldn't work. Updating the seed list will remain a load of work, though.
Regarding duplicates, I'd strongly suggest to match question notes between questions, as this:
- ensures questions are ordered identically in the seed / variant overview
- doesn't prevent you from expanding the seed list manually should the need arise (having duplicates in one question but not the other would require another run of the workaround)

**Comment by sangwinc** [comment]
Yes, using the XML is probably a sensible work-around.  I'd rather try to have an official supported mechanism for this!

Actually, your suggestion of XML reminds me of how useful it would be, at certain moments, to be able to cut and paste between text-based question markup of some kind...

The other options with variant is that when we collate the stats we have an option to "group by identical note".  The very rudimentary stats functions (basic report page) has a standing assumption that notes are basically unique so doesn't bother grouping.

**Comment by timhunt** [comment]
There is no plan to change how variantsselectionseed works in Moodle.

I agree it causes a usability issue in relation to STACK's deployed seeds - and we need to find a way around that. Really, when genrating deployed seeds you need to consider all questoins with the same variantsselectionseed at the same time. But currntly STACK's seed deploying UI is focussed on one question at a time.

**Comment by sangwinc** [comment]
I think anyone using this advanced feature will need to live with the possible duplicate question notes.  I've changed the mechanism to create a warning in a question when this happens.  Actually, we only check for duplicate answer notes when deploying.  So, if you deploy and then change the question you can currently end up with duplicates anyway.

This seems like a very useful feature.
Chris
