### ISSUE TITLE
stackjson_stringify() producing randomly strings or numbers

### ISSUE THREAD

**Issue by mkraska** [maths/moodle-qtype_stack#730]
In the attached question, a Maxima list of lists is converted using stackjson_stringify() for further use in a JSXGraph block.

While debugging the question, I found that the Maxima list `["beam","",[4.5,-3.0],[4.5,-4.0],0.7]` is converted by `stackjson_stringify(float( ))` into `[\"beam\",\"\",[4.5,\"-3.0\"],[4.5,\"-4.0\"],0.7]`

Obviously, some floats are kept verbatim, others are converted to strings. This happens at various places in a bigger list of lists.

I don't know if that is the source of my problems with the attached question but at least it seems to be unintended behaviour of the stringify function. 

[quiz-MMM-TM3 09 03 virtual work 1-20210809-1000.zip](https://github.com/maths/moodle-qtype_stack/files/6952852/quiz-MMM-TM3.09.03.virtual.work.1-20210809-1000.zip)

**Comment by mkraska** [comment]
This issue indeed was the source of my problems in the given question. To mitigate it I have to wrap all expected numbers with `parseFloat()` in the JSXGraph block. 

Fortunately, this function does not complain if the argument is already a float, so it can be applied without previous testing.

**Comment by aharjula** [comment]
Ohh... So this happens, probably an unary minus thing again:
```
numberp(-1.2);
(%o4)                                true
simp:false;
(%o5)                                false
numberp(-1.2); 
(%o6)                                false  !!!!!!!!! 
numberp(-1.2),simp;
(%o7)                                true
ev(numberp(-1.2),simp);
(%o8)                                true
```
Which is relevant due to these [lines](https://github.com/maths/moodle-qtype_stack/blob/b764b39675c19d3b4c8017d7040ce87b1e28b106/stack/maxima/stackstrings.mac#L224-L225). So the stringify function breaks if we have `simp:false`, obviously it should not break. For now though in that example question things should work, if you return the `simp:true` value before the call for "stringify". 

I'll make the function use force when checking if the value is a number, note that it will force constatns like `%pi` and fractions into floats although that is probably not a problem, but I should probably leave `simp` in its external state for the expressions in case someone needs to pass through them without simplification.

**Comment by aharjula** [comment]
So that is my suggested fix, if you happen to know of any reason why it should not convert `%pi` or `%e` to floats in cases where the value is a raw number after simplification please let me know and we can still tune this. To me, it feels like it makes more sense to return them as floats so that one would not need to convert them, as a special case, in later processing but I am not sure if that is the best approach for everyone.

**Comment by mkraska** [comment]
Great! Returning to `simp: true` works indeed. Much better mitigation than applying parseFloat everywhere! Thanks a lot!

I think that converting `%pi`  and `%e` to floats is good, because `JSON.parse()` anyways can't handle `Math.PI` or `Math.E`. In my questions I always wrap the structure to convert with `float` anyways. Yet maybe, that is not required if simp is true.

**Comment by aharjula** [comment]
Ok. The fixed logic will do the work of your `float` wrapping automatically for all values that can be simplified to a single number. If you wish to turn constants into floats inside expressions then you need to have that `float` wrapping, but I think that would be a very odd use-case, although given the labels and equations you might include in those free-body-diagrams it could be that constants could exist in some expression values (not as input but for passing to other logic maybe, some logic that would push them to other inputs through scripting for example), and in that case not doing the wrapping at the top level could be useful.

In any case, values that can be turned into a single number will now work the same way, both when `simp` is `false` and when it is `true`.

**Comment by mkraska** [comment]
All symbolic stuff in my questions with interactive input is handled as string on JS side. For use in STACK I there is a separate input field of type Algebraic. 
For example, an interactive spline object returns it's symbolic equation for convenient evaluation in STACK, see [iMecLib](https://github.com/mkraska/meclib/tree/main/iMecLib)
