### ISSUE TITLE
Strange behaviour with regex containing | after a *

### ISSUE THREAD

**Issue by nfa019** [maths/moodle-qtype_stack#736]
Hi,

I see a strange behaviour. I am not sure, if we had this before we updated some weeks before. I use STACK Version 2020120600.

If I have a regex with a star and then with an or, the or part is ignored by stack

example
`((a|b)*)|((cd)*)`
is expected to match a,b, aaa, abab, and so on and additionally cd, cdcd, cdcdcd and so on
but it only finds a,b, aaa, abab, and so on

If you change the order to
`((cd)*)|((a|b)*)`
 it only finds cd, cdcd, cdcdcd and so on.

Do I something wrong or is this really a bug ?

Best regards
Frauke

[example-with-regex.zip](https://github.com/maths/moodle-qtype_stack/files/7090535/example-with-regex.zip)

**Comment by aharjula** [comment]
Difficult to say, the `sregexp` Maxima library is not exactly our own and I don't know how perfectly it implements the expected syntax behavior of specific regexp dialects.

Maybe I am missing the point, but to me those patterns do match and the part that matches is `""`? Could it be that the logic you use to check for "exact" matching is what is causing the confusion here? Think about what is the difference between `*` and `+` and then wonder if greedily matching `""` would lead to the observed behavior.

Anyway, I still recommend anchors for that type of "exact" matching if it is needed.

**Comment by nfa019** [comment]
`$` is not allowed in STACK, but `\Z` helped.

Thank you.

**Comment by nfa019** [comment]
Sorry for the confusion - \Z does not help and $ is not allowed in STACK. It helps im Maxima, yes.

`(a|x)+|(bc)+` is not a problem, but `(a|b)+|(bc)+` where parts of the second part are in the first part. 

For me, it seems, that the regexp Maxima library has changed.

OK, I will work around that.

**Comment by nfa019** [comment]
An example is in my first post here.

If I teach regular languages in theoretical computer science - testing words with regular expressions is the standard way. 

I use them for questions like

Give some words

- accepted by the following automaton ...
- produced by the grammar ....
- of the language ...
- described by the regex ...

Many students have problems with the abstract language, so it helps a lot to find examples.

I don't think, that there is a better way for this than regular expressions.

**Comment by sangwinc** [comment]
Frank,
Just to let you know I very recently fixed the bug which prevents $s inside strings in the question variables.  This should now be ok in future releases.
Chris

**Comment by nfa019** [comment]
Thanks.

Frauke

**Comment by aharjula** [comment]
`(a|b)+|(bc)+` has the same problem as the first one i.e. the first part matches the start of the second part and as there are no anchors you will get a partial match for just the first `"b"`. `^(a|b)+$|^(bc)+$` would do the trick assuming that `$` is available in the version of STACK.

Maybe some regexp systems will select the longest match if there are multiple branches for a `|` but to me, it seems logical that the first matching would be used like in most programming languages evaluating `or`s.

The [commit log](https://sourceforge.net/p/maxima/code/ci/dd14fa33d3277030f86217435b1753754a9e5b7f/log/?path=/share/stringproc/sregex.lisp) for `sregexp` does not show anything interesting, but maybe the issue is deeper either in the LISP used or the [pregexp](https://github.com/ds26gte/pregexp/commits/master) library it is built on.

**Comment by aharjula** [comment]
Just an update for STACK22 people:
![dollar](https://user-images.githubusercontent.com/980957/165272354-0a7cb638-0af4-4e67-99a8-8175e6c17464.png)
 
Those bad characters seem to work on 4.4beta just fine, both in input and logic and should work on the latest 4.3 versions but I would recommend waiting for 4.4. and not updating to the latest 4.3 versions as they have other issues.

**Comment by nfa019** [comment]
Thanks a lot !
