### ISSUE TITLE
Interpretation of underscore in Stack Question

### ISSUE THREAD

**Issue by amandalavinia** [maths/moodle-qtype_stack#737]
When using underscore in user input, the typesetting engine and the math engine does interpret the same.

E.g. I define the answer to be M_1. 
If user input M_1 or M1, they shown the same in the typesetting window, but only the first will be interpreted as correct when checking the answer.

![Skjermbilde 2021-09-04 kl  14 02 23](https://user-images.githubusercontent.com/89910780/132093784-beaa8cfd-492c-4c3c-acad-77f258b55754.png)

The same happens if I define the answer using M1, then M_1 is not accepted as correct.

Is there a way to make it accept both ways of writing a subscript?

**Comment by sangwinc** [comment]
Background on this issue is here: https://docs.stack-assessment.org/en/Authoring/Author_FAQ/#how-can-i-use-subscripts-in-stack

**Comment by christianp** [comment]
We resolved this in Numbas by rewriting `x1` to `x_1` at the parsing stage. See numbas/Numbas#753.

**Comment by aharjula** [comment]
Chris,

Given the syntax needs that physics and chemistry might have, I would really not like to see any new globally enabled mechanisms for this. Should this be solved by applying some form of an input filter then that filter should be an option that could be toggled for the question or at the input level.

Christians solution is probably something that would work, but given the amount of global "magic" we already have around the underscores and the way those are used in different fields I would indeed prefer this to be something that the author chooses and not something that we force for all. Here the author has already selected whether to force single letter variables and apparently the fix for `x1 => x*1` has not been applied so who are we to now decide that all `x1 => x_1`, it needs to be an elective thing...

As to the original problem:

1. One can forbid one of the forms as a forbidden word and thus force the students to use the "correct" one. Obviously not a bright idea. Especially, if one needs to remember to do this for all the variables.
2. One could do manual substitution of selected identifiers in the feedback variables. Or define the variants as equivalent earlier in the logic. Again a general filter would make things simpler as remembering to deal with all the possible variables is a bit tedious.

**Comment by sangwinc** [comment]
Yes Matti,
I agree this should not be some kind of universal thing!  What about a Maxima function like `exdowncase` which you can apply to the argument of an answer test?  Individual question authors can choose to apply this function either in the feedback variables or individual answer test.  This has an advantage of not adding more options to the inputs etc.
Chris

**Comment by sangwinc** [comment]
Any comments on this @aharjula or should I merge this back into dev?

**Comment by aharjula** [comment]
The filter makes sense, I don't object to this I just need to remember to add an option on the Stateful side to use that once it moves to the next STACK and this is out.

**Comment by sangwinc** [comment]
Thanks Matti, I'll merge this code into dev to make sure the fix is in the next release.
