### ISSUE TITLE
Compact feedback not displaying symbol

### ISSUE THREAD

**Issue by mkraska** [maths/moodle-qtype_stack#739]
Two of three response trees of the attached question don't work properly. The first tree is a formative one, followed by two compact ones, all operating on the same inputs.

The nodal feedback is displayed correctly and the score is computed correctly but the symbol from the compact feedback is missing. I suspect accidental interference with internal variables, but that is just a guess.

![image](https://user-images.githubusercontent.com/12987918/133600687-e883f8fc-c7b6-4bd5-abf3-7a8b1d619e95.png)
[quiz-MMM-FBD Tutorial Kräfte ausrichten-20210916-1302.zip](https://github.com/maths/moodle-qtype_stack/files/7177145/quiz-MMM-FBD.Tutorial.Krafte.ausrichten-20210916-1302.zip)

**Comment by mkraska** [comment]
one more observation: the Preview score field says "incomplete answer" even though both input fields are filled with the model answer (when pressing "correct answer" in the preview field or when providing the correct answer interactively)

Here is a new version of the question with improved model answer but that does not make a difference.

[quiz-MMM-FBD Tutorial Kräfte ausrichten-20210916-1733.zip](https://github.com/maths/moodle-qtype_stack/files/7179145/quiz-MMM-FBD.Tutorial.Krafte.ausrichten-20210916-1733.zip)

**Comment by stebac** [comment]
Hi Martin,
I've had similar problems in the past and my guess is, that this is due to either feedback variables or nodes of the prt which cannot be evaluated correctly. At least this would cause the same behaviour. 
Stephan

**Comment by mkraska** [comment]
Hi Stephan, thanks a lot, that hint pointed in the right direction. Indeed, in the feedback variables there was an expression which did not evaluate correctly, yet was not used further on in the PRT, so that the feedback did not indicate why there should be a problem.
After removing the culprit, it works as expected. 

BTW, I found another hint on the problem: In the response summary of the preview:

`Loslager: # = | ATAlgEquiv_STACKERROR_SAns. | Loslager-1-F`

**Comment by sangwinc** [comment]
I am trying to develop better run-time error messages, especially in the question checking page.

**Comment by mkraska** [comment]
Thanks, Chris, anything would be better here than silently dropping the symbol. Would re-directing Maxima messages to the browser console  an option?

**Comment by sangwinc** [comment]
Sorry it has taken me so long to review this question in detail - the start of term has been super busy....

Your question was missing question tests.  Just adding a test which checks if the teacher's answer was actually marked as correct by the PRT would have revealed this runtime error.  You can bulk test all your existing questions and easily add in this test.  It saves everyone a lot of time.

I've been reflecting on the runtime error in the feedback variables.  We need this error message in the testing page but NOT on the student page.  Some questions use the feedback variables for computation which might end in an error and we'd need to trap the error.  So, just because some question variables throw an error should not be visible to students.  A difficult balance.
