### ISSUE TITLE
Feature request: allowing one PRT to access the feedback variables of another PRT

### ISSUE THREAD

**Issue by azampa** [maths/moodle-qtype_stack#740]
Many times I need to use the computations done in a certain PRT to analyse the answers in another PRT. Up to now the only way to "do" this is to copy part of the code of the former PRT to the latter, duplicating it. This has at least two disadvantages: the first concerns the time of execution, the second is that the latter PRT runs only if the inputs used in the former have been entered by the student.
An example case is the following: you want to ask a student to establish if a statement, as (A &wedge; &not;B) &vee; (B &wedge; &not;A) is a tautology, a contradiction or neither, and to justify the answer compiling a truth table.
A first PRT analyses the truth table in order to establish if all possible cases have been entered, if there are contradicting lines in the table, if the values of the statement are all correct, ...
The second PRT checks if the answer regarding the type of statement is correct or coherent with the entered truth table (you would like to accept correct answers even if not justified by means of the truth table, probably reducing the score in this case, or to accept wrong answers that are coherent with a wrong truth table). The second PRT needs to know if the entered truth table corresponds to one of the three types of statements in order to check coherence of the answer, but the analysis has almost entirely been made in the first PRT, where to a suitable variable (e.g. tp) can be assigned the type (tp: t if the truth table corresponds to a tautology, tp: c for contradictions, tp: n for neither tautology nor contradiction).
Of course the answer concerning the type of statement could be entered without entering the truth table: in this case the variable tp is unbound. All this can work if
- PRTs are evaluated in an explicit order (e.g. PRT1 is the first, then PRT2, then PRT3, ...) so a PRT can know something about preceding PRTs
- there is a way to know if a variable is unbound (STACK could define a predicate _unboundp_ in order to avoid the use of _values_, which is forbidden).

Another solution could be to allow PRTs to change the values of question variables, against which following PRTs could test (in this case too the order of execution of PRTs is important).

**Comment by sangwinc** [comment]
Gosh, the design keeps the PRTs separate and this is really "baked in" to the whole model.  This separation makes it possible for one PRT to fire when another PRT depends on an invalid input.  I really don't want to make the design more complex!  

Matti, is this something in the stateful model, and do you have any comments?

**Comment by aharjula** [comment]
A PRT may never rely on anything in another PRT, it needs to be atomic and it must not have side effects, this is very much my view. The way the future compiled/single-pass PRTs that handle #150 and other issues are very intentionally built so that any values bound inside the singular PRT processing function stay local and could not be seen in another PRT executed later in the chain. This is primarily done to avoid unexpected side effects. This also applies to question variables, which are turned to local variables for the PRT, i.e. even though the compiled PRTs might be executed in the same CAS session modifying those variables in PRT1 would not be visible in PRT2 no matter what the order of execution of those PRTs would be.

"Changing values of question variables" sounds like Stateful, even in that context the moment a PRT changes the value of any of the so-called "state-variables" (in Stateful terms triggers a transition) the processing of the remaining PRTs (of that scene) stops as the question switches state/scene and the world has changed.

Now I have had an idea, that I have not explored further that might be relevant here. In the input2 system, the validation logic will be extended in various ways and at some point, I even thought of something called "validation variables" i.e. something not entirely unlike "feedback variables" but tied into the input instead of the PRT and would thus be shared for all the users of that input. However, I dropped that idea mainly because I only saw use for such logic in cases where the validation would act on groups of inputs and PRTs are already the logical feature dealing with groups of inputs. Currently, input2 also includes the "customised validation box" feature that allows multiple inputs to share a single validation message and to control the layout the message in more complex ways. The current idea is that the message box would not override the validity of the member inputs, but it might be extended so that there could be additional "validation variables" present there that could allow one to do _validation in relation to other inputs_ (which is something that might be quite useful) and maybe leave something in the session for use in PRTs. However, as validation would happen in a different session than PRT evaluation that something would need to be redone in the PRT session anyway but at least it would be shared by the PRTs. But overall, I don't like the idea of anything from the validation leaking to PRTs any more than I like the idea of PRTs leaking over to other PRTs.

I would rather not see those "validation variables" being used for PRT shared features, but as the "compiled PRTs" thing will also bring in the raw-string presentation of inputs into some places and we could use that same to deduce the validity of the inputs a "common feedback variables" that could contain code that the author could write with conditionals that would protect from using missing inputs and would then produce shared (but not mutable by PRTs) context for the PRTs. But I am not a fan of this either, it would be an extension of the question model that very few would need and most would probably use wrongly. To me, the whole issue of evaluating something that is so slow that it is noticeable in the PRTs is probably an issue elsewhere and should be solved if there is a need to solve it using other means. If this is only about maintaining repeated code then maybe the #691 style include logics could be extended by local cloning as an option, i.e. annotate some section in one PRT somehow and include it into another, not a performance improvement but maybe would simplify code maintenance...


Unrelatedly:

In case it is not clear, this is what the "custom validation box" in input2/Stateful can do, it is entirely customisable using CASText and as you can evaluate pretty much anything in CASText it can even run answer-tests if need be:

![Screenshot_2021-10-02_14-48-15](https://user-images.githubusercontent.com/980957/135714777-ddf64723-02ad-4302-b3ca-2188bdb8942c.png)

The corresponding configuration for that is, some special variables are present and the rendering of invalid and missing values is being overridden by the system, the raw values and the state of the values is available for logic if need be:
```
<p>Your answer was interpreted as:</p>
<table style="margin-left:auto;margin-right:auto;">
    <tr>
    	<td style="text-align:right;">\(u(x)=\)</td><td style="padding-right:2em;">{@ansu@}</td>
       <td style="text-align:right;">\(v'(x)=\)</td><td>{@ansdv@}</td>
    </tr>
    <tr>
    	<td style="text-align:right;">\(u'(x)=\)</td><td style="padding-right:2em;">{@ansdu@}</td>
       <td style="text-align:right;">\(v(x)=\)</td><td>{@ansv@}</td>
    </tr>
</table>
[[ if test="not (%_valid_ansu and %_valid_ansdv and %_valid_ansdu and %_valid_ansv)"]]
<p>Please fill in all four correctly.</p>
[[ else ]]
<p>Now that all four have been given use the "check"-button to check them and if they fill the conditions we will move onwards.</p>
[[/if]]
[[list_errors:ansu,ansdu,ansv,ansdv]]
[[list_variables:ansu,ansdu,ansv,ansdv]]
```

**Comment by sangwinc** [comment]
Thanks Matti,
Interesting idea of having computation tied to the input, or groups of inputs.  That might be a longer term solution.  For now, I'll close this issue.  
Chris
