### ISSUE TITLE
Misleading german translation of error message

### ISSUE THREAD

**Issue by mkraska** [maths/moodle-qtype_stack#741]
If two PRT branches have the same answer note, we get an error message:

> Duplicate answer notes detected in this potential response tree.

The german version says

> Doppelte Antwortknoten im Antwortbaum erkannt. 

This is misleading, because "Antwortknoten" means "answer node" instead of "answer note". 

The correct translation would be

> Doppelte Antworthinweise im Antwortbaum erkannt. 

STACK itself produces duplicate answer notes by default in certain situations, e.g.

- create nodes 1, 2 and 3
- delete node 2, now previous node 3 is node 2, answer notes still being PRTname-3-T/F
- create another node, this is the third node and silently gets the same default answer notes

It would be good to check new default names for clashes at generating them and not at save time (where a lot of material might have been added and then fails to save if the actual problem can't be realized)

**Comment by sangwinc** [comment]
Sorry it has taken me so long to deal with this - busy start of term.

If you need an urgent fix then you can download and modify the language pack locally: https://docs.moodle.org/311/en/Language_packs

I'm hugely grateful to the team of colleagues who have helped to translate moodle, and STACK.  But I've had very little contact with most of them. A lot of the translators are not maths (or STACK) experts, and so it is highly likely they will not have understood where the string is actually uses, and hence the best translation.  To fix this globally (please do!) you'll need to contact the translator through

https://lang.moodle.org/

Because this isn't really a bug with the plugin itself, I'm going to close the issue here.  Thanks for reporting it, and please to contact the translator with your suggestion.  Or you could signup and review and improve the whole translation of the plugin itself.
