### ISSUE TITLE
Expand the context variables

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#758]
We need to allow question authors to place anything which is legitimately inside the question variables into the context variables to allow situations like this to propagate into the PRT.

[LL,UL]:rand([[a,b],[c,d],[s,t],[m,n]]);
assume(UL>LL);
assume(LL>0);

**Comment by aharjula** [comment]
The easiest way to do this is to simply prepend the question variables in their entirety to the session that executes PRTs. It is actually quite fast as you might see in the castext2-branch. Picking parts of the vars to save room or time is pretty pointless as the costs that were saved 10-15 years ago are no longer relevant and we have spent the last five years replacing the relevant things with more performant bits.

Is this still about the issue of validation message rendering needing to happen in an inert context where there is absolutely no possibility of variables expanding, due to them being defined? Surely we can easily wrap the validation message things with logic that makes sense:
```
(%i1) ta:4;
(%o1)                                  4
(%i2) tex1(ta);
(%o2)                                  4
(%i3) block([ta],tex1(ta));
(%o3)                              {\it ta}
```
We have a parser that will easily identify exactly what needs to be protected in addition to the existing logic which stops those values from being outputted.

I do understand that context-variables were a band-aid for the old input system so that it could allow some tuning of validation messages, but we should probably start taking the steps towards input2 and start removing this and using the whole question vars and finding some other means for that validation message issue if it is necessary.

**Comment by georgekinnear** [comment]
This has just come up for me again, in a question I wrote a while back about integration:
[questions-FAC 23-24-8.4.2 Partialfracs hence integrate 1quad-20231115-1014.zip](https://github.com/maths/moodle-qtype_stack/files/13363208/questions-FAC.23-24-8.4.2.Partialfracs.hence.integrate.1quad-20231115-1014.zip)

In the randomisation, I have:
```
a:rand([2,4,6]);
b:-a
assume(x>a);
```

This used to mean that when I later integrated something like 1/(x-a), Maxima would give the answer as `log(x-a)` rather than `log(abs(x-a))`.

The behaviour has changed since I wrote the question, so it now has the `log(abs(x-a))` version as the model answer and students were getting marked incorrect if they missed the `abs` (which is not what I wanted here).

The fix in this case was just to change the assumption to `assume(x>6)` which works in every random variant. But I can imagine other cases where the assumption really relies on randomised variables.

**Comment by georgekinnear** [comment]
Just to check, does this mean the `assume(x>a)` example above will work in the next version?

**Comment by sangwinc** [comment]
No George, this issue is not yet fixed.

**Comment by sangwinc** [comment]
An example confirming this issue is fixed is here
https://github.com/maths/moodle-qtype_stack/blob/master/tests/helper.php#L3536
