### ISSUE TITLE
Add "narrative" to PRT nodes

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#761]
I'm proposing to add an optional "narrative" field to each PRT node.

The question author can add a note (in free text) explaining what the purpose of the test is.  This could really help someone else read through the question, and will make much more sense in reports.  We could use the answer note and make this meaningful, but in practice people don't use it this way.

Like all documentation the narrative (if used) will only be as good/accurate as the author makes it.  However, I've been doing a lot of analysis of students' responses and there is a lot of back/forward between the report and the question edit form which is really tedious.

**Comment by aharjula** [comment]
Why? We already have the name field and it allows one to do much, it even keeps the description short. The current "name is node number logic" is a quite pointless way of using that existing field in the DB. Anyway, the compiled PRT branch would be the ideal place to make names or narrative labels a thing.

This is how the name field makes Statefuls PRTs easier to read:
![narrative](https://user-images.githubusercontent.com/980957/145024287-33a201e6-8b21-4a14-9833-e06a01ad7150.png)

Stateful does place "description" fields in many other places and encourages descriptions, but for now, I believe that the node name should be enough for PRTs. But PRTs it is nice to have short (name like) descriptions so that they may be easily placed into the graph representation of the PRT.

In any case, if there is a new field it must be a node thing and not a branch thing, the branches are already quite full, and will be even fuller if some ideas about complex or vector-valued scoring go anywhere. Also, the question-tests could have their own narrative descriptions, again Stateful uses names for the test cases so that the listing is short and fits the preview windows.

**Comment by aharjula** [comment]
Of course, [this](https://github.com/maths/moodle-qtype_stack/blob/24308fee8c0ff9c39ad7e5ab05fc1111254bbbb6/db/install.xml#L90) would need to be longer. Something like [this](https://github.com/maths/moodle-qtype_stateful/blob/abe41c6ec199ad3712512dcc51fb6d1e03d30436/db/install.xml#L129).

**Comment by timhunt** [comment]
I think I am with Matti. Let's use the Node name for this.

Your propose field name of 'Narrative' was not very self-documenting. I had to read your explanation before I understood it.

**Comment by aharjula** [comment]
If we are doing PRT mods I have one that has been floating in my mind for a while. A fail-flag. What it would do would be as follows:

- All branches would have a boolean setting, a fail-flag, any branch could be marked with it by the author
- If at any point the evaluation of the answer would go through a branch where that flag has been set a variable would be set
- All nodes could check for the current value of that fail flag variable `AlgEquiv(PRT_FAIL, true)`...
- Not all nodes or PRTs have branches marked with this and the default for existing would be `false` i.e. not-fail

Now, why would I want this? If you look at the above screenshot you notice that in it we have a series of tests in sequence but each of them exits the PRT as there is no easy way of letting the following nodes know whether we have already failed. This only the first failed one will generate feedback as the remaining ones are skipped. In this case, I would like that tree to not have those red arrows but instead of them a single test before the final grading node that would check the overall fail state and exit if the flag is up. In the case of Stateful it would affect transitions and scoring but for STACK a node checking for the fail flag would probably just adjust scores.

I have seen cases where people have duplicated nodes because they have not been able to route the traffic in the PRT easily enough, and in most cases that they have not duplicated things they have simply not given all the feedback from all the additional tests they might have wanted to give. Alternatively, people have also done the grading in feedback variables to overcome this issue and those are PRTs that are truly annoying to read. Often, the feedback variable logic however distils down to evaluating a fail-flag used just as described above, and the evaluation essentially repeats the tests of the nodes.

This would of course lead to many trees turning to lists but it could make authoring easier and simpler to test.

And know that the castext2 branch PRTs do not have this but they currently allow the author to see the path traversed (in the nodes sans, tans and options fields as well as the points and penalties and feedback) and they could if they so wished read from it the branches that have been activated. We probably do not want that as if we have that path accessible the function of the PRT code will be forever fixed to using those data structures with those names. So we should make those names forbidden to access so that the PRT evaluation state could not be seen through them.

**Comment by sangwinc** [comment]
Ok, thanks folks.  I will have a look at updating the "name" field accordingly.

The only down-side I can see at this point is the change breaks back-compatibility when people use longer names.  I.e. people with older servers will not be able to import questions with long names.

**Comment by timhunt** [comment]
I don't see that as a huge issue. Certainly, it is only a transient one.

**Comment by sangwinc** [comment]
Agreed, and is true of many other improvements.

**Comment by aharjula** [comment]
Not an issue to me either, the people that just cannot update will always have to work with old materials and it is not likely that everyone will immediately start naming nodes.

Or you could simply wait for STACK 5 or whenever we mess up the inputs, at that point, this is the least of the compatibility problems. When that hits we can always map the old inputs to new ones but mapping backwards is never going to be an option and the old installs won't have a clue about the new format.

Anyway good that the XML-dumps now have version information, so that it is easier to identify if we have names or numbers.

**Comment by jcopado** [comment]
Hello everyone, first time writing here :)
I am Jesus Copado, STACK question plugin for ILIAS developer.

On this topic I agree with Chris, I would better add an extra optional field, than modify the node's variable type.
It will improve usability for authors a lot, so they can describe with words, the purpose of the node. Letting the users to change the name will result on huge node names, that will disturb the User Interface and the prt graphic presentation.

With an extra textfield on the node is everything much easier, I think.

**Comment by aharjula** [comment]
Personally, I would think that if the authors see the UI or the graph being disturbed by overly long names they would be able to self-correct and choose shorter names. And the name field would obviously not be text-area thus discouraging writing long things.

**Comment by aharjula** [comment]
Also if we need longer "narratives" I would rather place them at the PRT-level, if one is doing so complex binary tests that they cannot be easily described in a handful of words one is probably also doing pre-processing and other complex things worth describing. However, one can already do that as a comment in the feedback variables field so we already have this capability.

**Comment by jcopado** [comment]
I also agree with Matti's last comment, it would make sense to include this "narrative" at the prt level, but still think that we need a new optional field to improve usability for authors, even if everything is described in the docu, I did never see any stack question with this kind of comments in the feedback. I can see this solution not as a new feature, but as improving usability small rework. Much smaller than changing the variable type of the nodes from int to string in the whole plugin and db.

**Comment by timhunt** [comment]
But, actually, there are alredy ways to add a narrative to PRTs. For example, you could add a comment in the Maxima code for feedback variables. So, I would just make the name change now.

**Comment by aharjula** [comment]
Ok, I guess we are getting out of scope and my feedback-variables comment made a mess.

 1. The use of the name field should not mean any change to the data-type other than the length. We are not talking about the id-column we are talking about [this one](https://github.com/maths/moodle-qtype_stack/blob/24308fee8c0ff9c39ad7e5ab05fc1111254bbbb6/db/install.xml#L90) and the ones on lines 77, 99 and 106 which would need to be tuned to be strings/varchars longer than 8 characters maybe 128 would be enough? As long as I know there are less than 10 places in the code where that field is used and in the castext2 branch there are only a handful so changing that should not be a problem. Unless ILIAS has a wildly different database schema?
 2. One of the points of the narrative field would be to provide labels for analytical tools so any static narrative description at the PRT level would be useless, having it at the node level gives us the ability to pick the descriptions that are relevant and show those. Traditionally, those that know have used the answer-notes as the way of generating labels for analytics, but apparently, most people leave them to defaults and thus they are pretty much pointless unless you read the whole PRT and figure out what the bit does. Simply naming the node and knowing the result (true/false) of the test should function for most use cases thus making answer notes somewhat pointless, but then you could use answer notes for other types of things that do not care about the node name.
 3. It would be even better if the analytics tool would not need to re-run the PRT with the inputs to get these classifications and narratives/names/answernotes. Tim would it be a bad thing if we would push the paths (nodes/branches visited and the answernotes generated) through the PRT(s) into the attempt_step_data? Or am I forgetting something obvious and these are already present somewhere else in the database? Basically, I might in the screenshot above push to step data a JSON-list like '[[["do the parts match", true], ["du matches u", true], ["dv matches v", false]],["answernote1",...,"answernoteN"]]' into a var named by the PRT name or some such, just for analytics use. I know it is caching but the results change when STACK or the question gets upgraded and it is hard to know what it was during the first run...

**Comment by aharjula** [comment]
@sangwinc so I was thinking of doing this in the castext2-branch, going for 128 char limit for the node names. Should we at the same time make it possible to select the root node, or is it still automatically the topmost node? The nodes are in any case ordered by the database ID i.e. creation order.

Planned as follows:

1. Validation will never allow a PRT to have two nodes with the same name (after trimming). Also, a name must not be an empty string or just whitespace.
2. Editor field is visually much smaller than 128 chars.
3. Database upgrade will replace all existing node names with "Node $nodename+1". The PRT root will also get upgraded.
4. Import logic will include similar name translation for imports with no version information or an older version.
5. Editor allows renaming of nodes, renaming will also rename the next-node values in other nodes, and the root node.
6. Editor will not allow switching of names of nodes in a single operation, this is due to 5. above being a problem if you do that.
7. The default names from now on are "Node N" and N here starts from 1. Like before the smallest free N will be selected.

After all this, every bit of code that does `$key + 1` style logic is probably wrong, so the analysis side will have trouble. The keys will now be actual names.

**Comment by timhunt** [comment]
I don't think that this change should be mixed up with other changes.

Best to do a sequence of small canges, each of which is completely successfully (meaning merged into master), before moving on to the next.

Remember the tidyquestion.php script. This is the current way to re-number PRT nodes. We could start with that being the only recognised way to rename them.

**Comment by aharjula** [comment]
Well given that castext2-branch is already rewriting PRTs i.e. compiled single pass PRTs it makes sense to do any mods requiring changes to PRT logic/model there and this does do quite a lot as the editor side uses interesting indexing. So instead of bringing up all sorts of details to the editor from the old system why not do it from the new system instead.

And before anyone asks castext2 is the new CAS side evaluatable compiled and cached version of castext and why it happens at the same time as PRTs is because the PRT evaluation is now a single pass process that also generates the feedback in the same call. So they are not really small things that make sense to separate from each other.

**Comment by sangwinc** [comment]
Matti, when do you plan to merge castext2 back into master?  I'm inclined to agree with Tim, and aim for smaller regular changes if at all possible.

**Comment by aharjula** [comment]
Whenever you first test it and give some feedback, as stated there are quite a few open questions and design decisions that you have to agree on. Basically, someone has to decide how much of the old gets carried around just for the old unit tests and all that.

**Comment by sangwinc** [comment]
This issue is now rolled in with issue #784.
