### ISSUE TITLE
Workaround to forbid functions

### ISSUE THREAD

**Issue by chigle** [maths/moodle-qtype_stack#765]
Re: https://github.com/maths/moodle-qtype_stack/issues/623#issuecomment-733148515

I would like `x*(t)` to be accepted as valid input but not `x(t)`. 

I know this is a suggested feature for future releases, but would it be possible to manually forbid specific functions or enforce a fixed list of expected variables in the student answer in STACK ver. 4.3.9 (2021072200)? For example, adding "x(" to the Forbidden words does not help.

**Comment by aharjula** [comment]
Unfortunately, 4.3.9 nor any of the current development versions has no type specifiers for the forbidden/allowed words. To the logic those are just identifiers or predefined sets of identifiers. While the logic at the level of (security) validation does know about variables vs. function names and can distinguish between `system:[...]` and `system("rm /")` and knows that the latter one is bad while the former is not, it does not get typed information from the forbidden words and just considers all usages equally bad.

It is possible that in the future we could include some ways of giving typed information in the forbidden words, maybe `y,z,fun:x` could mean "forbid all uses of `y` and `z` and the use of `x` as a function". But there is a lot of things in the development queue that has been stuck for the whole pandemic and really needs to come out so that we could get to work on the input-system rework which is probably the place where this type of a feature would belong.

So, sorry not now, and probably not any time soon, but when input2 comes out you can expect this to be a feature of it.

Not in validation that is... In the grading, you could still detect any use of any type and give 0-penalty valued feedback if you see those. For example, you could have this type of a function in your feedback-variables and you could check if it finds `x` as a function:
```
all_ops(%_expr) := block([%_edge, %_next_edge, %_tmp, %_op, %_result],
 /* Returns a list of all the operators and functions
    in use in the expression. Turn it to a bag if you need
    the counts or a set if only the existence matters. */
 %_next_edge : [%_expr],
 %_result : [],
 while length(%_next_edge) > 0 do (
  %_edge : %_next_edge,
  %_next_edge : [],
  for %_tmp in %_edge do (
   %_op : safe_op(%_tmp),
   if not (%_op = "") then (
    %_result : append(%_result, [%_op]),
    %_next_edge : append(%_next_edge, args(%_tmp))
   )
  )
 ),
 %_result
);
```

**Comment by chigle** [comment]
Thanks very much!

**Comment by aharjula** [comment]
Just in case you chose to use that workaround you should make sure that `all_ops` is not the name of the function in your solution. `all_ops` with the above behaviour is now going to be a part of STACK and will be marked as something that cannot be redefined at author level as it will have a role in the internal logic of STACK.

**Comment by chigle** [comment]
Thank you. I would also like to suggest a complementary restriction to forbid _accidental use of functions as variables_, such as a unit step function. For example, I need to allow `u(t-1)` but not `u*(t-1)`.  In older version of STACK it was possible to ban this by adding `u*` to the forbidden words, but it does not seem to work in 4.3.9.

As a temporary workaround, I wonder if you could suggest a Maxima way to convert every instance of `u*()` into `u()` in a student reponse (short of duplicating all PRT tests for the case of `u*()`)?

**Comment by aharjula** [comment]
I tried but cannot do it as those parentheses seem to disappear and are not returned when asking for the arguments of an operation. But something like this could be used to recurse over the expression tree and rewrite it if only one could detect the relevant pattern.
```
ustartofun(expr) := block([simp],
 simp:false,
 if safe_op(expr) = "*" and args(expr)[1] = u and safe_op(args(expr)[2]) = "(" then (
  return(funmake(u, [ustartofun(args(expr)[2])]))
 ) else if safe_op(expr) = "" then (
  return(expr)
 ),
 return(funmake(op(expr), map(ustartofun, args(expr))))
);
```

Might be that this cannot be done at the CAS level, and would need to be during PHP side input processing, but it would need parameters to declare what to act on and that is something that again would require that new input system.

**Comment by chigle** [comment]
Thanks very much again - looking forward to future releases with STACK!

**Comment by sangwinc** [comment]
This can now be solved by using the bespoke validators.
