### ISSUE TITLE
Update to 4.3.10 changes how variable is displayed

### ISSUE THREAD

**Issue by larsbonczek** [maths/moodle-qtype_stack#773]
After updating from 4.3.8 to 4.3.10, the way an expression is evaluated seems to have changed. The question variable `f: 2*x, x=2` used to be displayed as `4`, now it is displayed as `2*x` when used in the question text. Why does this happen?

**Comment by aharjula** [comment]
Unfortunately, there seems to be a logic bug that stops evaluation flags from being respected if they are used in question variables or feedback variables. Should you wish to have this fixed in your current STACK installation you could replace [this line](https://github.com/maths/moodle-qtype_stack/blob/8ed9f6777cb4f5e752c579d90cf70327e84e05ba/stack/cas/keyval.class.php#L332) with [these](https://github.com/maths/moodle-qtype_stack/blob/c95d43ad8e790bbe29bc6925b24727d9aac895e6/stack/cas/keyval.class.php#L401-L405). Problem is that that fix requires that you then save those questions again to re-compile them, as the error has been cached to improve "performance".

A separate bug-fix release might be released at some point but we might wait until a bigger release and fix this with many others. The release upgrade logic handles that re-compile step automatically so one would not need to re-save/compile anything...

Anyway, my bad, my code and my fault and so on. Sorry about that.

If you only have this issue with a few questions you could also rewrite those evaluation flags yourself so that the compilers error would not affect them e.g.:
```
f:ev(x^2,x=2);
/* Or even, */
ev(f:x^2,x=2);
```
