### ISSUE TITLE
Convenience tool for using JSXG text fields in PRT

### ISSUE THREAD

**Issue by Bjoern-Ge** [maths/moodle-qtype_stack#776]
Hello everyone,
In many questions, I do use the opportunity to move a point in JSXG and analyse it with the PRT. For this, I do use the function 
stack_jxg.bind_point(stateRef, p);

Sometimes I like to use text fields in JSXG and analyse them with the PRT.
I didn’t find an easy-to-use function, like for points, for that. Is there a function for that? If not, I think it would be a nice thing to have.
 
I used the construction below that works, but might not be the best way.

Best regards,
Björn

`[[jsxgraph  
input-ref-ans2="stateRef2" 
input-ref-ans3="stateRef3" 
input-ref-ans6="stateRef6" 
input-ref-ans7="stateRef7" 
input-ref-ans8="stateRef8" 
input-ref-ans9="stateRef9" 
input-ref-ans10="stateRef10" 
 ]]
        JXG.Options.text.fontSize = 20; 
        const board = JXG.JSXGraph.initBoard(divid, {showCopyright:false,showNavigation:false,
            boundingbox: [-.7, 2, 3.5, -2], axis: false,
              drag: {
                      enabled: false // Allow dragging
              } ,
              zoom: {
                        factorX: 1,  // horizontal zoom factor (multiplied to JXG.Board#zoomX)
                        factorY: 1,  // vertical zoom factor (multiplied to JXG.Board#zoomY)
                        wheel: false,     // allow zooming by mouse wheel or
  				   // by pinch-to-toom gesture on touch devices
                        needShift: true,   // mouse wheel zooming needs pressing of the shift key
                        min: 1,  // minimal values of JXG.Board#zoomX and JXG.Board#zoomY, limits zoomOut
                        max: 1, // maximal values of JXG.Board#zoomX and JXG.Board#zoomY, limits zoomIn
                        pinchHorizontal: false, // Allow pinch-to-zoom to zoom only horizontal axis
                        pinchVertical: false,   // Allow pinch-to-zoom to zoom only vertical axis
                        pinchSensitivity: 7 // Sensitivity (in degrees) for recognizing horizontal or vertical pinch-to-zoom gestures.
                        }  
     });
board.attr.pan.enabled = false;
board.mode = JXG.Board.BOARD_MODE_NONE;
        var p01 = board.create('point', [0, 0], {fixed: true, name:'alle', label:{autoPosition: true, offset:[10, 10]}});
        var p11 = board.create('point', [1, 1], {fixed: true, name:'A', label:{autoPosition: true, offset:[10, 10]}});
        var p12 = board.create('point', [1, -1], {fixed: true, name:'nA', label:{autoPosition: true, offset:[10, 10]}});
        var p21 = board.create('point', [2, 1.5], {fixed: true, name:'B', label:{autoPosition: true, offset:[10, 10]}});
        var p22 = board.create('point', [2, 0.5], {fixed: true, name:'nB', label:{autoPosition: true, offset:[10, 10]}});
        var p23 = board.create('point', [2, -0.5], {fixed: true, name:'B', label:{autoPosition: true, offset:[10, 10]}});
        var p24 = board.create('point', [2, -1.5], {fixed: true, name:'nB', label:{autoPosition: true, offset:[10, 10]}});
        var l11 = board.create('line', [p01, p11], {straightFirst:false, straightLast:false})
        var l12 = board.create('line', [p01, p12], {straightFirst:false, straightLast:false})
        var l21 = board.create('line', [p11, p21], {straightFirst:false, straightLast:false})
        var l22 = board.create('line', [p11, p22], {straightFirst:false, straightLast:false})
        var l23 = board.create('line', [p12, p23], {straightFirst:false, straightLast:false})
        var l24 = board.create('line', [p12, p24], {straightFirst:false, straightLast:false})
var stateRefs = [];
stateRefs[0] = null
stateRefs[1] = document.getElementById(stateRef2);
stateRefs[2] = document.getElementById(stateRef3);
stateRefs[3] = null
stateRefs[4] = null
stateRefs[5] = document.getElementById(stateRef6);
stateRefs[6] = document.getElementById(stateRef7);
stateRefs[7] = document.getElementById(stateRef8);
stateRefs[8] = document.getElementById(stateRef9);
stateRefs[9] = document.getElementById(stateRef10);

var inputAttributes = [ 
[-1.5,0.4,'1/2', '' ],     
[0.1,-0.4, '', ' '],   
[1.1,1.45, '', ' '],   
[-1.5,0.55, '1/4', ''],   
[-1.5,-0.55, '1/3', '' ],  
[1.1,-1.45, '', ' '],  
[2.32, 1.45, '', ' '],  
[2.32, 0.55, '', ' '],  
[2.32, -0.55, '', ' '], 
[2.32, -1.45, '', ' ']
]
        var p24 = board.create('point', [0.1,0.4], {fixed: true, name:'{#tans1#}', label:{autoPosition: false, offset:[10, 10]}, size:0});
        var p24 = board.create('point', [1.1,0.55], {fixed: true, name:'{#tans4#}', label:{autoPosition: false, offset:[10, 10]}, size:0});
        var p24 = board.create('point', [1.1,-0.55,], {fixed: true, name:'{#tans5#}', label:{autoPosition: false, offset:[10, 10]}, size:0});

inputAttributes = inputAttributes.map( 
(attr,index) =>{  attr[2] = stateRefs[index] ? stateRefs[index].value : '' ; return attr;});

let inputs = inputAttributes.map( attr =>  board.create('input', attr, {cssStyle: 'width: 60px'}) );

board.on('update', function () {
inputs.forEach(  (currentInput, index) => {
     let stateInput =stateRefs[index];
    if (stateInput && currentInput.Value() !== undefined && currentInput.Value() !== "") {
        stateInput.value = currentInput.Value();
    }})} )
[[/jsxgraph]]
<div style="display: hidden;">
[[validation:ans2]][[validation:ans3]][[validation:ans6]]
[[validation:ans7]][[validation:ans8]]
[[validation:ans9]][[validation:ans10]]</div>
<div style="display: none;">

[[input:ans2]]=
[[input:ans3]]=
[[input:ans6]]=
[[input:ans7]]=
[[input:ans8]]=
[[input:ans9]]=
[[input:ans10]]=
</div>`

**Comment by aharjula** [comment]
Interesting, it is not entirely impossible that such a function could be created but the current (or actually the one to be released this year) version of the STACK-JSXGraph binding logic relies on the objects being JSXGraphs objects so for it the concept of binding to HTML input elements that have been plugged into a JSXGraph might be troublesome. However, should it be so that the change events of those input elements can be listened to through the board element and I suspect they can be then the future version of our script should be easy to extend to deal with this.

The short overview of the future script logic is that everything that gets bound will have its own serialiser and deserialiser functions that can be defined by the author, or that are predefined for those normal bind functions. In this model, the infrastructure then attaches to the input field and the object(s) bound to it and keeps track of any changes to them and uses those serialisation/deserialisation functions to sync them. It should not be difficult to write like this (in the future when one has the new scripts installed):

```
var serialiser = () => inputObject.value;
var deserialiser = (value) => inputObject.value = value;
stack_jxg.custom_bind(stateInputRef, serialiser, deserialiser, [inputObject]);
```

Of course, there could be a specific bind function (e.g. `bind_html_text_input`) that would do that without the author having to write out the serialisation logic. But this would only work if that `inputObject` is something that the board can listen (I feel like it might be so, as I believe it is probably more difficult to not listen than to listen). However, if the input element does not follow the general pattern that our system expects then a separate logic would need to exist alongside the normal JSXGraph objects handling logic.

If one wants to see more of the future logic of the binding system one can look [here](https://github.com/maths/moodle-qtype_stack/blob/be7a3edaf5c18c38fd6ac3dfb57e3f196db1e1e3/amd/src/jsxgraph.js#L285-L297), that is an example of the future systems implementation of the `bind_point_dual`-function. The new logic exists primarily to provide logic for dealing with grouped updates to objects so that morning any will consider the group as a whole to have been touched and dealing with the use cases where some things need to be marked as touched from the start. It also has tools for dealing with variable object count bindings but those have no examples yet.

All that said, I am only adding this to a wishlist and maybe I'll create something after our current backlog clears. I will also need to think about whether this is actually something that can be done in a way that does not cause any additional issues or lead to authors doing silly things just because there is a convenience feature for it. I do have a real fear of a pattern forming using text processing in STACK and that leading to bad places if the barrier to entry for that is too low.

**Comment by Bjoern-Ge** [comment]
Thanks for the explanation. The coming function, you mention, would totally do the job for my case. 
If there is a nice option to bind any kind of object, that's even better than a special one for tests.
I think points are the most common objects, but most others (like text) might be rare.
