### ISSUE TITLE
Forbidden function ntuple

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#777]
The mechanism for preventing students using coordinates exists by putting "ntuple" into the forbidden words.

But we need better error messages for students, e.g. "Coordinates are not permitted in this input".

We need to intercept the error message to be more meaningful than "Forbidden function: ntuple".

**Comment by aharjula** [comment]
Well either you catch it at [the source](https://github.com/maths/moodle-qtype_stack/blob/be7a3edaf5c18c38fd6ac3dfb57e3f196db1e1e3/stack/cas/parsingrules/998_security.filter.php#L382-L389), or you could use the new error class and detect and modify it there. I would rather see the latter so that all the overridden and rewritten errors would be in a single place, i.e. in the error class even though it will cause some issues for me outside STACK.
