### ISSUE TITLE
Question narrative fields

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#784]
In working with teacher over the years a couple of people have asked for a field for "notes" about a question.  This might be a narrative on how and why the randomisation is set, the place of a question in a sequence, or the goals and design of the PRT.

Question authors can, and do, add comments to the question variables, and the feedback variables in each PRT. Some people use this approach for a narrative.

This would be especially useful if more than one person is designing/writing a question.  E.g. the teacher could say.  "I want it to do this..." and a more technical person would then have the notes within the question (not email....) and could resolve/comment etc.  

Like any meta-data I don't expect many people will use it, and there is no guarantee it would be accurate. However, it would be relatively cheap to add another field to the question itself to help authors.  

Comments on this proposal would be especially welcome.

Chris

**Comment by christianp** [comment]
Do it! We have fields for this kind of narrative in Numbas, and they're _very_ useful when you come back to a question years later.

The field should take rich text. Our descriptions typically include lots of mathematical notation to explain code in the functional part of the question.

It will be well-used if made prominent and easy to use.

**Comment by timhunt** [comment]
Have you tried Moodle 4.0 yet? E.g. https://qa.moodledemo.net/question/edit.php?courseid=2

Note that the question bank now has a 'Comment' feature. Does that meet your needs?

**Comment by aharjula** [comment]
Sounds like the description fields in Statefuls question model, in it, there are three places for description:

 1. The question-text field of Moodle questions has no role for a Stateful question so it is the main description of the whole question and has the additional benefit of being what the question-bank displays by default. Have to wonder if I should map this to that `Comment` that Tim mentioned.
  2. Each scene of the question has its own description field where one can write anything they want to describe that scene. As a scene is basically just a STACK question this is probably the closest to that "notes" field you mention.
  3. As state variables are the most important thing in a Stateful question each of them also has a description so that one can document what they are supposed to contain and for what purpose they are to be used etc.
  
There are no description fields for inputs or PRTs in Stateful, I chose to draw a line at that point and assume that people do not want to spread notes everywhere (fragmented documentation is always at risk of becoming inconsistent with itself), those things can be described in the description of the scene and in the case of PRTs, the preferred ways is to do like described in #761, i.e. using node naming or comments in feedback-variables.

**Comment by aharjula** [comment]
Tim, those comments, are they such that they get exported and imported with the question or are they like attempts and need to be exported as a part of a larger context? Typically these "notes" if I understood correctly would be useful even after the iterative creation process of the material and need to be carried with the question forever (i.e. over exports and imports) to help understand its objectives and mechanisms. If those comments don't stick to the question then they would not fulfil that requirement.

**Comment by timhunt** [comment]
I think at the moment, they are not exported/imported, but that is a bug.

**Comment by aharjula** [comment]
Well if I understood correctly the comments tie into users (or are those names just static strings) so import/export of them could be interesting as one would need to also export/import those users or at least create anonymous ones. That might be a problem for material sharing between organisations. And it is not uncommon that a teacher cannot do restores of backups or other things that would require the creation of users due to those rights being removed from their roles, so some people might not be able to import questions due to that or end up importing them without comments and we might lose that history of comments when they then reshare that question.
