### ISSUE TITLE
Support for Maxima's "concat()" command

### ISSUE THREAD

**Issue by taraghi** [maths/moodle-qtype_stack#787]
Hi,

Using the function `concat()`, the question cannot be saved, with the error message: `Forbidden function: concat.`

The package `stringproc` is obviously not missing on the server. Then when I run the `concat` command manually on the server, it appears to work.

We use 
- plugin version `2021120900`
- Maxima version `5.44.0`

Thanks for your help in advance!

**Comment by aharjula** [comment]
`concat()` is forbidden as it allows one to construct identifiers that the old static security system could not check, so we simply fenced it off and pointed to and built alternatives.

If one needs to concatenate strings one can use `sconcat()` which is safe (and more importantly always produces strings) and if one needs to construct variable names or other identifiers one can use the STACK specific `vconcat()` which wraps the normal `concat()` with logic that validates that the identifier built by concatenation is not "evil" and errors out before it can be used if it sees evil things.

We might get back to this in a couple of years, but for now, the function will stay forbidden so that people running on our new security system cannot author materials that recent old ones could not run simply due to a difference in security logic. That might change when we next see a major update that breaks forward compatibility with basic materials.

**Comment by taraghi** [comment]
Thank you very much for your quick reply

**Comment by taraghi** [comment]
@aharjula 
This also seems to affect other functions of the package as well. Trying to use some functions leads to the error message "Forbidden function" (e.g. with `printf()`, `sprintf()`, and `parse_string()`).

 Is there somewhere a documented list of the stringproc functions that are available or not available?
 That would make the creation of the tasks much easier for our teachers.

Last but not least, do you know if there is in general a way to find out which packages are available on a STACK environment?

**Comment by aharjula** [comment]
The functions you listed can be used to do quite interesting things (well `sprintf` might be miss classified if such a function even exists in Maxima). Just imagine what one could do with `parse_string(sconcat/"r", "m", " -rf /"))`, that is the reason why we block these.

The full list of all the classifications we have done is in the [security-map.json](https://github.com/maths/moodle-qtype_stack/blob/master/stack/cas/security-map.json), but it is quite large so probably simpler to just try.

The actual libraries loaded depends on the version of Maxima in use, with older ones some functionality that has been added to the core has been loaded from libraries.

Quick look at the [code](https://github.com/maths/moodle-qtype_stack/tree/master/stack/maxima) tells me that these should be present: `descriptive`, `distrib`, `functs`, `opsubst`, `sregex`, `stats`, `trigtools`. But note that there is a Moodle setting through which one can load some additional ones if one so wishes. the most common thing that people load through that is `simplex`, it is also the only one currently supported to be loaded through that method, as most of the others whitelisted have become part of the normal STACK libraries... One does not want to load excessive numbers of libraries as that might affect the general response speed and one cannot select which libraries are to be loaded for a particular question (due to reasons too complex to explain here)...

In case it is not clear from our security model's point of view evaluating input directly is not an option so a `parse_string` style function is very much forbidden (again this is the old security model and the forward compatibility issue). But as people have needs for parsing stuff like JSON (people that use JSXGraph may wish to [encode complex structures](https://docs.stack-assessment.org/en/Authoring/JSXGraph/#general-considerations-when-building-interactive-graphs) into JSON) we do have some naive implementations of such parsers in out our library and those implementations most definitely do not play with `parse_string`.

**Comment by thallinger** [comment]
Dear Matti,
  thanks a lot for your detailled reply.

> The full list of all the classifications we have done is in the [security-map.json](https://github.com/maths/moodle-qtype_stack/blob/master/stack/cas/security-map.json), but it is quite large so probably simpler to just try.

I matched the entries in the security map with the functions defined in `stringproc` .
From the 81 functions the following 15 strinproc functions are not available:
`    close, eval_string, flength, fposition, freshline, newline, opena, openr,`
`    openw, parse_string,  printf, readbyte, readchar, readline, sprint`

 Perhaps this list is useful for other STACK users, who run into the same situation.

**Comment by thallinger** [comment]
> Quick look at the [code](https://github.com/maths/moodle-qtype_stack/tree/master/stack/maxima) tells me that these should be present: `descriptive`, `distrib`, `functs`, `opsubst`, `sregex`, `stats`, `trigtools`. But note that there is a Moodle setting through which one can load some additional ones if one so wishes.

  Is there a command which can be entered manually on the server, which displays all loaded packages
   (perhaps together with their version)?
