### ISSUE TITLE
Allow students to type subscripts like F_1x

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#792]
This is a valid atom in Maxima  F_1x.

However, students are not permitted to type this even when "insert *" is set to false.

To allow this we need to have an option to disable 403_split_at_number_letter_boundary for some student's input.
https://github.com/maths/moodle-qtype_stack/blob/master/stack/input/inputbase.class.php#L866

**Comment by aharjula** [comment]
The base of the stack is ready, we just need to fix the topmost layer of the input system so that it allows one to declare these things in more detail. For some reason, the input2 model in Stateful already has an option for just this. and the system seems to work.
![tailendofoptions](https://user-images.githubusercontent.com/980957/165762178-1a6b86e0-46b5-4971-9a26-6a0544c938ee.png)
_That pic only has a fraction of the full option set of an algebraic input in Stateful._

**Comment by sangwinc** [comment]
Thanks Matti!

**Comment by mkraska** [comment]
I agree with the added test cases in the abovementioned commit. I see that F_1x is understood as F_1*x when inserting stars is active. 

What particular "insert stars"? If insert stars for spaces is active, this should not trigger the letter/number boundary filter, so I should get  F_{1x} with insert stars for spaces. I understand that if "insert stars assuming single letter names" is active, then F_1*x is a correct interpretation.

Also, I would recommend to not cascade subscript levels but to replace repeated underscores by spaces or some other delimiter in the one and only subscript level. I am old and my eyes are bad. That's why I don't like tiny symbols.


in `tests/fixtures/subscriptsfixtures.class.php` instead of 

        array('F_1_x', 'F_1_x', '!', '{{F}_{1}}_{x}', '!'),
        array('M_x1', 'M_x1', '!', '{M}_{x_{1}}', '!'),

I would recommend

        array('F_1_x', 'F_1_x', '!', '{F}_{1,x}', '!'),
        array('M_x1', 'M_x1', '!', '{M}_{x1}', '!'),

This essentially means that there is only one level of subscripts. Repeated underscores would be converted to space or delimiter symbols, preferrably kommas.

I know that some people use notation with leading commas in subscrips to indicate derivative. That could be written as u__x (double underscore) and would be correctly formatted as  u_{,x} or u__x_y as u_{,x,y}.
