### ISSUE TITLE
Proposal for ATVariables

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#793]
At the STACK meeting there was a proposal for a new answer test to check if variables in one expression match variables in another.  This is basically a "good idea".  Can the people who want this explain in detail, what they need, what feedback (if any) the test should give, provide test cases and so on?

Also, does the existing "sets" answer test suffice?  E.g. what about the following?

ATSets(setify(listofvariables(ans1)),setify(listofvariables(ta)))

Would this do the job?  I'm happy to add another test if you specify exactly what you need!

**Comment by mkraska** [comment]
I implemented something similar here  [https://github.com/mkraska/meclib/wiki/fb_vars](https://github.com/mkraska/meclib/wiki/fb_vars)

This implementation is based on the discussion in https://github.com/maths/moodle-qtype_stack/issues/662

Test with ATSets looks like this:

![image](https://user-images.githubusercontent.com/12987918/165813816-36c3adbc-b3a2-44f7-86af-904bc7ada041.png)

Mathematically the test is equivalent to the first part of ATVariables(). However, in ATVars() the formatting is more compact (which I prefer in particular for multipart questions).

Also, the second part (comparison of terms) remains to be done then in a separate test. So in total you have three nodes instead of 1 

![image](https://user-images.githubusercontent.com/12987918/165813328-d707afaa-e33d-42c3-a2cc-18cafaf72920.png)

[questions-MMM-Test of ATSets-20220428-1934.zip](https://github.com/maths/moodle-qtype_stack/files/8585108/questions-MMM-Test.of.ATSets-20220428-1934.zip)

**Comment by sangwinc** [comment]
Matti,
I hope this doesn't work at cross purposes with "input2" innovations.  At least the design, documentation, some of the Maxima code and the test cases will help there.

More test cases welcome!
Chris

**Comment by mkraska** [comment]
Chris, thanks for the implementation. It actually seems to exactly adress issue #662, including the selective modes proposed by Matti there.

My proposal actually included a test of algebraic equivalence test for the terms with a given set of variables.
This was mainly meant for formative feedback on expressions with multiple summands.

    tans: 3*a+4*b^2+c*k
    sans: 4*a+4*b^2+c*k^2

`fb_vars(sans, tans, [a,b,c])` would produce the feedback

    Check the terms with a, c.

I have in mind checking of equations of equillibrium, which are sums of contributions of various forces and moments and I want to point the students to the wrong terms.

**Comment by aharjula** [comment]
Chris,

This does not affect "input2" in any way, well of course I will again need to check if it does anything with `stack_validate*` and update the option sets in Stateful, but that is not a major thing, adding options there is trivial... One can bolt anything one wants into the input2 validation step if one wants to do extra validation and if this is more of a PRT thing it exists outside of the input systems realm. To me, this sounds more like a PRT thing that gives feedback after an attempt, but there could again be a matching test in the input validation as well.

In any case, I can't wait for the time when we can eliminate those `stack_validate` and `stack_validate_typeless` functions. They are ugly and seem to have collected way too many things that are a bit unrelated and all that just because all the inputs use one of those functions. In input2 one would not share a single function, instead, the inputs would define their own ones and could compose the rules from smaller and simpler parts as needed thus making it simpler to test separate parts of those rules. A bit like the AST filters separated the parts of the input processing into manageable things...

**Comment by sangwinc** [comment]
I agree Matti, factoring out  stack_validate and stack_validate_typeless functions are long overdue refactoring!   This has all grown up and needs a complete redesign.

**Comment by sangwinc** [comment]
We're not going to add in an extra option to the input.  Instead, we can use the new "bespoke validator" options, combined with @mkraska's fb_vars code. I'd be delighted if someone could document how to do this please.
