### ISSUE TITLE
Command to find out which libraries are available in a STACK environment?

### ISSUE THREAD

**Issue by thallinger** [maths/moodle-qtype_stack#795]
This is a follow-up on issue  #787:
 
> Quick look at the [code](https://github.com/maths/moodle-qtype_stack/tree/master/stack/maxima) tells me that these should be present: `descriptive`, `distrib`, `functs`, `opsubst`, `sregex`, `stats`, `trigtools`. But note that there is a Moodle setting through which one can load some additional ones if one so wishes.

  Is there a command which can be entered manually on the server, which displays all loaded libraries
   (perhaps together with their version)?

**Comment by sangwinc** [comment]
I don't think Maxima has such a command, and since we only use the "load" command we don't keep a record.  You can find out from your server's doc page which libraries are loaded.  E.g. see at the bottom of this page on the demo server
https://stack-demo.maths.ed.ac.uk/demo/question/type/stack/doc/doc.php/

On your server you'll need to go to /question/type/stack/doc/doc.php/ to get the corresponding page.

To find out which version you are using you'll need to know which version of Maxima you have installed, and that can be found on the health check page, but you need to be a Moodle admin to get there.

Chris

**Comment by thallinger** [comment]
Hi Chris,
  thanks for your quick reply. 

>  E.g. see at the bottom of this page on the demo server
> https://stack-demo.maths.ed.ac.uk/demo/question/type/stack/doc/doc.php/

   There the output is `Your site is running STACK version 2021120900 (descriptive, distrib, simplex, stats).`

> On your server you'll need to go to /question/type/stack/doc/doc.php/ to get the corresponding page.

  The page on our server displays: `Ihre Seite verwendet die STACK-Version 2021120900 ().` 

   If I interpret this correctly, then no libraries at all are loaded.

Gerhard

**Comment by sangwinc** [comment]
Yes, it looks like your Moodle admin didn't include any libraries.  Some versions of Maxima don't ship with them (!) which is why a user can include/exclude them.  But, they are useful to talk with your local admins and ask if they will include them. If they do include the libraries they will need to re-create the maxima image.
