### ISSUE TITLE
Presentation of complex numbers

### ISSUE THREAD

**Issue by sohagan1** [maths/moodle-qtype_stack#802]
I'd like to request that STACK modify the Maxima presentation of complex numbers.

When displaying a complex number:
- the real part should always appear to the left of the imaginary part;
- i (or whatever symbol is being used for the imaginary unit) should appear on the right of its coefficient if and only if the coefficient is a specific constant. By "specific" constant, I mean something like 2\sqrt{2}\pi but not things like \( a \pi \), even if \( a \) is denoting a constant.

Examples:

1. `{@ 3+2*%i @}` should display as  `3+2\,\mathrm{i}` 
2. `{@ -3+2*%i @}` should display as  `-3+2\,\mathrm{i}` 
3. `{@ -3-2*%i @}` should display as  `-3-2\,\mathrm{i}` 
4. `{@ 3 - 2*%i @}` should display as  `3-2\,\mathrm{i}`
5. `{@ a+b*%i @}` should display as  `a+\mathrm{i}\, b` 
6. `{@ -a+b*%i @}` should display as  `-a+\mathrm{i}\, b` 
7. `{@ -a-b*%i @}` should display as  `-a-\mathrm{i}\, b` 
8. `{@ a-b*%i @}` should display as  `a-\mathrm{i}\, b` 
9. `{@ %i * 3/5 @}` should display as  `\frac35 \,\mathrm{i}` 
10. `{@ %i * p/q @}` should display as  `\mathrm{i}\,\frac pq`
11. `{@ %i * sqrt(2) @}` should display as `\sqrt2\, \mathrm{i}`
12. `{@ %i * sqrt(2) / 5 @}` should display as  `\frac{\sqrt2}{5}\, \mathrm{i}`
13. `{@ %i * %pi @}` should display as ` \pi \,\mathrm{i}`
14. `{@ %i * 2*%pi @}` should display as  `2\pi \,\mathrm{i}`
15. `{@ %i * 2*%pi / 3 @}` should display as ` \frac{2\pi}{3} \,\mathrm{i}`

Many thanks!

**Comment by sangwinc** [comment]
Thanks Steven,
This is a very sensible suggestion.

Complex numbers, especially the display of complex numbers, is a surprisingly subtle issue.   This is because there is some genuine ambiguity in whether \(a+\mathrm{i}\, b\) is a single object or the sum of two parts.  In mathematics we use this ambiguity to our advantage, but in online assesment we need to be more precise.  There are also issues of unary minus, e.g. _not_ displaying \(1 + (-2)\mathrm{i}\). Similarly we typically do _not_ display numbers like \(0+1\mathrm{i}\), unless of course we want to at which point we need the option to do so!

**Comment by sohagan1** [comment]
Thanks very much. From the testing I've done, this is working like a charm!
