### ISSUE TITLE
Diagram of PRT has too many decimal places

### ISSUE THREAD

**Issue by georgekinnear** [maths/moodle-qtype_stack#821]
The latest update seems to have changed the way the score values are displayed in the diagram of the PRT. They now appear with many more decimal places, making them often unreadable, e.g.:

![image](https://user-images.githubusercontent.com/30723394/180799755-fb36fb71-cb4b-4454-99ac-b09477dce7a9.png)

**Comment by timhunt** [comment]
Just to note that scores are stored in the database to 7dp, so it seems that what is happening is that hte value is coming out of the DB as a string, and never being cast to a float, which used ot happen, and would get rid of the trailing 0s.)

**Comment by aharjula** [comment]
The old database stored floats, but as we now allow those fields to be expressions, the field is now a string field. Chris did not want to chop the trailing zeros during the migration (as that would not have solved the issue with imported materials still having those trailing zeros), so that is why the old materials still have those extra zeros. This should not affect new materials but will cause some annoyance for those that care about this little detail. If it really causes serious trouble, one could parse every single one of those expressions and render them with some specific number of decimal places but do we really want to waste time on that?

If the values are of a sane length in the PRT-nodes in the editor, then the logic still chops the zeros there, and it might be that simply saving the question, the database fields would get filled with those pretty printed values and the bit of logic that renders that graph would get sane values to display instead of the original long ones.

**Comment by georgekinnear** [comment]
Saving the question with no edits does indeed seem to fix this - thanks for the explanation!

Given that these labels can now be expressions, I think the real issue is that in my screenshot, many of them are cut off. e.g. it is not possible to see what is written on the True branch of node 2. Perhaps there's some way to add padding to the left and right of the diagram to alleviate this?

**Comment by sangwinc** [comment]
I can think of no downside to adding some padding in the diagram George, and we'll certainly need this if we have complex expressions in PRT scores. Thanks for the suggestion.
