### ISSUE TITLE
Question from 4.4b fails in 4.4

### ISSUE THREAD

**Issue by mkraska** [maths/moodle-qtype_stack#823]
The attached question was created in STACK 2022022300 (an 4.4b server provided by Matti)

Now our local moodle system was upgraded to STACK 2022071300, which according to the tag list on github should be 4.4.
So I tried the questions from the 4.4b server, which make use of multilingual features and external links. So far the test is a complete fail:

In the preview I get this message

    Rendering of text content failed: this question is broken. Please contact your teacher.
    This text content was never evaluated.

In the question test I get this:

    (%i4) STACK-OUTPUT-BEGINS> The CAS timed out. ] ] ] ]
    Das Feld ""Aufgabentext"" erzeugte den folgenden Fehler: TIMEDOUT
    Das Feld ""Aufgabenvariablen"" erzeugte den folgenden Fehler: TIMEDOUT

[questions-Meclib-FBD demo (l)-20220731-1944.zip](https://github.com/maths/moodle-qtype_stack/files/9229314/questions-Meclib-FBD.demo.l.-20220731-1944.zip)

Can you reproduce the problem? Or should I assume that our local installation is broken?
STACK 4.3 questions seem to work though (with much faster preview than before).

With a minimal working example I could get a question with inclusion to work, perhaps due to less time required for processing the stuff.  Yet, initially it failed and then succeeded when I switched format from Markdown to HTML (in the Marklar editor). But it might just have succeeded in the second try, because after resetting format to Markdown the question still works.

I also have to mention that Matti has set the timeout on his server to 300, yet the error message with lower timeout was different: `504 Gateway Time-out`

Here is the minimum working example, which failed just one time:

[quiz-MMM-Inclusion in question text-20220731-2115.zip](https://github.com/maths/moodle-qtype_stack/files/9229556/quiz-MMM-Inclusion.in.question.text-20220731-2115.zip)

**Comment by aharjula** [comment]
For me, it (at least the topmost linked one) seems to work. Two things come to mind:

 1. `[[lang]]` behaviour if there are no language packs installed? Does the server have multiple languages in use, if not then this behaviour is bad and we need to fix it so that it will work even in a single language installs.
 2. Maxima image could be old. Do try putting in `{@stackmaximaversion@}` into some question text and see if it outputs that expected value matching the 4.4 installation. It is not uncommon to see people forgetting to upgrade the Maxima scripts if the installation is in some sense more complex e.g. using MaximaPool or some other hacks related to Maxima.

**Comment by mkraska** [comment]
Our admin increased qtype_stack|castimeout from 10 to 60, now the questions work.
