### ISSUE TITLE
Grade problem with multi answer question

### ISSUE THREAD

**Issue by steveorulez** [maths/moodle-qtype_stack#845]
Hello,

when you have multiple answers with different grade per each answer you will get only 1 point per correct answer. 

answer1 : 2points
answer2: 2points
total points with correct answers: 2/4

![image](https://user-images.githubusercontent.com/4101369/186088096-870e0761-2050-43d8-95cb-7ade37bf2196.png)

it is working on moodle 3.10.10+ and STACK version 4.3.10 for Moodle 3.5+ 2021072200

it is not working on moodle 3.11.9+ and STACK 4.4.0 for Moodle 3.9+ 2022071300

if you need i can upload a test question.

the same issue was reported on the moodle plugin page from another user: https://moodle.org/plugins/qtype_stack

have a nice day!
christian

**Comment by sangwinc** [comment]
I'm really sorry about this - it's a consequence of some internal re-engineering and interactions with the Moodle quiz which were not covered by our unit testing.  It has been fixed in the dev branch and I'm planning to release this next week.
Chris

**Comment by steveorulez** [comment]
Thanks a lot for the prompt reply! I will update to the dev branch on my test platform and let you know if it is fixed.

**Comment by sangwinc** [comment]
Thanks, help with testing would be much appreciated.

**Comment by steveorulez** [comment]
Hello,
I can confirm that with the dev branch it works (mark 4/4)
question1= 3points
question2=1point
![image](https://user-images.githubusercontent.com/4101369/186447083-60d6a327-3fa2-4dab-824e-0e14a941d5d9.png)

**Comment by sangwinc** [comment]
Thanks, that's very helpful to know!
Chris

**Comment by ngandrass** [comment]
Hey,

we currently run into the same problem at our university, resulting in incorrect grading of exam questions. I assume that it is **not safe** to upgrade to the `dev` branch right now and it is advised to wait for the upcoming `4.4.1` release, correct?

Can we help getting the release of 4.4.1 out in any way?

Thanks for keeping us updated :+1:

**Comment by angstr0m** [comment]
I'm having the same issue.

**Comment by aharjula** [comment]
All testing of `dev` in advance of the release will be helpful. Every problem detected just before release is likely to push the release more than those detected early.

This is very much not an official statement or opinion of any other STACK dev, but as I have caused and fixed many of the issues in 4.4.0, I have to say this:

I (as a person that has the option to hot patch systems, which is not something many have the option to do) would suggest that those that can, are willing, **and have already updated to 4.4.0** (if running something earlier than 4.4 just wait for 4.4.1) should upgrade to `dev` if the alternative is to run for a whole semester with 4.4.0. The fixes in `dev` are significant, and there are things that are truly broken, like this grading. If you have the option of waiting for 4.4.1, which is likely coming out "next week", then it makes sense to wait for it, but if that is not an option, then `dev` will make your lives simpler. This suggestion applies to `dev` at this moment, i.e. commit 4a7daccc050669882299a2964ca9f8c7838b27ec, I cannot say it would be safe at any other moment.

As to what is safe, I would rate 4.3.x -> 4.4.0 as a much less safe upgrade than to upgrade 4.4.0 -> dev at this point in time. And dev in its current form is quite close to release, so it should be stable enough. There are no data-model changes in the current `dev`, so it will still be safe/easy to upgrade from it to 4.4.1+ once that comes out.

If you are running 4.3.x you should wait for 4.4.1 before updating. Unfortunately, Moodle does not make it easy to downgrade from 4.4, and there would be database changes which would make it even more difficult, so that is not really an option.

**Comment by sangwinc** [comment]
Folks,
I'm really sorry about the problem in 4.4.0, which we have fixed in the dev branch. The dev branch contains nothing irreversible (e.g. database upgrades) and it would be "safe" to upgrade from 4.4.0 to the dev branch. I'm on holiday this week, but my plan is to review and release a new version on Monday 29th based on the current dev code.
Chris

**Comment by ngandrass** [comment]
Many thanks to @aharjula for clearing things up. We surely can wait until the beginning of next week. I'm much more in favor of a clean upgrade versuch using the `dev` branch for our live system.

If the release of 4.4.1 should be delayed for whatever reason I'll spin up a clone of our system with the `dev` branch version and temporarily re-grade all affected exams with that one. So take your time @sangwinc and enjoy your holidays :)

**Comment by angstr0m** [comment]
Thanks for all the effort to everyone :)! Looking forward to the release!

Niels Gandraß ***@***.***> schrieb am Do. 25. Aug. 2022 um
19:56:

**Comment by ngandrass** [comment]
Version 4.4.1 fixes the observed problems. Thank your for taking quick action! :+1:
