### ISSUE TITLE
Unable to use simp:false within CASText

### ISSUE THREAD

**Issue by georgekinnear** [maths/moodle-qtype_stack#849]
I would often use something like `{@(simp:false, 1+1)@}` within a worked solution to show the details of a step (e.g. the question in #848). That seems not to work any more - if simplification is on at the end of the question variables, the output appears as "2".

So, it seems that it is no longer possible to turn off `simp` within subsequent CASText.

## Example

Question variables:
```
var1:1+1;
simp:false;
var2:1+1;
```
Question text | result with `simp:true` at end of question vars | result with `simp:false` at end of question vars
------|--------|----------
{@var1@} | 2 | 2
{@var2@} | 2 | 1+1
{@1+1@}| 2 |  1+1
{@(simp:false, 1+1)@} | 2 |  1+1
{@(simp:true, 1+1)@} | 2 |  2

I'm concerned that I will now have lots of questions with unhelpful worked solutions, because the steps that I'd tried to show are now being simplified. Plus, this change in behaviour is not picked up by bulk question tests, so it will take a bit of detective work to find them all.

## Workaround

To get selective control of simplification in the question text / worked solution, it seems that you must now have `simp:false;` at the end of the question variables.

**Comment by aharjula** [comment]
How unfortunate. this is the primary reason why that no longer works, the other reason is that solving #844 requires us to detect the simp value from the expression, and we can only reliably detect the value from the end of the expression (we could catch it during runtime... however I would rather not for various reasons):
```
Maxima restarted.
(%i7) simp;

(%o7) true
(%i8) (simp:false,1+1);

(%o8) 1+1
(%i9) simp;

(%o9) false
(%i10) 1+1,simp:true;

(%o10) 2
(%i11) simp;

(%o11) false
(%i12) 1+1;

(%o12) 1+1
```
Note how the simp value outside the evaluation of `%i8` changed i.e. `%i9` now returns `false`. Whereas the way one can tune the simplification in `%i10` does not affect the global simp. 

Basically, if you need to tune evaluation details in CASText injections, you should use evaluation flags and write `{@1+1,simp=false@}` that will make sure that the modification of simplification only applies to that single injections evaluation and does not leak out nor gets wrongly detected.

The current defined functional requirements for CASText `{@injections@}` are [here](https://github.com/maths/moodle-qtype_stack/blob/364679965ee1addf8597348622c115bf9295a551/tests/castext2_test.php#L82), and they have been tested for multiple years. But again, the old system was used in interesting ways and replacing it led to the detection of those interesting ways.

@sangwinc if we want to support tuning of simplification in this way, i.e. adjusting global simplification i.e. all injections for the rest of the CASText we can do so by capturing the value of `simp` after the evaluation of the expression. But to me, it would be cleaner if we were to force people to use evaluation flags as the example in this issue leaks and such leakage can cause additional issues and probably causes more unexpected behaviour than we would want.

As to what is broken... The bit of logic [identifying](https://github.com/maths/moodle-qtype_stack/blob/364679965ee1addf8597348622c115bf9295a551/stack/cas/castext2/blocks/latex.block.php#L36) whether we have simplification on for the injection fails for an expression of this shape, and as the injection needs to turn `simp:false` to transfer things and then adjust it again at the other end it now adjusts the value to the wrong value, i.e. [the value as it was before](https://github.com/maths/moodle-qtype_stack/blob/364679965ee1addf8597348622c115bf9295a551/stack/cas/castext2/blocks/latex.block.php#L53) this expression was executed.

What makes this difficult to fix is the way we need to support evaluation flags that will not modify the external simplification and thus make it difficult to detect if simplification was adjusted inside the evaluation, whereas things that leak are much simpler to detect. However, if both are in play and do opposing things, the detection is no longer a simple string match as it is currently implemented, nor is it something easily solvable as a quick runtime check due to the very nature of that evaluation flag behaviour.

**Comment by georgekinnear** [comment]
Thanks, I wasn't aware of the `{@3/9,simp=false@}` syntax!

I couldn't find anything about it in the docs either, perhaps it could be mentioned at https://docs.stack-assessment.org/en/CAS/Simplification/#selective-simplification and/or https://docs.stack-assessment.org/en/Authoring/CASText/

My course materials have about 1000 STACK questions in them, and I've found that about 100 of them have `{@(simp:false` somewhere in CASText. It seems like it should be generally straightforward (if tedious) to translate those using the pattern:

`{@(simp:false,...)@}` --> `{@(...),simp=false@}`

I think I will have to fix all these manually now, as we're locked into the latest version and my materials are live now.

If `{@(simp:false...` continues to be unsupported, perhaps this could be flagged in the bulk testing script.

**Comment by aharjula** [comment]
I'll look into whether the `(simp:false,...)` version can be reliably detected. I do believe it could be done for your particular use pattern. However, if one does:

```
(simp:false,...,simp:true,...,simp:x,...)

 or 

(simp:false,...),simp
```
Then we are in trouble as static detection becomes quite impossible.

Also, if you find yourself in a position where most of the injections need that tuning, you might want to look at the `[[define/]]`-block:
```
{@a,simp:false@} {@b,simp:false@} {@c,simp:false@} ....

That is equivalent to:

[[define simp="false"/]]
{@a@} {@b@} {@c@} ...
[[define simp="true"/]]  <<< note that it is good to return to whatever value is typical.
```
Alternatively, one could turn simplification off for the whole question, but that tends to be less convenient. The `[[define/]]` basically lets you change the global value of `simp` so that all the injections after it use that same. You may also change any other values with it.

In any case, your usage has that side effect and simply converting `{@(simp:false,...)@}` --> `{@(...),simp=false@}` would leave some other injections below it to use the wrong `simp` value as the value would not leak to them. So the fix might not be that simple from the authors side, and I believe it is well worth the effort to cover the simplest use cases in our logic, even if we cannot handle all the possible ways one could tune simplification.

**Comment by georgekinnear** [comment]
I was using the following regex to find examples in my course backup XML file:
```
\{@\(simp\s?:\s?false\s?,([^@]*)\)@\}
```

In almost all cases, it's a single expression after the simp - there's no switching on and off within the block. I say "almost all" as I sometimes set other flags to tweak the display, e.g. `{@(simp:false,make_multsgn("dot"),ev(int1,x=x2))@}`

As you say, there may be side effects that I'm relying on, since setting `simp` in this way used to persist throughout the CASText, so everything will need to be looked at manually to make sure the display is as intended.

At least I have been able to make a list of all the affected questions, and I've found a Chrome plugin that enables regex-based find/replace, so on the question editing form I can quickly replace matches of the regex above with
```
{@($1),simp=false@}
```

**Comment by georgekinnear** [comment]
I've noticed a strange behaviour with `{@...,simp=false@}` giving results that are inconsistent with other ways of turning off simp.

Defining `p1:x^2-2*x+1;` in the question variables, I get the following results:

| CASText | Displayed as |
| ----- |------ |
| {@p1@} | x^2-2x+1
| {@p1,simp=false@} |  1-2x+x^2
| [[define simp="false" /]] {@p1@}  | x^2-2x+1

i.e. the `{@...,simp=false@}` version seems to affect the ordering of polynomials, in a way that other versions do not. (I'm pretty sure that my old technique of `{@(simp:false, p1)@}` would have given the same as `{@p1@}` above, but I can't test that now that our server is updated!)

**Comment by georgekinnear** [comment]
Thanks Chris - am I right in thinking this has restored the functionality as I was using it before?

From a quick test on your coulomb server running the latest code, it looks like `{@(simp:false, 1+1)@}` (from my original post about the issue) is back to showing as `1+1`.

In that case, should the edits I made to the docs be reverted?

I've also just tested `{@(simp:false, p1)@}` as in my previous comment, and it does indeed return x^2-2x+1. So there's something strange going on with the `{@...,simp=false@}` version.

**Comment by sangwinc** [comment]
George,

Thanks for picking this up. I've tested the current code, and pushed some changes to the docs reflecting the current behaviour. I'd be very grateful if you would review the docs now in dev, test the functionality and contribute updated docs and further test cases.  The wider variety of test cases you can contribute the better confidence we'll have of long term stability.

Pull requests are preferred to comments in issued please!

Chris
