### ISSUE TITLE
Special characters(umlauts) not getting displayed correctly

### ISSUE THREAD

**Issue by Amrita1991** [maths/moodle-qtype_stack#858]
Hi ,

We are part of a german university which uses this plugin. Unfortunately, the special characters in the german language  (üöäß) are not rendered correctly. (See pic)

![image](https://user-images.githubusercontent.com/19415046/191729441-deaf6c60-3a73-41e0-b90e-82539f9daec5.png)
The umlauts are changed to '?'

I think the issue comes from here: https://github.com/maths/moodle-qtype_stack/blob/29f077be3a11c8de632d418bb7018fde03e6bc0e/stack/cas/cassession2.class.php#L405

**Comment by aharjula** [comment]
4.4.x? On a local Maxima?

What is probably happening is that when we moved all the PRT processing into Maxima in 4.4 the text processing that was previously safe from encoding issues and happened mostly on PHP side now had to work with Maxima's encoding issues as it now happens on the CAS side, and not everyone seems to have their Maxima running with the correct environment variables to actually support Unicode and umlauts.

As long as your Maxima is newer than 5.38.1 which was released back in 2016 then your Maxima installation should be able to work with Unicode. Problem is that when running Maxima locally through the web-server the process inherits the web-servers locale settings and those tend to default to ASCII. To fix this ask your Moodle admin to set the maxima command line for STACK so that it starts the correct Maxima and to prefix a suitable environment-changing portion to it. e.g. `LANG=en_US.UTF-8 /path/to/your/maxima`, obviously pick a locale that you have installed as long as it is a Unicode locale, also depending on your server's operating system the locale might be controlled by other variables not necessarily `LANG`. Clear the CAS cache after that and things should work, working with a maxima-image might require similar prefixing...

Assuming a Debian derivative and `www-data` your admin may test what is happening by running Maxima on the server as both a normal user and as the `www-data` user (also possible that the apache/nginx process itself changes the environment when starting) and comparing the default environments and the effects of those environments for Maxima when it gets asked to evaluate something like this:
```
(%i1) slength("äöü");
(%o1)                                  3
```
They may then choose whichever method they wish to use to tune the Maxima processes environment.
