### ISSUE TITLE
Unclosed comment in feedback variables destroys question

### ISSUE THREAD

**Issue by mkraska** [maths/moodle-qtype_stack#871]
If you have an unclosed comment in the feedback variables like this

    /* this is an unclosed comment

then there is a big chance that you loose the question (can't save, can't open again, can't preview)

The error message is:
   
     Argument 1 passed to stack_ast_filter_pipeline::filter() must be an instance of MP_Node, instance of SyntaxError given, called in [dirroot]/question/type/stack/stack/cas/keyval.class.php on line 340

How to reproduce: 

- create a new STACK question 
- make minimal inputs (essentially this is title, model solution and Sans and Tans in the PRT) 
- save the question and go on editing
- add an unclosed comment to the feedback variables.
- try to save. 
- Eventually add an executable line of maxima before the comment, the comment alone doesn't seem to trigger the problem
 
        a:1;
        /* this is an unclosed comment

- The question can still be exported. Then close the comment in some editor and re-import. The question now works.

The  attachment contains two questions: "Unclosed comment" and "Closed comment".

STACK version 2022071300

[Closed and unclosed comment.zip](https://github.com/maths/moodle-qtype_stack/files/9873140/Closed.and.unclosed.comment.zip)

**Comment by aharjula** [comment]
I think this was fixed in https://github.com/maths/moodle-qtype_stack/commit/fc77133f23f8876bf1167f8bac820f561e56f5c1, but I guess someone should check...

**Comment by sangwinc** [comment]
Yes, this problem exists with the dev branch.

**Comment by aharjula** [comment]
Ok. There was a difference in the way the validation and compilation steps dealt with comments. The former simply dropped them with a logic that did not care about them not being closed, while the latter wanted to parse them as it want to be prepared for future annotations that might be present in those comments. The latter assumed that the former caught all possible syntax errors and that it could simply parse anything that was valid. Well, it was not valid...

I made a decision to make it so that a hanging comment leads to a syntax error in the validation step as well so that things are mo consistent as I really want those annotations in the future...
