### ISSUE TITLE
Question score not calculated as expected

### ISSUE THREAD

**Issue by cbosoft** [maths/moodle-qtype_stack#873]
I have a question with three PRTs. One PRT with a question value of four and the others have a value of two. I expect the total score for the student to be calculated as follows:

`total_score = 4*PTR1 + 2*PRT2 + 2*PRT3`

(where PRTx is the value 0-1 returned by the PRTs)

The question has a total of 8 marks. However, STACK is returning a student's score of 6 out of 8, despite the student getting all questions correct. Any help with this would be much appreciated.

I apologise, I do not know what version of STACK we're working with although I do know that it has been recently updated.

**Comment by georgekinnear** [comment]
This sounds like an issue we were seeing in the summer when our STACK server was upgraded - and I think @sangwinc fixed the bug and had our server updated again, since we don't have this issue any more.

I think this bug came up in 4.4.0 and was fixed in 4.4.1

https://github.com/maths/moodle-qtype_stack/commit/c4be0bdfc59a1a04a1143d23eb6fed3516a135ed
