### ISSUE TITLE
Edge case with  get_stack_maxima_latex_replacements()

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#878]
Matti,
Sorry, I've struggled and failed to fix this myself....

{@"!AND!"@}

does not have get_stack_maxima_latex_replacements() applied to it anywhere in the chain.  I think this is a little inconsistent, given that this function is applies within strings elsewhere, e.g.

{@a or "!AND!"@}

Can we apply get_stack_maxima_latex_replacements() in the first case as well, and how do we do so?

Thanks
Chris

**Comment by aharjula** [comment]
Chris,

The processing for atomic sting values skips the post-processing logic. Basically, it comes back from the CAS without the magical wrapping that triggers that processing:

https://github.com/maths/moodle-qtype_stack/blob/a55f392528cd146e872fddb4b1d731eba824dbd0/stack/maxima/stackstrings.mac#L424-L429

If you want to apply that translation to every string it sees, you need to return the value wrapped like this:

https://github.com/maths/moodle-qtype_stack/blob/a55f392528cd146e872fddb4b1d731eba824dbd0/stack/maxima/stackstrings.mac#L443-L444

One can naturally ask whether this processing should be applied to such static strings and, if it is being applied to them, should it then be applied to the CASText2 as a whole? Personally, I would not apply it to the whole string as that would require that whatever syntax identifies the replacement targets would need to be safe outside our injection logic, and that could be a problem. Thus we need that wrapping to identify the parts that get this processing from the parts that are not meant for this processing.

Now why the CAS side logic did not do that wrapping? Well, to it, the primary objective was to get everything evaluated down to strings as completely as possible so that the return value would be as short and simple as possible, and I saw no reason for a static string nor a string constructed "manually" to need any translations. Note that outside the function above, those string fragments can get simplified down further by concatenation, but the one with those wrappings cannot be concatenated.

**Comment by sangwinc** [comment]
Thanks Matti, that's super helpful.  I'd forgotten the translation was triggered on the Maxima side of the code.

The interesting thing is that at the moment, we have an inconsistency between pure strings, and expressions which contain strings. To remove that inconsistency I suggest we apply translation to all strings coming out of Maxima. That, of course, is not the whole CASText2 I think.
