### ISSUE TITLE
Bad "ordergreat" and "exdowncase" interaction in Moodle 4.0

### ISSUE THREAD

**Issue by timlowe** [maths/moodle-qtype_stack#887]
Hi,
(Chris: I think Tim H has discussed this question with you, one of our mysterious upgrade failings, but I now seem to have identified the key issue.)

When considering a function of two variables (x,y), I set "ordergreat(x)" to nicely order the terms.

But then AlgEquiv does not think  exdowncase(student_answer) = teachers_answer, even when correct!
Disabling "ordergreat(x)" solves the problem.

However, I want to use "ordergreat(x)" !.  My workaround is to test
exdowncase(student_answer) = exdowncase(teachers_answer)
which then works.

Not sure that I should need to do this though!

Minimal example question attached (with extension changed to .xml.txt to permit upload . Need to comment/uncomment ordergreat in Question Variables to see the effect.
Tim

[questions-MATHS-WS-OSEP-exdowncase test-20221130-1526.xml.txt](https://github.com/maths/moodle-qtype_stack/files/10124605/questions-MATHS-WS-OSEP-exdowncase.test-20221130-1526.xml.txt)

**Comment by timhunt** [comment]
I did raise this by email last week, but I don't think we worked out a solution.

**Comment by sangwinc** [comment]
Thanks for raising this as an issue on github, it makes sure it won't get lost!  Sorry I've been a bit slow, things are backing up in the last week of semester.

The problem is the way ordergreat interacts with exdowncase inside a block.  This is a change of behaviour: we used to execute Maxima statements separately, now they are one command wrapped in a block.

Here is a minimal example illustrating the issue, which can be pasted into an empty desktop Maxima session.

```
exdowncase(ex) := block([lv],
  lv:listofvars(ex),
  lv:map(lambda([v], v=parse_string(sdowncase(string(v)))),lv),
  return(subst(lv,ex)))$
simp:false$

block(ordergreat(x,y), q:x+y, ?print(q), p:exdowncase(X+y), ?print(p), ?print(x), is(p=q));
is(p=q);
```
The results of executing this in a maxima session are as follows.  The results are as follows

```
((MPLUS) $X $Y) 
((MPLUS) |_102X| |_101Y|) 
$X
false
false
```

Notice that the variables in the second ?print statement are different from the first, hence the failure of `is(p=q).  Now if we run separate expressions (in a clean Maxima session)

```
ordergreat(x,y)$ 
q:x+y$ 
?print(q)$
p:exdowncase(X+y)$ 
?print(p)$
?print(x)$
is(p=q);
```

We get

```
((MPLUS) |_102X| |_101Y|) 
((MPLUS) |_102X| |_101Y|) 
|_102X| 
true
```

Since the expression `ordergreat` has finished all variables are now the new re-ordered ones.

Not sure how to fix this - it must be possible.  I suspect re-writing exdowncase is the place to start.

**Comment by sangwinc** [comment]
Part of the problem is this line:   

[`if (method_exists($statement, 'is_toplevel_property') && $statement->is_toplevel_property('blockexternal')) {`](https://github.com/maths/moodle-qtype_stack/blob/dev/stack/cas/cassession2.class.php#L355)

which now does nothing useful.

The block externals code in compile of keyvals is also not doing anything useful either!
