### ISSUE TITLE
Feature request: Open question in external editor

### ISSUE THREAD

**Issue by mkraska** [maths/moodle-qtype_stack#897]
The request is to add an option to context menu of questions in the question bank "External edit".

This would export the question xml to a local file, which can be modified and afterwards be re-imported. The difference to the existing export/edit/import would be that the changes would be stored in place, and not as a separate new question. 

External editors (notepad++, VSCode etc) would be able to provide syntax highlighting and perhaps code introspection in CAS and CAStext fields. 

The current export/import loop requires the author to upgrade all references to the questions in test activities.  

Perhaps, an import option "Replace" would be sufficient, but a configurable button which sends the export to a temp file, launches the editor and re-imports the edits when done, would give a smoother user experience.

In case of errors, the Web edit UI with the import could be launched as if the changes had been input there.

This request, of course, is a special version of "I'd like to have a language-aware editor" (HTML, Maxima, JS, Latex, Markdown)

For the question variables, a button "Open in Sandbox" would be great. This button would use wxmaxima as external editor.

**Comment by aharjula** [comment]
Import into/over is probably one of those things that should be at the Moodle level. Especially now that Moodle has that question versioning feature and thus a possibility to ever messed up things. Basically, all the steps you mention and in particular that open in the Web editor if not valid, are such that they would probably map to all possible Moodle question types. Thus I would try to get this onto the Moodle level instead of building it into STACK.

As to "Open in Sandbox", what we need is a bit of JavaScript behind that button that creates a download with a particular MIME type and then it is up to the user to have a program (e.g. wxmaxima) that can open that MIME type and a browser configured to open it directly there. That script could easily also construct fake PRT functions (to transfer the whole PRT as one thing) for trial but would probably not do CASText processing, also includes might be asking for a bit too much. Mapping changes back from that program, however, is not that easy, so it probably requires manual copy-pasting from the user.

**Comment by sangwinc** [comment]
We have plans to address this by a combination of the gitsync plugin to export/import materials, and the new API to view them.

**Comment by sangwinc** [comment]
In particular, I don't think we will add an in-build function to "open in external editor" as suggested in the foreseeable future.  Instead, use the new gitsync plugin to get your questions outside moodle and work from there.
