### ISSUE TITLE
Parser memory limit exceeded

### ISSUE THREAD

**Issue by timlowe** [maths/moodle-qtype_stack#899]
I cannot save (even without edits) an existing question as the question text code exceeds the parser memory limits.
(The question is on group theory and includes a grid of 12 SVG images.)

Tim Hunt kindly diagnosed the problem, which generates the following error messages:

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/moodle/question/type/stack/stack/maximaparser/autogen/parser.mbstring.php on line 1721

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 24576 bytes) in /var/www/html/moodle/lib/classes/session/handler.php on line 54

Cutting back the question, I reckon I can get 80% of it into the system.

Any chance of increasing the parser memory limit by 50% (or even more!)

Tim

**Comment by timhunt** [comment]
I am not sure it is a case of increasing the memory limit. It is more "Why does the parser eat so much memory on this relatively modest question?"

Tim, can you attached the question here? (Github does not let you attache XML files, so you have to rename to .txt.)

**Comment by aharjula** [comment]
Assuming this is the question with "Orbits" and "finite sets" in its name, this is my analysis:

1. The parser does indeed use excessive amounts of memory.
2. The thing it parses is the result of CASText2 compilation of the question text. That result has 2048 opening parenthesis and parsing it on the parser eats about 162Mb of RAM.
3. The parser is indeed not optimal as my in-development version of the parser that will be eventually replacing this used 61Mb and parsed in a quarter of the time.

Now, why do we end up in this situation, with this "modest question"?

 1. That question has a total of 504 `{#...#}` injections in its question-text, each of which gets compiled to a bit of logic that juggles around simplification settings and captures errors with traceback all the way to the injection site.
 2. The logic then does a silly thing and compiles the whole CASText as string fragments that it glues together to finally parse the end result just to check that all worked (also secures variables being modified (to protect from side effects) inside the compilation result). That check has to deal with a massive blob of code (about 52k chars, but it is not the chars; it is the number of items with depth in a singular list), and that is where things break.
 3. The silly thing is actually avoidable, we could simply replace the CASText2 interfaces to return AST objects instead of strings, and that would remove the need to do this completely. It would mean that testing the behaviour of those interfaces would be harder, but it would be worth it. I am going to do this (@sangwinc this will mean that your Geogebra block builders will need to rewrite parts of the block).

In the long run, we will naturally bring in that new parser, but it is not the solution for this. Instead, we restructure the whole chain related to CASText to deal with the compilation results in "parsed form" instead of passing strings around and parsing them as needed.


To work around this in this particular question, one could use the `[[foreach]]`-block to cut down the number of injections to a manageable level. For example, in this case, iterating over a row should cut the injections down to nearly a quarter. Would need to encode the selection of those circles indices in those `cx`/`cy` lists into a list to iterate over, though. That would also allow you to randomise the placements...

I would not recommend raising the PHP memory limit in your context. In that scale, it would no doubt cause issues.

**Comment by timlowe** [comment]
Thanks Matti. In the short term I'll rewrite the question as suggested - good point!

**Comment by aharjula** [comment]
Looking at the question, even `[[foreach]]` loops are not actually the ideal way to do this. The ideal solution in the world of 4.4 would be to define a CASText-generating function within the question variables. That function would then handle the generation of a singular plot, and the actual question text would simply inject calls to that function with relevant parameters. The function could use the inline CASText feature to do this as easily as possible.

In the future, an even better method will be coming. There will be a `[[template]]`-block in STACK this time next year or probably by summer. It will allow similar function/macro-styled logic to be written within the CASText itself, allowing one to define once and then copy that template around. Within the text, combined with the `[[define]]`-block, it should make it even simpler to produce repetitive content that is not directly mappable to loops.

But for now, I'll focus on upping the number of injections the system can survive. After all, not everyone has the time or skills to use advanced methods to cut down the number of those injections and it is often faster to prototype without such optimisation

**Comment by aharjula** [comment]
If inline CASText is not already a familiar thing it basically allows one to write stuff like this:
```
/* In question variables. */
explanation(a,b) := castext("Note in maxima you do not need to escape line changes inside strings.
<p>Due to {@a@} we got {@b@}...</p>
Any and all CASText blocks/injections work here, just remember to be careful with quotes.
Switching formatting mode might cause some trouble though, so be explicit about it if that becomes a problem.
");
```
You could then inject the output of the function into the question text or anywhere else:
```
[[comment]]Inquestion text[[/comment]]]
{@explanation(x, y)@}
{@explanation(y, z)@}
{@explanation(x, z)@}
```
Key things to remember though:
 - `castext()` the function is not available in the sandbox environment as it is a compile-time feature.
 - The function's argument must be a singular atomic string, not a reference to one but a static string value.
 - The actual object coming out of that function is a list of strings of some sort, you cannot really do any processing with it as it might contain compressed placeholders and other complicated things. You can, however, use `castext_concat()` to join two such objects together and also join raw strings into them.
