### ISSUE TITLE
Does the stack have reserved word(s)?

### ISSUE THREAD

**Issue by helour** [maths/moodle-qtype_stack#912]
Hi, 

I noticed some very strange behaviour. I put the 'end' variable in the simple calculations and I have a serious problem. After entering the correct result, the stack stops for a while and does not evaluate anything. Please see my attached xml file.

[questions-E-learning-Derivative of the function-20230115-1413.xml.zip](https://github.com/maths/moodle-qtype_stack/files/10420272/questions-E-learning-Derivative.of.the.function-20230115-1413.xml.zip)

Thank you for your reply.

STACK is 2022082900

**Comment by sangwinc** [comment]
Can you please be much more specific about the nature of the problem?  This question works fine on 2023010400.

**Comment by aharjula** [comment]
Chris,
Do check the way that `end` is just the only content of a statement there at the end of question variables. Maybe this ties to the already ripped-out static validation, or maybe those formatted prints of the values on the question test page. The latter has changed significantly since that release. The former, I think, was already well on its way out at that point but may still have been there.

In any case, while STACK does have plenty of reserved words, `end` is not one of them. Most of the words are related to Maxima's own keywords (check the Programming category in the Maxima manual for some of them), but there are also plenty of Maxima functions whose names are absolutely forbidden to be used as a function name, there typically relate to file-system access, and some operators and variables are also forbidden.  The [security-map](https://github.com/maths/moodle-qtype_stack/blob/master/stack/cas/security-map.json) should give a good picture of those that have been marked as "globallyforbidden" or with "f" for forbidden in a given role.

**Comment by sangwinc** [comment]
Matti,
I don't think `end` is a Maxima keyword!  There is no help entry associated with end (? end or ?? end), and the for-loop structures, if-then, etc. in Maxima use a block, so no need for an end statement there.  There's no entry for "end" in our security map.  As far as I know, `end` is as good as any other atom.  Did I miss something?
Chris

**Comment by aharjula** [comment]
As I said, it is not a keyword. But what I think may matter here is that those question variables there end with a null statement only evaluating `end;`. How that type of a statement behaves in various bits of logic is the thing that you might want to think through, although I am pretty sure there are no other bits like the one related to PRT rendering as maxima code you already worked on some time ago.

I am pretty certain that whatever issue there is, it is not related to the identifier name being `end`. Instead, it would probably relate to the context of the identifier. For example, how do you extract a "key" from that and so on? Naturally, I have not tested this with anything but based on the exported file, that is what I would look for. I have, however, done the full search of our code base for `end` and it does not exist in any role that would matter inside the Maxima side logic or parser.

**Comment by helour** [comment]
Sorry, my mistake. The string `(-x^2+1)/(x^2+1)^2` must be entered as the student's answer, then the problem will appear.

Originally, the question and calculations were more complex. I left out the parts that didn't cause a problem.

After removing the **end** variable, the problem no longer occurs.

**Comment by helour** [comment]
I have the same problem in the Maxima Stack Sandbox. The last expression `ATAlgEquiv(v1, v2)` will not be evaluated and Maxima will freeze.

Please try this:
```
v1: (-x^2+1)/(x^2+1)^2;
v2: 1/(x^2+1)-(2*x^2)/(x^2+1)^2;
end: 0;
ATAlgEquiv(v1, v2);
```

**Comment by aharjula** [comment]
Well, Chris, these might be the things that cause the issue, not that I have tested anything, but I at least used more exact searches for the variable usage to find these:
https://github.com/maths/moodle-qtype_stack/blob/425a13af3b9d59f627fd1a1039b72d3a804a3678/stack/maxima/assessment.mac#L551
https://github.com/maths/moodle-qtype_stack/blob/425a13af3b9d59f627fd1a1039b72d3a804a3678/stack/maxima/stackmaxima.mac#L2452

Both become infinite loops if `end` is no longer an unbound variable, as after that, the return value from `part` becomes somewhat difficult to match. Probably better to test if those two functions could insist on using their own `end` as a block local variable or maybe forbid `end` itself. Forbidding `end` would obviously stop people from doing things with it so maybe it only needs to be turned into a read-only identifier.

**Comment by helour** [comment]
Yes, you're right. The problem is passed to the function `algebraic_equivalence(SA, SB)`, which internally uses `anyfloatex(SA-SB)`. I just realized it.

**Comment by sangwinc** [comment]
Thanks for such a careful report @helour, this is much appreciated.  To be honest, I completely forgot that the maxima function part used the `end` atom, and this doesn't come up with the Maxima help search.  Thanks Matti for sorting out when this goes wrong.  I have a fix and I'll test it before closing this issue.
