### ISSUE TITLE
Feature request: Make it easier to preview the latest version of question being edited

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#915]
So when I edit questions, I like to have the question open in a preview window at the same time. 

Earlier, this was very convenient, because as I had made an edit, I just saved the question and reloaded the preview window, and immediately, I had the latest changes to the question reflected in the preview.

Now, however, it seems like the question is saved as a new version every time I save the question, and the preview is stuck with an old version of the question. This forces more clicking on the question maker, and it creates a lot of rubbish versions of the question.

Can this be improved somehow, or is it just me doing it wrong again?

**Comment by aharjula** [comment]
Almost certainly a Moodle 4 issue, I assume you are trying it? The versioned question-bank thing in it leads to this, all versions being complete questions. It might be nice for the preview window to have a toggle for forcing it to check if a newer version has appeared and show it instead, but that is a Moodle side issue. Maybe that kind of a toggle would be something a question editor could as a GET parameter when opening the preview so that the normal behaviour keeps showing just the initial version given, as that makes more sense in many contexts.

STACK should not be creating new questions in older Moodles, and if it sis then the detection of the Moodle version logic must be broken.

**Comment by alcarola** [comment]
Indeed, you are right that I am using Moodle 4, but I forgot to write out my Moodle and STACK versions.

I also came to think that this may be a more general Moodle issue, but as a non-technical end user, it is hard for me to know where to report problems.

(As a side note, if anybody knows how to set a course layout in Moodle 4, which has the clear look and structure of a Moodle 3 course, with a reasonable effort, then I will be most happy to hear about that!)
