### ISSUE TITLE
Inserting {@castext(A_12)@} makes saving the question impossible

### ISSUE THREAD

**Issue by mkraska** [maths/moodle-qtype_stack#916]
How to reproduce:

- Edit any STACK question (tested in 4.4.1 and 4.4.2)
- Insert {@castext(A_12)@} somewhere in the question text (tested in the end, at the beginning) 
- Save and continue editing

You get an error message and are redirected to the moodle dashboard. Using Backspace (browser history) gets you back to the edit page with or without other edits being lost.

![image](https://user-images.githubusercontent.com/12987918/213745822-ce69ba29-9f2c-4bb3-bec4-0b17c0746661.png)

**Comment by mkraska** [comment]
Thanks, Matti. Yet, I'd prefer such errors not to crash the edit session ;)

**Comment by sangwinc** [comment]
I'm sorry about this - error trapping is an ongoing and thankless task. I agree that errors caused by a user editing a question should be returned in a form which enables users to edit and correct their question.  Exceptions should be reserved for problems which arise from the design of the code base itself!  I've suggested a mechanism to get the existing error message back to the user above.  Any comments on how this suggestion fits with the design @aharjula?

**Comment by sangwinc** [comment]
@aharjula, do you have any comments here?  If you agree, then I'll put this into the dev branch for the next release. 
Thanks
