### ISSUE TITLE
Behaviour of "Not equal to" (#) operator in MCQ, Radio input

### ISSUE THREAD

**Issue by KZerva** [maths/moodle-qtype_stack#923]
I have a very trivial MCQ, in which I uswe the Radio input type and I ask if a variable is equal, smaller, larger or not equal to a number.

`Null_options: [[mu = 3, true], [mu < 3, false], [mu > 3, false], [mu # 3, false]];`

When I display the question, the not equal option is displayed reversed, meaning that the number is printed first and then the variable. Having a positive or negative number it doesn't affect the outcome, the number is always first.
![image](https://user-images.githubusercontent.com/79198720/216962543-d59cbe04-b69f-48a2-b774-e826fa2afdb7.png)

If instead of a number I have a different variable, let's say compare mu and k, then the way the outcome is displayed depends on the alphabetical order of the variables. 

![image](https://user-images.githubusercontent.com/79198720/216962859-53878a5e-c093-462f-8eff-2aa305414125.png)

![image](https://user-images.githubusercontent.com/79198720/216963046-28d88934-612e-49ca-aacb-dfb61fe24168.png)

**Comment by sangwinc** [comment]
Konstantina,

Thanks for raising this.  I think the problem is this line,
https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/stackmaxima.mac#L192

Note that # is a Maxima core function, not something we've added into STACK.

I added in the commutativity declare in this commit
https://github.com/maths/moodle-qtype_stack/commit/6d5103c4293630dd526a86f35c277e80db97a056

If we remove this line, then your problem (which is easy reproduce with a minimal example of `p:mu # 3') disappears.  From memory, I needed to make sure # was commutative to get these test cases to work.  Yes, we need it for this test

`ATAlgEquiv(a#b,b#a);`

So, can you use simp:false in your question?  Is so, please close this issue!

Chris

**Comment by aharjula** [comment]
Alternatively, if one does not want to play with `simp` one could always simply override the label of a given option. In the past one simply gave a third element in the list to declare a string value for that label like this:

```
[mu # 3, false, "\\(\\mu \\neq \ 3\\)"]
```
However, since 4.4+ use of inline castext has also been possible if one does not want to play with those escapes or wants to inject other values as well:
```
[mu # 3, false, castext("{@mu # 3,simp=false@}")]
```

However, these tricks do not affect the validation messages. for that, in the current input system, one needs to have `simp:false` at the end of question variables using whatever means one wants to control simplification. Personally, I would rather have the input system always have `simp:false` so that whatever is defined outside it stays in its original form.

**Comment by aharjula** [comment]
More importantly, if that `ATAlgEquiv` test case is irrelevant to you in this question, you can always simply undo/remove the declaration of commutativity in the question variables. And if it suddenly becomes relevant after that, you might restore it...
```
remove("#", commutative);
```

**Comment by KZerva** [comment]
Yes, castext was my solution. I was more interested to know why this behavior appears.

**Comment by sangwinc** [comment]
Thanks for raising this Konstantina, if nothing else questions like this add test cases and flag where we need to improve the documentation!
