### ISSUE TITLE
Issues with creating and download CSVs generated by STACK

### ISSUE THREAD

**Issue by SHayashi314** [maths/moodle-qtype_stack#933]
Hi all,

I am using STACK in hopes of creating an assessment where students can download randomly generated data, use it in a MATLAB/Python script and answer corresponding problems within the Moodle quiz. 

I have read and seen the "Serving Out Data" in the STACK documentation, and have successfully replicated the code required to create and download a CSV file. So far so good. 

The issue I came across is that the students are unable to download this, and they are given an error message saying "The question is not accessible for the active user". Going through the repository I found the "stack_user_can_view_question" function, and I believe it has something to do with that.

So, I am unsure with how to allow students to access the data within either STACK or Moodle through this condition. If I could get some help, that would be amazing.

Kind regards,
Seigan

**Comment by aharjula** [comment]
Hi,

It seems like I had a logic failure when creating this and forgot to ensure that this worked. Actually found the TODO post-it that says, "allow either the teacher with the view right or check if the attempts user is the active user", and that second bit is obviously missing leading to the first condition blocking student access.

If you have the possibility to modify your own installation and consider it unlikely that someone will guess suitable numbers and uses those to cause extra load, you can simply remove the whole check, i.e., these lines:

https://github.com/maths/moodle-qtype_stack/blob/3f676971ff390604eba2bfa36934ba90571e14f2/textdownload.php#L62-L67

I am sure we will soon have a patch in the dev branch, though, and that would tell how to have full protections against people triggering excess file generation through this.


This feature has had a rocky start... When it was supposed to come out in 4.4.0 it came out completely broken (someone code-styled it to death just before release) and even though it became functional within previews in 4.4.1 it apparently was not functional... Well maybe by 4.4.3 things will finally work.

-Matti

**Comment by sangwinc** [comment]
Seigan,
Thanks for raising this, and I'm sorry you're having these problems.  We'll try to get this fixed in the next release.

Matti,  I've written a sample question following our docs (!) but I've run into a problem. 
https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Authoring/Serving_out_data.md

If we have 
```Load the data from <a href="[[textdownload name="data.csv"]]{@stack_csv_formatter(data,lab)@}[[/textdownload]]">this file</a>```
then we strip out the newlines somewhere along the chain of events, and the downloaded file is malformed.  See the attached file.

If we have 
```Load the data from <a href="[[textdownload name="data.csv"]]{#stack_csv_formatter(data,lab)#}[[/textdownload]]">this file</a>```
then we get the newlines, but we top and tail the output with string delimitars!

Which should this be?  (Or do I have a server setup problem stripping out newlines in {@"...."@}?!)

Thanks,
Chris

[data.csv](https://github.com/maths/moodle-qtype_stack/files/11045706/data.csv)

**Comment by sangwinc** [comment]
Thanks Matti, that's now fixed it.
