### ISSUE TITLE
If, when authoring a question, you switch from radio/dropdown to checkboxes or back, you will probably break a PRT because of mismatched types.

### ISSUE THREAD

**Issue by lhueber** [maths/moodle-qtype_stack#937]
Dear everyone, 
Coming across this sentence, "If, when authoring a question, you switch from radio/dropdown to checkboxes or back, you will probably break a PRT because of mismatched types." [here](https://moodle.ucl.ac.uk/question/type/stack/doc/doc.php/Authoring/Multiple_choice_questions.md ) and having pulled my hair out too many times...
When I try to set up a drop down question, I too often get the "Your answer should be a list, but is not. Note that the syntax to enter a list is to enclose the comma separated values with square brackets." and I've played around with the PRT but can't seem to get it to work. mcq_correct returns a list doesn't it? Except for dropdown menus? And if it's not a list, what should I tell the PRT to do? 
I assume that this problem has been addressed. If you can direct me to it. I couldn't find it here. 
Thank you.

**Comment by sangwinc** [comment]
This behaviour is by design.  We had two choices, (i) have all MCQ type inputs return the same type (list), or (ii) have MCQ type inputs return the most natural/simplest type of object.  For dropdown/radio the simplest type is an expression, so the variable representing the student's answer is the expression they selected (not a list of one expression!)

PRTs are totally separate from inputs.  `mcq_correct` always returns a list.  If you use `mcq_correct` in the question/feedback variables and want to compare the result of this function with a dropdown/radio input you probably need `first(mcq_correct(...))` in the PRT.

I'm sorry, there is no way to "tell `mcq_correct`" that the value will later be used with a radio input!

Of course, the other choice would cause equal frustration:  "Why when comparing a radio selection to the teacher's expression do I have to add/remove a list when this is always a single expression?"!  

I'm sorry this is frustrating.  The design is doing what we intended.  I'm open to suggestions for a better/improved design.

Chris

**Comment by lhueber** [comment]
first(mcq_correct(tal1))
got it. 
I think part of the frustration was that I knew it was more about layout than the maths. Thank you for your help.
