### ISSUE TITLE
Behat tests spanning over Moodle versions with/without certain strings e.g. tests/behat/create_preview_edit.feature

### ISSUE THREAD

**Issue by lucaboesch** [maths/moodle-qtype_stack#953]
Dear @sangwinc 

As explained here https://github.com/moodle/moodle/commit/c05a29018fb588934e4b1faf5d009ec2a7b15318#r114192319
I think the only way to work around non existing strings in some tests is not to execute them in certain Moodle versions.
I hope this helps you in the releasing of a new version.

>IMHO you can't. That's why it's useful to write two separate steps and let the one run for Moodle ≤ 4.0 and the other for Moodle ≥ 4.1 as seen in https://github.com/lucaboesch/moodle-qtype_kprime/blob/moodle401compatibility/tests/behat/05.feature#L32 thus using the Given instructions as follow.

```
    Given the site is running Moodle version 4.0 or lower
    Given the site is running Moodle version 4.1 or higher

```

>Best,
>Luca

**Comment by sangwinc** [comment]
Thank you so much [lucaboesch](https://github.com/lucaboesch) for all your help.
Chris

**Comment by timhunt** [comment]
Sorry for not getting here sooner.

For reference, the text chagne was part of improving usability - fixing a minor issue that was causing confusion among a number of OU staff.

You already found two of the possible solutions, and there are others:

 1. Rely on the fact that button text uses sub-string matching.
 2. Write two tests, ang limit them by Moodle version.
 3. While you should generally interact with buttons using the visible lable, you can also use the button id - now I think of it, that would have been the cleanest solution here.
 4. You could also have defined a custom step (`When I restart the preview of the STACK question` which clicks the button by looking up the button label lang string.
 5. Really, this test is not about testing the ability to re-start a preview with no options. We are testing STACK. So ideally, we would not be doing this as part of the test - it is basically making every test take longer to run than necessary. If you like, you could try to make it possible to say `When I am on the "Test STACK question" "qtype_stack > preview" page`. Do do that, you need to create a function like https://github.com/moodleou/moodle-qtype_pmatch/blob/main/tests/behat/behat_qtype_pmatch.php#L42-L68, which takes the question name, and constructs the required URL. And, the code that works out the URL for core_question > preview is https://github.com/timhunt/moodle/blob/c4ece59bda12628564d3bcad1f4dc5f99bc64637/question/tests/behat/behat_core_question.php#L86-L89. You can specify pretty much all the preview optoins in the URL (although I am pretty sure that behaviour is the only non-default one you need.)

**Comment by sangwinc** [comment]
Thanks Tim, this is really helpful.

What I'd ideally like is a very short path to the do the following.
1. Edit a STACK question normally, and export it as Moodle XML and save it somewhere (sample questions/test fixtures) 
2. Create a behat test which imports this moodle XML and gets the teacher ready to interact with this on the preview page.

From that point we can then really test the top-level interaction with the question, especially JS interaction and JSXGraph which is really taking off.

I really don't want to code up the questions as samples like this
https://github.com/moodleou/moodle-qtype_pmatch/blob/main/tests/helper.php#L75-L116
The fromform is very time consuming to code up because the STACK question types have so many fields to complete.

I agree uploading the backup quiz isn't the right solution (!) but it was the only path I could find through to achieve this.  I've tried this morning to achieve this, but I haven't managed to get anything working.
