### ISSUE TITLE
Forbidden words: Problems with underscores and Greek letters

### ISSUE THREAD

**Issue by jonaslache** [maths/moodle-qtype_stack#960]
Hello everybody!

I have problems with the "forbidden words" option for STACK input fields. I noticed that expressions such as `x_1` or `a_b` that include an underscore cannot be forbidden. After typing `a_b` (or `x_1`) in the field "forbidden words", then students can still use these expressions. However, the issue does not accur with similar expressions that do not include an underscore (e.g. `x1`).

I then tried a workaround where I defined the expressions that I want to forbid as variables in the question text (because when defining a variable like `x` there, students cannot use them in input fields). Even this workaround does not work for `a_b` or `x_1`. Students can still use the expressions.

In addition, when I generally want to forbid undescores by entering `_` (or `\_`, I thought why not try it) into the field for forbidden words, students can still use expressions that include an underscore. 

A similar but less serious problem seems to exist with Greek letters: if, for example, `alpha:1;` is defined in the question variables, alpha can be used by students as an input. However, the "forbidden words" function works here (other than `x_1`, `a_b` etc.).

Thank you and best regards!

**Comment by LukeLongworth** [comment]
Hello! Depending on the context, you may have some luck with the checkvars option in the input. In particular, if you use the extra option checkvars:1, then any answer with spurious variables (i.e. variables that do not appear in the teacher's answer) will be considered invalid. This falls apart somewhat if you need to account for things like constants of integration, but I find it generally quite useful 

I do agree that some more flexibility with the Forbidden and Allowed Variables would be nice. For example, I would like to blacklist a variable "ln" from many integration questions, because students insist on typing `ln*abs(x)` and ignoring both the multiplication sign and the validation box that tells them they are wrong, but if I include ln and log in the forbidden variables, they are also forbidden as functions, which is not suitable. If I flag spurious variables, I need to specify that the arbitrary constant must be (for example) a capital C. Ideally I could forbid ln as a variable but allow it as a function, but I imagine this might be complicated.

**Comment by jonaslache** [comment]
Thanks, Luke, using the `checkvars` keyword is a workaround in some cases (including mine). However, a more flexible solution would be more satisfiying of course.

**Comment by aharjula** [comment]
There has been a long process of adding type information to STACKs security system (which is also used for validating these things), and that subsystem exists in modern versions of STACK. However, the old "forbidden words" feature does not define whether we are targeting functions, variables or operators. It simply interprets the lists it receives to target everything. We could naturally add some extra syntax to it to allow one to declare that, for example, `ln` is forbidden as a variable but not as a function but for now, there have not been any sensible ideas for such a syntax.

The general path to a type aware forbidden words is like this:
  1. All modifications happen inside `stack_cas_security` class. And in particular, in the `list_to_map` function used to convert both forbidden words and allowed words lists into identifier maps. After that, all the `is_allowed*` functions should be made aware of the modified map structure that would now include information about the type (i.e. var, fun, or op) of the identifier.
  2. Luckily, a large portion of this is already there as the allowed words side actually already has a potenttially type-aware structure. Unfortunately, it is not being used as the predefined lists like `[[basic-algebra]]` ended up being typeless. However, most of the `is_allowed*` functions already check for the possibility of there being a type.
  3. The biggest question is what type of syntax one would use for the word lists. Would `ln[function]` style bracketed suffix to the identifier work? Would we allow multiple suffixes? What would be the separator of multiple values if the top-level list is comma-separated? We must not forget that one might want to forbid `[`, well luckily that is always an operator so should not be a problem...



The original issue with underscores is largely related to the way underscores get rewritten or interpreted before the list of forbidden things gets checked. The problem is that currently, we only check the parts and not the whole:
https://github.com/maths/moodle-qtype_stack/blob/94203102274e9922c7b0c04357790ec40cc716a6/stack/cas/parsingrules/998_security.filter.php#L481-L484
I wonder if it makes sense to clear that array of tokens to check on line 484 and thus ignore the whole identifier, but I believe it was done to match the original behaviour. This could be a real bug, and it could be that simply removing lien 484 would fix things, or better yet, on line 483, we could also check if the whole identifier is forbidden before we go for checking if its parts are.

**Comment by jonaslache** [comment]
Thanks @aharjula for your explanation!

Meanwhile, I have realised that @LukeLongworth's idea (using `checkvars:1`) is not a solution to my problem: The engineering students are supposed to enter an equation using variables like `M_A` and `F_B`. The reason I wanted to forbid some variables is to prevent students from using lower case letters (e.g. `M_a` or `f_B`). In particular, all other variables should be allowed. However, when using `checkvars:1`, any variable that is not in the example solution is forbidden

I would really appreciate any other suggestions to work around the problem that I can't use the "forbidden words" option.

Thank you!

**Comment by sangwinc** [comment]
Yes, the whole point of introducing bespoke validator functions was to avoid the need to make the validation options more complex!  So, this and similar issues can now be fixed locally, for example you can forbid all underscore with this validator
````
validate_underscore(ex) := if is(sposition("_", string(ex)) = false) then "" 
                   else "Underscore characters are not permitted in this input.";
````
I'm really excited about this new feature.  I want to document, and support, a range of bespoke validators.  Please, if you regularly use a validator let us know and we will add that function to the core and support it longer-term without the need to put the code into individual questions.
