### ISSUE TITLE
Import/Export of STACK questions fails for questions with unused files

### ISSUE THREAD

**Issue by btelgen** [maths/moodle-qtype_stack#962]
Hello everyone,

Thanks a lot for your efforts in making STACK such an awesome tool!

When migrating our question bank from last years course, I stumbled upon an import/export issue and was wondering if anybody can confirm this: When exporting questions with unused .png files, the export to "Moodle XML format" works seemingly fine. In the corresponding .xml file, I can find all used and unused .png files in "base64" format. However, when trying to import the files in a new course, the import fails without any kind of error message.

I could fix the problem by removing all unused files, but it took me a while to figure it out. I hope this issue saves time for others.

Cheers,
Bastian

**Comment by timhunt** [comment]
When you say "import fails without any kind of error message" - that is probably the sign of an out-of-memory error, if PHP error reporting is disabled, which is the sensible setting on live servers - but you might have something in your server logs.

**Comment by btelgen** [comment]
Hi Tim, this sounds reasonable. Unfortunately, I am a simple end-user and have no access to the server logs.
I assume that there is no way to add some verbosity for this kind of issues without enabling the reporting?

**Comment by timhunt** [comment]
Not without talking to your admins. Debugging settings can be controlled in the Moodle admin screens, under Development -> debugging. It might be OK to turn it on briefly while investigating an issues.

**Comment by aharjula** [comment]
In any case, it would be interesting to know how many of these files, both unused and used ones, are there in such an import and how large they were in total. One would assume that unless we talk about many hundreds of files and some megabytes in total, normal settings should be enough.

Also, it would be interesting to know the version of STACK in use on those systems, as the next release will actually include logic that checks for the existence of unused files, although not during import itself. This check exists primarily because unused files stick to materials and are starting to take up some room in various places, and we want to encourage their removal. There have not been any issues related to them before yours, though, so this is a new thing.

**Comment by sangwinc** [comment]
I don't think this is a problem specifically with the STACK question type.  As Tim says, it's probably a memory issue.  We have just included a test for unused files in the STACK bulk tester in the next release (imminent) which will help you spot questions in this position and edit them.  70MB does sound quite large, and you probably need to tidy up these materials!

**Comment by btelgen** [comment]
Thanks. I have already cleaned the questions and the export was successful. Feel free to close this issue if you think it is not useful for anybody else. Thanks again for your quick support.
