### ISSUE TITLE
Bug: Multiple reveal blocks on quiz page

### ISSUE THREAD

**Issue by m-r-k** [maths/moodle-qtype_stack#969]
If you have multiple questions with reveal blocks on a quiz page, the visibility control does not work correctly:
In the second question you can influence the contents of the first.

This is because within a question an enumerated numbering is used for the IDs, but this is not unique for the question.

**Comment by aharjula** [comment]
Ahh, well, when testing multiple questions, be careful to also test the case where they are not being compiled at the same time in the same request, otherwise you do not see the counter resetting...

I guess we should have a running number feature in the [[iframe]] block that would replace a placeholder in the content at render time, thus ensuring unique identifiers. I doubt this will be the last time we will be needing numbering of targets for scripts. However, with the reveal-block the problem is with the naming of the div that exists outside the iframe and any solution that the iframe might have won't reach that. Maybe we just name them with compile-time timestamps and hashes of the non-rendered content.
