### ISSUE TITLE
Proposal: change STACK options to cascading options

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#993]
We have a lot of options which don't get set very often, and many of these are what I think of as "aesthetic" rather than as "content".  For example, lots of the display preference options such as the logic symbol (word vs symbol).
https://github.com/maths/moodle-qtype_stack/blob/master/stack/options.class.php#L64

Options such as the shape of brackets
https://github.com/maths/moodle-qtype_stack/blob/master/stack/options.class.php#L112
normally is an aesthetic preference, but of course may need to be set for some applications.

The proposal is to add a new value for every option of "default".

1. New questions start with the "default" value for the option.
2. The "default" value of the option queries the site default when the question is compiled, and the option used.
    This might be a simple single line here:  https://github.com/maths/moodle-qtype_stack/blob/master/stack/options.class.php#L176
3. We plan a text-based (YAML?) question authoring format.  I expect users will only need to set options which differ from the default in any text-based authoring system.  I don't see a problem with a text-based authoring system without fixing this issue, but this issue confirms the design.

Note to self: changing the site default will need to result in clearing the question compilation cache.  Of course we almost never actually change site default options and so this performance hit will not really be a significant issue.

This is particularly useful for options such as the decimal separator proposed in issue #789.  When we share questions we almost certainly want to import/export materials using the "default" option.  Continental users will not want my questions with a British "." as the decimal separator and the certainly don't want to edit them!

(We had this feature in STACK v1.0 at the start of the century but it got lost, sorry!)

**Comment by aharjula** [comment]
Now if we only had this at the course/category level in Moodle instead of the site level. So that all the electrical engineers could switch to using the `j` in all questions and everyone else could simply keep `i` in play. Moodle does not provide a system for that, but I wonder if we could have one of those Moodle "blocks" that one could plug into a course or category, override configuration there and then we could look for those in the hierarchy of the site and pick the values from the nearest one, or from the whole chain.

As to recompiling, that depends on the options themselves. Most of them are just display options and are present in the preamble that gets generated during use, just like setting active the language and seed and thus have no role in the code coming out of the compilation. So simply checking which options get changed will probably save us from doing that. Overall, all options should be clearly defined and classified in some meta-data that can be processed in code so that we know which ones affect specific parts of logic. And I think that we do not currently have any options that would affect the compilation result.

**Comment by sangwinc** [comment]
Thanks for the clarification on caching Matti.

I agree it would be very useful to set non-default options at the course level. I think this is an ideal candidate for another Moodle plugin:  "Set plugin options at the course level".  It might already exist, but I didn't check!  (@timhunt ?)  

If we demonstrate its value for STACK by resolving this issue then it might become a higher priority for the Moodle community (including us).

**Comment by aharjula** [comment]
Also note that if this expands to settings related to decimal separators, we will eventually need to provide a way for a student/teacher to check the active settings at the question usage level. At that point, these would not only affect visible things but would also affect what they need to input at a much more complex level than just the `i` vs. `j` issue.

**Comment by timhunt** [comment]
I am slightly hesitant to do this. There is a great simplicity in each question having settings that are stored in the question. This means that each questoin is self-contained.

For example, the caching of question defintions in Moodle, which is very important for performance during quiz attempts, relies on this. How would you avoid breaking that?

So, I think we should look at other ways to achieve this requirement: make it easy to ensure that all questions in a quiz are using certain settings.

One alternate way to do that would be to make question bank plugin that implements a bulk action, so you can select a bunch of (stack) questions, and then update certain settings in all of them. That is a simple and self-contained development that satisfies most needs, and is worth having anyway.

The one case this does not solve is where you want a single shared questions in a central location, which is used in different places where you would like it to pick up different default options. How necessary is that?

**Comment by sangwinc** [comment]
Ok, thanks for the comments Tim, Matti.  We'll leave things as they are for now.

**Comment by Bjoern-Ge** [comment]
Starting to use the continental comma option, I'm facing the problem of changing this option in numerous questions.

Maybe it's an option, to have a menu like in /question/type/stack/adminui/bulktestindex.php 
that changes an option in all questions of a category by adding a new version of the question?
