### ISSUE TITLE
What are the use cases for question version control?

### ISSUE THREAD

**Issue by EJMFarrow** [maths/moodle-qtype_stack#999]
The plan for this plugin is to create a way of tracking and combining changes to all types of questions via Git. Ultimately we want to make sharing questions and question improvements easier to deal with. This also ties in with the moodle-qbank_importasversion plugin.

Initial set up:

Questions will be stored as Moodle XML in a Git repository on the Moodle server. They will be linked to Moodle via a JSON manifest file containing questionid and filenames (also in the repo). Git operations will be performed via the command line.

**What are the issues/ use cases that need to be dealt with?**

I'm still a bit unclear on how any of this works :), but I'm thinking: 

- Being able to check what changes have been made to a question.
- Compare changes to a question made in 2 different instances of Moodle, combine them and then re-import them to either instance (although that will involve more manual steps on one than the other).

**Comment by georgekinnear** [comment]
+1 to the two points you list!

I have some questions in my course that were "borrowed" from another course in the department (just as others have re-used some of my questions). It would be nice if anyone using a given question pointed to the same file under git control, so that if one of us spots and fixes a bug, the other can update their course with the revised version of the question.
